import type { FieldDoc, NodeDoc } from '../types';

const help = (
  field: string,
  why: string,
  when: string,
  enter: string,
  source: string,
  later: string,
  format: string,
  example: string,
  wrong: string,
  mistake: string,
) => `What this field is: ${field}
Why it matters: ${why}
When to fill it: ${when}
What to enter: ${enter}
Where the value comes from: ${source}
How to use it later: ${later}
Accepted format: ${format}
Real workplace example: ${example}
If it is empty or wrong: ${wrong}
Common mistake: ${mistake}`;

const field = (doc: FieldDoc): FieldDoc => doc;

const fields: FieldDoc[] = [
  field({
    name: 'User Input',
    internalKey: 'userInput',
    type: 'textarea',
    required: false,
    description: 'Optional direct message for the agent. Runtime also accepts upstream message, text, input, or the whole incoming object.',
    helpText: help(
      'The message or task the agent should answer when you want to set it directly in this node.',
      'The runtime ultimately sends one user message to the selected language model; this field can provide that message when the previous node did not already provide one.',
      'Fill it for test runs, scheduled jobs, or workflows where the task is fixed. Leave it blank when a Chat Trigger, form, webhook, or previous node supplies message, text, input, or another payload.',
      'Enter a natural-language request or an expression such as {{$json.message}}. Objects from upstream are converted to text when no message-like field is found.',
      'Usually from a chat trigger, webhook body, ticket text, form answer, or a previous transform node.',
      'The response is returned as {{$json.response_text}} and, for JSON/key-value modes, {{$json.response_json}}.',
      'Plain text or a template expression that resolves to text. JSON objects are allowed upstream but may be stringified.',
      'A support workflow maps {{$json.message}} so the agent replies directly to the customer question.',
      'If no useful input is available, the model may receive an empty string or a stringified object and produce a poor answer rather than a validation error.',
      'Do not paste a whole webhook object here when you only want one field; map the exact message text instead.',
    ),
    example: '{{$json.message}}',
  }),
  field({
    name: 'Model',
    internalKey: 'model',
    type: 'select',
    required: true,
    description: 'Language model used by the agent. Provider is inferred from the model name.',
    options: ['gemini-3.5-flash', 'gemini-3.1-pro-preview', 'claude-3-5-sonnet', 'gpt-4o'],
    defaultValue: 'gemini-3.5-flash',
    helpText: help(
      'The model that generates the agent answer: gemini-3.5-flash, gemini-3.1-pro-preview, claude-3-5-sonnet, or gpt-4o in the current UI.',
      'The runtime infers the provider from this value, so it decides whether Gemini, Claude, or OpenAI credentials are needed.',
      'Choose it for every agent. Use Gemini for the platform-default path, Claude for Claude-specific behavior, and GPT-4o for OpenAI workflows that provide an OpenAI key.',
      'Select one dropdown value exactly. Generated configs may also send another model string, but the provider detector only recognizes gpt-, claude-, and gemini-style names.',
      'Comes from the workflow designer or from a previous setup step only when model choice is dynamic.',
      'The chosen provider/model is included in {{$json.reasoning.model}} when Include Reasoning is enabled.',
      'Model identifier string such as gemini-3.5-flash, gemini-3.1-pro-preview, claude-3-5-sonnet, or gpt-4o.',
      'A customer support agent uses gemini-3.5-flash for fast replies; a legal-review agent uses claude-3-5-sonnet.',
      'If the provider has no usable key, Gemini paths return {{$json._error}} and non-Gemini provider calls can fail the node.',
      'Do not assume changing the model also changes the rest of the prompt; the system prompt still controls the job.',
    ),
    example: 'gemini-3.5-flash',
  }),
  field({
    name: 'System Prompt / Instructions',
    internalKey: 'systemPrompt',
    type: 'textarea',
    required: true,
    description: 'Instruction text that sets the agent role, behavior, boundaries, and response style.',
    helpText: help(
      'The standing instruction sent as the system message before the user input.',
      'It shapes every answer and is the main guardrail for tone, task scope, formatting, and what the agent should refuse or ask back.',
      'Fill it for every production agent. Leave it blank only when you deliberately want the runtime default automation-agent prompt or the chatbot-specific default.',
      'Write the role, task, constraints, output format, and any business rules. You may include expressions for workflow-specific context.',
      'Usually written by the workflow builder from the team process, support policy, review checklist, or business SOP.',
      'A good prompt makes {{$json.response_text}} predictable and makes {{$json.response_json}} easier to map downstream.',
      'Plain text. Bullets and short sections are fine. Template expressions such as {{$json.policy}} are supported.',
      'A support team sets: You are a concise support assistant. Answer from the help-center text and ask for an order ID when missing.',
      'If weak or blank, the agent may answer too broadly, explain workflow internals, or produce a format downstream nodes cannot use.',
      'Do not put API keys, passwords, or customer secrets into the prompt; use service connections and mapped business data only.',
    ),
    example: 'You are a concise support assistant. Return JSON when asked.',
  }),
  field({
    name: 'Temperature',
    internalKey: 'temperature',
    type: 'number',
    required: false,
    description: 'Sampling temperature passed to the model call.',
    defaultValue: '0.7',
    helpText: help(
      'A number that controls how varied the model response can be.',
      'Lower values make answers more repeatable; higher values allow more variation for brainstorming or drafting.',
      'Use lower values for extraction, classification, and JSON. Use higher values for creative writing or idea generation.',
      'Enter a decimal number, commonly 0.2, 0.7, or 1.0.',
      'Usually chosen by the workflow designer based on how predictable the downstream step must be.',
      'It affects the text in {{$json.response_text}} and any parsed {{$json.response_json}}.',
      'Number. The UI suggests a broad 0.0 to 2.0 range, but keep ordinary workflows near 0.0 to 1.0.',
      'An invoice classifier uses 0.2; a campaign-idea generator uses 0.9.',
      'Blank or invalid values fall back to 0.7. Very high values can make JSON or policy-sensitive output less stable.',
      'Do not use high temperature to fix missing context; map the needed data into User Input or System Prompt instead.',
    ),
    example: '0.7',
  }),
  field({
    name: 'Max Tokens',
    internalKey: 'maxTokens',
    type: 'number',
    required: false,
    description: 'Maximum response length requested from the model.',
    defaultValue: '2000',
    helpText: help(
      'The approximate maximum amount of text the agent may generate.',
      'It limits cost and prevents a response from becoming too long for the next workflow step.',
      'Increase it for reports, summaries, and JSON with many fields. Lower it for chat replies and labels.',
      'Enter a whole number such as 500, 2000, or 4000.',
      'Comes from the expected response size for this workflow.',
      'Downstream nodes read whatever was returned in {{$json.response_text}} or {{$json.response_json}}.',
      'Positive integer token limit. One token is roughly a few characters, not one exact word.',
      'A weekly report generator uses 3000; a chatbot answer uses 500.',
      'Blank or invalid values fall back to 2000. Too small a value can truncate the answer.',
      'Do not set a huge value just in case; it can increase cost and delay the workflow.',
    ),
    example: '2000',
  }),
  field({
    name: 'Top-P',
    internalKey: 'topP',
    type: 'number',
    required: false,
    description: 'Nucleus sampling value read by the runtime but not currently passed into the LLM adapter call.',
    defaultValue: '1.0',
    helpText: help(
      'A legacy sampling-control field in the visual panel.',
      'It looks like an AI generation control, but the current AI Agent runtime reads it and then does not pass it to the model adapter.',
      'Leave it at the default unless a future runtime update starts honoring it.',
      'Use 1.0. Changing it today should not affect the generated answer.',
      'This is chosen in the workflow UI, not from an external service.',
      'There is no reliable downstream signal showing this value was applied because the current runtime does not send it to the provider.',
      'Number such as 1.0.',
      'An existing workflow leaves Top-P at 1.0 while using Temperature for actual variation control.',
      'If changed, the workflow still runs, but the current response is not expected to change because Top-P is ignored by the adapter call.',
      'Do not tune Top-P expecting it to fix output quality; tune System Prompt, User Input, Temperature, and Max Tokens instead.',
    ),
    example: '1.0',
  }),
  field({
    name: 'Frequency Penalty',
    internalKey: 'frequencyPenalty',
    type: 'number',
    required: false,
    description: 'Legacy repetition-control field read by the runtime but not passed into the model adapter call.',
    defaultValue: '0.0',
    helpText: help(
      'A panel field intended to discourage repeated wording.',
      'The current runtime parses it but does not send it to the provider, so it is effectively a no-op today.',
      'Leave it at 0.0 unless a later worker change documents support.',
      'Enter 0.0. Other numbers are accepted by the UI but should not change current output.',
      'Chosen by the workflow designer; it does not come from credentials or account setup.',
      'No downstream field confirms it was used, because the model call does not receive it.',
      'Number, commonly 0.0.',
      'A report-writing workflow leaves Frequency Penalty at 0.0 and reduces repetition through prompt instructions instead.',
      'Changing it does not raise an error, but it also is not expected to reduce repetition in the current runtime.',
      'Do not rely on this field for production behavior until worker support is added.',
    ),
    example: '0.0',
  }),
  field({
    name: 'Presence Penalty',
    internalKey: 'presencePenalty',
    type: 'number',
    required: false,
    description: 'Legacy topic-diversity field read by the runtime but not passed into the model adapter call.',
    defaultValue: '0.0',
    helpText: help(
      'A panel field intended to encourage or discourage new topics.',
      'The current runtime parses it but does not pass it to the LLM adapter, so it has no reliable effect today.',
      'Leave it at 0.0 in production workflows.',
      'Enter 0.0 unless you are preserving an old config for compatibility.',
      'Chosen in the node settings, not retrieved from any AI provider.',
      'The agent output in {{$json.response_text}} will not indicate whether this field was used.',
      'Number, commonly 0.0.',
      'A policy-answering bot leaves Presence Penalty at 0.0 and tells the model to stay on policy in the system prompt.',
      'Changing it does not fail the workflow, but the model call currently ignores it.',
      'Do not use this as a substitute for precise prompt instructions.',
    ),
    example: '0.0',
  }),
  field({
    name: 'Timeout',
    internalKey: 'timeoutLimit',
    type: 'number',
    required: false,
    description: 'Maximum milliseconds the agent waits for one model attempt. Also used as the fallback for Agent Timeout (ms) when that field is blank.',
    defaultValue: '30000',
    helpText: help(
      'The time limit for an individual model call attempt.',
      'It prevents a workflow from waiting indefinitely on a slow provider response. This field has two different real jobs depending on whether a Tool is attached: with no Tool attached, this is the only timeout the agent uses (wraps the single model call). With at least one Tool attached, "Agent Timeout (ms)" (timeoutMs) is used instead for the whole run, and this field is only consulted if Agent Timeout (ms) is somehow blank.',
      'Increase it for large prompts or complex responses. Lower it when workflows need fast failure. If this agent has no attached Tool, this is the field that actually controls the timeout — Agent Timeout (ms) below has no effect in that case.',
      'Enter milliseconds such as 30000, 60000, or 120000.',
      'Comes from your workflow latency requirement and provider speed expectations.',
      'If the call times out after retries, there may be no normal {{$json.response_text}} because the node throws after exhausting attempts.',
      'Positive integer milliseconds. 30000 means 30 seconds.',
      'A chatbot uses 30000 so the user is not left waiting too long.',
      'Blank or invalid values fall back to 30000 (no-Tool path) or are ignored in favor of Agent Timeout (ms) (Tool-attached path). Too low a value can cause avoidable timeout failures.',
      'Do not set it lower than your provider normally needs for the selected model and response length. Do not assume raising this field alone fixes a timeout once a Tool is attached — raise Agent Timeout (ms) instead in that case.',
    ),
    example: '30000',
  }),
  field({
    name: 'Agent Timeout (ms)',
    internalKey: 'timeoutMs',
    type: 'number',
    required: false,
    description: 'Global timeout for the whole agent run (model calls plus every attached tool execution combined). Only enforced when at least one Tool node is attached.',
    defaultValue: '60000',
    helpText: help(
      'The maximum total time the agent loop — every model call and every tool call combined, across all iterations — is allowed to run.',
      'Long-running agents that call several tools in sequence can otherwise run far longer than a single model-call timeout would suggest; this caps the whole loop.',
      'This field only matters when at least one Tool node is attached to this AI Agent\'s Tool port. With no Tool attached, the agent makes exactly one model call and this field is never read — Timeout (timeoutLimit) governs that call instead.',
      'Enter milliseconds such as 60000 (1 minute) or 120000 (2 minutes) for agents that call several tools per run.',
      'Chosen from how many tools the agent is expected to call per run and how slow those tools are (an HTTP Request tool calling a slow external API needs more headroom than a Math tool).',
      'On timeout the run throws an error with code TIMEOUT ("AI Agent timed out") instead of returning {{$json.response_text}}; nothing partial is returned.',
      'Positive integer milliseconds, clamped by the runtime to between 1000 (1 second) and 300000 (5 minutes) regardless of what is entered.',
      'A research agent that searches, then fetches a page, then summarizes sets this to 120000 so all three tool calls have room to finish.',
      'Blank falls back to Timeout (timeoutLimit) and then to a runtime default of 60000. Too low a value cuts off a multi-tool agent mid-run even though each individual step was healthy.',
      'Do not confuse this with Timeout (timeoutLimit) above — when a Tool is attached, this field is the one that actually applies; raising Timeout instead will not help.',
    ),
    example: '60000',
  }),
  field({
    name: 'Max Iterations',
    internalKey: 'maxIterations',
    type: 'number',
    required: false,
    description: 'Maximum number of model/tool-call round trips before the agent stops. Only relevant when at least one Tool node is attached.',
    defaultValue: '10',
    helpText: help(
      'The maximum number of think-then-call-a-tool cycles the agent may run before it is forced to stop and return whatever it has.',
      'An agent without a hard cap could keep calling tools indefinitely on an ambiguous task or a model that never decides it is done, burning time and provider cost.',
      'This field only matters when at least one Tool node is attached to this AI Agent\'s Tool port. With no Tool attached, the agent always makes exactly one model call and this field is never read.',
      'Enter a whole number such as 5 for simple single-tool lookups or 15-25 for agents expected to chain several tools together.',
      'Chosen from how many distinct tool calls the task realistically needs — a "look up the customer, then check their order, then reply" agent needs at least 3-4.',
      'When the cap is hit, the run stops with a failure output carrying code ITERATION_LIMIT ("AI Agent reached the maximum iteration limit") instead of a normal answer.',
      'Positive integer, clamped by the runtime to between 1 and 25 regardless of what is entered.',
      'A support-ticket triage agent with two tools (CRM lookup, ticket update) sets this to 6 to allow retries without looping forever.',
      'Blank or invalid values fall back to 10. Too low a value can cut off a legitimate multi-step task before it finishes; too high a value lets a confused agent burn a lot of tool calls before Repeated Tool Call detection or the cap itself stops it.',
      'Do not set this very high as a substitute for a clear System Prompt — a well-instructed agent finishes in fewer iterations than a vague one.',
    ),
    example: '10',
  }),
  field({
    name: 'Tool Result Limit',
    internalKey: 'maxToolResultChars',
    type: 'number',
    required: false,
    description: 'Maximum characters of a tool\'s output the agent feeds back to the model per call. Only relevant when at least one Tool node is attached.',
    defaultValue: '8000',
    helpText: help(
      'A cap on how many characters of a tool\'s result get sent back into the model\'s next turn.',
      'Tools like Database, HTTP Request, or Google Sheets can return very large payloads; passing all of it back to the model wastes tokens/cost and can push the request over the model\'s context limit.',
      'This field only matters when at least one Tool node is attached to this AI Agent\'s Tool port — it caps what the model sees from that tool\'s result, not this node\'s own final answer.',
      'Enter a whole number of characters, such as 4000 for a lightweight lookup tool or 20000 for a tool whose full detail genuinely matters to the model\'s next decision.',
      'Chosen from how verbose the attached tool\'s typical output is and how much of it the model actually needs to decide its next step.',
      'The full (untruncated) tool result is still recorded in the run for logging/debugging; only what is fed back into the model\'s conversation is capped by this value.',
      'Positive integer, clamped by the runtime to between 1000 and 50000 regardless of what is entered.',
      'A Database List tool returning hundreds of rows sets this to 6000 so the model gets a representative slice instead of the entire result set.',
      'Blank or invalid values fall back to 8000. Too low a value can hide the exact record the model needed to see, causing it to answer incorrectly or ask again.',
      'Do not raise this indefinitely to "be safe" — a very high limit increases every subsequent model call\'s token cost for the rest of the run.',
    ),
    example: '8000',
  }),
  field({
    name: 'Repeated Tool Call Limit',
    internalKey: 'maxRepeatedToolCalls',
    type: 'number',
    required: false,
    description: 'How many times the same tool can be called with identical arguments before the run is stopped as a loop. Only relevant when at least one Tool node is attached.',
    defaultValue: '3',
    helpText: help(
      'A loop guard that stops the agent if it calls the exact same tool with the exact same arguments too many times in a row.',
      'A model can occasionally get stuck retrying an identical call expecting a different result (for example after a tool returns an error); this prevents that from silently burning iterations and cost.',
      'This field only matters when at least one Tool node is attached to this AI Agent\'s Tool port.',
      'Enter a whole number such as 2 for a strict setup or 5 for a tool whose repeated use is sometimes legitimate (e.g., paginated list calls with different-looking but structurally similar arguments).',
      'Chosen from how tolerant the workflow should be of an agent retrying the same tool call before treating it as stuck.',
      'When the limit is hit, that specific tool call is refused with a failure output carrying code LOOP_DETECTED ("Repeated identical tool call detected") — the agent then sees that refusal on its next turn and can choose a different approach.',
      'Positive integer, clamped by the runtime to between 2 and 10 regardless of what is entered.',
      'An agent with a flaky HTTP Request tool sets this to 2 so a genuinely stuck loop is caught quickly instead of wasting most of Max Iterations on the same failing call.',
      'Blank or invalid values fall back to 3. Too low a value can block a legitimate case where calling the same tool with the same arguments twice is actually correct (rare, but possible for idempotent checks).',
      'Do not confuse this with Max Iterations — this only blocks identical repeats of one tool call, not the overall number of different tool calls the agent makes.',
    ),
    example: '3',
  }),
  field({
    name: 'Memory Scope',
    internalKey: 'memoryScope',
    type: 'select',
    required: false,
    description: 'Whether and how this agent reads/writes conversation memory. Only takes effect when at least one Tool node is also attached to this AI Agent.',
    options: ['none', 'conversation', 'user'],
    defaultValue: 'none',
    helpText: help(
      'Controls whether the agent loads prior conversation history before answering and saves the new turn afterward, and at what scope (per conversation vs. per user across conversations).',
      'Without memory, every run is stateless — the agent only sees what this run\'s input and system prompt give it, with no awareness of earlier messages in the same chat.',
      'Set to conversation or user when this agent should remember earlier turns (e.g., a support chatbot that should recall what the customer already said). Leave as none for one-shot, stateless tasks like classifying a single incoming record.',
      'Choose none, conversation, or user from the dropdown. If a Memory node is attached to this agent\'s Memory port and this is left at none, the runtime automatically upgrades it to conversation — you do not have to change this field just because a Memory node is attached.',
      'Set by the workflow designer, informed by whether a Memory sidecar node is attached and what scope the use case needs.',
      'The response reflects awareness of prior turns when memory is active; the output field memory_written (true/false, inside the agent\'s internal result, not a top-level {{$json}} field on this dropdown\'s own line) confirms whether this run actually wrote to memory.',
      'One of none, conversation, or user.',
      'A recurring support chatbot uses conversation so it remembers earlier messages within the same chat thread, but not across different customers.',
      'IMPORTANT — this field (and the attached Memory node) has no effect at all unless at least one Tool node is also attached to this AI Agent\'s Tool port: with no Tool attached, the agent runs a single-shot legacy path that never reads or writes memory, regardless of this setting or a connected Memory node.',
      'Do not attach only a Memory node expecting it to work — attach at least one Tool node as well, even a simple one, or memory is silently never read or written.',
    ),
    example: 'conversation',
  }),
  field({
    name: 'Approval Gate',
    internalKey: 'requireApprovalFor',
    type: 'select',
    required: false,
    description: 'Which class of attached-tool actions require human approval before running. Only relevant when at least one Tool node is attached.',
    options: ['none', 'destructive', 'write_and_destructive'],
    defaultValue: 'destructive',
    helpText: help(
      'A safety gate that blocks the agent from actually running a tool call the registry classifies as risky, until a human approves it.',
      'It stops an autonomous agent from silently deleting, cancelling, or otherwise irreversibly changing data just because the model decided to.',
      'This field only matters when at least one Tool node is attached. Keep the default (destructive) for any agent whose tools can delete or cancel records. Loosen to none only for read-only or low-stakes tool sets you fully trust.',
      'Choose none (never block), destructive (block only destructive actions like delete/cancel), or write_and_destructive (also block create/update actions) from the dropdown.',
      'Set by the workflow designer based on how much autonomy the agent should have over its attached tools. Each tool operation\'s risk class (none/read/write/destructive) comes from registry metadata for that node/operation; an operation with no explicit classification defaults to write.',
      'A blocked call returns a failure output for that tool call with code APPROVAL_REQUIRED ("Tool <name> requires approval before execution") instead of running it; the agent sees that refusal and must respond without having made the change.',
      'One of none, destructive, write_and_destructive.',
      'An agent with a "Delete Record" database tool keeps the default destructive so it can freely read/update but never delete without a human in the loop.',
      'An unrecognized value falls back to destructive. Setting this to none for a delete-capable tool set removes the only safety check between the model\'s decision and the actual deletion.',
      'Do not assume this reviews or logs the blocked action anywhere visible by default — it simply prevents that one tool call from executing; build a separate approval/notification step if a human needs to be alerted.',
    ),
    example: 'destructive',
  }),
  field({
    name: 'Retry Count',
    internalKey: 'retryCount',
    type: 'number',
    required: false,
    description: 'Number of retry attempts after a model call fails.',
    defaultValue: '3',
    helpText: help(
      'How many extra attempts the node should make when the model call errors or times out.',
      'Retries can recover from temporary provider failures but add time and cost.',
      'Use the default for ordinary workflows, 0 for fail-fast workflows, and a small higher value only for important batch jobs.',
      'Enter a whole number such as 0, 1, or 3.',
      'Chosen from business tolerance for delay, duplicate model calls, and cost.',
      'If a retry succeeds, downstream nodes receive {{$json.response_text}} normally; if all fail, the node throws or returns a provider-specific error.',
      'Non-negative integer.',
      'A nightly summarization workflow uses 3 retries because a delayed run is acceptable.',
      'Invalid values fall back to 3. Too many retries can slow a workflow and spend more tokens.',
      'Do not use retries to hide bad prompts or missing credentials; fix the root cause first.',
    ),
    example: '3',
  }),
  field({
    name: 'Output Format',
    internalKey: 'outputFormat',
    type: 'select',
    required: false,
    description: 'How the runtime formats the response into response_text, response_json, or response_markdown.',
    options: ['text', 'json', 'keyvalue', 'markdown'],
    defaultValue: 'text',
    helpText: help(
      'The output packaging mode: text, json, keyvalue, or markdown.',
      'It decides whether the runtime tries to parse the model answer into {{$json.response_json}} or also returns {{$json.response_markdown}}.',
      'Use text for normal replies, json for structured data, keyvalue for simple colon-separated lines, and markdown for formatted human-readable content.',
      'Choose text, json, keyvalue, or markdown from the dropdown and tell the model the same format in the System Prompt.',
      'Chosen by the workflow designer based on what the next node expects.',
      'Downstream nodes can map {{$json.response_text}}, {{$json.response_json}}, or {{$json.response_markdown}} depending on this setting.',
      'One of text, json, keyvalue, markdown.',
      'A triage workflow chooses json and asks for {"priority":"high","reason":"..."}.',
      'If json parsing fails, the runtime wraps the raw text as response_json.content rather than raising a parse error.',
      'Do not choose JSON without also instructing the model to return valid JSON.',
    ),
    example: 'json',
  }),
  field({
    name: 'Include Reasoning',
    internalKey: 'includeReasoning',
    type: 'boolean',
    required: false,
    description: 'Adds a small runtime metadata object with provider and model, not full chain-of-thought.',
    defaultValue: 'false',
    helpText: help(
      'A toggle that adds a reasoning metadata object to the output.',
      'The current runtime adds steps, provider, and model; it does not expose private chain-of-thought.',
      'Enable it while testing or when audit logs need to know which provider/model answered.',
      'Use true to include {{$json.reasoning}} or false for cleaner production output.',
      'Chosen by the workflow designer for debugging and audit needs.',
      'When enabled, downstream nodes can map {{$json.reasoning.provider}} and {{$json.reasoning.model}}.',
      'Boolean true or false.',
      'A QA workflow enables it during rollout to confirm Gemini answered before notifications are sent.',
      'If false, the answer still works but no reasoning metadata is returned.',
      'Do not expect this to show the model private reasoning process; it is runtime metadata only.',
    ),
    example: 'false',
  }),
];

export const aiAgentDoc: NodeDoc = {
  slug: 'ai_agent',
  displayName: 'AI Agent',
  category: 'AI',
  logoUrl: '/icons/nodes/ai_agent.svg',
  description: 'Run a prompt-driven AI agent that extracts user input from workflow data, calls the selected LLM provider, and returns structured response fields. Runtime behavior forks on whether a Tool node is attached to this agent\'s Tool port: with no Tool attached, it makes exactly one model call (fast, simple, ignores Max Iterations/Agent Timeout/Tool Result Limit/Repeated Tool Call Limit/Memory Scope/Approval Gate entirely); with one or more Tools attached, it runs a full think-call-tool-repeat loop where all of those fields take effect.',
  credentialType: 'AI provider credentials',
  credentialSetupSteps: [
    'Create the provider connection or environment key needed by the selected Model. Gemini can use the configured Gemini wallet/key pool; Claude and OpenAI model choices need their matching provider key.',
    'Store provider secrets in CtrlChecks Connections, credential vault, wallet, or worker environment variables. Do not put API keys in User Input, System Prompt, or ordinary business payload fields.',
    'Connect this node output to downstream parser, message, approval, or storage steps; any service node account connection belongs on that downstream service node.',
    'Test with a short harmless prompt before using long customer data, because retries and long max token limits can increase provider cost.',
  ],
  credentialDocsUrl: 'https://docs.ctrlchecks.com',
  resources: [
    {
      name: 'Configuration',
      description: 'AI Agent has one runtime operation: prepare a system/user message pair, call the detected LLM provider, and package the response.',
      operations: [
        {
          name: 'Run Agent (No Tools Attached)',
          value: 'default',
          description: 'Extracts a user message from User Input or upstream fields, applies the System Prompt, calls the selected model once with timeout/retry handling, and returns response_text plus optional response_json, response_markdown, and reasoning metadata. This is what runs whenever no Tool node is attached to this agent\'s Tool port — Max Iterations, Agent Timeout (ms), Tool Result Limit, Repeated Tool Call Limit, Memory Scope, and Approval Gate are all ignored in this mode.',
          fields,
          outputExample: { response_text: 'The ticket is billing related and should be routed to Tier 2.', response_json: { category: 'billing', priority: 'medium' }, confidence_score: 0.8, used_tools: [], memory_written: false, error_flag: false, error_message: null, reasoning: { steps: 1, provider: 'gemini', model: 'gemini-3.5-flash' } },
          outputDescription: 'response_text contains the model answer. response_json is parsed JSON/key-value output or null. response_markdown appears only for markdown mode. confidence_score is fixed at 0.8 today. used_tools is always an empty list in this mode (no tools ran). memory_written is always false in this mode, even if a Memory node is attached — memory only activates when a Tool is also attached (see Memory Scope). error_flag and error_message are normal output flags, while provider failures may return _error or throw. reasoning appears only when Include Reasoning is true.',
          usageExample: { scenario: 'Classify a support message and return structured routing data for the next workflow step', inputValues: { userInput: '{{$json.message}}', model: 'gemini-3.5-flash', systemPrompt: 'Classify the support request and return JSON with category and priority.', temperature: '0.2', maxTokens: '800', topP: '1.0', frequencyPenalty: '0.0', presencePenalty: '0.0', timeoutLimit: '30000', retryCount: '3', outputFormat: 'json', includeReasoning: 'true' }, expectedOutput: 'Use {{$json.response_json.category}} to route the ticket and {{$json.response_text}} for the audit note.' },
          externalDocsUrl: 'https://docs.ctrlchecks.com',
        },
        {
          name: 'Run Agent (One Or More Tools Attached)',
          value: 'default',
          description: 'Runs a think-then-optionally-call-a-tool loop: the model can call any attached Tool node, see its (sanitized, length-capped) result, and decide whether to call another tool or produce a final answer, up to Max Iterations. This is what runs whenever at least one Tool node is attached to this agent\'s Tool port — this is the only mode where Max Iterations, Agent Timeout (ms), Tool Result Limit, Repeated Tool Call Limit, Memory Scope, and Approval Gate actually take effect.',
          fields,
          outputExample: { success: true, output: 'I looked up the order and it is out for delivery, arriving today.', iterations: 2, toolCalls: [{ toolId: 'tool_1', nodeType: 'google_sheets', success: true, durationMs: 340 }], metadata: { model: 'gemini-3.5-flash', provider: 'gemini', memoryScope: 'conversation', durationMs: 1120 }, response_text: 'I looked up the order and it is out for delivery, arriving today.', response_json: null, used_tools: ['google_sheets'], memory_written: true, error_flag: false, error_message: null },
          outputDescription: 'response_text/response_json/response_markdown work the same as the no-tools mode. used_tools now lists the node type of every tool actually called this run, and memory_written reflects whether Memory Scope resolved to something other than none for this run (also true if a Memory node is attached and Memory Scope was left at none, since the runtime auto-upgrades that combination to conversation). iterations and toolCalls (one entry per tool call, with success/duration) are additional fields not present in the no-tools mode. A blocked or failed tool call does not stop the whole run and does not return _error at the top level — the agent instead sees a failure output for that specific call (see commonErrors below, codes like APPROVAL_REQUIRED/LOOP_DETECTED/TOOL_NOT_ATTACHED) and can try something else on its next iteration, up to Max Iterations. A run that exhausts Max Iterations or exceeds Agent Timeout (ms) does throw, so downstream nodes see no output at all rather than an _error field.',
          usageExample: { scenario: 'Look up a customer\'s order status in Google Sheets before replying in chat', inputValues: { userInput: '{{$json.message}}', model: 'gemini-3.5-flash', systemPrompt: 'You can look up orders using the attached Google Sheets tool before answering.', maxIterations: '6', timeoutMs: '90000', maxToolResultChars: '6000', maxRepeatedToolCalls: '2', memoryScope: 'conversation', requireApprovalFor: 'destructive' }, expectedOutput: 'Use {{$json.response_text}} for the reply and {{$json.used_tools}} to confirm the Google Sheets tool actually ran.' },
          externalDocsUrl: 'https://docs.ctrlchecks.com',
        },
      ],
    },
  ],
  commonErrors: [
    { error: 'Gemini/provider credential error in _error', cause: 'The selected provider has no usable key, wallet, vault value, or key-pool access.', fix: 'Connect the correct AI provider account or configure the worker environment key for the selected model.' },
    { error: 'Timeout (no Tool attached)', cause: 'The single model attempt exceeded Timeout (timeoutLimit) and retries were exhausted.', fix: 'Raise Timeout, lower Max Tokens, simplify the prompt, or use a faster model.' },
    { error: 'AI Agent timed out (code TIMEOUT, Tool attached)', cause: 'The whole agent loop — every model call plus every tool call combined — exceeded Agent Timeout (ms).', fix: 'Raise Agent Timeout (ms), reduce Max Iterations, or use faster/fewer tools. Raising Timeout (timeoutLimit) instead has no effect once a Tool is attached.' },
    { error: 'AI Agent reached the maximum iteration limit (code ITERATION_LIMIT)', cause: 'The agent used up all of Max Iterations without producing a final answer.', fix: 'Raise Max Iterations, or simplify the System Prompt/task so fewer tool calls are needed.' },
    { error: 'Repeated identical tool call detected (code LOOP_DETECTED)', cause: 'The model called the same tool with the exact same arguments more times in a row than Repeated Tool Call Limit allows.', fix: 'Raise Repeated Tool Call Limit if repeats are expected, or fix the tool/prompt so the model does not keep retrying an unchanged call.' },
    { error: 'Tool "<name>" requires approval before execution (code APPROVAL_REQUIRED)', cause: 'Approval Gate blocked a tool call classified as destructive (or write, under write_and_destructive) before it could run.', fix: 'This is a safety gate, not a bug — either accept that this action needs a human, or loosen Approval Gate if the attached tool set is fully trusted.' },
    { error: 'Model requested a tool that is not attached to this agent (code TOOL_NOT_ATTACHED)', cause: 'The model tried to call a tool name that does not match any node actually attached to this agent\'s Tool port.', fix: 'Confirm the intended Tool node is attached, or adjust the System Prompt so the model only references attached tools.' },
    { error: 'JSON output is wrapped as response_json.content', cause: 'Output Format is json but the model returned text that could not be parsed as JSON.', fix: 'Add strict JSON instructions to System Prompt and lower Temperature.' },
    { error: 'No message-like field found in upstream object', cause: 'The incoming object did not contain message, text, input, content, query, prompt, or userInput.', fix: 'Map the exact field into User Input or create a Set/Edit Fields node that exposes message.' },
    { error: 'Memory node attached but memory_written stays false', cause: 'A Memory node is attached but no Tool node is attached — memory only activates on the Tool-attached execution path.', fix: 'Attach at least one Tool node alongside Memory, even a simple one, so the agent runs the loop that actually reads/writes memory.' },
  ],
  relatedNodes: ['ai_chat_model', 'chat_model', 'memory', 'tool', 'openai_gpt', 'anthropic_claude', 'google_gemini'],
};
