import type { FieldDoc, NodeDoc } from '../types';

const help = (field: string, why: string, when: string, enter: string, source: string, later: string, format: string, example: string, wrong: string, mistake: string) => `What this field is: ${field}
Why it matters: ${why}
When to fill it: ${when}
What to enter: ${enter}
Where the value comes from: ${source}
How to use it later: ${later}
Accepted format: ${format}
Real workplace example: ${example}
If it is empty or wrong: ${wrong}
Common mistake: ${mistake}`;

const fields: FieldDoc[] = [
  { name: 'Provider', internalKey: 'provider', type: 'select', required: true, description: 'UI-visible provider field. Runtime currently ignores it and returns provider gemini.', options: ['gemini'], defaultValue: 'gemini', helpText: help('The provider dropdown shown in the Chat Model panel; currently only gemini is offered.', 'This node is a support/config node, and the runtime is hardcoded to return Gemini config.', 'Leave it as gemini. Use provider-specific AI nodes when you need OpenAI, Claude, or Cohere execution.', 'Select Google Gemini / gemini.', 'Chosen in the UI, not retrieved from a provider account.', 'The output includes {{$json.provider}} as gemini regardless of other hidden config.', 'One option: gemini.', 'An AI Agent support workflow leaves Provider as gemini for the default model configuration.', 'Changing generated configs to another provider will not change runtime output for this node.', 'Do not use this node as a multi-provider chat completion node; it is not that today.'), example: 'gemini' },
  { name: 'API Key', internalKey: 'apiKey', type: 'string', required: false, description: 'Legacy UI field that the current chat_model executor does not read.', helpText: help('A visible key field left from older provider-config designs.', 'The current runtime does not use it; Chat Model returns static Gemini config and does not make a provider API call.', 'Leave it empty. Put provider keys on the actual AI execution node or configured connection/wallet.', 'Nothing is required here for current runtime behavior.', 'If used at all, it would come from a secure credential store, not ordinary input data.', 'No downstream output proves this key was used because it is ignored.', 'Secret text, but should be blank for this node today.', 'A workflow leaves API Key empty and uses AI Agent or AI Chat Model for the actual model call.', 'Pasting a key here does not authenticate anything in the current executor.', 'Do not store production API keys in this field expecting Chat Model to call the provider.'), example: '' },
  { name: 'Model Name', internalKey: 'model', type: 'select', required: true, description: 'UI model selector ignored by the current runtime, which returns gemini-3.5-flash.', options: ['gemini-3.5-flash', 'gemini-3.1-pro-preview', 'gemini-3.1-flash-lite'], defaultValue: 'gemini-3.5-flash', helpText: help('The model dropdown displayed for this support node.', 'The runtime currently returns model gemini-3.5-flash no matter which value is configured.', 'Leave it at gemini-3.5-flash unless the worker executor changes.', 'Choose gemini-3.5-flash in the UI.', 'Chosen in the workflow editor.', 'Downstream AI Agent-style configs can read {{$json.model}}, which will be gemini-3.5-flash.', 'One of gemini-3.5-flash, gemini-3.1-pro-preview, gemini-3.1-flash-lite in the UI.', 'A legacy agent canvas uses Chat Model only to emit a Gemini config object.', 'Changing it should not alter the current output.', 'Do not assume this node performs a model call; it only returns configuration fields.'), example: 'gemini-3.5-flash' },
  { name: 'System Message / Prompt', internalKey: 'prompt', type: 'textarea', required: true, description: 'Legacy UI prompt field ignored by the current chat_model executor.', helpText: help('A visible prompt field in the panel.', 'Despite the label, the current chat_model runtime does not send this prompt to any model.', 'Avoid using this node for direct prompting. Use AI Chat Model, AI Agent, or a provider-specific node instead.', 'If kept for legacy configs, write a short note only; it will not be sent by this executor.', 'Usually from old workflow templates, not from a current runtime need.', 'No downstream response is generated from this prompt; downstream only receives provider/model/temperature/_chat_model_config.', 'Plain text, but ignored today.', 'A migrated workflow moves the actual prompt to AI Chat Model and leaves this support node unused.', 'If you expect an answer, none is generated by Chat Model itself.', 'Do not place business instructions here expecting the model to follow them.'), example: 'You are a helpful assistant.' },
  { name: 'Temperature', internalKey: 'temperature', type: 'number', required: false, description: 'Only runtime-used configurable field; returned with the static Gemini model config.', defaultValue: '0.7', helpText: help('The creativity value included in the config object this node returns.', 'It is the only visible field the current executor actually reads and preserves in output.', 'Set it only when another workflow step consumes the Chat Model config output.', 'Enter a decimal such as 0.2, 0.7, or 1.0.', 'Chosen by the workflow designer.', 'Downstream nodes can reference {{$json.temperature}} along with {{$json.provider}}, {{$json.model}}, and {{$json._chat_model_config}}.', 'Number. Invalid or blank values fall back to 0.7.', 'A legacy AI Agent setup reads the returned temperature when configuring its model behavior.', 'If blank or invalid, the output temperature is 0.7.', 'Do not confuse this with a model call; Chat Model does not generate text.'), example: '0.7' },
];

export const chatModelDoc: NodeDoc = {
  slug: 'chat_model',
  displayName: 'Chat Model',
  category: 'AI',
  logoUrl: '/icons/nodes/chat_model.svg',
  description: 'UI-visible but backend-internal support node that returns static Gemini chat model configuration and does not call an AI provider.',
  credentialType: 'None',
  credentialSetupSteps: [
    'No third-party account connection is required; this support node does not use credentials or call an external AI API by itself.',
    'Connect this node output only when a legacy workflow expects a chat model config object; any real AI provider or service node account connection belongs on the node that actually calls the model.',
    'Do not paste API keys into this node. The current executor ignores apiKey and returns provider/model/temperature/_chat_model_config.',
    'For a real prompt/response call, use AI Chat Model, AI Agent, Anthropic Claude, OpenAI GPT, Google Gemini, or Cohere instead.',
  ],
  credentialDocsUrl: 'https://docs.ctrlchecks.com',
  resources: [{ name: 'Configuration', description: 'Chat Model has one support operation: return Gemini model configuration for legacy/internal agent wiring.', operations: [{
    name: 'Return Config',
    value: 'default',
    description: 'Reads Temperature, ignores Provider/API Key/Model/Prompt in the current executor, and returns the incoming fields plus provider gemini, model gemini-3.5-flash, temperature, and _chat_model_config true.',
    fields,
    outputExample: { orderId: 'A100', provider: 'gemini', model: 'gemini-3.5-flash', temperature: 0.7, _chat_model_config: true },
    outputDescription: 'provider is always gemini. model is always gemini-3.5-flash. temperature is parsed from config or defaults to 0.7. _chat_model_config is true. Incoming fields are spread into the output. No response text is generated and no _error path is implemented for normal config values.',
    usageExample: { scenario: 'Preserve a legacy agent-support config while moving real prompting to AI Agent', inputValues: { provider: 'gemini', apiKey: '', model: 'gemini-3.5-flash', prompt: 'You are a helpful assistant.', temperature: '0.7' }, expectedOutput: 'Use {{$json._chat_model_config}} to detect this config object and {{$json.temperature}} if a downstream step still consumes it.' },
    externalDocsUrl: 'https://docs.ctrlchecks.com',
  }] }],
  commonErrors: [
    { error: 'No AI response is generated', cause: 'Chat Model is a support/config node, not a direct prompt execution node.', fix: 'Use AI Chat Model or AI Agent for real model responses.' },
    { error: 'Provider, API Key, Model, and Prompt are ignored', cause: 'The legacy executor hardcodes provider/model and only reads temperature.', fix: 'Do not rely on those fields until the worker executor changes.' },
    { error: 'Missing downstream account connection', cause: 'A later service node account connection is still required even if Chat Model ran first.', fix: 'Connect credentials on the downstream email, CRM, storage, or messaging node.' },
    { error: 'Configured temperature looks changed but only metadata changes', cause: 'This node returns temperature in a config object and does not generate a model response.', fix: 'Use AI Chat Model, AI Agent, or a provider-specific node when temperature must affect generated text.' },
  ],
  relatedNodes: ['ai_agent', 'ai_chat_model', 'google_gemini'],
};
