import type { NodeDoc } from '../types';

export const csvDoc: NodeDoc = {
  slug: 'csv',
  displayName: 'CSV',
  category: 'Data',
  logoUrl: '/icons/nodes/csv.svg',
  description: 'Parse CSV text into rows/items or generate CSV text from object arrays.',
  credentialType: 'None',
  credentialSetupSteps: ['This node does not need a saved account connection.'],
  credentialDocsUrl: 'https://docs.ctrlchecks.com',
  resources: [
    {
      name: 'Operations',
      description: 'CSV exposes operation choices directly.',
      operations: [
        {
          name: 'Parse',
          value: 'parse',
          description: 'Parse CSV text into items, rows, and headers.',
          fields: [
            {
              name: 'CSV',
              internalKey: 'csv',
              type: 'textarea',
              required: false,
              description: 'CSV content to parse.',
              helpText: 'Provide CSV text or an expression such as {{$json.content}}.',
              placeholder: 'name,email\nAda,ada@example.com',
              example: '{{$json.content}}',
            },
            {
              name: 'Delimiter',
              internalKey: 'delimiter',
              type: 'string',
              required: false,
              description: 'Delimiter used to split fields. Use \\t for tab-delimited data.',
              helpText: 'Default is comma. Semicolon, tab, and pipe are also supported.',
              placeholder: ',',
              example: ',',
              defaultValue: ',',
            },
            {
              name: 'Has Header',
              internalKey: 'hasHeader',
              type: 'boolean',
              required: false,
              description: 'Whether the first row contains column names.',
              helpText: 'When false, columns are named 0, 1, 2, and so on.',
              defaultValue: 'true',
            },
          ],
          outputExample: {
            items: [{ Name: 'Alice', Email: 'alice@example.com', Plan: 'Pro' }],
            rows: [{ Name: 'Alice', Email: 'alice@example.com', Plan: 'Pro' }],
            headers: ['Name', 'Email', 'Plan'],
          },
          outputDescription: 'items/rows: Parsed row objects. headers: Column names used as object keys.',
          usageExample: {
            scenario: 'Parse a CSV file downloaded from Google Drive',
            inputValues: { csv: '{{$json.content}}', delimiter: ',', hasHeader: 'true' },
            expectedOutput: 'Each CSV row becomes an object in `{{$json.items}}` and `{{$json.rows}}`.',
          },
          externalDocsUrl: 'https://docs.ctrlchecks.com',
        },
        {
          name: 'Generate',
          value: 'generate',
          description: 'Generate CSV text from an array of objects.',
          fields: [
            {
              name: 'Data',
              internalKey: 'data',
              type: 'json',
              required: false,
              description: 'Array of objects to generate. If empty, runtime uses input.items.',
              helpText: 'Use an array expression such as {{$json.users}}, or leave blank to use upstream items.',
              placeholder: '[{"name":"Ada","email":"ada@example.com"}]',
              example: '{{$json.users}}',
            },
            {
              name: 'Delimiter',
              internalKey: 'delimiter',
              type: 'string',
              required: false,
              description: 'Delimiter used between generated fields.',
              helpText: 'Default is comma. Values are quoted when needed.',
              placeholder: ',',
              example: ',',
              defaultValue: ',',
            },
          ],
          outputExample: { csv: 'Name,Email,Status\nAlice,alice@example.com,Active' },
          outputDescription: 'csv: The generated CSV string.',
          usageExample: {
            scenario: 'Export users as CSV before uploading a file',
            inputValues: { data: '{{$json.users}}', delimiter: ',' },
            expectedOutput: 'CSV text is available in `{{$json.csv}}`.',
          },
          externalDocsUrl: 'https://docs.ctrlchecks.com',
        },
      ],
    },
  ],
  commonErrors: [
    {
      error: 'Empty CSV input',
      cause: 'Parse received an empty CSV string.',
      fix: 'Map CSV to the csv field or pass CSV text from the previous node.',
    },
    {
      error: 'No data to generate',
      cause: 'Generate received no data array and no upstream items.',
      fix: 'Set Data to an array of objects or connect a node that outputs items.',
    },
  ],
  relatedNodes: [],
};
