import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const facebookWebhookDocs = 'https://developers.facebook.com/docs/graph-api/webhooks/';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Facebook OAuth2 connection ID used when registering Page webhooks.',
    helpText: 'What this field means: Connection points to the saved Facebook OAuth2 account that can see and manage the Facebook Page. The visual node usually uses the selected/default Facebook connection rather than asking you to type this ID. Why it matters: CtrlChecks uses this connection when it registers or tests the Page webhook and when it needs a Page access token. When to fill it: Leave it blank when the workflow should use your active Facebook connection. Use a specific connection only when your workspace has more than one Facebook account. What to enter: Select the Facebook connection in the Connections UI, or use the saved connection ID in generated workflow config. Where the value comes from: CtrlChecks Connections stores it after OAuth sign-in; do not copy a Meta access token into this field. How to use it later: This setup value is not emitted as {{$json.connectionId}}; downstream Facebook reply nodes use {{$json.senderId}}, {{$json.pageId}}, or {{$json.commentId}} from the trigger output. Accepted format: Saved connection reference such as facebook_oauth_123, not a raw OAuth token. Real workplace example: A support workflow uses the Facebook connection owned by the social care team so it can receive Messenger events for the company Page. If it is empty or wrong: Empty falls back to the active Facebook connection; a wrong ID can cause No active Facebook connection found or Selected connection is not a Facebook connection. Common mistake: Pasting a Graph API access token here instead of connecting Facebook in Connections.',
    placeholder: 'Use selected/default Facebook connection',
    example: 'facebook_oauth_123',
    notes: 'Credential-owned backend field. Prefer the Connections picker/default connection instead of editing this as normal workflow data.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Facebook event families that are allowed to start this workflow.',
    helpText: 'What this field means: Event Types decides which normalized Facebook events this trigger accepts. Why it matters: Messenger messages, comments, mentions, postbacks, lead ads, and feed changes usually need different workflows. When to fill it: Keep the default while testing; narrow it before production so unrelated Page activity does not start the workflow. What to enter: Use comma-separated values such as message, comment, mention, postback, leadgen, feed. The runtime also accepts aliases such as messages, dm, comments, leads, and feed_event. Where the value comes from: Choose the Meta webhook fields and business events your team wants to handle. How to use it later: Route with {{$json.eventType}}; message covers message.text and message.media, while feed covers feed.post and feed.comment. Accepted format: Comma-separated text or an array in generated config. Real workplace example: message, postback for an AI Messenger assistant; comment, feed for public comment moderation; leadgen for lead ad routing. If it is empty or wrong: Empty defaults to message, comment, mention, postback, leadgen, feed. Unsupported values cause matching events to be ignored with no workflow execution. Common mistake: Choosing leadgen without subscribing the Meta app/Page to the leadgen webhook field and granting leads_retrieval.',
    placeholder: 'message, comment, mention, postback, leadgen, feed',
    defaultValue: 'message, comment, mention, postback, leadgen, feed',
    example: 'message, postback',
    notes: 'Supported families: message, comment, mention, postback, leadgen, feed. Runtime-normalized detailed types include message.text, message.media, feed.post, and feed.comment.',
  },
  {
    name: 'Facebook Page ID',
    internalKey: 'pageId',
    type: 'string',
    required: false,
    description: 'Optional Page ID filter. Only events for this Page are accepted when set.',
    helpText: 'What this field means: Facebook Page ID is the numeric ID of the Page this workflow should listen to. Why it matters: One Meta app or OAuth account may manage several Pages, and this filter keeps the wrong Page from starting the workflow. When to fill it: Fill it when your connection can access multiple Pages or when you want webhook registration to subscribe one exact Page. What to enter: The Page ID, not the Page name, profile URL, username, or Business Manager ID. Where the value comes from: Facebook OAuth test calls read /me/accounts, and Meta Business Suite/Page settings can show the Page ID. How to use it later: The trigger output includes {{$json.pageId}} so reply nodes can send from or act on the same Page. Accepted format: Numeric text such as 123456789012345. Real workplace example: A retail brand has separate India and US Pages, so the India support workflow filters to the India Page ID only. If it is empty or wrong: Empty accepts events for any connected/subscribed Page. A wrong ID causes valid events to be ignored as a different Page, or webhook registration may not find a Page access token. Common mistake: Pasting a post ID, comment ID, or page URL instead of the Page ID.',
    placeholder: '123456789012345',
    example: '123456789012345',
  },
  {
    name: 'Allowed Sender IDs',
    internalKey: 'allowedSenderIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated Facebook PSIDs or user IDs allowed to start this workflow.',
    helpText: `What this field means: Allowed Sender IDs limits the trigger to specific Facebook senders. Why it matters: It can keep a testing or VIP workflow from reacting to every Page visitor or commenter. When to fill it: Use it for internal testing, approved partner users, or a controlled rollout. Leave it blank for normal public Page automations. What to enter: Comma-separated sender IDs or PSIDs such as 1234567890, 9876543210. Where the value comes from: Use senderId/chatId from a previous Facebook Trigger test run, Messenger PSID records, or an internal allowlist. How to use it later: The accepted event still outputs {{$json.senderId}} and {{$json.chatId}} for replies or audits. Accepted format: Comma-separated text or an array in generated config. Real workplace example: Before launching a Messenger assistant, the team allows only two employee PSIDs so they can test without responding to customers. If it is empty or wrong: Empty allows every matching sender; a wrong ID silently ignores that person's events. Common mistake: Using a person's visible Facebook profile URL instead of the Page-scoped sender ID from a webhook event.`,
    placeholder: '1234567890, 9876543210',
    example: '1234567890, 9876543210',
  },
  {
    name: 'Verify Token',
    internalKey: 'verifyToken',
    type: 'password',
    required: false,
    description: 'Shared value Meta sends during webhook callback verification.',
    helpText: 'What this field means: Verify Token is the shared text Meta sends during the webhook challenge to prove you configured the callback intentionally. Why it matters: Meta will not activate the webhook callback unless CtrlChecks returns the challenge for the exact matching token. When to fill it: Fill it before verifying the callback URL in Meta for Developers. What to enter: A random phrase or generated secret that is unique to this workflow, such as fb-webhook-verify-2026-support. Where the value comes from: Create it yourself in a password manager or admin setup note, then enter the exact same value in Meta Webhooks. How to use it later: This token is only for webhook setup; it is never emitted as {{$json.verifyToken}} for downstream nodes. Accepted format: Plain text shared token. Real workplace example: The social operations admin sets fb-support-prod-verify-rotate-me while adding the CtrlChecks callback URL to the Meta app. If it is empty or wrong: Callback verification returns Invalid verify token, and Meta will not save the webhook URL. Common mistake: Confusing this with a Facebook OAuth access token, Page token, app secret, or account password.',
    placeholder: 'fb-webhook-verify-2026-support',
    example: 'fb-webhook-verify-2026-support',
    notes: 'The visual config field uses a standard text control because password is not a supported node panel field type, but the value should still be treated as setup-secret material.',
  },
  {
    name: 'Validate Meta Signature',
    internalKey: 'validateSignature',
    type: 'boolean',
    required: false,
    description: 'Whether incoming webhook requests must include a valid X-Hub-Signature-256 signature.',
    helpText: 'What this field means: Validate Meta Signature checks that Meta signed the webhook request with your app secret. Why it matters: A public webhook URL should reject requests that did not come through the expected Meta app. When to fill it: Keep it enabled for production. Disable only for a controlled local test where you cannot generate Meta signatures. What to enter: true/enabled for real workflows; false/disabled only for temporary debugging. Where the value comes from: This is a security choice made by the workflow owner or admin. The app secret itself comes from worker environment variables META_APP_SECRET or FACEBOOK_APP_SECRET, not from a workflow field. How to use it later: This setting protects whether a workflow starts; it is not output as {{$json.validateSignature}}. Accepted format: Boolean checkbox. Real workplace example: A live Messenger support workflow keeps validation enabled so only signed Meta webhook deliveries can create replies or tickets. If it is empty or wrong: Default true requires the worker app secret; if the secret is missing or mismatched, requests fail with Invalid Facebook webhook signature. Common mistake: Turning this off permanently instead of configuring META_APP_SECRET/FACEBOOK_APP_SECRET correctly.',
    defaultValue: 'true',
    example: 'true',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive Facebook event',
  value: 'receive',
  description: 'Receives Meta webhook deliveries for Facebook Page and Messenger activity, verifies the callback token during setup, optionally validates request signatures, normalizes Messenger messages, Page comments, mentions, postbacks, lead ads, and feed changes, then starts one workflow execution per accepted event.',
  fields,
  outputExample: {
    eventId: 'm_abc123',
    eventType: 'message.text',
    source: 'facebook',
    userId: '1234567890',
    username: '',
    text: 'Can you help me track my order?',
    timestamp: '2026-07-19T10:20:00.000Z',
    chatId: '1234567890',
    senderId: '1234567890',
    recipientId: '123456789012345',
    pageId: '123456789012345',
    messageId: 'm_abc123',
    messageType: 'text',
    commentId: null,
    postId: null,
    parentId: null,
    leadgenId: null,
    formId: null,
    postbackPayload: '',
    field: 'messages',
    verb: '',
    item: '',
    raw: { entry: { id: '123456789012345' }, messaging: { message: { mid: 'm_abc123' } } },
    trigger: 'facebook',
    workflow_id: 'workflow_123',
    node_id: 'facebook-trigger-1',
    sessionId: 'facebook_workflow_123_1234567890',
    _facebook: true,
  },
  outputDescription: 'eventId: stable message/change/lead ID or generated fallback. eventType: normalized type such as message.text, message.media, comment, mention, postback, leadgen, feed.post, or feed.comment. source: facebook. userId: sender/user ID when available. username: sender name when Meta includes it. text: message/comment/postback text or attachment URL fallback. timestamp: Meta event time normalized to ISO. chatId: sender conversation ID for Messenger-style replies. senderId: Facebook PSID/user ID. recipientId: Page or recipient ID. pageId: Page ID for filtering and replies. messageId: Messenger message ID. messageType: text, attachment type, postback, feed, comment, mention, or leadgen. commentId: Page comment ID. postId: Page post ID. parentId: parent post/comment ID. leadgenId: Lead Ads lead ID. formId: Lead Ads form ID. postbackPayload: quick reply/postback payload. field: Meta webhook field such as messages, feed, comment, mention, or leadgen. verb: feed change action when supplied. item: feed item type. raw: original Meta event fragment. trigger: facebook marker. workflow_id: workflow receiving the event. node_id: trigger node ID. sessionId: facebook_workflowId_chatId or generated fallback. _facebook: true marker.',
  usageExample: {
    scenario: 'Reply to Facebook Messenger questions with an AI Agent and send the answer back from the same Page',
    inputValues: {
      connectionId: '',
      eventTypes: 'message, postback',
      pageId: '123456789012345',
      allowedSenderIds: '',
      verifyToken: 'fb-webhook-verify-2026-support',
      validateSignature: 'true',
    },
    expectedOutput: 'Use {{$json.text}} as the visitor question, {{$json.senderId}} as the Facebook recipientId, {{$json.pageId}} as the Page ID for the Facebook reply node, and {{$json.eventType}} to route messages separately from postbacks or comments.',
  },
  externalDocsUrl: facebookWebhookDocs,
};

export const facebookTriggerDoc: NodeDoc = {
  slug: 'facebook_trigger',
  displayName: 'Facebook Page/Messenger Trigger',
  category: 'Triggers',
  logoUrl: '/icons/nodes/facebook_trigger.svg',
  description: 'Start workflows from real-time Facebook Page and Messenger events delivered through Meta webhooks.',
  credentialType: 'Facebook OAuth2',
  credentialSetupSteps: [
    'Connect Facebook OAuth2 in Connections with the Facebook account that manages the Page. CtrlChecks stores OAuth access token material in the credential vault; do not paste Graph API access tokens into normal workflow fields.',
    'The connection requests Page and Messenger permissions used by trigger and reply workflows: pages_show_list, pages_read_engagement, pages_manage_metadata, pages_manage_posts, pages_manage_engagement, pages_messaging, leads_retrieval, public_profile, and email. Some Page permissions may require Meta App Review before production use.',
    'Test the connection with the built-in Facebook test request. It calls https://graph.facebook.com/v19.0/me/accounts?fields=id,name,access_token&limit=5 to confirm the account can list Pages and retrieve Page access token data.',
    'Set Event Types, optional Facebook Page ID, optional Allowed Sender IDs, Verify Token, and Validate Meta Signature on the trigger node.',
    'In Meta for Developers -> Webhooks, add the generated CtrlChecks callback URL for this workflow/node and enter the exact same Verify Token. Subscribe the Page app to messages, feed, mention, and leadgen fields as needed.',
    'Keep Validate Meta Signature enabled in production and configure META_APP_SECRET or FACEBOOK_APP_SECRET on the worker so CtrlChecks can verify X-Hub-Signature-256.',
    'Activation/registration may attempt to subscribe the Page automatically through /{pageId}/subscribed_apps. The returned setup status still marks manualSetupRequired: true, so confirm the subscription in Meta if the automatic subscribe call is not permitted.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Facebook OAuth2 connection authorizes Facebook webhook/list/Page-token behavior, while Slack, CRM, email, database, or ticketing nodes use their own credentials.',
  ],
  credentialDocsUrl: facebookWebhookDocs,
  resources: [
    {
      name: 'Meta webhook',
      description: 'Receives Facebook Page and Messenger webhook deliveries, filters accepted events, and starts workflow executions with normalized event data.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Invalid verify token.',
      cause: 'Meta sent a webhook challenge with a token that does not exactly match the trigger Verify Token, or Verify Token is blank.',
      fix: 'Copy the same generated token into CtrlChecks and Meta for Developers -> Webhooks, then verify the callback URL again.',
    },
    {
      error: 'Invalid Facebook webhook signature.',
      cause: 'Validate Meta Signature is enabled and the worker has no META_APP_SECRET/FACEBOOK_APP_SECRET, the secret is wrong, or the request was not signed by the configured Meta app.',
      fix: 'Set the correct app secret on the worker, restart it, and retry a real Meta webhook delivery. Disable validation only for temporary local tests.',
    },
    {
      error: 'Facebook webhook received, no events matched this trigger.',
      cause: 'The webhook payload was valid, but Event Types, Facebook Page ID, or Allowed Sender IDs filtered out every normalized event.',
      fix: 'Broaden Event Types, clear filters temporarily, send a fresh Page/Messenger test event, then narrow the filters after confirming the output.',
    },
    {
      error: 'No active Facebook connection found. Create one in Connections first.',
      cause: 'Webhook registration or auto-subscription could not resolve a saved Facebook OAuth2 connection for the workflow owner.',
      fix: 'Connect Facebook in Connections with a Page-managing account, then rerun activation or webhook registration.',
    },
    {
      error: 'Selected connection is not a Facebook connection.',
      cause: 'The saved connection ID points to another provider or an inactive credential.',
      fix: 'Select a Facebook OAuth2 connection or leave Connection blank so CtrlChecks can use the active Facebook connection.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Facebook webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Meta must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to execute Facebook-triggered workflows.',
      cause: 'A matching event was accepted, but the worker could not call /api/execute-workflow for the new execution.',
      fix: 'Set PUBLIC_BASE_URL, restart the worker, and send another matching Facebook event.',
    },
    {
      error: 'Facebook Trigger node not found in this workflow.',
      cause: 'The callback URL points to a node ID that is missing, renamed incorrectly, or no longer has type facebook_trigger.',
      fix: 'Save the workflow with the Facebook Trigger node still present, then copy the fresh callback URL.',
    },
    {
      error: 'Next node cannot find Facebook trigger fields',
      cause: 'The next step is mapped to a field that is only present for another event type, such as commentId on a Messenger message or senderId on some leadgen events.',
      fix: 'Use {{$json.eventType}} to branch by event family before mapping event-specific fields. Use {{$json.senderId}} for Messenger replies, {{$json.commentId}} for comment replies, and {{$json.leadgenId}}/{{$json.formId}} for lead routing.',
    },
    {
      error: 'Permission denied after Facebook Trigger',
      cause: 'The trigger received the event, but the downstream Facebook reply, Slack, CRM, email, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node account connection and make sure the Facebook action node has pages_messaging/pages_manage_engagement or the relevant Page permission for the action.',
    },
  ],
  relatedNodes: ['facebook', 'ai_agent', 'slack_message', 'http_request'],
};
