import type { FieldDoc, NodeDoc, OperationDoc } from '../types';
import { richFieldHelp } from './_sharedFieldHelp';

const operationValues = [
  'get_repo',
  'list_repos',
  'create_issue',
  'update_issue',
  'close_issue',
  'list_issues',
  'get_issue',
  'add_issue_comment',
  'create_pr',
  'update_pr',
  'merge_pr',
  'list_prs',
  'get_pr',
  'add_pr_comment',
  'create_branch',
  'list_branches',
  'get_branch',
  'delete_branch',
  'create_commit',
  'list_commits',
  'get_commit',
  'create_release',
  'list_releases',
  'get_release',
  'get_workflow_runs',
  'trigger_workflow',
  'list_contributors',
];

const fields: FieldDoc[] = [
  {
    name: 'Operation',
    internalKey: 'operation',
    type: 'select',
    required: true,
    description: 'The GitHub action to run.',
    options: operationValues,
    helpText: richFieldHelp({
      what: 'The GitHub action selector. It covers repository reads, repo lists, issue create/update/close/list/get/comment, pull request create/update/merge/list/get/comment, branch create/list/get/delete, commit create/list/get, release create/list/get, workflow run reads, workflow dispatch, and contributors.',
      why: 'The operation decides which GitHub API route the social dispatcher calls and which fields become important.',
      when: 'Choose it before filling owner, repo, title, issueNumber, prNumber, branchName, file fields, release fields, workflowId, or ref.',
      enter: 'Select one visible operation value exactly.',
      source: 'The workflow goal, such as creating issues from incidents, dispatching CI, or notifying contributors.',
      later: 'Successful output keeps incoming fields and adds success, provider, action, plus GitHub response fields at the top level.',
      format: `One of: ${operationValues.join(', ')}.`,
      example: 'A CI workflow chooses trigger_workflow after a release approval event arrives.',
      empty: 'Runtime defaults GitHub to post_issue, but the visible panel defaults to get_repo; choose an explicit supported value.',
      mistake: 'Expecting a nested data object; the worker spreads provider data at the top level on success.',
    }),
    defaultValue: 'get_repo',
    example: 'create_issue',
    notes: `Supported visible options: ${operationValues.join(', ')}.`,
  },
  {
    name: 'Owner/Organization',
    internalKey: 'owner',
    type: 'string',
    required: false,
    description: 'GitHub repository owner.',
    helpText: richFieldHelp({
      what: 'The GitHub username or organization before the repository name.',
      why: 'Most repository operations call /repos/{owner}/{repo}.',
      when: 'Fill it for operations that target a specific repository.',
      enter: 'Use the first path segment from github.com/OWNER/repo or map {{$json.owner}}.',
      source: 'Repository URL, GitHub webhook payload, project config, or a previous GitHub step.',
      later: 'Incoming fields are preserved, so {{$json.owner}} can still be used after a successful GitHub node.',
      format: 'Slug string only, for example acme-platform.',
      example: 'For https://github.com/acme-platform/api-service, enter acme-platform.',
      empty: 'Operations that require a repository fail with messages such as owner, repo, and title are required.',
      mistake: 'Entering the full URL instead of only the owner/organization slug.',
    }),
    placeholder: 'acme-platform',
    example: 'acme-platform',
  },
  {
    name: 'Repository',
    internalKey: 'repo',
    type: 'string',
    required: false,
    description: 'GitHub repository name.',
    helpText: richFieldHelp({
      what: 'The repository slug after the owner.',
      why: 'Repository, issue, PR, branch, commit, release, workflow, and contributor operations need the repo slug.',
      when: 'Fill it for operations that target one repository.',
      enter: 'Use only the repository name, such as api-service, or map {{$json.repo}}.',
      source: 'Repository URL, webhook repository.name field, setup form, or previous workflow config.',
      later: 'Because successful output preserves incoming fields, downstream steps can still read {{$json.repo}}.',
      format: 'Repository slug with no owner and no .git suffix.',
      example: 'For github.com/acme-platform/api-service, enter api-service.',
      empty: 'Repository operations fail or return _error from the GitHub dispatcher.',
      mistake: 'Entering acme-platform/api-service in Repo while also filling Owner.',
    }),
    placeholder: 'api-service',
    example: 'api-service',
  },
  {
    name: 'Title',
    internalKey: 'title',
    type: 'string',
    required: false,
    description: 'Issue, pull request, or release title.',
    helpText: richFieldHelp({
      what: 'The title for create/update issue and create/update pull request operations.',
      why: 'GitHub requires a clear title when creating issues or pull requests.',
      when: 'Fill it for create_issue, update_issue, create_pr, update_pr, and any operation where you want to change a title.',
      enter: 'Type a short human-readable title or map {{$json.title}} from an incident, ticket, or release step.',
      source: 'Error log, support ticket, project form, release note generator, or upstream AI summary.',
      later: 'The returned GitHub fields can include title at the top level, and the incoming title is preserved.',
      format: 'Plain text.',
      example: 'Create issue title "[P1] Checkout fails for card payments".',
      empty: 'create_issue fails with missing required owner, repo, and title fields.',
      mistake: 'Putting the long issue body in Title instead of Body.',
    }),
    placeholder: '[P1] Checkout fails',
    example: '[P1] Checkout fails',
  },
  {
    name: 'Body',
    internalKey: 'body',
    type: 'textarea',
    required: false,
    description: 'Issue or pull request body text.',
    helpText: richFieldHelp({
      what: 'The longer description for issues and pull requests.',
      why: 'It gives maintainers context, reproduction steps, links, or review notes.',
      when: 'Fill it for create_issue, update_issue, create_pr, update_pr, or when a GitHub API action expects body text.',
      enter: 'Use plain text/markdown or map {{$json.description}}, {{$json.stack}}, or {{$json.releaseNotes}}.',
      source: 'Incident details, customer report, commit summary, AI analysis, or release note draft.',
      later: 'GitHub response fields such as body/html_url may be available top-level for downstream messages.',
      format: 'Markdown-capable text string.',
      example: 'A monitoring workflow writes stack trace and request ID into the issue body.',
      empty: 'Some operations allow an empty body; the issue/PR will have little context.',
      mistake: 'Putting JSON in Body unless you actually want GitHub to display JSON text.',
    }),
    placeholder: 'Steps to reproduce...',
    example: 'Steps to reproduce...',
  },
  {
    name: 'Workflow ID',
    internalKey: 'workflowId',
    type: 'string',
    required: false,
    description: 'GitHub Actions workflow filename or ID.',
    helpText: richFieldHelp({
      what: 'The GitHub Actions workflow identifier used by workflow operations.',
      why: 'get_workflow_runs and trigger_workflow need to know which workflow file or ID to target.',
      when: 'Fill it for get_workflow_runs and trigger_workflow.',
      enter: 'Use deploy.yml, ci.yml, or a workflow numeric ID; map {{$json.workflowId}} if supplied upstream.',
      source: '.github/workflows in the repository, the Actions tab, or a previous GitHub API response.',
      later: 'Workflow run responses can feed notifications, dashboards, or deployment checks.',
      format: 'Workflow filename such as deploy.yml or workflow ID string.',
      example: 'A release approval workflow dispatches deploy-production.yml on main.',
      empty: 'Workflow operations fail through the dispatcher or GitHub API because the workflow cannot be identified.',
      mistake: 'Using the workflow display name when GitHub expects the YAML filename.',
    }),
    placeholder: 'deploy.yml',
    example: 'deploy.yml',
  },
  {
    name: 'Branch/Ref',
    internalKey: 'ref',
    type: 'string',
    required: false,
    description: 'Branch, tag, or Git ref.',
    helpText: richFieldHelp({
      what: 'The branch, tag, or ref used by workflow, branch, commit, or PR operations.',
      why: 'GitHub needs a base/reference branch for dispatching workflows, creating commits, or comparing work.',
      when: 'Fill it for trigger_workflow, create_commit, create_branch, and operations that need a branch/ref.',
      enter: 'Use main, develop, refs/heads/main, or map {{$json.ref}} from a trigger.',
      source: 'Repository branch list, webhook ref, release process config, or a previous GitHub step.',
      later: 'The ref is preserved from input and GitHub responses may include ref/sha for downstream checks.',
      format: 'Branch name or full ref string depending on the operation.',
      example: 'A deploy workflow sets ref to main.',
      empty: 'Some operations default internally, but workflow dispatch usually needs a valid ref.',
      mistake: 'Using a pull request title instead of its source branch name.',
    }),
    placeholder: 'main',
    defaultValue: 'main',
    example: 'main',
  },
  {
    name: 'Issue Number',
    internalKey: 'issueNumber',
    type: 'number',
    required: false,
    description: 'Repository-scoped issue number.',
    helpText: richFieldHelp({
      what: 'The issue number shown as #123 in GitHub.',
      why: 'get_issue, update_issue, close_issue, and add_issue_comment need the exact issue number.',
      when: 'Fill it for operations that target one issue.',
      enter: 'Use 42 or map {{$json.number}} from create_issue/list_issues.',
      source: 'Issue URL, issue page title, webhook payload, or previous GitHub node output.',
      later: 'Use the same issueNumber in follow-up comments or close_issue steps.',
      format: 'Number only. Do not include #.',
      example: 'A support escalation adds a comment to issueNumber 42 after a customer replies.',
      empty: 'Issue-specific operations fail through the dispatcher or GitHub API.',
      mistake: 'Using database ID instead of the visible repository issue number.',
    }),
    placeholder: '42',
    example: '42',
  },
  {
    name: 'Pull Request Number',
    internalKey: 'prNumber',
    type: 'number',
    required: false,
    description: 'Repository-scoped pull request number.',
    helpText: richFieldHelp({
      what: 'The pull request number shown as #456 in GitHub.',
      why: 'get_pr, update_pr, merge_pr, and add_pr_comment need the exact PR number.',
      when: 'Fill it for operations that target one pull request.',
      enter: 'Use 456 or map {{$json.prNumber}}/{{$json.number}} from a previous GitHub step.',
      source: 'Pull request URL, PR page title, webhook payload, or list_prs output.',
      later: 'The number can be reused to merge or comment after checks pass.',
      format: 'Number only. Do not include # or the full URL.',
      example: 'A release workflow merges prNumber 456 after approval.',
      empty: 'PR-specific operations fail through the dispatcher or GitHub API.',
      mistake: 'Using issueNumber for a pull request when the workflow expects prNumber.',
    }),
    placeholder: '456',
    example: '456',
  },
  {
    name: 'State',
    internalKey: 'state',
    type: 'select',
    required: false,
    description: 'Issue or PR state.',
    options: ['open', 'closed'],
    helpText: richFieldHelp({
      what: 'The state value used when filtering or updating issue/PR records. open means active; closed means no longer active.',
      why: 'GitHub issue and PR operations often need a state to filter or update results.',
      when: 'Fill it for update_issue, list_issues, update_pr, or list_prs when state matters.',
      enter: 'Choose open or closed.',
      source: 'Workflow rule, support status, review outcome, or upstream mapping.',
      later: 'Returned GitHub records may include state top-level for downstream branching.',
      format: 'One of open or closed.',
      example: 'A cleanup workflow lists closed issues before creating a report.',
      empty: 'Runtime/API defaults may apply depending on the operation.',
      mistake: 'Using "done" or "resolved"; GitHub expects open or closed.',
    }),
    defaultValue: 'open',
    example: 'open',
    notes: 'Options: open, closed.',
  },
  {
    name: 'Comment',
    internalKey: 'comment',
    type: 'textarea',
    required: false,
    description: 'Comment text for issue or PR comments.',
    helpText: richFieldHelp({
      what: 'The text written as a GitHub issue or pull request comment.',
      why: 'add_issue_comment and add_pr_comment need the comment body to post.',
      when: 'Fill it for add_issue_comment and add_pr_comment.',
      enter: 'Type the comment or map {{$json.comment}}, {{$json.summary}}, or {{$json.reviewNote}}.',
      source: 'Approval step, AI review summary, support reply, monitoring event, or release checklist.',
      later: 'The created comment response may include id, body, and html_url at the top level.',
      format: 'Markdown-capable text string.',
      example: 'An AI code-review workflow posts "Risk found in auth middleware" to a PR.',
      empty: 'Comment operations fail or create no useful comment depending on the dispatcher/API validation.',
      mistake: 'Putting comment text in Body while using add_issue_comment; this panel field is Comment.',
    }),
    placeholder: 'Reviewed and approved.',
    example: 'Reviewed and approved.',
  },
  {
    name: 'Merge Method',
    internalKey: 'mergeMethod',
    type: 'select',
    required: false,
    description: 'Method used for merge_pr.',
    options: ['merge', 'squash', 'rebase'],
    helpText: richFieldHelp({
      what: 'The merge strategy for merge_pr. merge creates a merge commit, squash combines commits into one, and rebase replays commits onto the base branch.',
      why: 'Repositories enforce different history policies, and GitHub can reject disabled merge methods.',
      when: 'Fill it for merge_pr when your repo requires a specific strategy.',
      enter: 'Choose merge, squash, or rebase.',
      source: 'Repository merge settings, team policy, or upstream release rule.',
      later: 'The merge response can tell downstream steps whether the PR was merged.',
      format: 'One of merge, squash, rebase.',
      example: 'A release workflow uses squash so the main branch receives one clean commit.',
      empty: 'Runtime/UI default is merge.',
      mistake: 'Choosing rebase in a repository where rebase merges are disabled.',
    }),
    defaultValue: 'merge',
    example: 'squash',
    notes: 'Options: merge, squash, rebase.',
  },
  {
    name: 'Branch Name',
    internalKey: 'branchName',
    type: 'string',
    required: false,
    description: 'Branch name for branch, PR, or commit operations.',
    helpText: richFieldHelp({
      what: 'A branch name used as the target/source for branch operations, PR creation, deletion, or commit creation.',
      why: 'GitHub branch and commit routes need the exact branch reference.',
      when: 'Fill it for create_branch, get_branch, delete_branch, create_pr, and create_commit when the branch differs from ref.',
      enter: 'Use feature/add-login, release/2026-07, or map {{$json.branchName}}.',
      source: 'Git branch naming convention, webhook branch, form request, or previous GitHub response.',
      later: 'The branch name remains available from preserved input and may appear in GitHub response fields.',
      format: 'Git branch name string, without refs/heads unless the operation explicitly expects a full ref.',
      example: 'A bug workflow creates branch fix/checkout-timeout from main.',
      empty: 'Branch-specific operations fail or fall back to ref depending on the dispatcher helper.',
      mistake: 'Using a commit SHA as Branch Name; use SHA/Commit Hash for commit IDs.',
    }),
    placeholder: 'feature/add-login',
    example: 'feature/add-login',
  },
  {
    name: 'SHA/Commit Hash',
    internalKey: 'sha',
    type: 'string',
    required: false,
    description: 'Commit SHA used by branch/commit operations.',
    helpText: richFieldHelp({
      what: 'A Git commit SHA or object SHA.',
      why: 'Creating a branch needs the commit to branch from, and get_commit can target a specific commit.',
      when: 'Fill it for create_branch and get_commit when a SHA is required.',
      enter: 'Use a full or accepted short SHA such as abc123def456 or map {{$json.sha}}.',
      source: 'GitHub commit page, list_commits output, webhook payload, or git log.',
      later: 'Returned commit/branch data can feed deployment checks, release notes, or notifications.',
      format: 'Hex commit SHA string.',
      example: 'A release branch workflow uses the approved commit SHA from a change ticket.',
      empty: 'Operations needing a source commit fail through the dispatcher or GitHub API.',
      mistake: 'Using a branch name in SHA when the operation needs a commit hash.',
    }),
    placeholder: 'abc123def456',
    example: 'abc123def456',
  },
  {
    name: 'Commit Message',
    internalKey: 'commitMessage',
    type: 'textarea',
    required: false,
    description: 'Message for create_commit file changes.',
    helpText: richFieldHelp({
      what: 'The commit message used when create_commit writes file content.',
      why: 'GitHub requires a message when committing file changes.',
      when: 'Fill it for create_commit.',
      enter: 'Write a concise change summary or map {{$json.commitMessage}}.',
      source: 'Release automation, config update request, generated changelog, or human approval step.',
      later: 'Commit response fields can be used in downstream notifications or audit logs.',
      format: 'Plain text commit message.',
      example: 'Update customer portal config for July release.',
      empty: 'create_commit fails or GitHub rejects the request because no commit message is present.',
      mistake: 'Putting the file path in Commit Message instead of File Path.',
    }),
    placeholder: 'Update generated config',
    example: 'Update generated config',
  },
  {
    name: 'File Path',
    internalKey: 'filePath',
    type: 'string',
    required: false,
    description: 'Repository path for create_commit.',
    helpText: richFieldHelp({
      what: 'The path of the file to create or update in the repository.',
      why: 'create_commit needs to know which file path to write.',
      when: 'Fill it for create_commit.',
      enter: 'Use src/config/generated.json, docs/report.md, or map {{$json.filePath}}.',
      source: 'Repository structure, generated artifact metadata, or a workflow config step.',
      later: 'Commit output can include content/commit metadata for the path that was written.',
      format: 'Repository-relative path. Do not start with github.com/owner/repo.',
      example: 'A documentation workflow writes docs/release-notes.md.',
      empty: 'create_commit fails because there is no target file path.',
      mistake: 'Using a local Windows path instead of a repository-relative path.',
    }),
    placeholder: 'docs/release-notes.md',
    example: 'docs/release-notes.md',
  },
  {
    name: 'File Content',
    internalKey: 'fileContent',
    type: 'textarea',
    required: false,
    description: 'File content for create_commit.',
    helpText: richFieldHelp({
      what: 'The content written to File Path during create_commit.',
      why: 'The commit helper needs file content to create or update the file.',
      when: 'Fill it for create_commit.',
      enter: 'Use text content, JSON text, markdown, or map {{$json.fileContent}} from an upstream generator.',
      source: 'AI-generated notes, report builder, config generator, or previous HTTP/download step.',
      later: 'GitHub response fields identify the commit and content location for downstream use.',
      format: 'Text string. The helper handles the API call; do not include a whole commit object here.',
      example: 'A release workflow commits generated release notes markdown.',
      empty: 'create_commit has no content to write and fails or creates an invalid request.',
      mistake: 'Putting a base64 file object here when the helper expects the content value for the file.',
    }),
    placeholder: '# Release notes',
    example: '# Release notes',
  },
  {
    name: 'Tag Name',
    internalKey: 'tagName',
    type: 'string',
    required: false,
    description: 'Tag for create_release.',
    helpText: richFieldHelp({
      what: 'The Git tag name for a release.',
      why: 'create_release needs the tag GitHub should attach to the release.',
      when: 'Fill it for create_release.',
      enter: 'Use v1.2.0, release-2026-07, or map {{$json.tagName}}.',
      source: 'Versioning step, package metadata, changelog generator, or release approval form.',
      later: 'Release output may include tag_name/html_url for announcements.',
      format: 'Git tag string.',
      example: 'A deployment workflow creates release tag v2.4.0.',
      empty: 'create_release fails because GitHub requires a tag.',
      mistake: 'Putting the release title in Tag Name; use Release Name for display text.',
    }),
    placeholder: 'v1.2.0',
    example: 'v1.2.0',
  },
  {
    name: 'Release Name',
    internalKey: 'releaseName',
    type: 'string',
    required: false,
    description: 'Display name for create_release.',
    helpText: richFieldHelp({
      what: 'The human-readable title for a GitHub release.',
      why: 'It appears on the release page and in release notifications.',
      when: 'Fill it for create_release when you want a friendly release title.',
      enter: 'Use "Release v1.2.0" or map {{$json.releaseName}}.',
      source: 'Release checklist, package version, changelog generator, or approval step.',
      later: 'Release output may include name and html_url for downstream announcement nodes.',
      format: 'Plain text.',
      example: 'Release v2.4.0 - Billing improvements.',
      empty: 'GitHub may display the tag as the release title.',
      mistake: 'Using releaseId here; releaseId is for get_release.',
    }),
    placeholder: 'Release v1.2.0',
    example: 'Release v1.2.0',
  },
  {
    name: 'Release Body',
    internalKey: 'releaseBody',
    type: 'textarea',
    required: false,
    description: 'Release notes body.',
    helpText: richFieldHelp({
      what: 'The markdown description for a GitHub release.',
      why: 'It tells users what changed, what to test, and where to find details.',
      when: 'Fill it for create_release when release notes should be published.',
      enter: 'Write markdown or map {{$json.releaseBody}} from a changelog generator.',
      source: 'Changelog step, merged PR summary, AI release-note generation, or manual approval form.',
      later: 'Release output may include body/html_url for Slack, email, or customer notifications.',
      format: 'Markdown-capable text string.',
      example: 'A release workflow inserts features, fixes, and migration notes from the approved changelog.',
      empty: 'The release can be created with little or no description.',
      mistake: 'Putting the tag in Release Body instead of Tag Name.',
    }),
    placeholder: '## Changes',
    example: '## Changes',
  },
  {
    name: 'Release ID',
    internalKey: 'releaseId',
    type: 'number',
    required: false,
    description: 'GitHub release numeric ID.',
    helpText: richFieldHelp({
      what: 'The numeric ID of a GitHub release.',
      why: 'get_release can use releaseId to fetch one release.',
      when: 'Fill it for get_release when you have the API release ID.',
      enter: 'Use a number such as 12345 or map {{$json.releaseId}}.',
      source: 'list_releases output, release API response, or stored release metadata.',
      later: 'The release response can feed deployment records or announcements.',
      format: 'Number only.',
      example: 'A release audit workflow fetches releaseId 12345 before posting a summary.',
      empty: 'get_release cannot target a specific release unless another supported identifier is provided by the dispatcher.',
      mistake: 'Using the tag name where a numeric release ID is expected.',
    }),
    placeholder: '12345',
    example: '12345',
  },
  {
    name: 'Commit SHA',
    internalKey: 'commitSha',
    type: 'string',
    required: false,
    description: 'Commit SHA for release or commit-related operations.',
    helpText: richFieldHelp({
      what: 'A commit SHA value used by release/commit workflows.',
      why: 'Some GitHub actions need a commit target or commit lookup separate from the generic sha field.',
      when: 'Fill it when the selected operation asks for commitSha or when your workflow stores the approved commit under that name.',
      enter: 'Use a full/short SHA such as abc123def456 or map {{$json.commitSha}}.',
      source: 'GitHub commit page, webhook payload, list_commits output, or release approval data.',
      later: 'The returned GitHub data can be matched back to the commit for audit or deployment steps.',
      format: 'Hex commit SHA string.',
      example: 'A release workflow maps the built artifact commit into commitSha before creating a release.',
      empty: 'Operations that require a commit target fail or use other branch/ref values where supported.',
      mistake: 'Confusing commitSha with issueNumber or releaseId because all may appear near a release ticket.',
    }),
    placeholder: 'abc123def456',
    example: 'abc123def456',
  },
  {
    name: 'Labels',
    internalKey: 'labels',
    type: 'json',
    required: false,
    description: 'Optional issue labels array for legacy/AI-generated configs.',
    helpText: richFieldHelp({
      what: 'An optional array of GitHub issue labels accepted by some dispatcher paths and older schema metadata.',
      why: 'Labels help route and filter GitHub issues after creation.',
      when: 'Use only when your operation/helper supports labels, usually create_issue or update_issue style workflows.',
      enter: 'Use ["bug","priority-high"] or map {{$json.labels}} when it is already an array.',
      source: 'Support severity mapping, incident category, triage form, or repository label policy.',
      later: 'Returned issue data may include labels for downstream routing.',
      format: 'JSON array of label names.',
      example: 'A monitoring workflow labels outage issues with ["incident","p1"].',
      empty: 'No labels are sent by this compatibility field.',
      mistake: 'Typing a comma-separated string instead of a JSON array.',
    }),
    placeholder: '["bug","priority-high"]',
    example: '["bug","priority-high"]',
  },
  {
    name: 'Access Token',
    internalKey: 'accessToken',
    type: 'password',
    required: false,
    description: 'Legacy credential metadata; the main runtime path uses the connected GitHub account token.',
    helpText: richFieldHelp({
      what: 'A legacy OAuth token metadata field. In the current social dispatcher path, the worker retrieves the GitHub token from the connected account/token manager.',
      why: 'The schema still lists credential metadata for discovery, but normal UI execution depends on the saved GitHub connection.',
      when: 'Use only for legacy/config compatibility when your environment explicitly supports it.',
      enter: 'Use a secure credential expression from Connections, not business input data.',
      source: 'GitHub OAuth connection, credential system, or credential vault.',
      later: 'It authorizes the request only and is not returned in output.',
      format: 'Secret OAuth access token string.',
      example: 'A migrated workflow keeps accessToken metadata while the active token comes from the connected GitHub account.',
      empty: 'The social dispatcher still looks up the connected GitHub account token; if none exists, output contains _error.',
      mistake: 'Assuming this visible docs field means the panel reads direct tokens; the runtime token comes from the account connection.',
    }),
    placeholder: '{{$credentials.github.accessToken}}',
    example: '{{$credentials.github.accessToken}}',
  },
  {
    name: 'API Key',
    internalKey: 'apiKey',
    type: 'password',
    required: false,
    description: 'Legacy GitHub PAT metadata.',
    helpText: richFieldHelp({
      what: 'A legacy GitHub Personal Access Token metadata field.',
      why: 'Some registry metadata mentions PATs, but the execute-workflow GitHub case calls the social token manager for the connected account.',
      when: 'Use only for legacy compatibility where a secure credential expression is deliberately injected.',
      enter: 'Use a saved credential expression such as {{$credentials.github.apiKey}}.',
      source: 'GitHub Personal Access Token or OAuth connection stored in the credential vault.',
      later: 'The secret is not returned; successful output includes success/provider/action and GitHub data fields.',
      format: 'Secret string, often ghp_ or github_pat_.',
      example: 'A legacy automation references a PAT stored in the vault while modern workflows use Connections.',
      empty: 'No issue if the connected GitHub account token is available; otherwise _error reports no github token found.',
      mistake: 'Treating the PAT as issue body or repository data.',
    }),
    placeholder: '{{$credentials.github.apiKey}}',
    example: '{{$credentials.github.apiKey}}',
  },
  {
    name: 'Credential ID',
    internalKey: 'credentialId',
    type: 'string',
    required: false,
    description: 'Stored credential identifier metadata.',
    helpText: richFieldHelp({
      what: 'An optional identifier for a saved GitHub credential record.',
      why: 'The backend schema keeps it for credential discovery/injection metadata.',
      when: 'Use only in advanced/legacy setups managed by the credential system.',
      enter: 'A credential record ID such as github_oauth_123, usually not manually edited by workplace users.',
      source: 'CtrlChecks credential system or account connection metadata.',
      later: 'It is used to find credentials and is not returned in GitHub operation output.',
      format: 'Internal credential ID string.',
      example: 'An admin-created workflow references github_oauth_123 during migration.',
      empty: 'The runtime uses the connected account token lookup instead.',
      mistake: 'Putting a GitHub repository ID here; this field is about credentials, not repos.',
    }),
    placeholder: 'github_oauth_123',
    example: 'github_oauth_123',
  },
];

const outputExample = {
  success: true,
  provider: 'github',
  action: 'issues.create',
  id: 123456,
  number: 42,
  title: '[P1] Checkout fails',
  state: 'open',
  url: 'https://github.com/acme-platform/api-service/issues/42',
};

const makeOperation = (name: string, value: string, description: string): OperationDoc => ({
  name,
  value,
  description: `${description} Runtime uses the connected GitHub account, preserves incoming fields, and spreads returned provider data at the top level with success/provider/action.`,
  fields,
  outputExample,
  outputDescription: 'Successful GitHub output preserves incoming fields and adds success, provider, action, plus provider data spread at the top level. Depending on operation, top-level fields can include id, number, title, body, state, url, html_url, sha, name, workflow_runs, contributors, merged, or release fields. Failures return _error such as "github node: No github token found..." rather than a nested data object.',
  usageExample: {
    scenario: `Run ${name} in a DevOps workflow that reacts to incidents, code review, release approvals, or repository reporting.`,
    inputValues: {
      operation: value,
      owner: 'acme-platform',
      repo: 'api-service',
    },
    expectedOutput: 'Use {{$json.success}}, {{$json.provider}}, {{$json.action}}, {{$json.html_url}}, {{$json.number}}, or {{$json._error}} in downstream nodes.',
  },
  externalDocsUrl: 'https://docs.github.com/en/rest',
});

export const githubDoc: NodeDoc = {
  slug: 'github',
  displayName: 'GitHub',
  category: 'DevOps',
  logoUrl: '/icons/nodes/github.svg',
  description: 'Runs GitHub repository, issue, pull request, branch, commit, release, workflow, and contributor operations through the connected GitHub account.',
  credentialType: 'GitHub Personal Access Token or GitHub OAuth',
  credentialSetupSteps: [
    'Connect GitHub in Connections using GitHub OAuth or a GitHub Personal Access Token stored in the credential system / credential vault.',
    'The runtime GitHub social dispatcher retrieves the token from the connected account/token manager; direct accessToken/apiKey fields are legacy credential metadata, not the normal visual-panel path.',
    'Grant repo or public_repo scope for private/public repository work, and ensure the account can read/write issues, pull requests, workflows, branches, commits, and releases needed by the operation.',
    'CtrlChecks can validate a GitHub token against api.github.com/user before repository operations; reconnect if the token expires or loses permissions.',
    'Connect the output to the next service node with an outgoing line, then map top-level fields such as {{$json.number}}, {{$json.html_url}}, {{$json.sha}}, {{$json.provider}}, or {{$json._error}}.',
  ],
  credentialDocsUrl: 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token',
  resources: [
    {
      name: 'Repositories, Issues, Pull Requests, Branches, Commits, Releases, Workflows',
      description: 'GitHub operations are dispatched by the social service layer. The visual panel exposes 27 operation values and the worker spreads successful GitHub response data at the top level.',
      operations: [
        makeOperation('Get Repository', 'get_repo', 'Reads repository details for owner/repo.'),
        makeOperation('List Repositories', 'list_repos', 'Lists repositories available to the connected GitHub account.'),
        makeOperation('Create Issue', 'create_issue', 'Creates a GitHub issue. Requires owner, repo, and title; body and labels may add context.'),
        makeOperation('Update Issue', 'update_issue', 'Updates an existing issue by issueNumber with fields such as title, body, or state.'),
        makeOperation('Close Issue', 'close_issue', 'Closes an existing issue by issueNumber.'),
        makeOperation('List Issues', 'list_issues', 'Lists issues for owner/repo, optionally using state.'),
        makeOperation('Get Issue', 'get_issue', 'Reads one issue by issueNumber.'),
        makeOperation('Add Issue Comment', 'add_issue_comment', 'Adds Comment text to one issue by issueNumber.'),
        makeOperation('Create Pull Request', 'create_pr', 'Creates a pull request using title, body, branchName/head, and ref/base details.'),
        makeOperation('Update Pull Request', 'update_pr', 'Updates an existing pull request by prNumber.'),
        makeOperation('Merge Pull Request', 'merge_pr', 'Merges a pull request by prNumber using merge, squash, or rebase.'),
        makeOperation('List Pull Requests', 'list_prs', 'Lists pull requests for owner/repo, optionally by state.'),
        makeOperation('Get Pull Request', 'get_pr', 'Reads one pull request by prNumber.'),
        makeOperation('Add PR Comment', 'add_pr_comment', 'Adds Comment text to one pull request by prNumber.'),
        makeOperation('Create Branch', 'create_branch', 'Creates a branchName from a commit SHA/ref.'),
        makeOperation('List Branches', 'list_branches', 'Lists branches for owner/repo.'),
        makeOperation('Get Branch', 'get_branch', 'Reads one branch by branchName.'),
        makeOperation('Delete Branch', 'delete_branch', 'Deletes one branch by branchName.'),
        makeOperation('Create Commit', 'create_commit', 'Creates or updates filePath with fileContent and commitMessage on branchName/ref.'),
        makeOperation('List Commits', 'list_commits', 'Lists commits for owner/repo, optionally by ref.'),
        makeOperation('Get Commit', 'get_commit', 'Reads one commit by sha or commitSha.'),
        makeOperation('Create Release', 'create_release', 'Creates a release using tagName, releaseName, releaseBody, and optional commitSha/ref.'),
        makeOperation('List Releases', 'list_releases', 'Lists releases for owner/repo.'),
        makeOperation('Get Release', 'get_release', 'Reads one release by releaseId where supported by the dispatcher.'),
        makeOperation('Get Workflow Runs', 'get_workflow_runs', 'Lists GitHub Actions workflow runs for workflowId/ref.'),
        makeOperation('Trigger Workflow', 'trigger_workflow', 'Dispatches a GitHub Actions workflow using workflowId and ref.'),
        makeOperation('List Contributors', 'list_contributors', 'Lists contributors for owner/repo.'),
      ],
    },
  ],
  commonErrors: [
    {
      error: 'No github token found',
      cause: 'The social dispatcher could not find a connected GitHub account token for the user.',
      fix: 'Reconnect GitHub in Connections, verify the service node account connection, and confirm the token manager has a valid GitHub token.',
    },
    {
      error: 'Unsupported GitHub operation',
      cause: 'The workflow sent an operation outside the dispatcher mappings or a stale alias that is not accepted.',
      fix: 'Use one of the visible dropdown values such as create_issue, merge_pr, trigger_workflow, or list_contributors.',
    },
    {
      error: 'Missing required fields: owner, repo, and title are required',
      cause: 'create_issue was selected without the repository owner/repo or issue title.',
      fix: 'Fill Owner, Repository, and Title, or map them from upstream fields before the GitHub node runs.',
    },
    {
      error: 'Invalid or expired GitHub token',
      cause: 'The connected OAuth/PAT token failed validation or lacks repo/public_repo/workflow permissions for the operation.',
      fix: 'Reconnect GitHub, grant the needed scopes, and test the connection against api.github.com/user.',
    },
    {
      error: 'Successful output spreads provider data at top level',
      cause: 'The workflow expected {{$json.data.html_url}} but runtime spreads GitHub response fields onto {{$json}}.',
      fix: 'Map {{$json.html_url}}, {{$json.number}}, {{$json.sha}}, {{$json.provider}}, and {{$json.action}} directly.',
    },
  ],
  relatedNodes: ['github_trigger', 'bitbucket', 'gitlab', 'slack_message'],
};
