import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const githubWebhookDocs = 'https://docs.github.com/en/webhooks/about-webhooks';
const githubPatDocs = 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token';

const fields: FieldDoc[] = [
  {
    name: 'GitHub Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved GitHub connection reference used by generated workflow config.',
    helpText: `What this field means: GitHub Connection points to the saved GitHub account or token that can create and remove repository webhooks. The visual panel usually uses your active GitHub connection rather than asking you to type this ID. Why it matters: CtrlChecks needs this connection when it calls the GitHub API to register the repository webhook and later remove it. When to fill it: Leave it blank in normal visual workflows. Use a specific saved connection only when your workspace has more than one GitHub account. What to enter: Select or reference the saved GitHub connection; do not paste a Personal Access Token here as workflow data. Where the value comes from: Connections stores it after GitHub OAuth or GitHub Personal Access Token setup. How to use it later: This setup value is not emitted as {{$json.connectionId}}; downstream nodes use fields such as {{$json.repository}}, {{$json.issueNumber}}, {{$json.prNumber}}, and {{$json.commentBody}}. Accepted format: Saved connection reference such as github_pat_123 or github_oauth_123. Real workplace example: A platform team uses the GitHub connection owned by the release manager so CtrlChecks can create a webhook on octo-org/api-service. If it is empty or wrong: Empty falls back to the active GitHub credential lookup; a wrong or inactive connection can cause no active GitHub connection or GitHub API permission errors during registration. Common mistake to avoid: Pasting the raw ghp_ token into a normal workflow field instead of saving it in Connections.`,
    placeholder: 'Use selected/default GitHub connection',
    example: 'github_pat_123',
    notes: 'Credential-owned runtime field. Prefer Connections instead of treating this as ordinary workflow input.',
  },
  {
    name: 'Owner/Organization',
    internalKey: 'owner',
    type: 'string',
    required: true,
    description: 'GitHub user or organization that owns the repository to watch.',
    helpText: `What this field means: Owner/Organization is the account name before the repository name in a GitHub URL. Why it matters: GitHub webhooks are created on one exact repository, so CtrlChecks needs the owner and repository name to call /repos/{owner}/{repo}/hooks. When to fill it: Always fill it before saving or activating a GitHub Trigger. What to enter: Enter only the owner part, such as octocat or acme-platform, not the full URL. Where the value comes from: Open the repository in GitHub and copy the first path segment after github.com. How to use it later: The trigger output includes {{$json.repository}} as owner/repo, which you can use in messages, logs, or GitHub action nodes. Accepted format: GitHub login or organization name using normal GitHub URL characters, without https://github.com/. Real workplace example: For https://github.com/acme-platform/api-service, enter acme-platform. If it is empty or wrong: Validation fails with A GitHub repository owner is required, registration fails, or events from the intended repository never arrive. Common mistake to avoid: Entering the repository name, branch name, display organization title, or full repository URL in this field.`,
    placeholder: 'octocat',
    example: 'acme-platform',
  },
  {
    name: 'Repository',
    internalKey: 'repo',
    type: 'string',
    required: true,
    description: 'Repository name under the selected owner or organization.',
    helpText: `What this field means: Repository is the repo name after the owner in a GitHub URL. Why it matters: CtrlChecks registers the webhook on this exact repository and only receives events from that repository. When to fill it: Always fill it with Owner/Organization before activating the workflow. What to enter: Enter only the repository name, such as api-service or Hello-World. Where the value comes from: Open the repository in GitHub and copy the second path segment after github.com/{owner}/. How to use it later: Use {{$json.repository}} to include the full owner/repo in alerts, tickets, dashboards, or GitHub action steps. Accepted format: Repository slug text without the owner, branch, issue number, or URL. Real workplace example: For https://github.com/acme-platform/api-service, enter api-service. If it is empty or wrong: Validation fails with A GitHub repository name is required, auto-registration records Repository owner and name are required, or GitHub API returns a 404/403 permission error. Common mistake to avoid: Pasting acme-platform/api-service into Repository after already entering acme-platform as Owner.`,
    placeholder: 'Hello-World',
    example: 'api-service',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated GitHub webhook event names allowed to start the workflow.',
    helpText: `What this field means: Event Types tells CtrlChecks which GitHub webhook events to subscribe to and accept. Why it matters: Pushes, issues, pull requests, releases, and comments usually need different workflow paths. When to fill it: Keep the default while testing; narrow it before production if the workflow should react only to issues, pull requests, releases, comments, or pushes. What to enter: Use GitHub event names such as push, issues, pull_request, release, issue_comment, star, fork, or pull_request_review. You may also use a specific normalized type such as issues.opened to filter an action after delivery. Where the value comes from: Choose from GitHub's repository webhook event list and the business event your team wants to automate. How to use it later: Use {{$json.eventType}} to branch; raw event families like issues may produce detailed values such as issues.opened or issues.closed. Accepted format: Comma-separated text or an array in generated config. Real workplace example: issues, pull_request for engineering triage, push for CI follow-up, release for customer release announcements. If it is empty or wrong: Empty defaults to push, issues, pull_request, release, issue_comment; unsupported names may register with GitHub but never match the events you expect. Common mistake to avoid: Typing friendly labels like pull requests or comments instead of GitHub event names such as pull_request and issue_comment.`,
    placeholder: 'push, issues, pull_request, release, issue_comment',
    defaultValue: 'push, issues, pull_request, release, issue_comment',
    example: 'issues, pull_request',
  },
  {
    name: 'Webhook Secret Override',
    internalKey: 'webhookSecret',
    type: 'string',
    required: false,
    description: 'Optional signing secret override for advanced webhook setup.',
    helpText: `What this field means: Webhook Secret Override is an optional secret text used to sign GitHub webhook deliveries. Why it matters: GitHub sends X-Hub-Signature-256, and CtrlChecks accepts the webhook only when the HMAC-SHA256 signature matches the secret stored for this node. When to fill it: Leave it blank for normal workflows because CtrlChecks generates and stores a secret automatically during registration. Fill it only for a controlled migration or manually managed webhook where your team must reuse a known secret. What to enter: A long random secret generated by your admin or password manager, not a GitHub Personal Access Token. Where the value comes from: Usually CtrlChecks creates it; if you override it, use the same value in the GitHub repository webhook settings. How to use it later: It is setup-only and is never emitted as {{$json.webhookSecret}} for downstream nodes. Accepted format: Plain secret text; the visual field uses a supported text control even though the value should be treated as secret setup material. Real workplace example: A DevOps admin migrates an existing repository webhook and temporarily reuses the approved signing secret while switching the URL to CtrlChecks. If it is empty or wrong: Empty uses the generated stored secret; a wrong manual value causes Invalid GitHub webhook signature and no workflow execution. Common mistake to avoid: Confusing this with the GitHub PAT/OAuth token used to create the webhook.`,
    placeholder: 'Leave blank to generate automatically',
    example: 'github-webhook-secret-2026',
    notes: 'Credential/setup-owned value. Prefer leaving blank so CtrlChecks generates and stores the secret in webhook state.',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional case-insensitive keyword matched against normalized event text.',
    helpText: `What this field means: Keyword Filter lets only GitHub events whose normalized text contains a word or phrase start the workflow. Why it matters: Busy repositories can produce many events; this filter keeps a workflow focused on urgent issues, release names, commit messages, pull request titles, or comment bodies. When to fill it: Use it when the workflow should react only to a phrase such as urgent, sev1, billing, security, or release-candidate. Leave it blank to accept every configured event type. What to enter: A simple keyword or short phrase, not GitHub search syntax. Where the value comes from: Pick the label, customer name, module name, severity term, or release keyword your team uses in commits, issue titles, PR titles, release names, or comments. How to use it later: The accepted event output still includes {{$json.text}} and event-specific fields such as {{$json.issueTitle}}, {{$json.prTitle}}, or {{$json.commentBody}} for downstream routing. Accepted format: Plain text case-insensitive contains match. Real workplace example: security starts only security-related issue and pull request workflows. If it is empty or wrong: Empty accepts all configured event types; a too-specific or misspelled filter returns Ignored GitHub event not matching this trigger. Common mistake to avoid: Expecting repo:owner/name label:bug syntax here; this is not GitHub search, only a simple text contains filter.`,
    placeholder: 'urgent',
    example: 'security',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive GitHub event',
  value: 'receive',
  description: 'Receives signed GitHub repository webhook deliveries, ignores webhook pings, validates the X-Hub-Signature-256 signature against the stored secret, filters accepted event types and optional keyword text, normalizes push, issue, pull request, release, comment, and other GitHub events, then starts one workflow execution for each accepted delivery.',
  fields,
  outputExample: {
    eventId: 'a1b2c3d4-0000-0000-0000-000000000000',
    eventType: 'issues.opened',
    source: 'github',
    userId: '583231',
    username: 'octocat',
    text: 'Bug: billing export fails for July invoices',
    timestamp: '2026-07-19T10:20:00.000Z',
    repository: 'acme-platform/api-service',
    action: 'opened',
    ref: null,
    commits: null,
    issueNumber: 42,
    issueTitle: 'Bug: billing export fails for July invoices',
    issueUrl: 'https://github.com/acme-platform/api-service/issues/42',
    prNumber: null,
    prTitle: null,
    prUrl: null,
    merged: null,
    releaseTag: null,
    releaseName: null,
    commentBody: null,
    commentUrl: null,
    raw: { action: 'opened', repository: { full_name: 'acme-platform/api-service' } },
    trigger: 'github',
    workflow_id: 'workflow_123',
    node_id: 'github-trigger-1',
    sessionId: 'github_workflow_123_a1b2c3d4-0000-0000-0000-000000000000',
    _github: true,
  },
  outputDescription: 'eventId: GitHub X-GitHub-Delivery ID or generated fallback. eventType: normalized event such as push, issues.opened, pull_request.closed, release.published, or issue_comment.created. source: github. userId: sender id when available. username: sender login. text: normalized event text such as last commit message, issue title, PR title, release name/tag, comment body, or event summary. timestamp: time CtrlChecks normalized the delivery. repository: owner/repo full name. action: GitHub payload action when supplied. ref: push branch/tag ref or pull request head ref. commits: push commit array. issueNumber/issueTitle/issueUrl: issue or commented issue fields. prNumber/prTitle/prUrl/merged: pull request fields. releaseTag/releaseName: release fields. commentBody/commentUrl: issue comment fields. raw: original GitHub payload. trigger: github marker. workflow_id: workflow receiving the event. node_id: trigger node ID. sessionId: github_workflowId_eventId. _github: true marker.',
  usageExample: {
    scenario: 'Triage new GitHub issues with AI and notify the engineering channel',
    inputValues: {
      connectionId: '',
      owner: 'acme-platform',
      repo: 'api-service',
      eventTypes: 'issues, pull_request',
      webhookSecret: '',
      query: 'billing',
    },
    expectedOutput: 'Use {{$json.eventType}} to branch issues from pull requests, {{$json.issueTitle}} or {{$json.prTitle}} as the AI prompt, {{$json.repository}} in the alert, and {{$json.issueUrl}} or {{$json.prUrl}} as the link for reviewers.',
  },
  externalDocsUrl: githubWebhookDocs,
};

export const githubTriggerDoc: NodeDoc = {
  slug: 'github_trigger',
  displayName: 'GitHub Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Github.svg',
  description: 'Start workflows from signed GitHub repository webhook events such as pushes, issues, pull requests, releases, and comments.',
  credentialType: 'GitHub Personal Access Token or GitHub OAuth',
  credentialSetupSteps: [
    'Connect GitHub in Connections. For reliable automatic repository webhook registration, use a GitHub Personal Access Token with repo access for private repositories or admin:repo_hook/public_repo access where appropriate. GitHub OAuth may also work when the stored OAuth token includes repository hook permissions.',
    'CtrlChecks stores the GitHub PAT or OAuth access token in the credential vault. Normal workflow fields should contain repository names, event filters, and mappings only; tokens and webhook secrets belong in Connections or webhook setup state.',
    'Test the connection with the built-in GitHub test request. PAT credentials call https://api.github.com/user; the OAuth credential registry also uses the GitHub user endpoint to confirm the token is valid.',
    'Fill Owner/Organization and Repository with the exact GitHub repository path parts. Optional Event Types and Keyword Filter narrow what can start the workflow.',
    'Save and activate the workflow. CtrlChecks builds a callback URL from PUBLIC_BASE_URL and registers a GitHub repository webhook through POST /repos/{owner}/{repo}/hooks.',
    'CtrlChecks generates a signing secret, stores it with the hook id in Redis under github:webhook:{workflowId}:{nodeId}, and GitHub signs each delivery with X-Hub-Signature-256.',
    'Use Webhook Secret Override only when migrating or manually managing a webhook that must reuse a known secret. In normal workflows, leave it blank so CtrlChecks generates the secret.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this GitHub connection authorizes webhook registration/removal, while Slack, email, CRM, database, or GitHub action nodes use their own connection requirements.',
  ],
  credentialDocsUrl: githubPatDocs,
  resources: [
    {
      name: 'Repository webhook',
      description: 'Receives signed GitHub repository webhook deliveries, validates and filters them, and starts workflow executions with normalized event data.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'A GitHub repository owner is required.',
      cause: 'Owner/Organization is blank in the trigger configuration.',
      fix: 'Open the repository URL and enter only the owner or organization part, such as acme-platform.',
    },
    {
      error: 'A GitHub repository name is required.',
      cause: 'Repository is blank in the trigger configuration.',
      fix: 'Enter only the repository slug, such as api-service, not the owner/repo pair.',
    },
    {
      error: 'Repository owner and name are required (set them on the GitHub Trigger node).',
      cause: 'The active workflow tried to auto-register webhooks but the trigger node did not have both Owner and Repository saved.',
      fix: 'Fill both fields, save the workflow, and activate it again.',
    },
    {
      error: 'No active GitHub connection found. Save a GitHub Personal Access Token (or connect via OAuth) in Connections first.',
      cause: 'Webhook registration could not resolve a saved GitHub credential for the workflow owner.',
      fix: 'Create or reconnect a GitHub PAT/OAuth connection in Connections with repository webhook permission, then re-activate the workflow.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register GitHub webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL GitHub must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, restart the worker, and activate/register again.',
    },
    {
      error: 'Invalid GitHub webhook signature.',
      cause: 'The request is missing X-Hub-Signature-256, the stored secret does not match GitHub, webhook state is missing, or the request did not come from the configured GitHub webhook.',
      fix: 'Re-register the webhook so CtrlChecks and GitHub share the same secret. If using Webhook Secret Override, make sure the same value is saved in GitHub webhook settings.',
    },
    {
      error: 'GitHub webhook ping received.',
      cause: 'GitHub sends a ping delivery when the repository webhook is created or tested.',
      fix: 'No fix is needed. Create a real push, issue, pull request, release, or comment event to test workflow execution.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'GitHub delivered a valid event, but the workflow status was not active.',
      fix: 'Activate the workflow and send another GitHub event.',
    },
    {
      error: 'Ignored GitHub event not matching this trigger.',
      cause: 'Event Types or Keyword Filter rejected the normalized event.',
      fix: 'Broaden Event Types, clear Keyword Filter temporarily, send a fresh GitHub event, then narrow the filters after confirming output.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to execute GitHub-triggered workflows.',
      cause: 'A matching event was accepted, but the worker could not call /api/execute-workflow for the new execution.',
      fix: 'Set PUBLIC_BASE_URL, restart the worker, and send another matching GitHub event.',
    },
    {
      error: 'GitHub Trigger node not found in this workflow.',
      cause: 'The callback URL points to a node ID that is missing, renamed incorrectly, or no longer has type github_trigger.',
      fix: 'Save the workflow with the GitHub Trigger node still present, then use the fresh webhook URL/registration.',
    },
    {
      error: 'Next node cannot find GitHub trigger fields',
      cause: 'The next step is mapped to a field that is only present for another event type, such as issueTitle on a push or prTitle on an issue.',
      fix: 'Use {{$json.eventType}} to branch by event family before mapping event-specific fields. Use {{$json.text}} when you need a generic title/body fallback.',
    },
    {
      error: 'Permission denied after GitHub Trigger',
      cause: 'The trigger received the event, but a downstream GitHub action, Slack, email, CRM, database, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node account connection and make sure any GitHub action node has repository permission for the action it performs.',
    },
  ],
  relatedNodes: ['github', 'ai_agent', 'slack_message', 'http_request'],
};
