import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const gmailPushDocs = 'https://developers.google.com/gmail/api/guides/push';

const fields: FieldDoc[] = [
  {
    name: 'Pub/Sub Topic',
    internalKey: 'pubsubTopic',
    type: 'string',
    required: true,
    description: 'Full Google Cloud Pub/Sub topic name that Gmail will publish mailbox watch notifications to.',
    helpText: 'What this field means: Pub/Sub Topic is the Google Cloud topic passed to Gmail users.watch when this trigger is registered. Why it matters: Gmail does not call the CtrlChecks workflow directly; Gmail publishes a small notification to this topic, and a Pub/Sub push subscription delivers it to the CtrlChecks webhook URL. When to fill it: Always fill this before activating or registering the watch. What to enter: Use the full topic path, for example projects/support-ops/topics/gmail-notifications. Where the value comes from: In Google Cloud Console, open Pub/Sub > Topics and copy the topic name. How to use it later: This setup value is not emitted as workflow output; downstream nodes use fields such as {{$json.subject}}, {{$json.threadId}}, and {{$json.eventType}}. Required setup: Grant Pub/Sub Publisher on the topic to gmail-api-push@system.gserviceaccount.com, then create a push subscription pointing at the webhook URL shown for this node. Accepted format: projects/PROJECT_ID/topics/TOPIC_NAME. Real workplace example: projects/acme-support/topics/gmail-inbox-notifications for support mailbox triage. If it is empty or wrong: Registration fails with A Google Cloud Pub/Sub topic name is required to watch a Gmail mailbox, or Gmail cannot publish notifications. Common mistake: Pasting only the topic display name, a subscription name, or the webhook URL instead of the full topic path.',
    placeholder: 'projects/my-project/topics/gmail-notifications',
    example: 'projects/acme-support/topics/gmail-inbox-notifications',
    notes: 'The runtime returns manualSetupRequired: true because the Google Cloud Pub/Sub topic, publisher permission, and push subscription must exist outside the workflow.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Gmail history event types that are allowed to start this workflow after CtrlChecks reads the mailbox history feed.',
    helpText: 'What this field means: Event Types decides which Gmail history changes can start the workflow. Why it matters: New messages, deleted messages, and label changes are different business events. When to fill it: Use message_added for new-email automations, label_added for workflows triggered by a triage label, label_removed for cleanup alerts, and message_deleted for audit workflows. What to enter: One or more values separated by commas or new lines. Where the value comes from: Choose the Gmail mailbox event your workflow should react to after a Pub/Sub notification arrives. How to use it later: Downstream nodes can route on {{$json.eventType}}. Accepted format: message_added, label_added, label_removed, message_deleted; spaces and hyphens are normalized to underscores. Real workplace example: message_added, label_added for new support emails and messages marked IMPORTANT. If it is empty or wrong: Empty defaults to message_added; unsupported values filter out all fetched history events. Common mistake: Assuming a Pub/Sub notification itself says the event type; CtrlChecks still has to call Gmail history and classify the changed message.',
    placeholder: 'message_added, label_added, label_removed',
    defaultValue: 'message_added',
    options: ['message_added', 'label_added', 'label_removed', 'message_deleted'],
    example: 'message_added, label_added',
    notes: 'message_added means a message was added to the mailbox. label_added means Gmail added a label to a message. label_removed means Gmail removed a label from a message. message_deleted means Gmail reported the message as deleted.',
  },
  {
    name: 'Label IDs',
    internalKey: 'labelIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated Gmail label IDs that accepted events must contain.',
    helpText: 'What this field means: Label IDs narrows the trigger to messages whose returned Gmail labels include at least one listed ID. Why it matters: Busy mailboxes often need different automations for INBOX, IMPORTANT, finance labels, or support labels. When to fill it: Fill it when the workflow should only handle a specific mailbox label or category. What to enter: Built-in Gmail label IDs like INBOX or IMPORTANT, or custom label IDs from the Gmail API. Where the value comes from: Built-in labels use stable uppercase IDs; custom labels can be found through Gmail API label listing or existing admin setup. How to use it later: Matching events expose {{$json.labelIds}} so later nodes can route by label. Accepted format: Comma-separated IDs such as INBOX, IMPORTANT. Real workplace example: INBOX, IMPORTANT for urgent support triage. If it is empty or wrong: Empty accepts events from any label; a wrong label ID filters out events even if the message subject matches. Common mistake: Using the visible custom label name when Gmail API returned a different custom label ID.',
    placeholder: 'INBOX, IMPORTANT',
    example: 'INBOX',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional simple keyword filter matched after Gmail message metadata is fetched.',
    helpText: 'What this field means: Keyword Filter is plain text that must appear in the message subject, sender, or snippet. Why it matters: It keeps broad inbox notifications from starting workflows for unrelated email. When to fill it: Fill it for focused flows such as invoices, refunds, cancellations, quotes, resumes, or escalations. What to enter: A word or short phrase your team expects in matching emails. Where the value comes from: Use real words found in message subjects, sender addresses, or Gmail snippets. How to use it later: Matching events expose {{$json.subject}}, {{$json.from}}, and {{$json.snippet}}. Accepted format: Plain text; matching is case-insensitive and not Gmail search syntax. Real workplace example: invoice for finance approvals from vendor emails. If it is empty or wrong: Empty accepts every event that matches Event Types and Label IDs; a typo filters out matching emails. Common mistake: Entering a Gmail search query like from:vendor has:attachment. This trigger only does a simple contains check against subject, sender, and snippet.',
    placeholder: 'invoice',
    example: 'invoice',
  },
  {
    name: 'Validate Push Auth',
    internalKey: 'validateAuth',
    type: 'boolean',
    required: false,
    description: 'Whether CtrlChecks should validate Google-signed Pub/Sub push OIDC tokens or a shared simulation secret.',
    helpText: 'What this field means: Validate Push Auth controls whether incoming Pub/Sub push requests must prove they came from the configured Google Pub/Sub delivery path. Why it matters: A trigger webhook is public, so production workflows should reject unsigned or incorrectly signed requests. When to fill it: Keep it enabled for real workflows. Disable only for controlled local testing when you cannot send a Google OIDC token or shared token. What to enter: true/enabled for production, false/disabled only in a temporary test environment. Where the value comes from: This is a security choice made by the workflow owner or admin. How to use it later: This field does not appear in {{$json}}; it protects whether a workflow run starts at all. Accepted format: Boolean checkbox. Real workplace example: Keep enabled for a support inbox automation that can create tickets or send replies. If it is empty or wrong: The default is enabled; disabling it can let anyone who knows the webhook URL simulate Gmail pushes. Common mistake: Turning this off to fix setup problems instead of configuring OIDC audience or a validation secret correctly.',
    defaultValue: 'true',
    example: 'true',
    notes: 'When enabled, the runtime accepts either a matching Validation Secret via token query/header or a Google-signed bearer token whose audience matches this webhook URL or the configured OIDC Audience.',
  },
  {
    name: 'OIDC Audience',
    internalKey: 'audience',
    type: 'string',
    required: false,
    description: 'Optional expected audience for the Google-signed Pub/Sub push OIDC token.',
    helpText: 'What this field means: OIDC Audience is the aud value CtrlChecks expects in the Pub/Sub push bearer token. Why it matters: Audience validation prevents a valid Google token for a different endpoint from being reused against this webhook. When to fill it: Leave empty when the Pub/Sub push subscription uses the webhook URL as its audience. Fill it only when your Google Cloud subscription is configured with a custom audience. What to enter: The exact audience string from the Pub/Sub push subscription OIDC settings. Where the value comes from: In Google Cloud Console, open the Pub/Sub subscription, edit push authentication, and check the audience value. How to use it later: This is auth setup, not workflow data; it will not be available as {{$json.audience}}. Accepted format: Usually the full webhook URL, or a custom HTTPS audience string. Real workplace example: https://app.ctrlchecks.com/api/gmail/webhook/workflow_123/gmail-trigger-1. If it is empty or wrong: Empty defaults to the generated webhook URL; a wrong value makes valid Google pushes fail as Invalid Gmail Pub/Sub push request. Common mistake: Setting this to the Pub/Sub topic name or project ID instead of the OIDC token audience.',
    placeholder: 'Defaults to the webhook URL',
    example: 'https://app.ctrlchecks.com/api/gmail/webhook/workflow_123/gmail-trigger-1',
  },
  {
    name: 'Validation Secret',
    internalKey: 'validationSecret',
    type: 'password',
    required: false,
    description: 'Optional shared secret for simulations or environments that cannot use Pub/Sub OIDC token validation.',
    helpText: 'What this field means: Validation Secret is an optional shared token that can authorize a Pub/Sub simulation request through the token query parameter or x-goog-pubsub-token header. Why it matters: It gives test environments a safer alternative to disabling Validate Push Auth entirely. When to fill it: Use it for local/manual simulations or a controlled Pub/Sub setup where OIDC is not available. Leave it empty when using Google-signed OIDC. What to enter: A long random secret value, stored in the workflow configuration as a secret-like field. Where the value comes from: Generate it in your password manager or deployment secret tooling; the runtime can also read GMAIL_PUBSUB_TOKEN from the environment. How to use it later: This secret is never output to {{$json}} and should never be mapped into downstream nodes. Accepted format: Plain secret text. Real workplace example: A staging workflow uses a generated token so QA can post sample Pub/Sub envelopes. If it is empty or wrong: Empty relies on OIDC validation; a wrong token causes Invalid Gmail Pub/Sub push request. Common mistake: Putting a Google OAuth access token here. OAuth tokens belong in Connections/credential vault, not in this field.',
    placeholder: 'Optional simulation secret',
    example: 'staging-gmail-push-token-rotate-me',
    notes: 'Use OIDC for production whenever possible. This field is credential-owned in the runtime override and should be treated as secret material.',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive Gmail notification',
  value: 'receive',
  description: 'Receives a Google Cloud Pub/Sub push notification for a watched Gmail mailbox, validates the push request, reads Gmail history from the stored historyId, filters accepted message or label events, and starts one workflow execution per accepted event.',
  fields,
  outputExample: {
    eventId: 'msg_1784399000-message_added',
    eventType: 'message_added',
    source: 'gmail',
    userId: 'support@example.com',
    username: 'support@example.com',
    text: 'Hi, I need help with invoice INV-1042...',
    timestamp: '2026-07-18T10:15:00.000Z',
    emailAddress: 'support@example.com',
    historyId: '1234567',
    messageId: 'msg_1784399000',
    threadId: 'thread_1042',
    subject: 'Invoice INV-1042 question',
    from: 'Customer Ops <customer@example.com>',
    to: 'support@example.com',
    snippet: 'Hi, I need help with invoice INV-1042...',
    labelIds: ['INBOX', 'IMPORTANT'],
    raw: { id: 'msg_1784399000', threadId: 'thread_1042', snippet: 'Hi, I need help with invoice INV-1042...' },
    trigger: 'gmail',
    workflow_id: 'workflow_123',
    node_id: 'gmail-trigger-1',
    sessionId: 'gmail_workflow_123_thread_1042',
    _gmail: true,
  },
  outputDescription: 'eventId: normalized message-event ID. eventType: message_added, label_added, label_removed, or message_deleted. source: gmail. userId: mailbox email address. username: mailbox email address. text: Gmail snippet. timestamp: message internal date or processing time. emailAddress: watched mailbox. historyId: latest Gmail history cursor. messageId: Gmail message ID. threadId: Gmail thread ID. subject: message Subject header. from: message From header. to: message To header. snippet: Gmail snippet. labelIds: labels returned for the message. raw: raw Gmail metadata or deleted-message fallback. trigger: gmail marker. workflow_id: workflow receiving the event. node_id: trigger node ID. sessionId: Gmail trigger session ID based on thread or message. _gmail: internal true marker.',
  usageExample: {
    scenario: 'Triage new support emails from the shared Gmail inbox and draft an AI-assisted reply in the same thread',
    inputValues: {
      pubsubTopic: 'projects/acme-support/topics/gmail-inbox-notifications',
      eventTypes: 'message_added',
      labelIds: 'INBOX, IMPORTANT',
      query: 'invoice',
      validateAuth: 'true',
      audience: '',
      validationSecret: '',
    },
    expectedOutput: 'The next node can use {{$json.subject}}, {{$json.from}}, {{$json.snippet}}, {{$json.threadId}}, {{$json.messageId}}, {{$json.labelIds}}, and {{$json.eventType}}.',
  },
  externalDocsUrl: gmailPushDocs,
};

export const gmailTriggerDoc: NodeDoc = {
  slug: 'gmail_trigger',
  displayName: 'Gmail Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Gmail.svg',
  description: 'Start workflows from watched Gmail mailbox changes delivered through Google Cloud Pub/Sub push notifications.',
  credentialType: 'Google OAuth2',
  credentialSetupSteps: [
    'Connect Google (Gmail) in Connections. CtrlChecks stores OAuth access token and refresh token material in the credential vault; do not paste OAuth tokens into normal workflow fields.',
    'The Gmail Trigger runtime requires Gmail read access: https://www.googleapis.com/auth/gmail.readonly. The shared Google OAuth connection may also include gmail.send for the Google Gmail action node.',
    'The connected Google account must be the mailbox owner or an account allowed to watch the mailbox; Gmail users.watch is registered for users/me using that connection.',
    'In Google Cloud Console, create or reuse a Pub/Sub topic such as projects/YOUR_PROJECT/topics/gmail-notifications and grant Pub/Sub Publisher to gmail-api-push@system.gserviceaccount.com.',
    'Create a Pub/Sub push subscription on that topic with the generated CtrlChecks webhook URL as the push endpoint. Use Google-signed OIDC authentication with the webhook URL as audience unless your admin configured a custom OIDC Audience.',
    'Save the full Pub/Sub topic name on the node and register/activate the workflow. CtrlChecks calls Gmail users.watch, stores the returned historyId in Redis under gmail:watch:${workflowId}:${nodeId}, keeps a 9-day local TTL, and renews watches every 6 hours when they are near expiration.',
    'If a notification arrives before state exists, CtrlChecks seeds the watch baseline from that notification and skips replaying old mailbox history. If Gmail says the stored historyId is too old, the service emits no replay events for the unrecoverable gap.',
    'For setup checks, the Google OAuth connection uses Google account identity endpoints such as oauth2/v2/userinfo; downstream nodes such as Google Gmail replies, Slack, CRM, or ticketing tools need their own account connections.',
    'Connect the trigger default output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Google OAuth connection only authorizes Gmail watch/read behavior.',
  ],
  credentialDocsUrl: gmailPushDocs,
  resources: [
    {
      name: 'Gmail push webhook',
      description: 'Receives Gmail Pub/Sub push notifications, validates push authentication, reads Gmail history, and emits normalized message or label events.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'PUBLIC_BASE_URL is required to register Gmail push webhooks.',
      cause: 'The app cannot build the public webhook URL that Pub/Sub must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks base URL, then reopen the webhook info/register flow.',
    },
    {
      error: 'A Google Cloud Pub/Sub topic name is required to watch a Gmail mailbox.',
      cause: 'Pub/Sub Topic is blank or only a partial topic name was entered.',
      fix: 'Enter the full topic path in the format projects/PROJECT_ID/topics/TOPIC_NAME.',
    },
    {
      error: 'Invalid Gmail Pub/Sub push request.',
      cause: 'Validate Push Auth is enabled and the request has neither a matching shared token nor a valid Google-signed OIDC bearer token with the expected audience.',
      fix: 'Configure Pub/Sub push OIDC authentication with the generated webhook URL as audience, or use a Validation Secret for controlled simulations.',
    },
    {
      error: 'No active Google connection found. Connect Google (Gmail) in Connections first.',
      cause: 'The workflow owner has no usable Google OAuth connection with Gmail read access.',
      fix: 'Reconnect Google (Gmail) in Connections and make sure gmail.readonly was granted.',
    },
    {
      error: 'Gmail API error (403)',
      cause: 'The connected Google account lacks permission, the Gmail API is disabled, or the Pub/Sub topic publisher permission is incomplete.',
      fix: 'Enable Gmail API, check the connected account, and confirm gmail-api-push@system.gserviceaccount.com can publish to the topic.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to execute Gmail-triggered workflows.',
      cause: 'A valid Gmail event was accepted, but the runtime could not hand the execution to /api/execute-workflow without a public base URL.',
      fix: 'Set PUBLIC_BASE_URL, then re-run the workflow activation/registration path.',
    },
    {
      error: 'No messages trigger after activation',
      cause: 'The Pub/Sub subscription endpoint/auth is wrong, the topic name is wrong, Event Types or Label IDs filter out the event, or activation seeded a baseline and old messages are intentionally skipped.',
      fix: 'Send a new matching email after activation, inspect Pub/Sub delivery attempts, verify label IDs and Keyword Filter, and confirm the watch state was registered.',
    },
    {
      error: 'Next node cannot find Gmail trigger fields',
      cause: 'The next step is reading fields that are not in this trigger output, or a deleted-message event lacks normal message metadata.',
      fix: 'Use {{$json.subject}}, {{$json.from}}, {{$json.snippet}}, {{$json.messageId}}, {{$json.threadId}}, {{$json.labelIds}}, and {{$json.eventType}}; branch on {{$json.eventType}} before relying on message metadata for deletions.',
    },
    {
      error: 'Permission denied after Gmail Trigger',
      cause: 'The trigger connection only authorizes reading Gmail event metadata; downstream apps still need their own credentials and permissions.',
      fix: 'Connect the account required by the next node, such as Google Gmail for replies or Slack/CRM/ticketing credentials for handoff.',
    },
  ],
  relatedNodes: ['google_gmail', 'ai_agent', 'slack_message', 'http_request'],
};
