import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const instagramWebhookDocs = 'https://developers.facebook.com/docs/instagram-platform/webhooks/';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Instagram OAuth2 connection ID used when registering the Instagram webhook subscription.',
    helpText: 'What this field means: Connection points to the saved Instagram OAuth2 account that can receive DMs, comments, and mentions for the connected professional account. The visual node usually uses the selected/default Instagram connection rather than asking you to type this ID. Why it matters: CtrlChecks uses this connection when it registers or tests the Instagram webhook subscription and when it needs the Instagram access token. When to fill it: Leave it blank when the workflow should use your active Instagram connection. Use a specific connection only when your workspace has more than one Instagram account connected. What to enter: Select the Instagram connection in the Connections UI, or use the saved connection ID in generated workflow config. Where the value comes from: CtrlChecks Connections stores it after Instagram/Facebook OAuth sign-in; do not copy a Graph API access token into this field. How to use it later: This setup value is not emitted as {{$json.connectionId}}; downstream Instagram reply nodes use {{$json.senderId}}, {{$json.chatId}}, or {{$json.commentId}} from the trigger output. Accepted format: Saved connection reference such as instagram_oauth_123, not a raw OAuth token. Real workplace example: A social support team uses the Instagram connection owned by the community manager so it can receive DM and comment events for the brand Instagram account. If it is empty or wrong: Empty falls back to the active Instagram connection; a wrong ID can cause No active Instagram connection found or Selected connection is not an Instagram connection. Common mistake: Pasting a Graph API access token here instead of connecting Instagram in Connections.',
    placeholder: 'Use selected/default Instagram connection',
    example: 'instagram_oauth_123',
    notes: 'Credential-owned backend field. Prefer the Connections picker/default connection instead of editing this as normal workflow data.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Instagram event types that can start this workflow.',
    helpText: 'What this field means: Event Types decides which normalized Instagram events this trigger accepts. Why it matters: DMs, story replies, comments, mentions, and postbacks usually need different workflows, and this list controls which of those can start this one. When to fill it: Keep the default while testing; narrow it before production so unrelated Instagram activity does not start the workflow. What to enter: Comma-separated values such as message, comment, mention, message.story_reply, postback. The runtime also accepts aliases such as dm, direct_message, messages, story_reply, comments, mentions, and postbacks. Where the value comes from: Choose the Instagram webhook fields and business events your team wants to handle. How to use it later: Route with {{$json.eventType}}; message covers message.text and message.media, while message.story_reply covers story reply DMs. Accepted format: Comma-separated text or an array in generated config. Real workplace example: message, message.story_reply for an AI DM assistant; comment, mention for public comment moderation. If it is empty or wrong: Empty defaults to message, comment, mention, message.story_reply. Unsupported values cause matching events to be ignored with no workflow execution. Common mistake: Choosing postback without expecting Instagram ice-breaker/quick-reply flows, which is the only current source of postback events.',
    placeholder: 'message, comment, mention, message.story_reply',
    example: 'message, message.story_reply',
    defaultValue: 'message, comment, mention, message.story_reply',
    notes: 'Supported families: message, comment, mention, message.story_reply, postback. Runtime-normalized detailed types include message.text and message.media.',
  },
  {
    name: 'Instagram Business Account ID',
    internalKey: 'instagramBusinessAccountId',
    type: 'string',
    required: false,
    description: 'Optional Instagram Business Account ID filter. Only events for this account are accepted when set.',
    helpText: 'What this field means: Instagram Business Account ID is the numeric ID of the Instagram professional account this workflow should listen to. Why it matters: One Meta app or OAuth account may manage several Instagram accounts, and this filter keeps the wrong account\'s events from starting the workflow. When to fill it: Fill it when your connection can access multiple Instagram accounts. Leave it blank for a single-account setup. What to enter: The numeric Instagram Business Account ID, not the @username, display name, or Facebook Page ID. Where the value comes from: Call Meta Graph API Explorer with /me/accounts and the instagram_business_account field, or read it from the saved Instagram connection. How to use it later: The trigger output includes {{$json.instagramBusinessAccountId}} so reply nodes can confirm which account received the event. Accepted format: Numeric text such as 17841400000000000. Real workplace example: An agency manages Instagram accounts for two clients, so each client\'s workflow filters to that client\'s Instagram Business Account ID only. If it is empty or wrong: Empty accepts events for any connected/subscribed Instagram account. A wrong ID causes valid events to be ignored as a different account. Common mistake: Pasting the Facebook Page ID or the Instagram @username instead of the numeric Instagram Business Account ID.',
    placeholder: '17841400000000000',
    example: '17841400000000000',
  },
  {
    name: 'Allowed Sender IDs',
    internalKey: 'allowedSenderIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated allowlist of Instagram sender IDs.',
    helpText: 'What this field means: Allowed Sender IDs limits the trigger to specific Instagram senders. Why it matters: It can keep a testing or VIP workflow from reacting to every DM sender or commenter. When to fill it: Use it for internal testing, approved partner accounts, or a controlled rollout. Leave it blank for normal public automations. What to enter: Comma-separated sender IDs such as 1234567890, 9876543210. Where the value comes from: Use senderId/chatId from a previous Instagram Trigger test run or an internal allowlist. How to use it later: The accepted event still outputs {{$json.senderId}} and {{$json.chatId}} for replies or audits. Accepted format: Comma-separated text or an array in generated config. Real workplace example: Before launching an Instagram DM assistant, the team allows only two employee sender IDs so they can test without responding to real customers. If it is empty or wrong: Empty allows every matching sender; a wrong ID silently ignores that person\'s events. Common mistake: Using a person\'s visible @username instead of the numeric sender ID from a webhook event.',
    placeholder: '1234567890, 9876543210',
    example: '1234567890',
  },
  {
    name: 'Verify Token',
    internalKey: 'verifyToken',
    type: 'string',
    required: false,
    description: 'Secret token Meta checks when verifying the callback URL.',
    helpText: 'What this field means: Verify Token is the shared text Meta sends during the webhook challenge to prove you configured the callback intentionally. Why it matters: Meta will not activate the webhook callback unless CtrlChecks returns the challenge for the exact matching token. When to fill it: Fill it before verifying the callback URL in Meta for Developers. What to enter: A random phrase or generated secret that is unique to this workflow, such as ig-webhook-verify-2026-support. Where the value comes from: Create it yourself in a password manager or admin setup note, then enter the exact same value in Meta for Developers -> Webhooks. How to use it later: This token is only for webhook setup; it is never emitted as {{$json.verifyToken}} for downstream nodes. Accepted format: Plain text shared token. Real workplace example: The social operations admin sets ig-support-prod-verify-rotate-me while adding the CtrlChecks callback URL to the Meta app. If it is empty or wrong: Callback verification returns Invalid verify token, and Meta will not save the webhook URL. Common mistake: Confusing this with an Instagram/Facebook OAuth access token, app secret, or account password.',
    placeholder: 'random-webhook-token',
    example: 'ig-webhook-verify-2026',
    notes: 'The visual config field uses a standard text control because password is not a supported node panel field type, but the value should still be treated as setup-secret material.',
  },
  {
    name: 'Validate Signature',
    internalKey: 'validateSignature',
    type: 'boolean',
    required: false,
    description: 'Validate Meta X-Hub-Signature-256 before creating an execution.',
    helpText: 'What this field means: Validate Signature checks that Meta signed the webhook request with your app secret. Why it matters: A public webhook URL should reject requests that did not come through the expected Meta app. When to fill it: Keep it enabled for production. Disable only for a controlled local test where you cannot generate Meta signatures. What to enter: true/enabled for real workflows; false/disabled only for temporary debugging. Where the value comes from: This is a security choice made by the workflow owner or admin. The app secret itself comes from worker environment variables META_APP_SECRET, INSTAGRAM_APP_SECRET, or FACEBOOK_APP_SECRET, not from a workflow field. How to use it later: This setting protects whether a workflow starts; it is not output as {{$json.validateSignature}}. Accepted format: Boolean checkbox. Real workplace example: A live Instagram DM support workflow keeps validation enabled so only signed Meta webhook deliveries can create replies or tickets. If it is empty or wrong: Default true requires the worker app secret; if the secret is missing or mismatched, requests fail with Invalid Instagram webhook signature. Common mistake: Turning this off permanently instead of configuring META_APP_SECRET/INSTAGRAM_APP_SECRET/FACEBOOK_APP_SECRET correctly.',
    defaultValue: 'true',
    example: 'true',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive Instagram event',
  value: 'receive',
  description: 'Receives Meta Instagram webhook deliveries, verifies the callback token during setup, optionally validates the request signature, normalizes DMs, story replies, comments, mentions, and postbacks, then starts one workflow execution per accepted event.',
  fields,
  outputExample: {
    eventId: 'mid.$abc123',
    eventType: 'message.text',
    source: 'instagram',
    userId: '1234567890',
    username: '',
    text: 'Can you help me?',
    timestamp: '2026-07-19T10:30:00.000Z',
    chatId: '1234567890',
    senderId: '1234567890',
    recipientId: '17841400000000000',
    instagramBusinessAccountId: '17841400000000000',
    pageId: null,
    messageId: 'mid.$abc123',
    messageType: 'text',
    commentId: null,
    mediaId: null,
    mentionId: null,
    postbackPayload: '',
    isStoryReply: false,
    raw: { entry: [{ messaging: [{ message: { mid: 'mid.$abc123', text: 'Can you help me?' } }] }] },
    trigger: 'instagram',
    workflow_id: 'workflow_123',
    node_id: 'instagram-trigger-1',
    sessionId: 'instagram_workflow_123_1234567890',
    _instagram: true,
  },
  outputDescription: 'eventId: stable message/change ID or generated fallback. eventType: normalized type such as message.text, message.media, message.story_reply, comment, mention, or postback. source: instagram. userId: sender/user ID when available. username: sender name when Meta includes it. text: normalized DM/comment/postback text or attachment URL fallback. timestamp: Meta event time normalized to ISO. chatId: sender conversation ID for DM replies. senderId: Instagram sender ID. recipientId: recipient/business account ID from the event. instagramBusinessAccountId: the Instagram professional account that received the event. pageId: linked Facebook Page ID when Meta includes it in the change payload, otherwise null. messageId: DM message ID. messageType: text, attachment type, or comment/mention/postback. commentId: comment ID for comment/mention events. mediaId: media ID the comment or mention was made on. mentionId: mention identifier for mention events. postbackPayload: quick reply/postback payload. isStoryReply: true when the DM is a reply to an Instagram story. raw: original Meta event fragment. trigger/workflow_id/node_id/sessionId/_instagram: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Reply to an Instagram DM with an AI Agent and send the answer back from the same account',
    inputValues: {
      connectionId: '',
      eventTypes: 'message, message.story_reply',
      instagramBusinessAccountId: '17841400000000000',
      allowedSenderIds: '',
      verifyToken: 'ig-webhook-verify-2026-support',
      validateSignature: 'true',
    },
    expectedOutput: 'Use {{$json.text}} as the visitor question, {{$json.senderId}} as the Instagram recipientId for the reply node, {{$json.instagramBusinessAccountId}} to confirm the receiving account, and {{$json.eventType}} to route messages separately from comments or mentions.',
  },
  externalDocsUrl: instagramWebhookDocs,
};

export const instagramTriggerDoc: NodeDoc = {
  slug: 'instagram_trigger',
  displayName: 'Instagram Trigger',
  category: 'Triggers',
  logoUrl: '/icons/nodes/instagram_trigger.svg',
  description: 'Start workflows from real-time Instagram DMs, comments, mentions, story replies, and postbacks received through Meta webhooks.',
  credentialType: 'Instagram OAuth2',
  credentialSetupSteps: [
    'Connect Instagram OAuth2 in Connections with the Facebook account linked to your Instagram Business or Creator account. CtrlChecks stores OAuth access token material in the credential vault; do not paste Graph API access tokens into normal workflow fields.',
    'The connection requests messaging/comment permissions used by trigger and reply workflows: instagram_basic, instagram_content_publish, instagram_manage_messages, instagram_manage_comments, pages_show_list, pages_read_engagement, pages_manage_metadata, and business_management. Some permissions may require Meta App Review before production use.',
    'Test the connection with the built-in Instagram test request. It calls https://graph.facebook.com/v19.0/me/accounts?fields=id,name,instagram_business_account to confirm the account can list Pages and resolve the linked Instagram Business Account ID.',
    'Set Event Types, optional Instagram Business Account ID, optional Allowed Sender IDs, Verify Token, and Validate Signature on the trigger node.',
    'In Meta for Developers -> Webhooks, add the generated CtrlChecks callback URL for this workflow/node and enter the exact same Verify Token. Subscribe the Instagram object fields you need, commonly messages, comments, and mentions.',
    'Keep Validate Signature enabled in production and configure META_APP_SECRET, INSTAGRAM_APP_SECRET, or FACEBOOK_APP_SECRET on the worker so CtrlChecks can verify X-Hub-Signature-256.',
    'Activation/registration may attempt to subscribe the Instagram Business Account automatically through /{instagramBusinessAccountId}/subscribed_apps. The returned setup status still marks manualSetupRequired: true, so confirm the subscription in Meta if the automatic subscribe call is not permitted.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Instagram OAuth2 connection authorizes Instagram webhook/receive behavior, while an Instagram reply node, Slack, CRM, email, or ticketing node uses its own credentials.',
  ],
  credentialDocsUrl: instagramWebhookDocs,
  resources: [
    {
      name: 'Meta webhook',
      description: 'Receives Meta Instagram webhook events, validates the challenge/signature, normalizes the payload, and starts the workflow.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Invalid verify token.',
      cause: 'Meta sent a webhook challenge with a token that does not exactly match the trigger Verify Token, or Verify Token is blank.',
      fix: 'Copy the same generated token into CtrlChecks and Meta for Developers -> Webhooks, then verify the callback URL again.',
    },
    {
      error: 'Invalid Instagram webhook signature.',
      cause: 'Validate Signature is enabled and the worker has no META_APP_SECRET/INSTAGRAM_APP_SECRET/FACEBOOK_APP_SECRET, the secret is wrong, or the request was not signed by the configured Meta app.',
      fix: 'Set the correct app secret on the worker, restart it, and retry a real Meta webhook delivery. Disable validation only for temporary local tests.',
    },
    {
      error: 'Instagram webhook received, no events matched this trigger.',
      cause: 'The webhook payload was valid, but Event Types, Instagram Business Account ID, or Allowed Sender IDs filtered out every normalized event.',
      fix: 'Broaden Event Types, clear filters temporarily, send a fresh DM/comment test event, then narrow the filters after confirming the output.',
    },
    {
      error: 'No active Instagram connection found. Create one in Connections first.',
      cause: 'The workflow owner has not connected Instagram or the saved connection expired.',
      fix: 'Reconnect Instagram in CtrlChecks -> Connections, then activate the workflow again.',
    },
    {
      error: 'Selected connection is not an Instagram connection.',
      cause: 'The saved connection ID points to another provider or an inactive credential.',
      fix: 'Select an Instagram OAuth2 connection or leave Connection blank so CtrlChecks can use the active Instagram connection.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Instagram webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Meta must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to execute Instagram-triggered workflows.',
      cause: 'A matching event was accepted, but the worker could not call /api/execute-workflow for the new execution.',
      fix: 'Set PUBLIC_BASE_URL, restart the worker, and send another matching Instagram event.',
    },
    {
      error: 'Instagram Trigger node not found in this workflow.',
      cause: 'The callback URL points to a node ID that is missing, renamed incorrectly, or no longer has type instagram_trigger.',
      fix: 'Save the workflow with the Instagram Trigger node still present, then copy the fresh callback URL.',
    },
    {
      error: 'Next node cannot find Instagram trigger fields',
      cause: 'The next step is mapped to a field that is only present for another event type, such as commentId on a DM or senderId on some mention events.',
      fix: 'Use {{$json.eventType}} to branch by event family before mapping event-specific fields. Use {{$json.senderId}} for DM replies and {{$json.commentId}} for comment/mention replies.',
    },
    {
      error: 'Permission denied after Instagram Trigger',
      cause: 'The trigger received the event, but the downstream Instagram reply, Slack, CRM, email, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node account connection and make sure the Instagram action node has instagram_manage_messages/instagram_manage_comments or the relevant permission for the action.',
    },
  ],
  relatedNodes: ['instagram', 'ai_agent', 'if_else'],
};
