import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const jiraWebhookDocs = 'https://developer.atlassian.com/cloud/jira/platform/webhooks/';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Jira connection ID (Atlassian email + API token). The visual node always uses your active Jira connection today.',
    helpText: 'What this field means: Connection points to the saved Jira credential (Atlassian account email + API token + site domain) CtrlChecks uses to verify your Jira account and to call the Jira API when registering webhook state. Why it matters: Without a working Jira connection, registration cannot confirm your account and the trigger cannot generate a webhook URL. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields, and CtrlChecks always resolves your active jira_api_key (or legacy jira) connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save your Atlassian email, API token, and domain. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw API token. Real workplace example: A platform team saves one Jira connection for the account that manages the SUPPORT and DEV projects, and every Jira Trigger node in the workspace reuses it. If it is empty or wrong: Registration fails with No active Jira connection found. Save your Jira email + API token in Connections first. Common mistake: Pasting your raw Atlassian API token into a normal workflow field instead of saving it under Connections.',
    placeholder: 'Uses your active Jira connection',
    example: 'jira_api_key_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Jira Site URL',
    internalKey: 'siteUrl',
    type: 'string',
    required: false,
    description: 'Your Atlassian domain. Defaults to the domain saved in your Jira connection if left blank.',
    helpText: 'What this field means: Jira Site URL is the Atlassian Cloud domain the webhook events belong to, such as yourcompany.atlassian.net. Why it matters: CtrlChecks uses it to build issue/comment links (issueUrl) in the trigger output and to confirm which site your webhook state belongs to. When to fill it: Leave it blank in almost every setup — CtrlChecks falls back to the domain already saved in your Jira connection. Fill it only if your workspace has connections for more than one Atlassian site and this workflow must be tied to a specific one. What to enter: The bare domain, such as yourcompany.atlassian.net, not a full https:// URL, not the site name, and not a project URL. Where the value comes from: Look at the address bar while logged into Jira Cloud — the part before /jira/ or /browse/. How to use it later: The trigger output includes {{$json.siteUrl}} and uses it to build {{$json.issueUrl}}. Accepted format: Plain domain text; CtrlChecks adds https:// automatically when needed. Real workplace example: An agency with two Atlassian sites sets Jira Site URL to client-a.atlassian.net on the client-specific workflow so registration and links stay scoped to that site. If it is empty or wrong: Empty falls back to your connection domain; a wrong or misspelled domain can produce broken issueUrl links or registration failures. Common mistake: Pasting a full issue URL such as https://yourcompany.atlassian.net/browse/PROJ-123 instead of just the domain.',
    placeholder: 'yourcompany.atlassian.net',
    example: 'yourcompany.atlassian.net',
  },
  {
    name: 'Project Key',
    internalKey: 'projectKey',
    type: 'string',
    required: false,
    description: 'Optional. Scope this trigger to one Jira project key.',
    helpText: 'What this field means: Project Key restricts this trigger to events from one Jira project, identified by its short key. Why it matters: A single Jira webhook (configured once in Jira) can cover every project on the site; without this filter, every project\'s events would start this same workflow. When to fill it: Fill it whenever this workflow should react to only one project, such as SUPPORT tickets but not internal DEV issues. Leave it blank to accept events from every project the underlying Jira webhook is configured to send. What to enter: The short project key shown before the dash in issue keys, such as PROJ or SUPPORT — not the full project name. Where the value comes from: Open any issue in the target project and read the prefix before the hyphen in its key, e.g. PROJ-123 means the key is PROJ. How to use it later: The trigger output includes {{$json.projectKey}} for logging, routing, or filtering later in the workflow. Accepted format: Plain project key text; CtrlChecks compares it case-insensitively. Real workplace example: A support team sets Project Key to SUPPORT so only customer support issues trigger the ticket-triage workflow, while internal engineering issues in the DEV project are ignored. If it is empty or wrong: Empty accepts every project the webhook covers; a key that does not match any incoming event\'s project silently ignores every event with the message Ignored Jira event for project. Common mistake: Typing the full project name (such as "Customer Support") instead of the short key (SUPPORT).',
    placeholder: 'PROJ',
    example: 'PROJ',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated Jira webhook event types to listen for.',
    helpText: 'What this field means: Event Types decides which Jira webhook event kinds are allowed to start this workflow. Why it matters: Issue creation, issue updates, issue deletion, and comment activity are usually very different workflows with different downstream actions. When to fill it: Keep the default while testing; narrow it before production so unrelated Jira activity does not start the workflow. What to enter: Comma-separated values such as jira:issue_created, jira:issue_updated, comment_created. Also accepted: jira:issue_deleted, comment_updated, comment_deleted, or any other webhookEvent value Jira sends (such as worklog_created) if your Jira webhook is configured to send it. Where the value comes from: Pick the exact webhookEvent names from Atlassian\'s webhook documentation, matching the events you selected when configuring the webhook in Jira itself. How to use it later: Route with {{$json.eventType}}, which always equals the raw webhookEvent value Jira sent. Accepted format: Comma-separated text, matched case-insensitively. Real workplace example: jira:issue_created, comment_created for a support triage workflow that reacts to new tickets and new customer replies, but ignores routine field edits. If it is empty or wrong: Empty defaults to jira:issue_created, jira:issue_updated, comment_created. A value that never matches an incoming eventType silently ignores every event with Ignored Jira event type. Common mistake: Typing a made-up event name instead of Jira\'s exact webhookEvent value, or forgetting that Jira itself must also be configured to send that event type.',
    placeholder: 'jira:issue_created, jira:issue_updated, comment_created',
    defaultValue: 'jira:issue_created, jira:issue_updated, comment_created',
    example: 'jira:issue_created',
  },
  {
    name: 'Webhook Secret Override',
    internalKey: 'secretToken',
    type: 'string',
    required: false,
    description: 'Optional override for the generated webhook secret (sent as ?secret= or X-Jira-Webhook-Secret).',
    helpText: 'What this field means: Webhook Secret Override lets you supply your own shared secret instead of the random one CtrlChecks generates automatically. Why it matters: Jira Cloud webhooks carry no signature at all, so this secret (checked as a URL query parameter or an X-Jira-Webhook-Secret header) is the only thing that stops a stranger from calling your webhook URL and faking Jira events. When to fill it: Leave it blank for almost every setup — CtrlChecks generates and stores a secret automatically the first time you register the webhook. Fill it only when migrating an existing Automation for Jira rule that must keep reusing one known secret value. What to enter: A long random string from a password manager or admin note, not your Atlassian API token or account password. Where the value comes from: Usually CtrlChecks generates it; if you override it, use that exact same value in Jira\'s WebHooks admin page URL or the Automation for Jira request header. How to use it later: This is setup-only and is never emitted as {{$json.secretToken}} to downstream nodes. Accepted format: Plain secret text; the visual field uses a standard text control even though the value should be treated as secret material. Real workplace example: A DevOps admin migrating an existing Automation for Jira rule reuses its already-approved secret here so they do not have to update the receiving system twice. If it is empty or wrong: Empty lets CtrlChecks generate and manage the secret automatically; a value here that does not match what is configured in Jira causes Invalid or missing Jira webhook secret and no workflow execution. Common mistake: Confusing this with the Jira API token used for the Connections credential — they are unrelated values.',
    placeholder: 'Auto-generated unless overridden',
    example: 'a1b2c3d4e5f6',
    notes: 'The visual config field uses a standard text control because password is not a supported node panel field type, but the value should still be treated as setup-secret material.',
  },
  {
    name: 'JQL Filter (configured in Jira)',
    internalKey: 'jql',
    type: 'string',
    required: false,
    description: 'Optional reminder field. JQL filtering is configured directly on the webhook in Jira, not enforced by CtrlChecks.',
    helpText: 'What this field means: JQL Filter is a reminder/documentation field showing the Jira Query Language filter you may have attached to the underlying webhook inside Jira itself. Why it matters: Jira lets you scope a System WebHook to only fire for issues matching a JQL query (for example, a specific project and priority); this field exists so the workflow shows that filter for reference. When to fill it: Only fill it to document what you already configured on the webhook inside Jira\'s System > WebHooks admin page — CtrlChecks never sends or enforces this value itself. What to enter: A valid JQL expression matching what you actually set in Jira, such as project = PROJ AND status = "In Progress". Where the value comes from: Copy it from the JQL filter box on the corresponding webhook entry in Jira Settings -> System -> WebHooks. How to use it later: This is a documentation value only; it is not emitted as {{$json.jql}} and CtrlChecks does not evaluate it. Accepted format: Plain JQL syntax text. Real workplace example: A team sets project = SUPPORT AND priority = Highest here purely so anyone editing the workflow later understands why only urgent Support tickets ever reach it. If it is empty or wrong: Leaving it blank has no effect on delivery — the real filtering happens only inside Jira\'s webhook configuration; entering text here that does not match the real Jira-side filter can mislead a teammate later. Common mistake: Assuming CtrlChecks applies this filter — if you need real filtering, configure the JQL on the webhook in Jira itself, or use Project Key/Keyword Filter on this node for filtering CtrlChecks does enforce.',
    placeholder: 'project = PROJ AND status = "In Progress"',
    example: 'project = PROJ AND status = "In Progress"',
    notes: 'Documentation-only field. CtrlChecks does not send or evaluate this JQL; set the real filter on the webhook inside Jira.',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional keyword matched against the event text (issue summary or comment body).',
    helpText: 'What this field means: Keyword Filter only lets events whose normalized text contains a word or phrase start the workflow. Why it matters: A busy Jira site can produce a lot of noise; this filter keeps the workflow focused on urgent issues or specific keywords without needing a second webhook in Jira. When to fill it: Use it when the workflow should react only to a phrase such as urgent, security, or a customer name. Leave it blank to accept every event matching Event Types and Project Key. What to enter: A simple keyword or short phrase, not JQL syntax. Where the value comes from: Pick the label, customer name, module name, or severity term your team uses in issue summaries or comment bodies. How to use it later: The accepted event output still includes {{$json.text}} (the issue summary or comment body) and {{$json.issueSummary}}/{{$json.commentBody}} for downstream routing. Accepted format: Plain text, case-insensitive contains match. Real workplace example: security starts only issue/comment workflows that mention security-related work. If it is empty or wrong: Empty accepts every event matching the other filters; a too-specific or misspelled filter causes Ignored Jira event not matching this trigger. Common mistake: Expecting JQL syntax such as text ~ "urgent" here — this is a simple text contains filter, not JQL.',
    placeholder: 'urgent',
    example: 'urgent',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive event',
  value: 'receive',
  description: 'Starts the workflow when a matching Jira Cloud webhook delivery arrives — jira:issue_created, jira:issue_updated, jira:issue_deleted, comment_created, comment_updated, comment_deleted, or any other webhookEvent your Jira webhook is configured to send.',
  fields,
  outputExample: {
    eventId: '10002',
    eventType: 'jira:issue_created',
    source: 'jira',
    userId: '5b10a2844c20165700ede21g',
    username: 'Alex Morgan',
    text: 'Bug: something broke',
    timestamp: '2026-07-19T10:20:00.000Z',
    siteUrl: 'https://yourcompany.atlassian.net',
    cloudId: null,
    issueKey: 'PROJ-123',
    issueId: '10002',
    issueSummary: 'Bug: something broke',
    issueUrl: 'https://yourcompany.atlassian.net/browse/PROJ-123',
    issueType: 'Bug',
    issueStatus: 'To Do',
    projectKey: 'PROJ',
    commentBody: null,
    commentUrl: null,
    raw: {},
    trigger: 'jira',
    workflow_id: 'workflow_123',
    node_id: 'jira-trigger-1',
    sessionId: 'jira_workflow_123_10002',
    _jira: true,
  },
  outputDescription: 'eventId: issue/comment ID when available, otherwise a generated ID. eventType: the raw webhookEvent value Jira sent, such as jira:issue_created or comment_created. source: jira. userId/username: the Jira account that triggered the event when Jira includes it. text: issue summary for issue events, comment body for comment events, or a generated fallback sentence for other event kinds. timestamp: ISO event time. siteUrl: the Atlassian domain, derived from the issue/comment self link. cloudId: always null today — reserved for a future Jira Cloud ID lookup. issueKey/issueId/issueSummary/issueUrl/issueType/issueStatus: issue details, null on non-issue events. projectKey: the project the issue belongs to. commentBody/commentUrl: populated only for comment_created/updated/deleted events. raw: the original Jira webhook payload. trigger/workflow_id/node_id/sessionId/_jira: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Triage new Jira issues with an AI Agent and post a summary comment back on the issue',
    inputValues: {
      siteUrl: '',
      projectKey: 'PROJ',
      eventTypes: 'jira:issue_created',
      secretToken: '',
      jql: '',
      query: '',
    },
    expectedOutput: 'Use {{$json.issueKey}} and {{$json.issueSummary}} in an AI Agent or downstream Jira action node, and {{$json.issueUrl}} in a Slack/email notification.',
  },
  externalDocsUrl: jiraWebhookDocs,
};

export const jiraTriggerDoc: NodeDoc = {
  slug: 'jira_trigger',
  displayName: 'Jira Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Jira.svg',
  description: 'Start workflows from Jira issue created/updated/deleted or comment created/updated/deleted events, delivered through a manually configured Jira Cloud webhook.',
  credentialType: 'Jira API Token (Email + API Token)',
  credentialSetupSteps: [
    'Create a Jira API token at id.atlassian.com/manage-profile/security/api-tokens.',
    'Connect Jira in Connections using your Atlassian account email, the API token, and your site domain (e.g. yourcompany.atlassian.net). CtrlChecks tests the connection with a GET request to https://{{domain}}/rest/api/3/myself.',
    'Add this trigger to a workflow, optionally set a Project Key, and save/activate the workflow — CtrlChecks generates the exact webhook URL and secret.',
    'Important: unlike GitHub/GitLab, CtrlChecks cannot automatically register this webhook with Jira. Jira Cloud\'s dynamic-webhooks REST endpoint is restricted to Connect/OAuth apps, and a Basic Auth email+API-token credential cannot call it. As a Jira site admin, open Jira Settings -> System -> WebHooks and create a webhook using the generated URL (the secret is already embedded as a query parameter). If you are not a site admin, use an "Automation for Jira" rule with a "Send web request" action instead, which can also send the secret as an X-Jira-Webhook-Secret header.',
    'Jira Cloud webhook payloads are never signed — there is no HMAC or JWT to validate. Keep the generated secret private; it is the only thing preventing an outside caller from faking Jira events on this URL.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Jira connection only authorizes reading your Jira account identity for registration, not the Slack, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: 'https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/',
  resources: [
    {
      name: 'Webhook',
      description: 'Receives Jira Cloud webhook deliveries and emits a normalized event payload.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'No active Jira connection found. Save your Jira email + API token in Connections first.',
      cause: 'The workflow owner has not connected Jira, or the saved email/API token/domain is invalid or incomplete.',
      fix: 'Save a valid Jira email + API token + site domain in Connections, then re-activate the workflow or re-register the webhook.',
    },
    {
      error: 'Invalid or missing Jira webhook secret.',
      cause: 'Jira does not sign webhook payloads. Validation relies on a per-node secret CtrlChecks generates and embeds in the webhook URL (or an X-Jira-Webhook-Secret header). The secret was missing or did not match.',
      fix: 'Re-register the webhook from the node to get a fresh URL with the correct secret, then update the URL configured in Jira\'s WebHooks admin page or Automation for Jira rule.',
    },
    {
      error: 'Ignored non-actionable Jira payload.',
      cause: 'The delivery had no recognizable webhookEvent field, such as a Jira connectivity test ping.',
      fix: 'No action needed for pings; confirm the webhook is configured for real issue/comment events in Jira if you expected a workflow run.',
    },
    {
      error: 'Ignored Jira event not matching this trigger.',
      cause: 'The event was valid, but Event Types, Project Key, or Keyword Filter filtered it out.',
      fix: 'Broaden Event Types, clear Project Key/Keyword Filter temporarily, trigger a fresh Jira test event, then narrow the filters again after confirming the output.',
    },
    {
      error: 'Webhook not receiving events after saving the workflow',
      cause: 'Unlike GitHub/GitLab, Jira Cloud webhook registration cannot be fully automated with an API-token credential — Jira restricts the dynamic webhooks REST endpoint to Connect/OAuth apps. CtrlChecks only generates the URL; nothing is registered on Jira\'s side automatically.',
      fix: 'As a Jira site admin, add the generated URL under Jira Settings -> System -> WebHooks, or use an Automation for Jira "Send web request" action if you do not have site-admin access.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Jira webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Jira must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to execute Jira-triggered workflows.',
      cause: 'A matching event was accepted, but the worker could not call /api/execute-workflow for the new execution.',
      fix: 'Set PUBLIC_BASE_URL, restart the worker, and send another matching Jira event.',
    },
    {
      error: 'Jira Trigger node not found in this workflow.',
      cause: 'The webhook URL points to a node ID that is missing, renamed incorrectly, or no longer has type jira_trigger.',
      fix: 'Save the workflow with the Jira Trigger node still present, then copy the fresh webhook URL.',
    },
    {
      error: 'Next node cannot find Jira trigger fields',
      cause: 'A downstream node is mapped to a field only present for another event family, such as {{$json.commentBody}} on an issue-created event.',
      fix: 'Use {{$json.eventType}} to branch by event family before mapping event-specific fields. Use {{$json.issueKey}}/{{$json.issueSummary}} for issue events and {{$json.commentBody}}/{{$json.commentUrl}} for comment events.',
    },
    {
      error: 'Permission denied after Jira Trigger',
      cause: 'The trigger fired correctly, but the downstream Jira action, Slack, email, or ticketing node lacks its own account connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Jira credential has permission for the project the action targets.',
    },
  ],
  relatedNodes: ['jira', 'ai_agent', 'if_else'],
};
