import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const linearWebhookDocs = 'https://linear.app/developers/webhooks';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Linear connection ID. The visual node always uses your active Linear connection today.',
    helpText: 'What this field means: Connection points to the saved Linear credential (Personal API Key or OAuth2) CtrlChecks uses to create and delete the Linear webhook on your behalf. Why it matters: Unlike Jira, Linear Trigger fully automates webhook setup by calling Linear\'s GraphQL webhookCreate mutation — this only works with a working, sufficiently-privileged connection. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Linear connection (checking a Personal API Key first, then OAuth2) automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save a Linear Personal API Key or complete Linear OAuth2. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw API key. Real workplace example: An engineering team saves one Linear connection from a workspace admin account so every Linear Trigger node in the workspace can register its own webhook automatically. If it is empty or wrong: Registration fails with No active Linear connection found. Save a Linear Personal API Key connection first, or with a Linear API error if the credential lacks permission to create webhooks. Common mistake: Saving a Personal API Key from a regular member account instead of a workspace admin account — Linear restricts webhook creation to admin-level access.',
    placeholder: 'Uses your active Linear connection',
    example: 'linear_api_key_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Team ID',
    internalKey: 'teamId',
    type: 'string',
    required: false,
    description: 'Optional Linear team UUID. Leave blank for all public teams.',
    helpText: 'What this field means: Team ID scopes the registered webhook (and this trigger\'s filtering) to one specific Linear team. Why it matters: A Linear workspace can have many teams; without this, the webhook watches every public team and every team\'s issues/comments can start this workflow. When to fill it: Fill it when this workflow should react to only one team\'s activity, such as an on-call rotation team or a single product squad. Leave it blank (with All Public Teams enabled) to watch every public team. What to enter: The team\'s UUID, not its short key (like ENG) and not its display name. Where the value comes from: Open the team in Linear, go to team Settings, and copy the team ID from the URL or the team\'s API details; you can also read {{$json.teamId}} from a previous test event. How to use it later: The trigger output includes {{$json.teamId}} and {{$json.teamKey}} for logging, routing, or filtering later in the workflow. Accepted format: Linear team UUID text. Real workplace example: A support engineering team sets Team ID to their own team\'s UUID so only their team\'s issues trigger the on-call notification workflow, not every team in the company. If it is empty or wrong: Empty (with All Public Teams on) registers for every public team; a UUID that never matches an incoming event\'s team silently ignores that event with Ignored Linear event for team. Common mistake: Typing the team key (such as ENG) instead of the full team UUID.',
    placeholder: 'team uuid',
    example: 'a1b2c3d4-0000-0000-0000-000000000000',
  },
  {
    name: 'All Public Teams',
    internalKey: 'allPublicTeams',
    type: 'boolean',
    required: false,
    description: 'Register the webhook for all public Linear teams when no team ID is provided.',
    helpText: 'What this field means: All Public Teams tells CtrlChecks whether the Linear webhook should be registered workspace-wide (every public team) instead of one specific team. Why it matters: This decides the scope Linear actually registers the webhook for, separate from Team ID which only filters what this particular trigger accepts afterward. When to fill it: Leave it enabled (the default) whenever Team ID is blank. Turn it off only if you are supplying a Team ID and want the underlying webhook itself scoped to that one team rather than registered broadly. What to enter: Enabled (true) to register broadly across all public teams; disabled (false) together with a filled Team ID to register the webhook narrowly for that team only. Where the value comes from: Decide it based on whether other workflows in your workspace might also want events from this same webhook, or whether you want the tightest possible registration. How to use it later: This is a setup/registration value only; it is not emitted as {{$json.allPublicTeams}} to downstream nodes. Accepted format: Boolean checkbox. Real workplace example: A platform team leaves All Public Teams enabled so one webhook can serve several workflows filtering by different Team IDs, Resource Types, and Event Types after delivery. If it is empty or wrong: Default true is safe and broad; disabling it without a valid Team ID still results in an all-public-teams registration since CtrlChecks needs a real team ID to scope narrowly. Common mistake: Assuming disabling this also filters your workflow\'s incoming events — use Team ID for per-workflow filtering; this field only affects what the underlying Linear webhook itself is registered for.',
    defaultValue: 'true',
    example: 'true',
  },
  {
    name: 'Resource Types',
    internalKey: 'resourceTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated Linear resource types to subscribe to.',
    helpText: 'What this field means: Resource Types decides which kinds of Linear objects the registered webhook itself is subscribed to receive changes for. Why it matters: Linear only sends events for the resource types you list here — for example, without Project in this list, project changes will never reach this trigger at all, regardless of Event Types. When to fill it: Keep the default (Issue, Comment) for most issue-triage and comment-notification workflows. Add more types when you need projects, cycles, labels, reactions, documents, initiatives, customers, or users. What to enter: Comma-separated Linear resource type names such as Issue, Comment, Project, Cycle, IssueLabel, Reaction, Document, Initiative, Customer, User. Where the value comes from: Pick from Linear\'s webhook resource type list based on what kind of change should start this workflow. How to use it later: The eventType/entityType fields in the trigger output reflect whichever resource type actually changed, such as issue_created or project_updated. Accepted format: Comma-separated text, matched against Linear\'s exact resource type names. Real workplace example: Issue, Comment, Project for a workflow that triages issues, tracks comment activity, and reports on project status changes. If it is empty or wrong: Empty defaults to Issue, Comment. Listing a resource type that does not exist in Linear\'s webhook system means CtrlChecks asks Linear to subscribe to it, but Linear simply will not send that kind of event. Common mistake: Assuming Event Types alone controls what data arrives — Resource Types controls the underlying webhook subscription, and Event Types only filters after delivery.',
    placeholder: 'Issue, Comment',
    defaultValue: 'Issue, Comment',
    example: 'Issue, Comment, Project',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated normalized event filters.',
    helpText: 'What this field means: Event Types filters which normalized events (after Resource Types has already let them through) are allowed to start this workflow. Why it matters: One Resource Type like Issue produces several different events — created, updated, removed — that usually deserve different downstream handling. When to fill it: Keep the default while testing; narrow it before production so only the exact activity you care about starts the workflow. What to enter: Comma-separated normalized values such as issue_created, issue_updated, issue_removed, comment_created, project_updated. You can also use the raw Linear entity type (Issue) or action (create) as a looser match. Where the value comes from: Build the name as resource_action, using the resource types you configured above and create/update/remove verbs. How to use it later: Route with {{$json.eventType}}, which is always the exact normalized value this filter compares against. Accepted format: Comma-separated text, matched case-insensitively. Real workplace example: issue_created for a new-issue triage workflow; comment_created for a customer-reply notification workflow. If it is empty or wrong: Empty accepts every event allowed through by Resource Types. A value that never matches an incoming eventType/entityType/action silently ignores every event with Ignored Linear event type. Common mistake: Listing an event type here for a resource you never added to Resource Types — the webhook itself will never deliver that data.',
    placeholder: 'issue_created, issue_updated, comment_created',
    defaultValue: 'issue_created, issue_updated, comment_created',
    example: 'issue_created',
  },
  {
    name: 'Issue ID',
    internalKey: 'issueId',
    type: 'string',
    required: false,
    description: 'Optional issue UUID or identifier filter.',
    helpText: 'What this field means: Issue ID restricts this trigger to events about one specific Linear issue. Why it matters: This turns the trigger from "any issue in this team/project" into a focused watcher on a single, already-known issue. When to fill it: Fill it only when you need a workflow tied to one specific issue, such as watching a single incident ticket for updates. Leave it blank for normal team- or project-wide triage workflows. What to enter: Either the issue\'s UUID or its human identifier such as ENG-123 — both are checked. Where the value comes from: Copy the identifier from the issue\'s URL or title in Linear, or read {{$json.issueId}}/{{$json.issueIdentifier}} from a previous test event. How to use it later: The trigger output still includes {{$json.issueId}} and {{$json.issueIdentifier}} for confirmation or logging. Accepted format: Linear issue UUID or identifier text such as ENG-123. Real workplace example: A release manager sets Issue ID to ENG-500 to get notified in Slack every time that specific tracking issue is commented on. If it is empty or wrong: Empty accepts events for any issue; an ID that never matches an incoming event\'s issue silently ignores it with Ignored Linear event for issue. Common mistake: Pasting a comment URL or project ID here instead of the issue\'s own ID/identifier.',
    placeholder: 'ENG-123 or issue uuid',
    example: 'ENG-123',
  },
  {
    name: 'Project ID',
    internalKey: 'projectId',
    type: 'string',
    required: false,
    description: 'Optional project UUID filter.',
    helpText: 'What this field means: Project ID restricts this trigger to events belonging to one specific Linear project. Why it matters: Teams often run several projects at once; this keeps a project-specific workflow from reacting to unrelated project activity. When to fill it: Fill it when the workflow should only react to one Linear project\'s issues, comments, or project-level updates. Leave it blank to accept events from every project. What to enter: The project\'s UUID, not its display name. Where the value comes from: Open the project in Linear and copy its ID from the project settings or API details, or read {{$json.projectId}} from a previous test event. How to use it later: The trigger output includes {{$json.projectId}} and {{$json.projectName}} for logging or routing. Accepted format: Linear project UUID text. Real workplace example: A vendor integration project sets Project ID to that project\'s UUID so only its own issues and updates reach the integration workflow. If it is empty or wrong: Empty accepts every project\'s events; an ID that never matches silently ignores the event with Ignored Linear event for project. Common mistake: Typing the project\'s display name instead of its UUID.',
    placeholder: 'project uuid',
    example: 'b2c3d4e5-0000-0000-0000-000000000000',
  },
  {
    name: 'Actor ID',
    internalKey: 'actorId',
    type: 'string',
    required: false,
    description: 'Optional Linear actor/user UUID filter.',
    helpText: 'What this field means: Actor ID restricts this trigger to events caused by one specific Linear user. Why it matters: It lets you build a workflow around a particular person\'s activity, such as a manager\'s issue creations or a specific engineer\'s comments. When to fill it: Fill it only for person-specific automations. Leave it blank for normal team-wide triggers so any teammate\'s activity can start the workflow. What to enter: The Linear user\'s UUID, not their display name or email. Where the value comes from: Read {{$json.userId}} from a previous test event triggered by that person, or find it via Linear\'s API/GraphQL explorer. How to use it later: The trigger output includes {{$json.userId}} and {{$json.username}} for confirmation or logging. Accepted format: Linear user UUID text. Real workplace example: A workflow watches only the support lead\'s issue creations so a Slack channel gets pinged specifically when they open a new escalation. If it is empty or wrong: Empty accepts events from any user; an ID that never matches silently ignores the event with Ignored Linear event from actor. Common mistake: Entering the user\'s email address or display name instead of their Linear user UUID.',
    placeholder: 'actor uuid',
    example: 'c3d4e5f6-0000-0000-0000-000000000000',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional keyword filter matched against issue titles, comment bodies, project names, and URLs.',
    helpText: 'What this field means: Keyword Filter only lets events whose normalized text contains a word or phrase start the workflow. Why it matters: A busy Linear workspace can produce a lot of activity; this keeps the workflow focused on urgent issues or specific keywords without needing a separate webhook. When to fill it: Use it when the workflow should react only to a phrase such as urgent, security, or a customer name. Leave it blank to accept every event matching the other filters. What to enter: A simple keyword or short phrase; this is a plain text contains match, not Linear\'s search syntax. Where the value comes from: Pick the label, customer name, module name, or severity term your team uses in issue titles, comment bodies, or project names. How to use it later: The accepted event output still includes {{$json.text}} (issue title, comment body, or project name) plus the specific fields it came from. Accepted format: Plain text, case-insensitive contains match. Real workplace example: security starts only issue/comment/project workflows that mention security-related work. If it is empty or wrong: Empty accepts every event matching the other filters; a too-specific or misspelled filter causes Ignored Linear event not matching this trigger. Common mistake: Typing multiple keywords expecting OR/AND logic — only a single literal phrase is matched as a substring.',
    placeholder: 'urgent',
    example: 'urgent',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Issue And Comment Activity',
  value: 'issue_comment_events',
  description: 'Starts the workflow when a Linear webhook delivery for a subscribed resource type (Issue, Comment, Project, Cycle, IssueLabel, Reaction, Document, Initiative, Customer, or User) arrives, after validating the Linear-Signature HMAC and a fresh webhook timestamp.',
  fields,
  outputExample: {
    eventId: 'a1b2c3d4-0000-0000-0000-000000000000',
    eventType: 'issue_created',
    source: 'linear',
    userId: 'user_uuid',
    username: 'Alex Morgan',
    text: 'Fix billing retry',
    timestamp: '2026-07-19T10:20:00.000Z',
    deliveryId: 'a1b2c3d4-0000-0000-0000-000000000000',
    linearEvent: 'Issue',
    action: 'create',
    entityType: 'Issue',
    entityId: 'issue_uuid',
    organizationId: 'org_uuid',
    webhookId: 'webhook_uuid',
    webhookTimestamp: 1750000000000,
    url: 'https://linear.app/yourteam/issue/ENG-123',
    teamId: 'team_uuid',
    teamKey: 'ENG',
    teamName: 'Engineering',
    issueId: 'issue_uuid',
    issueIdentifier: 'ENG-123',
    issueTitle: 'Fix billing retry',
    issueUrl: 'https://linear.app/yourteam/issue/ENG-123',
    stateId: 'state_uuid',
    stateName: 'Todo',
    assigneeId: null,
    assigneeName: null,
    commentId: null,
    commentBody: null,
    projectId: null,
    projectName: null,
    raw: {},
    trigger: 'linear',
    workflow_id: 'workflow_123',
    node_id: 'linear-trigger-1',
    sessionId: 'linear_workflow_123_a1b2c3d4-0000-0000-0000-000000000000',
    _linear: true,
  },
  outputDescription: 'eventId: deliveryId, webhookId, or entity ID, whichever is available first. eventType: normalized resource_action value such as issue_created or comment_updated. source: linear. userId/username: the Linear user (actor) behind the change. text: issue title, comment body, or project name, whichever applies, else the event URL or eventType as a last resort. timestamp: ISO event time. deliveryId/linearEvent/action/entityType/entityId: raw Linear webhook delivery metadata. organizationId/webhookId/webhookTimestamp: Linear webhook identifiers. url: the Linear-provided link to the changed entity. teamId/teamKey/teamName: the Linear team the entity belongs to. issueId/issueIdentifier/issueTitle/issueUrl/stateId/stateName/assigneeId/assigneeName: issue-specific fields, null when the event is not about an issue. commentId/commentBody: comment-specific fields, null otherwise. projectId/projectName: project-specific fields, null otherwise. raw: the original Linear webhook payload. trigger/workflow_id/node_id/sessionId/_linear: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Triage new Linear issues with an AI Agent and notify the team in Slack',
    inputValues: {
      teamId: '',
      allPublicTeams: 'true',
      resourceTypes: 'Issue, Comment',
      eventTypes: 'issue_created',
      issueId: '',
      projectId: '',
      actorId: '',
      query: '',
    },
    expectedOutput: 'A normalized Linear issue payload available as {{$json.issueId}}, {{$json.issueIdentifier}}, {{$json.issueTitle}}, and {{$json.teamKey}} for an AI Agent or Slack notification node.',
  },
  externalDocsUrl: linearWebhookDocs,
};

export const linearTriggerDoc: NodeDoc = {
  slug: 'linear_trigger',
  displayName: 'Linear Trigger',
  category: 'Triggers',
  logoUrl: '/icons/nodes/linear.svg',
  description: 'Start a workflow from signed Linear webhook events for issues, comments, projects, cycles, labels, reactions, documents, initiatives, customers, and users.',
  credentialType: 'Linear Personal API Key',
  credentialSetupSteps: [
    'Open Linear Settings -> API -> Personal API Keys and create a key.',
    'Create the key from a workspace admin account — Linear restricts webhook creation to admin-level access, so a regular member\'s key can save/connect but registration will fail.',
    'In CtrlChecks, open Connections -> Add Connection -> Linear and save the key (OAuth2 is also accepted as a fallback credential).',
    'Add this trigger to a workflow, set Resource Types and Event Types, optionally set a Team ID, and save/activate the workflow — unlike Jira, CtrlChecks automatically calls Linear\'s webhookCreate GraphQL mutation and registers the webhook for you; no manual step in Linear\'s UI is required.',
    'Linear signs every delivery with a Linear-Signature HMAC-SHA256 header and includes a webhook timestamp; CtrlChecks validates both automatically using the secret it generated during registration, and rejects deliveries whose timestamp is more than about a minute old.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Linear connection only authorizes reading/registering the webhook, not the Slack, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: linearWebhookDocs,
  resources: [
    {
      name: 'Webhook Events',
      description: 'Receive Linear webhook deliveries, automatically registered and signed with Linear-Signature.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'No active Linear connection found. Save a Linear Personal API Key connection first.',
      cause: 'The workflow owner has not connected Linear, or the saved Personal API Key/OAuth2 credential is invalid.',
      fix: 'Save a valid Linear Personal API Key (or complete Linear OAuth2) in Connections, then re-activate the workflow.',
    },
    {
      error: 'Linear API error (403/401): ...',
      cause: 'The saved Linear credential does not have admin-level access, so Linear rejects the webhookCreate mutation.',
      fix: 'Use a Personal API Key generated from a workspace admin account, or an OAuth credential with admin scope.',
    },
    {
      error: 'Linear webhookCreate did not return a webhook id.',
      cause: 'Linear accepted the request but did not return webhook data, usually because of an invalid teamId or resourceTypes value.',
      fix: 'Check Team ID and Resource Types for typos, then save the workflow again to retry registration.',
    },
    {
      error: 'Invalid Linear webhook signature or timestamp.',
      cause: 'The Linear-Signature HMAC did not match the stored secret, or the webhook timestamp is more than about a minute old (Linear\'s replay-protection window).',
      fix: 'Re-register the webhook by saving the active workflow again so a fresh secret is issued; check that server clocks are roughly in sync if timestamps keep failing.',
    },
    {
      error: 'Ignored non-actionable Linear payload.',
      cause: 'The delivery had no recognizable action or resource type, such as a connectivity test.',
      fix: 'No action needed for test pings; confirm Resource Types/Event Types if you expected a real workflow run.',
    },
    {
      error: 'Ignored Linear event not matching this trigger.',
      cause: 'The event was valid, but Event Types, Team ID, Issue ID, Project ID, Actor ID, or Keyword Filter filtered it out.',
      fix: 'Broaden the relevant filter, clear filters temporarily, trigger a fresh Linear test event, then narrow the filters again after confirming the output.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Linear webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Linear must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then save/activate the workflow again.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to execute Linear-triggered workflows.',
      cause: 'A matching event was accepted, but the worker could not call /api/execute-workflow for the new execution.',
      fix: 'Set PUBLIC_BASE_URL, restart the worker, and send another matching Linear event.',
    },
    {
      error: 'Linear Trigger node not found in this workflow.',
      cause: 'The webhook URL points to a node ID that is missing, renamed incorrectly, or no longer has type linear_trigger.',
      fix: 'Save the workflow with the Linear Trigger node still present, then re-register the webhook so a fresh URL is generated.',
    },
    {
      error: 'Next node cannot find Linear trigger fields',
      cause: 'A downstream node is mapped to a field only present for another resource type, such as {{$json.commentBody}} on an issue-only event.',
      fix: 'Use {{$json.eventType}} or {{$json.entityType}} to branch by resource type before mapping type-specific fields.',
    },
    {
      error: 'Permission denied after Linear Trigger',
      cause: 'The trigger fired correctly, but the downstream Linear action, Slack, email, or ticketing node lacks its own account connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Linear credential has permission for the team the action targets.',
    },
  ],
  relatedNodes: ['linear', 'jira_trigger', 'trello_trigger'],
};
