import type { NodeDoc } from '../types';

const operationHelpText = `What this field means: Operation selects which Mailgun action this node performs. Today there is only one implemented action, Send Email.

Why it matters: The dropdown exists so future Mailgun actions (such as validating an address or checking delivery events) can be added later without changing this field's shape — right now it only ever does one thing.

When to fill it: Always has a value; it defaults to Send Email and the panel does not let you pick anything else yet.

What to enter: Leave it on Send Email.
- Send Email: sends one transactional email through the Mailgun Messages API using the fields below. This is the only option currently available, so choosing it is effectively automatic.

Where the value comes from: This is a fixed workflow setting, not something mapped from upstream data.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: The single dropdown value send_email.

Real workplace example: Every Mailgun node in every workflow today uses Send Email, whether it's a password reset, an order receipt, or a welcome email.

If it is empty or wrong: An empty value still runs as Send Email in practice, since it is the only implemented operation.

Common mistake: Expecting other Mailgun actions (like domain or event lookups) to appear here — only sending email is currently supported by this node.`;

const domainHelpText = `What this field means: Domain is the verified Mailgun sending domain (such as mg.yourcompany.com) that Mailgun's Messages API is called under. It comes from the connection you select on this node, not from a normal typed field.

Why it matters: Mailgun rejects the send if the domain is missing, unverified, or does not match where your sending reputation and DNS records live.

When to fill it: You do not fill this directly in the node panel. Select a Mailgun API Key connection on the node, and the domain saved on that connection is used automatically.

What to enter: Nothing here — set the Sending Domain field when you create or edit the Mailgun connection in Connections.

Where the value comes from: Mailgun dashboard → Sending → Domains, copied into the Mailgun connection's Sending Domain field.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: A verified domain name, for example mg.yourcompany.com, or a Mailgun sandbox domain such as sandboxXXXXXXXX.mailgun.org for testing.

Real workplace example: mg.yourcompany.com used as the sending domain for every transactional email your product sends.

If it is empty or wrong: The node returns "Mailgun: domain is required" before contacting Mailgun. A domain that is not fully verified in Mailgun causes the API call itself to fail.

Common mistake: Assuming a sandbox domain behaves like a production domain — Mailgun sandbox domains can only send to recipients you have explicitly authorized in the Mailgun dashboard.`;

const apiKeyHelpText = `What this field means: API Key is the Mailgun private sending key Mailgun uses to authenticate this node's requests. It comes from the connection you select on this node, not from a normal typed field.

Why it matters: This key proves to Mailgun that CtrlChecks is authorized to send on your behalf; a missing or wrong key fails every send.

When to fill it: You do not fill this directly in the node panel. Select a Mailgun API Key connection on the node, and the key saved on that connection is used automatically.

What to enter: Nothing here — paste the Private API Key when you create or edit the Mailgun connection in Connections.

Where the value comes from: Mailgun dashboard → Settings → API Keys → Add new key. Copy the Private API Key, which starts with key-. Never use the separate Public Validation Key for sending.

How to use it later: Not echoed back in the node's own output fields, and never appears in plain workflow data.

Accepted format: A string starting with key-, as generated by Mailgun.

Real workplace example: One shared Mailgun connection with your account's private API key, reused by every Mailgun node across your workflows.

If it is empty or wrong: The node returns "Mailgun: apiKey is required" before contacting Mailgun. A wrong or revoked key causes Mailgun to reject the request as unauthorized.

Common mistake: Pasting the API key into the From, To, or another normal workflow field. Save it only in the Mailgun connection under Connections.`;

const fromHelpText = `What this field means: From is the sender email address Mailgun puts in the message's From header.

Why it matters: Mailgun only accepts sends from addresses on the sending domain saved in your Mailgun connection — an address on a different domain is rejected.

When to fill it: Always required.

What to enter: An address on your verified Mailgun sending domain, such as noreply@mg.yourcompany.com or support@mg.yourcompany.com.

Where the value comes from: Decide a sender address for this type of email, matching the domain saved on your Mailgun connection.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: A single email address. Display-name formats like "Name <email@domain.com>" are not supported — use a plain address.

Real workplace example: receipts@mg.yourcompany.com for order confirmation emails, kept separate from support@mg.yourcompany.com for reply-friendly messages.

If it is empty or wrong: An empty value returns "Mailgun: from email is required" before contacting Mailgun. An address outside the verified sending domain is rejected by Mailgun itself as a send-time failure.

Common mistake: Using an address from a completely different domain than the one saved on the Mailgun connection — Mailgun will not send on behalf of a domain it has not verified for your account.`;

const toHelpText = `What this field means: To is who receives this email, entered as one address or several comma-separated addresses — not a JSON object like some other email nodes use.

Why it matters: Amazon SES or Gmail-style nodes in this product accept a structured {"to": [...]} object, but Mailgun's node does not — mixing up the two formats here would send the literal text instead of real addresses.

When to fill it: Always required.

What to enter: One address, or several separated by commas, with no JSON brackets or quotes.

Where the value comes from: Map it from an earlier step, such as a form submission or CRM lookup.

How to use it later: Not echoed back in the node's own output fields — only messageId/message/mailgun are returned on success.

Accepted format: A single email address (customer@example.com) or comma-separated multiple addresses (alice@example.com, bob@example.com). Do not wrap it in {"to": [...]} JSON — that syntax is for the Amazon SES node, not this one.

Real workplace example: {{$json.customerEmail}} mapped directly from a checkout or signup step for a single recipient, or "alice@example.com, bob@example.com" typed fixed for a small internal distribution list.

If it is empty or wrong: An empty value returns "Mailgun: to email is required" before contacting Mailgun.

Common mistake: Pasting a JSON array or object here (for example {"to": ["user@example.com"]}) — Mailgun's node expects a plain comma-separated string, and a JSON value would be sent as literal unusable text.`;

const subjectHelpText = `What this field means: Subject is the email subject line.

Why it matters: It is the first thing a recipient sees in their inbox, and Mailgun templates can also supply their own subject if this is left blank.

When to fill it: Optional at the schema level, but fill it whenever you are not using a Mailgun template that already defines its own subject.

What to enter: A short, clear description of the email's purpose.

Where the value comes from: Type a fixed subject, or map one from an earlier step such as an order or account record.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: Plain text. {{$json.field}} expressions are resolved before sending.

Real workplace example: "Your {{$json.planName}} receipt for {{$json.orderDate}}" for a billing confirmation email.

If it is empty or wrong: Left empty with no Template set, Mailgun sends the message with a blank subject line rather than failing the whole request — this node does not require Subject at either the schema or runtime level.

Common mistake: Leaving Subject blank while also not using Template — this is legal (Mailgun accepts it) but produces a confusing blank-subject email in the recipient's inbox.`;

const textHelpText = `What this field means: Text is the plain-text body of the email, used by email clients that do not render HTML and as a fallback everywhere else.

Why it matters: Mailgun requires at least one of Text, HTML, or Template to be filled — leaving all three empty fails the send before Mailgun is even contacted.

When to fill it: Fill it whenever you are writing the message content directly (not using a stored Mailgun template). Recommended even when HTML is also filled, as a readable fallback.

What to enter: The message content as plain text, with no HTML tags.

Where the value comes from: Type fixed wording, or map content from a previous step such as a generated summary or notification text.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: Plain text. {{$json.field}} expressions are resolved before sending.

Real workplace example: "Your reset link is {{$json.resetUrl}}. This link expires in 1 hour." as the plain-text half of a password-reset email.

If it is empty or wrong: If Text, HTML, and Template are all empty, the node returns "Mailgun: text, html, or template is required" before contacting Mailgun.

Common mistake: Filling only HTML and skipping Text. Some recipients' spam filters and older mail clients render better (or only work at all) with a plain-text part present.`;

const htmlHelpText = `What this field means: Html is the HTML-formatted body of the email, shown by email clients that support rich formatting.

Why it matters: Mailgun requires at least one of Text, HTML, or Template to be filled — leaving all three empty fails the send before Mailgun is even contacted.

When to fill it: Fill it whenever you want rich formatting (links, bold text, images, layout) instead of, or in addition to, Text.

What to enter: Hand-written HTML markup for the message body.

Where the value comes from: Type fixed HTML, or map content from a previous step such as a generated report or templated snippet.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: HTML markup. {{$json.field}} expressions are resolved before sending, including inside HTML attributes such as href.

Real workplace example: "<p>Click <a href=\\"{{$json.resetUrl}}\\">here</a> to reset your password.</p>" for a clickable password-reset email.

If it is empty or wrong: If Text, HTML, and Template are all empty, the node returns "Mailgun: text, html, or template is required" before contacting Mailgun. Malformed HTML is sent as-is and may render incorrectly in some clients, but does not fail the node.

Common mistake: Forgetting to escape or trust dynamic values placed inside HTML — a mapped value containing HTML-special characters can break the layout if it was not meant to include markup.`;

const ccHelpText = `What this field means: CC lists additional recipients who receive a visible copy of the email, shown in the message headers to every recipient including To.

Why it matters: Everyone on To and CC can see each other's addresses, unlike BCC.

When to fill it: Optional. Fill it when other people should visibly receive a copy, such as a manager or a shared team alias.

What to enter: One address, or several separated by commas — same format as To.

Where the value comes from: A fixed team address, or mapped from an earlier step such as an assigned account manager.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: A single email address or comma-separated multiple addresses, same as To. No JSON brackets.

Real workplace example: "sales-team@yourcompany.com" CC'd on every new-lead notification sent to a sales rep.

If it is empty or wrong: Left empty, no CC recipients are added — there is no error either way, since this field is optional.

Common mistake: Using CC when BCC was intended — CC recipients are visible to every other recipient on the email, which can expose customer addresses to each other.`;

const bccHelpText = `What this field means: BCC lists additional recipients who receive a hidden copy of the email — invisible to the To and CC recipients.

Why it matters: BCC is the right choice whenever a copy needs to go somewhere (compliance, archiving, internal visibility) without other recipients knowing.

When to fill it: Optional. Fill it for internal record-keeping, audit trails, or silent monitoring of outgoing mail.

What to enter: One address, or several separated by commas — same format as To.

Where the value comes from: A fixed internal address, such as a compliance or archive mailbox.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: A single email address or comma-separated multiple addresses, same as To. No JSON brackets.

Real workplace example: "audit@yourcompany.com" BCC'd on every outgoing customer invoice email for internal record-keeping.

If it is empty or wrong: Left empty, no BCC recipients are added — there is no error either way, since this field is optional.

Common mistake: Expecting BCC recipients to be visible anywhere in the delivered email's headers to other recipients — by design, they never are.`;

const replyToHelpText = `What this field means: Reply-To is the address a recipient's reply gets sent to, if it is different from From.

Why it matters: It lets an automated or no-reply sender still route human replies to a monitored inbox.

When to fill it: Optional. Fill it whenever replies to this email should land somewhere other than the From address.

What to enter: A monitored email address, such as a shared support inbox.

Where the value comes from: A fixed team address, or mapped from an earlier step such as an assigned agent's email.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: A single email address, for example support@mg.yourcompany.com.

Real workplace example: Send order confirmations From "receipts@mg.yourcompany.com" but Reply-To "support@yourcompany.com" so replies reach a monitored inbox instead of a receipts-only address.

If it is empty or wrong: Left empty, replies go to the From address as normal — there is no error either way.

Common mistake: Expecting this field to change who the email appears to be sent from — it only affects where replies go.`;

const tagsHelpText = `What this field means: Tags attaches one or more labels to this send, used by Mailgun's own analytics and logs (sent as Mailgun's o:tag parameter) to filter and report on delivery.

Why it matters: Tags let you slice Mailgun's delivery/open/click statistics by campaign or email type without needing separate sending domains per category.

When to fill it: Optional. Fill it when you want this send grouped or filtered in Mailgun's own dashboard and logs.

What to enter: One tag, or several separated by commas.

Where the value comes from: Decide tag categories that matter for your reporting, such as the email type or campaign name.

How to use it later: Not echoed back in the node's own output fields — tags only affect how Mailgun records and reports on the send internally.

Accepted format: Comma-separated plain text, for example welcome,onboarding. Each comma-separated value becomes one separate Mailgun tag.

Real workplace example: "password-reset,transactional" to separate password-reset emails from marketing sends in Mailgun's own analytics.

If it is empty or wrong: Left empty, the email sends normally with no tags attached — there is no error either way.

Common mistake: Confusing Mailgun Tags (internal Mailgun analytics labels) with recipient-facing content — tags are never visible to the email's recipient.`;

const templateHelpText = `What this field means: Template is the exact name of a stored Mailgun template to use for this send.

Why it matters: When set, Mailgun can supply message content from the stored template, so Text/HTML become optional for this send — this satisfies the requirement that at least one of Text, HTML, or Template is present.

When to fill it: Fill it only when you have already created a template in Mailgun and want to reuse its stored design instead of writing Text/HTML here each time.

What to enter: The template's exact name as it appears in Mailgun, case-sensitive.

Where the value comes from: Mailgun dashboard → Sending → Templates, where you create and name reusable templates.

How to use it later: Not echoed back in the node's own output fields.

Accepted format: Plain text matching an existing Mailgun template name exactly.

Real workplace example: "welcome_email" for a branded onboarding email maintained by the marketing team directly in Mailgun.

If it is empty or wrong: If Text, HTML, and Template are all empty, the node returns "Mailgun: text, html, or template is required". A template name that does not exist in Mailgun causes the send itself to fail as a Mailgun API error, since this node does not pre-validate the template name.

Common mistake: Assuming Template Variables alone is enough without Template being filled — Template Variables only has an effect when Template names an actual stored template.`;

const templateVariablesHelpText = `What this field means: Template Variables supplies the values a Mailgun stored template needs to fill in its own placeholders, sent to Mailgun as the t:variables parameter.

Why it matters: Without matching variables, a template's placeholders may render blank or literally in the delivered email.

When to fill it: Fill it whenever the selected Template contains placeholders that need real data.

What to enter: A JSON object whose keys match the variable names used inside the Mailgun template.

Where the value comes from: Match each key to a variable already defined inside the Mailgun template's design, and pull the values from earlier workflow steps.

How to use it later: Not echoed back in the node's own output fields; it is only used to populate the template before sending.

Accepted format: A JSON object, for example {"name": "Ada", "resetUrl": "https://example.com/reset"}. {{$json.field}} expressions inside values are resolved before sending.

Real workplace example: {"name": "{{$json.customerName}}", "resetUrl": "{{$json.resetUrl}}"} for a password-reset template that reads recipient.name and recipient.resetUrl.

If it is empty or wrong: A non-JSON-object value (for example plain text or a JSON array) returns "Mailgun: templateVariables must be a JSON object" before contacting Mailgun. Left empty entirely, the template still sends using its own default/static content.

Common mistake: Sending a JSON array (like ["Ada", "reset-url"]) instead of an object — Mailgun template variables must be keyed by name, not positional.`;

export const mailgunDoc: NodeDoc = {
  slug: 'mailgun',
  displayName: 'Mailgun',
  category: 'Communication',
  logoUrl: '/integrations-logos/Mailgun.svg',
  description: 'Send transactional emails through Mailgun using a saved API key, sending domain, and region, with automatic retry on temporary Mailgun errors.',
  credentialType: 'Mailgun API Key',
  credentialSetupSteps: [
    'What this is: The Mailgun API Key connection stores your private API key, verified sending domain, and region outside regular workflow fields — Domain and API Key are not typed directly into this node.',
    'Prerequisites: a Mailgun account, and a verified sending domain (Mailgun → Sending → Domains) — required before sending real emails; a sandbox domain works for early testing but only to pre-authorized recipients.',
    'How to connect: Mailgun dashboard → Settings → API Keys → Add new key → copy the Private API Key (it starts with key-; do not use the separate Public Validation Key). Note your verified sending domain, for example mg.yourcompany.com, and your account region (check the dashboard URL: app.mailgun.com is US, eu.mailgun.com is EU).',
    'In CtrlChecks: open Connections → Add Connection → Mailgun API Key, then paste the Private API Key, the Sending Domain, choose US or EU Region, and optionally a Default From Email the node can fall back to.',
    'Important: treat the Private API Key like a bank password. Store it only in Connections — never paste it into the From, To, Subject, or any other normal workflow field. If it is ever pasted somewhere outside Connections, revoke and regenerate it in Mailgun.',
    'Test it: save the connection, select it on a Mailgun node with a verified From address, run a simple send, and confirm the node returns success: true with a messageId.',
    'Downstream service node account connections are separate: connecting Mailgun only authorizes this node\'s email send — any node after it in the workflow still needs its own account connection and permissions for its own outgoing line of work.',
  ],
  credentialDocsUrl: 'https://documentation.mailgun.com/docs/mailgun/api-reference/authentication',
  resources: [
    {
      name: 'Operations',
      description: 'Mailgun exposes a single implemented action, configured directly with input fields — the Operation dropdown exists for future expansion but only has one working choice today.',
      operations: [
        {
          name: 'Send Email',
          value: 'send_email',
          description: 'Sends one transactional email through Mailgun\'s Messages API, either as raw Text/HTML content or by populating a stored Mailgun template, with automatic retry on temporary Mailgun errors such as rate limiting.',
          fields: [
            {
              name: 'Operation',
              internalKey: 'operation',
              type: 'select',
              required: true,
              description: 'The Mailgun action to perform (currently only Send Email is implemented)',
              helpText: operationHelpText,
              placeholder: 'send_email',
              example: 'send_email',
              defaultValue: 'send_email',
              options: ['send_email'],
            },
            {
              name: 'Domain',
              internalKey: 'domain',
              type: 'string',
              required: false,
              description: 'Mailgun sending domain saved on the selected Mailgun connection (credential-owned, not a normal typed field)',
              helpText: domainHelpText,
              placeholder: 'mg.yourdomain.com',
              example: 'mg.yourdomain.com',
            },
            {
              name: 'Api Key',
              internalKey: 'apiKey',
              type: 'password',
              required: false,
              description: 'Mailgun Private API Key saved on the selected Mailgun connection (credential-owned, not a normal typed field)',
              helpText: apiKeyHelpText,
              placeholder: 'key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
              example: 'key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            },
            {
              name: 'From',
              internalKey: 'from',
              type: 'email',
              required: true,
              description: 'Sender email address on your verified Mailgun domain',
              helpText: fromHelpText,
              placeholder: 'noreply@mg.yourdomain.com',
              example: 'noreply@mg.yourdomain.com',
            },
            {
              name: 'To',
              internalKey: 'to',
              type: 'string',
              required: true,
              description: 'Recipient email address(es), comma-separated (not a JSON array)',
              helpText: toHelpText,
              placeholder: 'recipient@example.com',
              example: 'recipient@example.com',
            },
            {
              name: 'Subject',
              internalKey: 'subject',
              type: 'string',
              required: false,
              description: 'Email subject line',
              helpText: subjectHelpText,
              placeholder: 'Hello from Mailgun!',
              example: 'Reset your password',
            },
            {
              name: 'Message (Plain Text)',
              internalKey: 'text',
              type: 'textarea',
              required: false,
              description: 'Plain text body of the email',
              helpText: textHelpText,
              placeholder: 'Your message here...',
              example: 'Your reset link is {{$json.resetUrl}}',
            },
            {
              name: 'Message (HTML)',
              internalKey: 'html',
              type: 'textarea',
              required: false,
              description: 'HTML body of the email',
              helpText: htmlHelpText,
              placeholder: '<p>Your HTML message here...</p>',
              example: '<p>Click <a href="{{$json.resetUrl}}">here</a>.</p>',
            },
            {
              name: 'CC',
              internalKey: 'cc',
              type: 'string',
              required: false,
              description: 'CC recipient email address(es), comma-separated',
              helpText: ccHelpText,
              placeholder: 'manager@example.com',
              example: 'manager@example.com',
            },
            {
              name: 'BCC',
              internalKey: 'bcc',
              type: 'string',
              required: false,
              description: 'BCC recipient email address(es), comma-separated',
              helpText: bccHelpText,
              placeholder: 'audit@example.com',
              example: 'audit@example.com',
            },
            {
              name: 'Reply-To',
              internalKey: 'replyTo',
              type: 'email',
              required: false,
              description: 'Reply-To email address for recipient replies',
              helpText: replyToHelpText,
              placeholder: 'support@mg.yourdomain.com',
              example: 'support@mg.yourdomain.com',
            },
            {
              name: 'Tags',
              internalKey: 'tags',
              type: 'string',
              required: false,
              description: 'Mailgun message tags, comma-separated (sent as o:tag)',
              helpText: tagsHelpText,
              placeholder: 'welcome,onboarding',
              example: 'welcome,onboarding',
            },
            {
              name: 'Template',
              internalKey: 'template',
              type: 'string',
              required: false,
              description: 'Optional Mailgun stored template name',
              helpText: templateHelpText,
              placeholder: 'welcome_email',
              example: 'welcome_email',
            },
            {
              name: 'Template Variables (JSON)',
              internalKey: 'templateVariables',
              type: 'json',
              required: false,
              description: 'JSON object of variables for the Mailgun template (sent as t:variables)',
              helpText: templateVariablesHelpText,
              placeholder: '{"name":"Ada","resetUrl":"https://example.com/reset"}',
              example: '{"name":"Ada","resetUrl":"https://example.com/reset"}',
            },
          ],
          outputExample: {
            success: true,
            messageId: '<20260718091500.1.ABCDEF1234567890@mg.yourdomain.com>',
            message: 'Queued. Thank you.',
            mailgun: { id: '<20260718091500.1.ABCDEF1234567890@mg.yourdomain.com>', message: 'Queued. Thank you.' },
          },
          outputDescription: 'On success: success is true, messageId is Mailgun\'s message ID (also duplicated inside mailgun.id) for tracking delivery in Mailgun\'s logs, message is Mailgun\'s own queue confirmation text (usually "Queued. Thank you."), and mailgun is the full raw JSON response Mailgun returned. Original upstream fields from before this node are preserved alongside these (Mailgun does not wipe $json the way slack_webhook does). On any failure — missing domain/apiKey/from/to, missing text/html/template, invalid Template Variables JSON, or Mailgun itself rejecting the send — the node returns _error (and _errorDetails with Mailgun\'s raw error body for HTTP-level failures) with no success field at all (not even success: false); check {{$json._error}} to detect failure, since {{$json.success}} being undefined and {{$json.success}} being false both mean "did not send."',
          usageExample: {
            scenario: 'Send a password-reset email through Mailgun right after a user requests one',
            inputValues: {
              from: 'noreply@mg.yourapp.com',
              to: '{{$json.email}}',
              subject: 'Reset your password',
              html: '<p>Click <a href="{{$json.resetUrl}}">here</a> to reset your password. This link expires in 1 hour.</p>',
            },
            expectedOutput: 'The email is queued by Mailgun. Use {{$json.messageId}} to look the send up in Mailgun\'s logs, and {{$json._error}} in a following node to detect and handle a failed send.',
          },
          externalDocsUrl: 'https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun/messages',
        },
      ],
    },
  ],
  commonErrors: [
    {
      error: 'Mailgun: domain is required / Mailgun: apiKey is required / Mailgun: from email is required',
      cause: 'No Mailgun connection is selected on this node (or its saved Domain/API Key/Default From are empty), and no From value was typed directly.',
      fix: 'Open Connections, add a Mailgun API Key connection with a valid Private API Key, Sending Domain, and Region, then select it on this node.',
    },
    {
      error: 'Mailgun: to email is required',
      cause: 'The To field resolved to an empty string after expressions were evaluated.',
      fix: 'Fill To with a fixed address or a valid {{$json.field}} expression, and confirm the upstream node actually produced that field.',
    },
    {
      error: 'Mailgun: text, html, or template is required',
      cause: 'Text, HTML, and Template were all left empty, so Mailgun would have nothing to send as message content.',
      fix: 'Fill at least one of Message (Plain Text), Message (HTML), or Template before running the node.',
    },
    {
      error: 'Mailgun: templateVariables must be a JSON object',
      cause: 'Template Variables resolved to something other than a JSON object — for example plain text, a JSON array, or malformed JSON.',
      fix: 'Enter a valid JSON object such as {"name": "Ada"}, keyed by the template\'s own variable names, not a list.',
    },
    {
      error: 'Mailgun send failed (<status>): <message> / Forbidden or unauthorized recipient',
      cause: 'Mailgun itself rejected the request — commonly an invalid or revoked API key, a From address outside the verified sending domain, or a sandbox domain sending to a recipient that was never authorized.',
      fix: 'Verify the API key and sending domain in the Mailgun connection, confirm From uses that exact domain, and for sandbox testing, add the recipient under Mailgun → Sending → Domains → Authorized Recipients.',
    },
    {
      error: 'Mailgun send failed: no response from API / Mailgun error',
      cause: 'A network, DNS, or Mailgun-availability issue prevented the request from completing, even after automatic retries on 429/500/502/503/504 responses.',
      fix: 'Retry later, and check Mailgun\'s status page if failures continue across multiple runs.',
    },
    {
      error: 'Next node cannot find the send result',
      cause: 'A downstream node is reading a field this node never produces, such as a nested response.id path instead of the flattened output.',
      fix: 'Use the real output fields: {{$json.success}}, {{$json.messageId}}, {{$json.message}}, {{$json.mailgun}}, and check {{$json._error}} for failures (this node never sets a plain success: false — check _error instead).',
    },
    {
      error: 'Permission denied after Mailgun',
      cause: 'The Mailgun connection only authorizes sending email through your Mailgun account — it does not grant any access to whatever service a later node in the workflow talks to.',
      fix: 'Connect the required account separately on each downstream service node and confirm that node\'s own permissions.',
    },
  ],
  relatedNodes: ['sendgrid', 'amazon_ses', 'email'],
};
