import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const teamsBotDocs = 'https://learn.microsoft.com/microsoftteams/platform/bots/how-to/create-a-bot-for-teams';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Microsoft Teams Bot connection ID. If blank, the active Microsoft Teams Bot connection is used.',
    helpText: 'What this field means: Connection points to the saved Microsoft Teams Bot credential (Microsoft App ID, App Password, and optional Validation Secret) CtrlChecks uses to verify incoming Bot Framework requests and reply through the bot. Why it matters: Without a resolvable connection, CtrlChecks has no App ID to check the Bot Framework JWT audience against and no App Password for replies. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Microsoft Teams Bot connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save the Microsoft App ID (and optionally App Password/Validation Secret). How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw App ID or secret. Real workplace example: An IT team saves one Microsoft Teams Bot connection for the company support bot, and every Teams Trigger node in the workspace reuses it. If it is empty or wrong: Empty falls back to the active Microsoft Teams Bot connection; a wrong or missing connection can cause No active Microsoft Teams Bot connection found or a failed JWT validation. Common mistake: Pasting the Azure app registration client secret into a normal workflow field instead of saving it under Connections.',
    placeholder: 'Uses your active Microsoft Teams Bot connection',
    example: 'microsoft_teams_bot_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated Teams activity types that can start this workflow.',
    helpText: 'What this field means: Event Types decides which normalized Bot Framework activity kinds this trigger accepts. Why it matters: Channel/personal messages, conversation updates (members added/removed), message reactions, and invoke actions (adaptive card buttons, task modules) usually need very different workflows. When to fill it: Keep the default while testing; narrow it before production so unrelated bot activity does not start the workflow. What to enter: Comma-separated values such as message, conversation_update, message_reaction, invoke. Aliases such as channel_message, personal_message, dm, member_added, member_removed, reaction, task_module, and adaptive_card_action are also accepted. Where the value comes from: Decide which Bot Framework activity kinds your workflow should react to. How to use it later: Route with {{$json.eventType}}, which is always one of message, conversation_update, message_reaction, invoke, installation_update, or unknown. Accepted format: Comma-separated text, matched case-insensitively. Real workplace example: message for an AI support bot; invoke for a workflow that only reacts to adaptive card button clicks. If it is empty or wrong: Empty defaults to message, conversation_update, invoke. A value that never matches an incoming activity type silently ignores that event with Ignored Microsoft Teams event type. Common mistake: Expecting installation_update to be included by default — it must be listed explicitly since the default set does not include it.',
    placeholder: 'message, conversation_update, invoke',
    defaultValue: 'message, conversation_update, invoke',
    example: 'message',
  },
  {
    name: 'Allowed Team IDs',
    internalKey: 'teamIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated Teams team IDs allowed to trigger this workflow.',
    helpText: 'What this field means: Allowed Team IDs restricts this trigger to activities from specific Microsoft Teams teams. Why it matters: A single bot can be installed across many teams; this keeps a team-specific workflow from reacting to every team\'s activity. When to fill it: Fill it when this workflow should only react to one or a few specific teams. Leave it blank to accept activity from any team (and personal chats, which have no team ID at all). What to enter: Comma-separated Teams team IDs such as 19:team-id@thread.tacv2. Where the value comes from: Read {{$json.teamId}} from a previous test activity, or check the Teams admin center/Graph API for the team\'s ID. How to use it later: The trigger output includes {{$json.teamId}} for logging or routing. Accepted format: Comma-separated text. Real workplace example: A company scopes its finance-approvals bot workflow to only the Finance team\'s ID so other teams\' bot installs cannot trigger it. If it is empty or wrong: Empty allows every team (and personal chats); a team ID that never matches an incoming activity silently ignores it with Ignored Teams event from a team that is not allowed. Common mistake: Using the team\'s display name instead of its 19:...@thread.tacv2 style ID.',
    placeholder: '19:team-id@thread.tacv2',
    example: '19:team-id@thread.tacv2',
  },
  {
    name: 'Allowed Channel IDs',
    internalKey: 'channelIds',
    type: 'string',
    required: false,
    description: 'Optional Teams channel allowlist.',
    helpText: 'What this field means: Allowed Channel IDs restricts this trigger to activities from specific Teams channels. Why it matters: A team can have many channels; this keeps a channel-specific workflow (such as one watching only a #incidents channel) from reacting to every channel in the team. When to fill it: Fill it when this workflow should only react to one or a few specific channels. Leave it blank for personal chats or broad testing across every channel. What to enter: Comma-separated Teams channel IDs such as 19:channel-id@thread.tacv2. Where the value comes from: Read {{$json.channelId}} from a previous test activity, or check the channel\'s details/link in Teams. How to use it later: The trigger output includes {{$json.channelId}} for logging or routing. Accepted format: Comma-separated text. Real workplace example: An IT operations workflow scopes to the #incidents channel ID only, so casual chatter in other channels never starts an incident workflow. If it is empty or wrong: Empty allows every channel and personal chat; a channel ID that never matches silently ignores the activity with Ignored Teams event from a channel that is not allowed. Common mistake: Confusing this with the team ID — a channel ID is specific to one channel inside a team, not the whole team.',
    placeholder: '19:channel-id@thread.tacv2',
    example: '19:channel-id@thread.tacv2',
  },
  {
    name: 'Allowed User IDs',
    internalKey: 'allowedUserIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated Teams/AAD user IDs allowed to trigger this workflow.',
    helpText: 'What this field means: Allowed User IDs limits the trigger to specific Teams users, identified by their Azure AD object ID or Bot Framework user ID. Why it matters: It can keep a testing or sensitive workflow from reacting to messages sent by anyone other than approved people. When to fill it: Use it for internal testing, approved reviewers, or a controlled rollout. Leave it blank for a normal bot that should respond to any user. What to enter: Comma-separated user IDs such as 00000000-0000-0000-0000-000000000000. Where the value comes from: Read {{$json.userId}} from a previous test activity sent by that person, or look up their Azure AD object ID. How to use it later: The accepted activity output still includes {{$json.userId}} and {{$json.username}} for replies or audits. Accepted format: Comma-separated text. Real workplace example: Before launching an HR bot company-wide, the team allows only two HR staff user IDs so they can test without responding to every employee. If it is empty or wrong: Empty allows every matching user; a user ID that never matches silently ignores that person\'s activity with Ignored Teams event from a user that is not allowed. Common mistake: Using the person\'s display name or email instead of their AAD object ID/Bot Framework user ID.',
    placeholder: '00000000-0000-0000-0000-000000000000',
    example: '00000000-0000-0000-0000-000000000000',
  },
  {
    name: 'Tenant ID',
    internalKey: 'tenantId',
    type: 'string',
    required: false,
    description: 'Optional Microsoft tenant ID filter.',
    helpText: 'What this field means: Tenant ID restricts this trigger to activities coming from one specific Microsoft 365 tenant (organization). Why it matters: A multi-tenant bot can receive activities from many different customer organizations; this keeps a customer-specific workflow scoped to just their tenant. When to fill it: Fill it for a bot that serves multiple organizations and this workflow should only react to one of them. Leave it blank for a single-tenant bot or when any tenant should be accepted. What to enter: The Microsoft 365 tenant GUID, not the organization\'s display name or domain. Where the value comes from: Read {{$json.tenantId}} from a previous test activity from that organization, or find it in the Microsoft 365 admin center/Azure AD. How to use it later: The trigger output includes {{$json.tenantId}} for logging or routing. Accepted format: Tenant GUID text. Real workplace example: An ISV\'s multi-tenant support bot scopes one workflow to a single enterprise customer\'s tenant ID so their support process stays isolated from other customers. If it is empty or wrong: Empty accepts activity from any tenant; a tenant ID that never matches silently ignores the activity with Ignored Teams event for a different tenant. Common mistake: Entering the organization\'s domain name (such as contoso.onmicrosoft.com) instead of the tenant GUID.',
    placeholder: '00000000-0000-0000-0000-000000000000',
    example: '00000000-0000-0000-0000-000000000000',
  },
  {
    name: 'Microsoft App ID',
    internalKey: 'appId',
    type: 'string',
    required: false,
    description: 'Optional Microsoft App ID override. Prefer storing it on the Teams Bot connection.',
    helpText: 'What this field means: Microsoft App ID is the Azure Bot registration\'s application ID, used to check that an incoming Bot Framework JWT was issued for this specific bot. Why it matters: Bot Framework JWT validation checks the token\'s audience claim against this exact App ID; a missing or wrong value can make every real Teams request fail validation. When to fill it: Leave it blank in almost every setup — CtrlChecks reads the App ID from your saved Microsoft Teams Bot connection automatically. Fill it only to override the connection\'s value for a specific node, such as testing against a second bot registration. What to enter: The Azure Bot / Teams app\'s Application (client) ID as a GUID. Where the value comes from: Azure Bot Channels Registration -> Configuration -> Microsoft App ID, or the Teams app manifest\'s botId. How to use it later: This is a setup/validation value only; it is not emitted as {{$json.appId}} to downstream nodes. Accepted format: GUID text. Real workplace example: A team testing a second, staging bot registration sets Microsoft App ID here temporarily to validate against the staging app instead of the production connection\'s app. If it is empty or wrong: Empty falls back to the connection\'s App ID; a wrong value causes every real Bot Framework request to fail JWT audience validation with Invalid Microsoft Teams/Bot Framework request. Common mistake: Pasting the App Password/client secret here instead of the App ID.',
    placeholder: '00000000-0000-0000-0000-000000000000',
    example: '00000000-0000-0000-0000-000000000000',
  },
  {
    name: 'Validation Secret',
    internalKey: 'validationSecret',
    type: 'string',
    required: false,
    description: 'Optional shared secret for simulations. Production Bot Framework requests should use JWT validation.',
    helpText: 'What this field means: Validation Secret is an optional shared-secret shortcut that lets a request skip full Bot Framework JWT validation if it presents the exact matching secret in an X-Ms-Teams-Secret, X-Teams-Secret, X-CtrlChecks-Teams-Secret header, or a secret query parameter. Why it matters: Real Microsoft Teams traffic always uses signed Bot Framework JWTs; this shortcut exists mainly for manual testing or simulated payloads where generating a real JWT is impractical. When to fill it: Leave it blank for production bots — rely on JWT validation instead. Fill it only for controlled local testing or a simulation harness. What to enter: A long random string from a password manager, not your Azure app client secret. Where the value comes from: Generate it yourself for testing purposes; it does not come from Microsoft. How to use it later: This is setup-only and is never emitted as {{$json.validationSecret}} to downstream nodes. Accepted format: Plain secret text; the visual field uses a standard text control even though the value should be treated as secret material. Real workplace example: A developer testing the webhook locally with curl sends X-Ms-Teams-Secret matching this value instead of building a real signed Bot Framework token. If it is empty or wrong: Empty means only real Bot Framework JWTs are accepted; a value that does not match an incoming request\'s header simply falls through to JWT validation instead of granting access. Common mistake: Leaving a testing secret configured in a production workflow, which creates a second, weaker way to authenticate besides JWT validation.',
    placeholder: 'Optional simulation secret',
    example: 'a1b2c3d4e5f6',
    notes: 'The visual config field uses a standard text control because password is not a supported node panel field type, but the value should still be treated as secret material.',
  },
  {
    name: 'Validate Bot Framework Auth',
    internalKey: 'validateJwt',
    type: 'boolean',
    required: false,
    description: 'Validates Bot Framework bearer JWTs or a configured shared secret.',
    helpText: 'What this field means: Validate Bot Framework Auth checks that an incoming request is either a genuine Bot Framework JWT (signed by Microsoft and issued for your App ID) or presents the matching Validation Secret. Why it matters: A public webhook URL should reject requests that did not come from real Microsoft Teams/Bot Framework traffic. When to fill it: Keep it enabled for production. Disable only for a controlled local test where you cannot generate a real Bot Framework token and are not using Validation Secret either. What to enter: true/enabled for real workflows; false/disabled only for temporary debugging. Where the value comes from: This is a security choice made by the workflow owner or admin. How to use it later: This setting protects whether a workflow starts; it is not output as {{$json.validateJwt}}. Accepted format: Boolean checkbox. Real workplace example: A live Teams support bot keeps validation enabled so only signed Bot Framework deliveries (or requests with the matching Validation Secret) can start a workflow. If it is empty or wrong: Default true requires either a valid JWT or Validation Secret; if neither is satisfiable, requests fail with Invalid Microsoft Teams/Bot Framework request. Common mistake: Turning this off permanently instead of correctly saving the Microsoft App ID on the connection.',
    defaultValue: 'true',
    example: 'true',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive activity',
  value: 'receive',
  description: 'Starts the workflow when an accepted Microsoft Teams Bot Framework activity (channel message, personal message, conversation update, message reaction, or invoke action) arrives, after validating the Bot Framework JWT or configured shared secret.',
  fields,
  outputExample: {
    eventId: 'activity-1',
    eventType: 'message',
    source: 'microsoft_teams',
    userId: 'aad-object-id-1',
    username: 'Alex Morgan',
    text: 'Can you help?',
    timestamp: '2026-07-19T10:20:00.000Z',
    tenantId: 'tenant-1',
    teamId: 'team-1',
    channelId: 'channel-1',
    chatId: 'channel-1',
    conversationId: 'conversation-1',
    serviceUrl: 'https://smba.trafficmanager.net/amer/',
    activityId: 'activity-1',
    replyToId: 'activity-1',
    locale: 'en-US',
    channelData: {},
    raw: {},
    trigger: 'microsoft_teams',
    workflow_id: 'workflow_123',
    node_id: 'teams-trigger-1',
    sessionId: 'teams_workflow_123_tenant-1_conversation-1',
    _microsoftTeams: true,
  },
  outputDescription: 'eventId: the Bot Framework activity ID, or a generated fallback. eventType: message, conversation_update, message_reaction, invoke, installation_update, or unknown. source: microsoft_teams. userId: the sender\'s Azure AD object ID (preferred) or Bot Framework user ID. username: sender display name when Teams includes it. text: message text, or the value.text of an invoke/adaptive-card payload. timestamp: ISO event time. tenantId/teamId/channelId: Microsoft 365 tenant, Teams team, and channel identifiers, null for personal chats. chatId: channelId when present, otherwise conversationId — useful as a single reply-target key. conversationId: the Bot Framework conversation ID needed for replies. serviceUrl: the regional Bot Framework endpoint your bot must call back through — always capture and reuse this per conversation, it can vary by region/tenant. activityId/replyToId: the activity to reply to. locale: sender\'s locale, such as en-US. channelData: raw Teams-specific metadata (team/channel/tenant objects). raw: the original Bot Framework activity. trigger/workflow_id/node_id/sessionId/_microsoftTeams: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Reply to a Microsoft Teams bot message with an AI Agent',
    inputValues: {
      eventTypes: 'message',
      teamIds: '',
      channelIds: '',
      allowedUserIds: '',
      tenantId: '',
      appId: '',
      validationSecret: '',
      validateJwt: 'true',
    },
    expectedOutput: 'Use {{$json.text}} as the user question, and {{$json.serviceUrl}}, {{$json.conversationId}}, {{$json.replyToId}} in a Microsoft Teams action node to reply to the same conversation.',
  },
  externalDocsUrl: 'https://learn.microsoft.com/microsoftteams/platform/bots/what-are-bots',
};

export const microsoftTeamsTriggerDoc: NodeDoc = {
  slug: 'microsoft_teams_trigger',
  displayName: 'Microsoft Teams Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Microsoft-Teams.svg',
  description: 'Start workflows from Microsoft Teams Bot Framework activities such as channel messages, personal messages, conversation updates, and invoke actions.',
  credentialType: 'Microsoft Teams Bot',
  credentialSetupSteps: [
    'Create or open an Azure Bot / Teams app in Azure Bot Channels Registration or the Microsoft Developer Portal.',
    'Copy the Microsoft App ID (Configuration -> Microsoft App ID) and save it on the Microsoft Teams Bot connection in CtrlChecks -> Connections.',
    'Create a client secret/App Password if workflows should reply through Bot Framework (required for Teams action replies), then save it on the connection too.',
    'Optionally save a Webhook Validation Secret on the connection or node if you need a simpler shared-secret check for manual testing; production traffic is validated with real Bot Framework JWTs regardless.',
    'Set the generated CtrlChecks webhook URL as the bot\'s messaging endpoint in the Azure Bot registration.',
    'Install the Teams app/bot into the target team, channel, group chat, or personal scope so it can actually receive activities.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Microsoft Teams Bot connection only authorizes validating and replying to Bot Framework activity, not the Slack, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: teamsBotDocs,
  resources: [
    {
      name: 'Webhook',
      description: 'Receives Microsoft Teams Bot Framework activities and emits a normalized event payload.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Invalid Microsoft Teams/Bot Framework request.',
      cause: 'The Bot Framework bearer JWT failed signature/audience/expiry checks, and no matching Validation Secret was presented either.',
      fix: 'Save the correct Microsoft App ID on the Teams Bot connection and confirm the bot registration\'s messaging endpoint matches the CtrlChecks webhook URL. Use Validation Secret only for controlled manual tests.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'A valid Bot Framework activity arrived, but the workflow has not been activated.',
      fix: 'Activate the workflow in CtrlChecks, then resend or wait for the next real Teams activity.',
    },
    {
      error: 'No matching CtrlChecks workflow trigger is active for this Microsoft Teams event.',
      cause: 'The activity was valid, but Event Types, Allowed Team IDs, Allowed Channel IDs, Allowed User IDs, or Tenant ID filtered it out.',
      fix: 'Broaden Event Types or clear the ID filters temporarily, send a fresh Teams test message, then narrow the filters again after confirming the output.',
    },
    {
      error: 'No active Microsoft Teams Bot connection found. Create one in Connections first.',
      cause: 'The workflow owner has not connected a Microsoft Teams Bot, or the saved connection has no usable App ID.',
      fix: 'Save the Microsoft App ID (and App Password if replies are needed) on a Microsoft Teams Bot connection, then re-activate the workflow.',
    },
    {
      error: 'Selected connection is not a Microsoft Teams Bot connection.',
      cause: 'The saved connection ID points to another provider or an inactive credential.',
      fix: 'Select a Microsoft Teams Bot connection or leave Connection blank so CtrlChecks can use the active one.',
    },
    {
      error: 'Teams bot reply failed',
      cause: 'The bot App Password/client secret is missing on the connection, or the bot has not been installed in the target Teams scope.',
      fix: 'Save the App Password on the Teams Bot connection and confirm the bot is installed in the team, channel, or chat you are replying to.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Microsoft Teams webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Bot Framework must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'Microsoft Teams Trigger node not found in this workflow.',
      cause: 'The webhook URL points to a node ID that is missing, renamed incorrectly, or no longer has type microsoft_teams_trigger.',
      fix: 'Save the workflow with the Microsoft Teams Trigger node still present, then copy the fresh webhook URL into the bot\'s messaging endpoint.',
    },
    {
      error: 'Next node cannot find Microsoft Teams trigger fields',
      cause: 'A downstream node is mapped to a field only present for another activity type, such as expecting text on a conversation_update event.',
      fix: 'Use {{$json.eventType}} to branch by activity type before mapping type-specific fields. Always use {{$json.serviceUrl}} and {{$json.conversationId}} together when replying — serviceUrl can vary per conversation/region.',
    },
    {
      error: 'Permission denied after Microsoft Teams Trigger',
      cause: 'The trigger fired correctly, but the downstream Microsoft Teams action, Slack, email, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Teams Bot connection has an App Password so it can post replies.',
    },
  ],
  relatedNodes: ['microsoft_teams', 'ai_agent'],
};
