import type { FieldDoc, NodeDoc, OperationDoc } from '../types';
import { richFieldHelp } from './_sharedFieldHelp';

const help = {
  apiKey: richFieldHelp({
    what: 'A legacy Notion token fallback for this node.',
    why: 'The current runtime primarily resolves Notion OAuth from Connections, but backend inventory still knows this legacy key.',
    when: 'Leave blank unless a legacy workflow explicitly asks for a token field.',
    enter: 'Prefer a saved Notion OAuth connection. If a legacy field is used, enter an internal integration token only where the product explicitly permits it.',
    source: 'Connections credential vault is preferred; internal integration tokens come from notion.so/my-integrations.',
    later: 'Do not map this secret as {{$json.apiKey}}. Let later Notion nodes use the saved service node account connection.',
    format: 'Secret token string, usually starting with secret_ for internal integrations.',
    example: 'Save Notion in Connections and leave apiKey empty.',
    empty: 'Runtime uses the saved Notion OAuth connection; if no connection is found it returns _error with OAuth connection required.',
    mistake: 'Pasting Notion secrets into ordinary workflow fields, examples, or screenshots.',
  }),
  accessToken: richFieldHelp({
    what: 'A legacy OAuth access token fallback name known by the backend inventory.',
    why: 'Notion API calls need OAuth access, but this executor resolves the token from the workflow owner connection.',
    when: 'Normally never fill this in the visual workflow; use Connections instead.',
    enter: 'Use the saved Notion connection rather than a raw token.',
    source: 'CtrlChecks Connections stores OAuth tokens in the credential vault after the user connects Notion.',
    later: 'Downstream Notion steps should also use Connections, not {{$json.accessToken}}.',
    format: 'OAuth access token when present, treated as a secret.',
    example: 'Reconnect Notion in Connections if access expires.',
    empty: 'Blank is correct when a Notion connection exists; without a connection runtime returns _error.',
    mistake: 'Treating an OAuth token as normal input data.',
  }),
  credentialId: richFieldHelp({
    what: 'A stored credential reference used by backend inventory and older generated workflow configs.',
    why: 'It can identify a saved credential record, but the current Notion executor resolves the workflow owner connection directly.',
    when: 'Leave blank in normal visual workflows.',
    enter: 'Use the Notion connection picker or Connections area rather than typing credential ids manually.',
    source: 'Credential IDs are system metadata from CtrlChecks, not values copied from Notion.',
    later: 'Use returned Notion data like {{$json.data.id}}, not credentialId, in downstream nodes.',
    format: 'Internal credential reference such as cred_123 when used by older configs.',
    example: 'Select the Notion account connection instead of typing a credential id.',
    empty: 'Blank is fine for the current OAuth resolver.',
    mistake: 'Confusing credentialId with a Notion page ID or database ID.',
  }),
  resource: richFieldHelp({
    what: 'The Notion object type this node works with.',
    why: 'The selected resource determines which Notion API group is called and which operations make sense.',
    when: 'Required for every Notion node.',
    enter: 'Choose page, database, block, user, comment, or search.',
    source: 'Select one option from the Resource dropdown in the node panel.',
    later: 'The node returns Notion data in {{$json.data}} and keeps the selected resource in the workflow config.',
    format: 'One of page, database, block, user, comment, or search.',
    example: 'Use database with query to fetch task rows, or page with create to add a child page.',
    empty: 'Runtime defaults to page, which may make the selected operation invalid for your intended object.',
    mistake: 'Choosing search but leaving Operation as get; search resource only supports operation search.',
  }),
  operation: richFieldHelp({
    what: 'The Notion action to run for the selected resource.',
    why: 'Notion operations are resource-specific; the same operation value can mean different required fields on page, database, block, user, comment, or search.',
    when: 'Required for every Notion node.',
    enter: 'Choose get, list, create, update, archive, restore, query, appendChildren, listChildren, delete, getMe, or search where it matches the selected resource.',
    source: 'Select it from the Operation dropdown. The documentation below explains valid resource-operation pairs.',
    later: 'Successful output is available under {{$json.data}} with {{$json.success}} true.',
    format: 'One operation value from the dropdown: get, list, create, update, archive, restore, query, appendChildren, listChildren, delete, getMe, or search.',
    example: 'Use resource database and operation query to fetch rows, then map {{$json.data.results}} downstream.',
    empty: 'Runtime defaults to get and returns _error if that operation is unknown for the selected resource.',
    mistake: 'Assuming every dropdown operation works with every resource. Notion rejects mismatched pairs.',
  }),
  pageId: richFieldHelp({
    what: 'The Notion page ID to read, update, archive, restore, or comment on.',
    why: 'Page operations and comment listing/creation need the exact page target.',
    when: 'Required for page get, update, archive, restore; required for comment list/create when Block ID or Parent Discussion ID is not used.',
    enter: 'A Notion page UUID copied from the page URL or mapped from a previous Notion result.',
    source: 'Open a Notion page, copy its link, and extract the 32-character or UUID page id; or map {{$json.data.id}} from a prior Notion step.',
    later: 'Use returned page IDs as {{$json.data.id}} in later update or archive steps.',
    format: 'Notion page UUID, with or without hyphens.',
    example: 'Archive the page created earlier with pageId {{$json.data.id}}.',
    empty: 'Runtime returns _error for operations that require pageId.',
    mistake: 'Using a public Notion page URL instead of the actual page ID.',
  }),
  databaseId: richFieldHelp({
    what: 'The Notion database ID.',
    why: 'Database get/query and page creation inside a database need this ID.',
    when: 'Required for database get/query/update; required for page create when creating a database row instead of a child page.',
    enter: 'A database UUID from the Notion database URL or a prior Notion output.',
    source: 'Open the database as a page, copy the link, and extract the database id; or map {{$json.databaseId}}.',
    later: 'Use the same database ID in query steps that feed reports or downstream service nodes.',
    format: 'Notion database UUID, with or without hyphens.',
    example: 'Query the task database with databaseId {{$json.taskDatabaseId}}.',
    empty: 'Runtime returns _error for database operations that require databaseId, or page create requires parentPageId instead.',
    mistake: 'Forgetting to share the database with the connected Notion integration/account.',
  }),
  blockId: richFieldHelp({
    what: 'The Notion block ID.',
    why: 'Block operations and comment listing by block need the exact block target.',
    when: 'Required for block get, listChildren, appendChildren, update, delete, and for comment list when Page ID is not used.',
    enter: 'A block UUID copied from Notion block link or returned by a previous Notion block operation.',
    source: 'Copy link to block in Notion or map a block id from {{$json.data.results[0].id}}.',
    later: 'Use block IDs to append child blocks or retrieve nested content in later Notion steps.',
    format: 'Notion block UUID, with or without hyphens.',
    example: 'Append follow-up notes under blockId {{$json.notesBlockId}}.',
    empty: 'Runtime returns _error for block operations that require blockId.',
    mistake: 'Using the page ID when the selected resource is block.',
  }),
  userId: richFieldHelp({
    what: 'The Notion user ID.',
    why: 'User get needs a user id so Notion knows which person or bot to retrieve.',
    when: 'Required for resource user with operation get.',
    enter: 'A Notion user id returned by user list or another Notion API response.',
    source: 'Run resource user with operation list and map {{$json.data.results[0].id}}.',
    later: 'Use returned user details from {{$json.data}} for routing, assignment, or audit logging.',
    format: 'Notion user UUID.',
    example: 'Fetch the Notion user mapped from {{$json.ownerUserId}}.',
    empty: 'Runtime returns _error saying userId is required for get operation.',
    mistake: 'Entering an email address when the Notion API expects a user id.',
  }),
  parentPageId: richFieldHelp({
    what: 'The Notion parent page where a new child page or database should be created.',
    why: 'Notion must know where to place a child page or a new database.',
    when: 'Required for page create when Database ID is blank, and required for database create.',
    enter: 'A Notion page UUID that the connected account can edit.',
    source: 'Copy the parent page link from Notion or map {{$json.parentPageId}} from an upstream lookup.',
    later: 'Created child pages/databases return their new id in {{$json.data.id}}.',
    format: 'Notion page UUID.',
    example: 'Create daily notes under parentPageId {{$json.dailyNotesParentId}}.',
    empty: 'Runtime returns _error when page create has neither databaseId nor parentPageId, or database create lacks parentPageId.',
    mistake: 'Providing both databaseId and parentPageId for page create; runtime rejects that combination.',
  }),
  title: richFieldHelp({
    what: 'The plain text page or database title.',
    why: 'Database create requires a title, and database update can change it.',
    when: 'Required for database create; optional for database update and page-related plain text workflows.',
    enter: 'Plain text title or a mapped value from previous workflow data.',
    source: 'Type a fixed title or map {{$json.title}}, {{$json.projectName}}, or {{$json.reportName}}.',
    later: 'Created or updated Notion objects return the title data in {{$json.data}}.',
    format: 'Plain text string; runtime converts it to Notion rich text where needed.',
    example: 'Weekly Support Report - {{$json.weekStart}}.',
    empty: 'Database create returns _error saying title is required; database update needs at least title or schema.',
    mistake: 'Sending a Notion rich_text array into Title when plain text is enough.',
  }),
  content: richFieldHelp({
    what: 'Plain text body content used to create paragraph blocks.',
    why: 'When Children Blocks is blank, runtime can convert this text into a Notion paragraph block for page create or appendChildren.',
    when: 'Use for simple page child creation or block append operations when you do not need custom block JSON.',
    enter: 'Readable plain text, optionally including mapped workflow values.',
    source: 'Type a note template or map {{$json.summary}}, {{$json.body}}, or {{$json.aiResponse}}.',
    later: 'The created/updated Notion response is returned under {{$json.data}}.',
    format: 'Plain text string.',
    example: 'Customer summary: {{$json.summary}}.',
    empty: 'If Children Blocks is also empty, page child creation and appendChildren return _error requiring children.',
    mistake: 'Expecting Markdown to become rich Notion formatting; runtime sends a simple paragraph block.',
  }),
  children: richFieldHelp({
    what: 'Raw Notion block JSON for child blocks or block updates.',
    why: 'It lets advanced workflows create or append structured Notion content beyond one plain paragraph.',
    when: 'Required for page create as child or appendChildren when Content is not used; required as an object for block update.',
    enter: 'A Notion blocks array for page create/appendChildren, or a block content object for block update.',
    source: 'Build JSON from Notion API examples or map a prepared value such as {{$json.notionBlocks}}.',
    later: 'The response is in {{$json.data}}; later steps can inspect created block IDs from the response.',
    format: 'Valid JSON. Array for child blocks; object for block update.',
    example: '[{"object":"block","type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"Hello"}}]}}]',
    empty: 'Runtime falls back to Content when possible, otherwise returns _error requiring children.',
    mistake: 'Using an array for block update; runtime expects a block content object for update.',
  }),
  properties: richFieldHelp({
    what: 'Notion database property values for a page row or page update.',
    why: 'Creating a page inside a database and updating a page require database properties in Notion API format.',
    when: 'Required for page create with Database ID and for page update.',
    enter: 'JSON keyed by exact Notion property names.',
    source: 'Copy property names from the Notion database, then map values from prior steps such as {{$json.status}}.',
    later: 'Returned page data under {{$json.data.properties}} can be used by later conditions or messages.',
    format: 'Valid Notion properties JSON.',
    example: '{"Name":{"title":[{"text":{"content":"{{$json.taskName}}"}}]},"Status":{"select":{"name":"Backlog"}}}',
    empty: 'Runtime returns _error for page create in database or page update.',
    mistake: 'Using simplified key/value JSON when this runtime path expects Notion API property objects.',
  }),
  query: richFieldHelp({
    what: 'Raw Notion database query body.',
    why: 'It lets database query include advanced filters, sorts, and start_cursor values supported by Notion.',
    when: 'Optional for database query; leave blank to query without extra body filters.',
    enter: 'A JSON object accepted by Notion databases.query.',
    source: 'Build it from Notion API filter/sort examples or map {{$json.query}}.',
    later: 'Query results are returned in {{$json.data.results}} or a collected results list when Return All is on.',
    format: 'Valid JSON object.',
    example: '{"filter":{"property":"Status","select":{"equals":"Done"}},"sorts":[{"property":"Created","direction":"descending"}]}',
    empty: 'Runtime sends an empty query body and returns the default page of database results.',
    mistake: 'Putting search filters here when the selected resource is search; search uses Filter and Sort fields.',
  }),
  schema: richFieldHelp({
    what: 'Notion database property schema.',
    why: 'Database create and update use it to define or change database properties.',
    when: 'Required for database create. Optional for database update when Title is provided.',
    enter: 'JSON object in Notion database properties schema format.',
    source: 'Build from Notion API examples or reuse a prepared schema from {{$json.schema}}.',
    later: 'Created/updated database metadata is returned under {{$json.data}}.',
    format: 'Valid Notion database property schema JSON.',
    example: '{"Name":{"title":{}},"Status":{"select":{"options":[{"name":"Backlog"},{"name":"Done"}]}}}',
    empty: 'Database create returns _error saying schema is required; database update needs title or schema.',
    mistake: 'Using row property values instead of database schema definitions.',
  }),
  richText: richFieldHelp({
    what: 'Notion rich_text array for creating a comment.',
    why: 'Comment create sends rich_text to Notion so the comment has text content.',
    when: 'Required for comment create unless the legacy comment field supplies plain text.',
    enter: 'A Notion rich_text JSON array.',
    source: 'Build from Notion API examples or map {{$json.richText}}.',
    later: 'The created comment response is returned in {{$json.data}}.',
    format: 'Valid JSON array of Notion rich_text objects.',
    example: '[{"type":"text","text":{"content":"Approved by {{$json.reviewer}}"}}]',
    empty: 'Runtime returns _error saying richText array is required for create comment.',
    mistake: 'Typing plain text directly into Rich Text instead of JSON; use a rich_text array format.',
  }),
  comment: richFieldHelp({
    what: 'A legacy plain text comment fallback read by runtime when Rich Text is blank.',
    why: 'Runtime can convert this plain text to a simple rich_text array for comment create.',
    when: 'Use only if this field is exposed by imported configs or AI-generated workflow data.',
    enter: 'Plain text comment content.',
    source: 'Map {{$json.comment}} or {{$json.aiResponse}} from a previous step.',
    later: 'The created comment response appears under {{$json.data}}.',
    format: 'Plain text string.',
    example: 'Thanks for the update, {{$json.name}}.',
    empty: 'If Rich Text is also empty, comment create fails.',
    mistake: 'Expecting this field in the visual panel; the main visible field is Rich Text JSON.',
  }),
  parentDiscussionId: richFieldHelp({
    what: 'The Notion discussion ID to attach a new comment to.',
    why: 'Comment create can target either a page or a parent discussion.',
    when: 'Required for comment create only when Page ID is blank.',
    enter: 'A Notion parent discussion id returned by Notion comment/thread data.',
    source: 'Map {{$json.parentDiscussionId}} from an upstream Notion step or integration payload.',
    later: 'The created comment response is returned in {{$json.data}}.',
    format: 'Notion discussion id string.',
    example: 'Reply to a discussion using parentDiscussionId {{$json.discussionId}}.',
    empty: 'Comment create requires either pageId or parentDiscussionId.',
    mistake: 'Using a comment ID; this field is for the parent discussion.',
  }),
  searchQuery: richFieldHelp({
    what: 'Search text sent to Notion search.',
    why: 'It narrows search results to pages/databases that match your terms.',
    when: 'Optional for resource search with operation search.',
    enter: 'Plain search text or a mapped query string.',
    source: 'Type a term or map {{$json.searchQuery}}, {{$json.customerName}}, or {{$json.projectName}}.',
    later: 'Search results are returned under {{$json.data.results}} or collected results when Return All is on.',
    format: 'Plain text string.',
    example: 'Find onboarding docs for {{$json.customerName}}.',
    empty: 'Notion search runs without a text query and may return broad results allowed by filters.',
    mistake: 'Putting database query JSON here; use Query Body for database query.',
  }),
  filter: richFieldHelp({
    what: 'JSON filter for Notion database list/search behavior.',
    why: 'It can limit search to pages or databases, or provide filters for database-related calls where supported.',
    when: 'Optional for database list/search resource operations.',
    enter: 'A Notion API filter object.',
    source: 'Build from Notion API examples or map {{$json.filter}}.',
    later: 'Filtered results are returned under {{$json.data.results}}.',
    format: 'Valid JSON object.',
    example: '{"property":"object","value":"database"}',
    empty: 'Database list defaults to filtering object database; search runs without an extra filter.',
    mistake: 'Using a Notion database query filter in the wrong resource context.',
  }),
  sort: richFieldHelp({
    what: 'JSON sort object for Notion search.',
    why: 'The runtime reads sort, not sorts, when resource is search.',
    when: 'Optional for resource search with operation search.',
    enter: 'A Notion search sort object such as sorting by last_edited_time.',
    source: 'Build from Notion search API examples or map {{$json.sort}}.',
    later: 'Sorted search results are returned under {{$json.data.results}}.',
    format: 'Valid JSON object, not an array.',
    example: '{"direction":"descending","timestamp":"last_edited_time"}',
    empty: 'Notion returns default search ordering.',
    mistake: 'Using the old UI field name sorts. Runtime reads sort.',
  }),
  pageSize: richFieldHelp({
    what: 'Maximum number of items requested per Notion API page.',
    why: 'It controls page size for list, query, children, user list, and search operations.',
    when: 'Optional for list/query/search style operations.',
    enter: 'A number between 1 and 100.',
    source: 'Type a fixed number or map {{$json.pageSize}} from workflow settings.',
    later: 'When Return All is off, this affects how many items appear in {{$json.data.results}}.',
    format: 'Integer 1-100. Runtime clamps values to that range.',
    example: 'Use 25 for a daily digest preview.',
    empty: 'Runtime defaults to 100.',
    mistake: 'Expecting Page Size to cap Return All totals; Return All collects every page unless a max is passed internally.',
  }),
  returnAll: richFieldHelp({
    what: 'Whether runtime should automatically collect all paginated Notion results.',
    why: 'Many Notion list/search endpoints return one page at a time; Return All follows pagination for supported operations.',
    when: 'Turn on for complete exports or syncs; leave off for quick lookups and previews.',
    enter: 'true/on to collect all pages, false/off to fetch one page.',
    source: 'Toggle it in the node panel or map a boolean such as {{$json.returnAll}}.',
    later: 'Collected results are returned as {{$json.data.results}} with object list.',
    format: 'Boolean true or false.',
    example: 'Turn on Return All when exporting all Done tasks from a Notion database.',
    empty: 'Runtime treats it as false.',
    mistake: 'Turning it on for very large workspaces without considering Notion rate limits.',
  }),
  isInline: richFieldHelp({
    what: 'Whether a created Notion database should be inline inside its parent page.',
    why: 'Notion databases can be inline or full page when created under a page.',
    when: 'Optional for database create.',
    enter: 'true/on for inline database, false/off for full-page database.',
    source: 'Toggle it in the node panel or map {{$json.isInline}}.',
    later: 'The created database metadata is returned in {{$json.data}}.',
    format: 'Boolean true or false.',
    example: 'Create an inline project tracker inside a client workspace page.',
    empty: 'Runtime defaults to false.',
    mistake: 'Expecting this to affect pages or existing databases; it only applies to database create.',
  }),
};

const fields: FieldDoc[] = [
  { name: 'API Key', internalKey: 'apiKey', type: 'password', required: false, description: 'Legacy Notion token fallback; prefer Connections.', helpText: help.apiKey, placeholder: 'Stored in Connections', example: 'Stored in Connections' },
  { name: 'Access Token', internalKey: 'accessToken', type: 'password', required: false, description: 'Legacy OAuth token fallback; prefer Connections.', helpText: help.accessToken, placeholder: 'Stored in Connections', example: 'Stored in Connections' },
  { name: 'Credential ID', internalKey: 'credentialId', type: 'string', required: false, description: 'Internal stored credential reference for older configs.', helpText: help.credentialId, placeholder: 'cred_123', example: 'Selected via Connections' },
  { name: 'Resource', internalKey: 'resource', type: 'select', required: true, description: 'Choose the Notion resource type.', helpText: help.resource, options: ['page', 'database', 'block', 'user', 'comment', 'search'], defaultValue: 'page', example: 'database' },
  { name: 'Operation', internalKey: 'operation', type: 'select', required: true, description: 'Choose the operation for the selected resource.', helpText: help.operation, options: ['get', 'list', 'create', 'update', 'archive', 'restore', 'query', 'appendChildren', 'listChildren', 'delete', 'getMe', 'search'], defaultValue: 'get', example: 'query' },
  { name: 'Page ID', internalKey: 'pageId', type: 'string', required: false, description: 'Notion page ID.', helpText: help.pageId, placeholder: 'page-id-from-url', example: '{{$json.data.id}}' },
  { name: 'Database ID', internalKey: 'databaseId', type: 'string', required: false, description: 'Notion database ID.', helpText: help.databaseId, placeholder: 'database-id-from-url', example: '{{$json.databaseId}}' },
  { name: 'Block ID', internalKey: 'blockId', type: 'string', required: false, description: 'Notion block ID.', helpText: help.blockId, placeholder: 'block-id-from-url', example: '{{$json.blockId}}' },
  { name: 'User ID', internalKey: 'userId', type: 'string', required: false, description: 'Notion user ID.', helpText: help.userId, placeholder: 'notion-user-id', example: '{{$json.data.results[0].id}}' },
  { name: 'Parent Page ID', internalKey: 'parentPageId', type: 'string', required: false, description: 'Parent page ID for child page or database creation.', helpText: help.parentPageId, placeholder: 'parent-page-id', example: '{{$json.parentPageId}}' },
  { name: 'Title', internalKey: 'title', type: 'string', required: false, description: 'Plain text page or database title.', helpText: help.title, placeholder: 'Project Tracker', example: '{{$json.title}}' },
  { name: 'Content', internalKey: 'content', type: 'textarea', required: false, description: 'Plain text content converted to a paragraph block.', helpText: help.content, placeholder: 'Page or block text', example: '{{$json.summary}}' },
  { name: 'Children Blocks', internalKey: 'children', type: 'json', required: false, description: 'Raw Notion block JSON.', helpText: help.children, placeholder: '[{"type":"paragraph","paragraph":{"rich_text":[{"text":{"content":"Hello"}}]}}]', example: '{{$json.notionBlocks}}' },
  { name: 'Properties', internalKey: 'properties', type: 'json', required: false, description: 'Notion database page properties.', helpText: help.properties, placeholder: '{"Name":{"title":[{"text":{"content":"Task"}}]}}', example: '{{$json.properties}}' },
  { name: 'Query Body', internalKey: 'query', type: 'json', required: false, description: 'Raw database query JSON body.', helpText: help.query, placeholder: '{"filter":{"property":"Status","select":{"equals":"Done"}}}', example: '{{$json.query}}' },
  { name: 'Database Schema', internalKey: 'schema', type: 'json', required: false, description: 'Notion database property schema.', helpText: help.schema, placeholder: '{"Name":{"title":{}}}', example: '{{$json.schema}}' },
  { name: 'Rich Text', internalKey: 'richText', type: 'json', required: false, description: 'Notion rich_text array for comments.', helpText: help.richText, placeholder: '[{"type":"text","text":{"content":"Comment text"}}]', example: '{{$json.richText}}' },
  { name: 'Comment', internalKey: 'comment', type: 'textarea', required: false, description: 'Legacy plain text comment fallback.', helpText: help.comment, placeholder: 'Comment text', example: '{{$json.comment}}' },
  { name: 'Parent Discussion ID', internalKey: 'parentDiscussionId', type: 'string', required: false, description: 'Parent discussion ID for comment creation.', helpText: help.parentDiscussionId, placeholder: 'discussion-id', example: '{{$json.discussionId}}' },
  { name: 'Search Query', internalKey: 'searchQuery', type: 'string', required: false, description: 'Search text for Notion search.', helpText: help.searchQuery, placeholder: 'project notes', example: '{{$json.searchQuery}}' },
  { name: 'Filter', internalKey: 'filter', type: 'json', required: false, description: 'Notion filter JSON.', helpText: help.filter, placeholder: '{"property":"object","value":"database"}', example: '{{$json.filter}}' },
  { name: 'Sort', internalKey: 'sort', type: 'json', required: false, description: 'Notion search sort object.', helpText: help.sort, placeholder: '{"direction":"descending","timestamp":"last_edited_time"}', example: '{{$json.sort}}' },
  { name: 'Page Size', internalKey: 'pageSize', type: 'number', required: false, description: 'Notion API page size.', helpText: help.pageSize, defaultValue: '100', example: '25' },
  { name: 'Return All', internalKey: 'returnAll', type: 'boolean', required: false, description: 'Auto-paginate supported list/search operations.', helpText: help.returnAll, defaultValue: 'false', example: 'true' },
  { name: 'Is Inline', internalKey: 'isInline', type: 'boolean', required: false, description: 'Create database inline in the parent page.', helpText: help.isInline, defaultValue: 'false', example: 'true' },
];

const outputDescription = 'On success, runtime preserves incoming fields and adds success true plus data containing the raw Notion SDK response. Some Return All paths wrap collected results as data.results with object list. Failures preserve incoming fields and return _error, and unexpected SDK failures can include _errorDetails with message, statusCode, code, and stack details.';

const makeOperation = (operation: {
  name: string;
  value: string;
  description: string;
  inputValues: Record<string, string>;
  outputExample: Record<string, unknown>;
  scenario: string;
  expectedOutput: string;
}): OperationDoc => ({
  name: operation.name,
  value: operation.value,
  description: operation.description,
  fields,
  outputExample: operation.outputExample,
  outputDescription,
  usageExample: {
    scenario: operation.scenario,
    inputValues: operation.inputValues,
    expectedOutput: operation.expectedOutput,
  },
  externalDocsUrl: 'https://developers.notion.com/reference/intro',
});

const baseInput = {
  resource: 'page',
  operation: 'get',
  pageId: '',
  databaseId: '',
  blockId: '',
  userId: '',
  parentPageId: '',
  title: '',
  content: '',
  children: '',
  properties: '',
  query: '',
  schema: '',
  richText: '',
  comment: '',
  parentDiscussionId: '',
  searchQuery: '',
  filter: '',
  sort: '',
  pageSize: '100',
  returnAll: 'false',
  isInline: 'false',
};

export const notionDoc: NodeDoc = {
  slug: 'notion',
  displayName: 'Notion',
  category: 'Productivity',
  logoUrl: '/icons/nodes/notion.svg',
  description: 'Read, create, update, archive, search, and manage Notion pages, databases, blocks, users, and comments through the Notion API.',
  credentialType: 'Notion OAuth Connection',
  credentialSetupSteps: [
    'What this is: The Notion node uses the workflow owner saved Notion OAuth connection so CtrlChecks can call Notion without exposing tokens in workflow fields.',
    'Where to start: In CtrlChecks, open Connections and connect Notion. For internal integrations, Notion setup begins at notion.so/my-integrations and each page or database must be shared with the integration/account.',
    'How to connect: Authorize Notion in Connections, then make sure the connected account or integration can access the pages and databases the workflow will touch.',
    'What is stored: CtrlChecks stores OAuth tokens in the Connections credential vault. Legacy apiKey/accessToken fields are documented only because backend inventory still knows them.',
    'What not to store: Do not paste Notion secrets, OAuth tokens, integration tokens, passwords, or client secrets into normal workflow fields or downstream nodes.',
    'Test it: Run resource user with operation getMe, or run database list after sharing a known database/page with the connected Notion account.',
    'Connect the output or outgoing line to the next node that should use returned Notion data such as {{$json.data.id}}, {{$json.data.results}}, or {{$json.success}}.',
    'Every downstream service node still needs its own account connection; the Notion service node account connection does not authenticate Slack, Linear, Trello, email, or CRM nodes.',
  ],
  credentialDocsUrl: 'https://developers.notion.com/docs/authorization',
  resources: [
    {
      name: 'Pages, databases, blocks, users, comments, and search',
      description: 'Notion operations are valid only for certain resources. The runtime returns _error for mismatched resource-operation pairs.',
      operations: [
        makeOperation({ name: 'Page Get', value: 'page.get', description: 'Retrieve one Notion page by Page ID. Use it when a workflow needs the current page metadata and properties before making a decision or sending that data to another service.', inputValues: { ...baseInput, resource: 'page', operation: 'get', pageId: '{{$json.pageId}}' }, outputExample: { success: true, data: { object: 'page', id: 'page-id', properties: {} } }, scenario: 'Read a customer project page before deciding whether the status should be updated.', expectedOutput: 'The next node can read {{$json.data.properties}} and {{$json.data.id}}.' }),
        makeOperation({ name: 'Page Create', value: 'page.create', description: 'Create a Notion page either inside a database with Properties and Database ID, or as a child page under Parent Page ID with Children Blocks or Content.', inputValues: { ...baseInput, resource: 'page', operation: 'create', databaseId: '{{$json.databaseId}}', properties: '{{$json.properties}}', content: '{{$json.summary}}' }, outputExample: { success: true, data: { object: 'page', id: 'new-page-id', url: 'https://notion.so/new-page-id' } }, scenario: 'Create a Notion task row from a new support ticket.', expectedOutput: 'Later steps can use {{$json.data.id}} as the new Page ID.' }),
        makeOperation({ name: 'Page Update', value: 'page.update', description: 'Update properties on an existing Notion page. Runtime requires Page ID and Properties and sends those properties directly to Notion pages.update.', inputValues: { ...baseInput, resource: 'page', operation: 'update', pageId: '{{$json.pageId}}', properties: '{"Status":{"select":{"name":"Done"}}}' }, outputExample: { success: true, data: { object: 'page', id: 'page-id', properties: { Status: { select: { name: 'Done' } } } } }, scenario: 'Mark a Notion task done after a Linear issue is closed.', expectedOutput: 'The updated properties can be checked at {{$json.data.properties}}.' }),
        makeOperation({ name: 'Page Archive', value: 'page.archive', description: 'Archive a Notion page by setting archived true through pages.update. Use it for cleanup workflows where the page should no longer be active.', inputValues: { ...baseInput, resource: 'page', operation: 'archive', pageId: '{{$json.pageId}}' }, outputExample: { success: true, data: { object: 'page', id: 'page-id', archived: true } }, scenario: 'Archive a temporary onboarding page after the customer workspace closes.', expectedOutput: 'A later node can confirm {{$json.data.archived}} is true.' }),
        makeOperation({ name: 'Page Restore', value: 'page.restore', description: 'Restore a previously archived Notion page by setting archived false. Use it when an upstream business rule reopens a record.', inputValues: { ...baseInput, resource: 'page', operation: 'restore', pageId: '{{$json.pageId}}' }, outputExample: { success: true, data: { object: 'page', id: 'page-id', archived: false } }, scenario: 'Restore a paused project page after a contract is renewed.', expectedOutput: 'A later node can check {{$json.data.archived}} to confirm it is false.' }),
        makeOperation({ name: 'Database Get', value: 'database.get', description: 'Retrieve one Notion database by Database ID. Use it to inspect database metadata, title, and property schema before building a query or creating rows.', inputValues: { ...baseInput, resource: 'database', operation: 'get', databaseId: '{{$json.databaseId}}' }, outputExample: { success: true, data: { object: 'database', id: 'database-id', properties: { Name: { type: 'title' } } } }, scenario: 'Check a project tracker schema before creating a new row.', expectedOutput: 'The schema is available at {{$json.data.properties}}.' }),
        makeOperation({ name: 'Database List', value: 'database.list', description: 'List databases available through Notion search. Runtime defaults the filter to object database and supports Page Size and Return All.', inputValues: { ...baseInput, resource: 'database', operation: 'list', filter: '{"property":"object","value":"database"}', returnAll: 'true' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'database', id: 'database-id' }] } }, scenario: 'Discover Notion databases shared with the connected account before choosing the right tracker.', expectedOutput: 'Downstream nodes can read {{$json.data.results}} and select {{$json.data.results[0].id}}.' }),
        makeOperation({ name: 'Database Query', value: 'database.query', description: 'Query a Notion database using Database ID and optional raw Query Body. Runtime supports Return All pagination and clamps Page Size to 1-100.', inputValues: { ...baseInput, resource: 'database', operation: 'query', databaseId: '{{$json.databaseId}}', query: '{"filter":{"property":"Status","select":{"equals":"Done"}}}', pageSize: '50' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'page', id: 'task-page-id' }] } }, scenario: 'Fetch all Done tasks from a project tracker for a weekly report.', expectedOutput: 'The report node can loop over {{$json.data.results}}.' }),
        makeOperation({ name: 'Database Create', value: 'database.create', description: 'Create a database under a parent page. Runtime requires Parent Page ID, Title, and Schema, and can set Is Inline to create an inline database.', inputValues: { ...baseInput, resource: 'database', operation: 'create', parentPageId: '{{$json.parentPageId}}', title: '{{$json.databaseTitle}}', schema: '{"Name":{"title":{}}}', isInline: 'true' }, outputExample: { success: true, data: { object: 'database', id: 'new-database-id', title: [] } }, scenario: 'Create a client project tracker under a new onboarding workspace page.', expectedOutput: 'Later Notion steps can use {{$json.data.id}} as Database ID.' }),
        makeOperation({ name: 'Database Update', value: 'database.update', description: 'Update a Notion database title and/or property schema. Runtime requires Database ID and at least Title or Schema.', inputValues: { ...baseInput, resource: 'database', operation: 'update', databaseId: '{{$json.databaseId}}', title: 'Updated Project Tracker', schema: '{"Priority":{"select":{"options":[{"name":"High"}]}}}' }, outputExample: { success: true, data: { object: 'database', id: 'database-id' } }, scenario: 'Add a Priority property to a team tracker after a process change.', expectedOutput: 'The updated database metadata is returned at {{$json.data}}.' }),
        makeOperation({ name: 'Block Get', value: 'block.get', description: 'Retrieve one Notion block by Block ID. Use it when the workflow needs the current block type, text, or archived state before appending or updating content.', inputValues: { ...baseInput, resource: 'block', operation: 'get', blockId: '{{$json.blockId}}' }, outputExample: { success: true, data: { object: 'block', id: 'block-id', type: 'paragraph' } }, scenario: 'Read a notes block before appending a follow-up paragraph.', expectedOutput: 'The next node can inspect {{$json.data.type}} and {{$json.data.id}}.' }),
        makeOperation({ name: 'Block List Children', value: 'block.listChildren', description: 'List child blocks under a Notion block. Runtime requires Block ID and supports Page Size plus Return All pagination.', inputValues: { ...baseInput, resource: 'block', operation: 'listChildren', blockId: '{{$json.blockId}}', returnAll: 'true' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'block', id: 'child-block-id' }] } }, scenario: 'Read all child blocks from meeting notes before summarizing them.', expectedOutput: 'The summary node can use {{$json.data.results}}.' }),
        makeOperation({ name: 'Block Append Children', value: 'block.appendChildren', description: 'Append children under a Notion block. Runtime requires Block ID and either Children Blocks JSON or plain Content converted to a paragraph.', inputValues: { ...baseInput, resource: 'block', operation: 'appendChildren', blockId: '{{$json.blockId}}', content: '{{$json.followUpNote}}' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'block', id: 'new-child-block' }] } }, scenario: 'Append an AI-generated customer call summary to an account notes page.', expectedOutput: 'New child block results are available at {{$json.data.results}}.' }),
        makeOperation({ name: 'Block Update', value: 'block.update', description: 'Update one Notion block. Runtime requires Block ID and Children Blocks as a block content object, not an array.', inputValues: { ...baseInput, resource: 'block', operation: 'update', blockId: '{{$json.blockId}}', children: '{"paragraph":{"rich_text":[{"type":"text","text":{"content":"Updated note"}}]}}' }, outputExample: { success: true, data: { object: 'block', id: 'block-id', type: 'paragraph' } }, scenario: 'Replace a stale status paragraph in a project page.', expectedOutput: 'The updated block is returned at {{$json.data}}.' }),
        makeOperation({ name: 'Block Delete', value: 'block.delete', description: 'Archive one Notion block by setting archived true. Use it for cleanup workflows that remove outdated block content from an active page.', inputValues: { ...baseInput, resource: 'block', operation: 'delete', blockId: '{{$json.blockId}}' }, outputExample: { success: true, data: { object: 'block', id: 'block-id', archived: true } }, scenario: 'Archive a temporary checklist block after onboarding is complete.', expectedOutput: 'A following condition can inspect {{$json.data.archived}}.' }),
        makeOperation({ name: 'User Get', value: 'user.get', description: 'Retrieve one Notion user by User ID. Use it when a workflow needs profile metadata for a known Notion user returned by another API call.', inputValues: { ...baseInput, resource: 'user', operation: 'get', userId: '{{$json.userId}}' }, outputExample: { success: true, data: { object: 'user', id: 'user-id', name: 'Asha Rao' } }, scenario: 'Fetch the owner profile for a Notion task before sending an assignment notice.', expectedOutput: 'The notification node can use {{$json.data.name}}.' }),
        makeOperation({ name: 'User List', value: 'user.list', description: 'List Notion users visible to the integration. Runtime supports Page Size and Return All, returning the Notion SDK users.list response.', inputValues: { ...baseInput, resource: 'user', operation: 'list', returnAll: 'false', pageSize: '100' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'user', id: 'user-id', name: 'Asha Rao' }] } }, scenario: 'Discover user IDs before matching Notion owners to another system.', expectedOutput: 'Downstream mapping can read {{$json.data.results[0].id}}.' }),
        makeOperation({ name: 'User Get Me', value: 'user.getMe', description: 'Retrieve the connected Notion bot/user identity. Use this as a safe connection test because it requires no page, database, block, or user ID.', inputValues: { ...baseInput, resource: 'user', operation: 'getMe' }, outputExample: { success: true, data: { object: 'user', id: 'bot-user-id', name: 'CtrlChecks' } }, scenario: 'Test a newly connected Notion account before touching workspace content.', expectedOutput: 'The workflow can confirm Notion access by checking {{$json.success}} and {{$json.data.id}}.' }),
        makeOperation({ name: 'Comment List', value: 'comment.list', description: 'List comments on a Notion page or block. Runtime requires either Page ID or Block ID and supports Page Size plus Return All.', inputValues: { ...baseInput, resource: 'comment', operation: 'list', pageId: '{{$json.pageId}}', returnAll: 'true' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'comment', id: 'comment-id' }] } }, scenario: 'Collect comments from a project page before summarizing open questions.', expectedOutput: 'The AI summary node can read {{$json.data.results}}.' }),
        makeOperation({ name: 'Comment Create', value: 'comment.create', description: 'Create a Notion comment on a page or parent discussion. Runtime requires Page ID or Parent Discussion ID, plus Rich Text JSON or legacy plain Comment text.', inputValues: { ...baseInput, resource: 'comment', operation: 'create', pageId: '{{$json.pageId}}', richText: '[{"type":"text","text":{"content":"Reviewed by {{$json.reviewer}}"}}]' }, outputExample: { success: true, data: { object: 'comment', id: 'comment-id' } }, scenario: 'Add an approval comment to a Notion project page after a manager approves a request.', expectedOutput: 'The created comment response is available as {{$json.data}}.' }),
        makeOperation({ name: 'Comment Get Unsupported', value: 'comment.get', description: 'The UI can choose get for comments, but the runtime returns a clear _error because the Notion API path used here cannot retrieve a single comment by ID. Use comment list instead.', inputValues: { ...baseInput, resource: 'comment', operation: 'get', pageId: '{{$json.pageId}}' }, outputExample: { _error: 'Notion node: The Notion API does not support retrieving a single comment by ID. Please use the "list" operation to retrieve comments for a page or block.' }, scenario: 'A workflow imported an old comment get step and needs to be corrected to list comments.', expectedOutput: 'Downstream error handling can check {{$json._error}} and route users to use list instead.' }),
        makeOperation({ name: 'Search', value: 'search.search', description: 'Search Notion pages and databases. Runtime reads Search Query, Filter, Sort, Page Size, and Return All for the search resource with operation search.', inputValues: { ...baseInput, resource: 'search', operation: 'search', searchQuery: '{{$json.query}}', filter: '{"property":"object","value":"page"}', sort: '{"direction":"descending","timestamp":"last_edited_time"}' }, outputExample: { success: true, data: { object: 'list', results: [{ object: 'page', id: 'page-id' }] } }, scenario: 'Find recently edited customer pages matching an account name before posting an update.', expectedOutput: 'Downstream nodes can inspect {{$json.data.results}} and choose {{$json.data.results[0].id}}.' }),
      ],
    },
  ],
  commonErrors: [
    { error: 'Notion node: OAuth connection required', cause: 'The workflow owner or current user does not have a Notion account connected.', fix: 'Reconnect Notion in CtrlChecks Connections and make sure the workflow owner has access.' },
    { error: 'Notion node: pageId is required for get/update/archive/restore', cause: 'A page operation was selected without Page ID.', fix: 'Map {{$json.data.id}} from a previous Notion step or copy the page ID from Notion.' },
    { error: 'Notion node: Either databaseId or parentPageId is required for create operation', cause: 'Page Create needs exactly one parent target.', fix: 'Use Database ID for database rows or Parent Page ID for child pages, but not both.' },
    { error: 'Notion node: properties is required', cause: 'Creating a database row or updating a page requires Notion properties JSON.', fix: 'Provide valid Notion API property JSON with exact database property names.' },
    { error: 'Notion node: databaseId is required for query/get/update', cause: 'A database operation was selected without Database ID.', fix: 'Copy or map the Notion database UUID and confirm it is shared with the connected account.' },
    { error: 'Notion node: blockId is required for block operations', cause: 'A block operation was selected without Block ID.', fix: 'Copy a block link or map a block id from a prior Notion response.' },
    { error: 'Notion node: richText array is required for create comment operation', cause: 'Comment Create did not receive Rich Text JSON or legacy plain comment text.', fix: 'Provide a Notion rich_text array or map a plain comment value where supported.' },
    { error: 'Notion node: The Notion API does not support retrieving a single comment by ID', cause: 'Resource comment with operation get is unsupported by this runtime path.', fix: 'Use comment list with Page ID or Block ID and filter downstream if needed.' },
    { error: 'Notion node: Unknown operation or resource', cause: 'The selected resource-operation pair is invalid, such as search with get or page with query.', fix: 'Use the documented valid pairs and keep imported workflow configs aligned to the visual dropdown values.' },
  ],
  relatedNodes: ['notion_trigger', 'linear', 'trello', 'typeform', 'google_sheets'],
};
