import type { NodeDoc } from '../types';

const operationHelp = [
  'What this field is: The Outlook action this node will run.',
  'Why it matters: The runtime currently supports only sending an email through Microsoft Graph sendMail.',
  'When to fill it: Leave it as Send Email unless the UI adds more Outlook operations in the future.',
  'What to enter: Choose Send Email, which stores the value send_email. The legacy value send is also accepted by runtime.',
  'Where the value comes from: Select it from the dropdown in the node panel.',
  'How to use it later: The output keeps your incoming fields and adds {{$json.success}} when Microsoft Graph accepts the message.',
  'Accepted format: send_email from the dropdown; send is accepted only for older configs.',
  'Real workplace example: Send a customer onboarding email from the connected sales mailbox.',
  'If it is empty or wrong: Unsupported values return an _error saying only send_email is supported.',
  'Common mistake: Expecting this Outlook node to read inbox mail or calendar events. Use Outlook Trigger for incoming Outlook activity.',
].join('\n');

const toHelp = [
  'What this field is: The recipient email address or comma-separated list of recipients.',
  'Why it matters: Microsoft Graph needs at least one valid recipient before it can send the email.',
  'When to fill it: Required for Send Email.',
  'What to enter: Type one address such as manager@company.com, or several addresses separated by commas.',
  'Where the value comes from: Use a fixed team address, or map a customer, requester, or assignee email from an earlier step.',
  'How to use it later: On success the node preserves incoming fields and adds {{$json.success}}, but Graph sendMail does not return the recipient list as a new output.',
  'Accepted format: Email addresses separated by commas. Spaces after commas are okay because runtime trims each address.',
  'Real workplace example: {{$json.customerEmail}} sends a confirmation to the customer who submitted a form.',
  'If it is empty or wrong: The node returns _error for missing to, subject, and body, or Microsoft Graph rejects invalid addresses.',
  'Common mistake: Do not paste a Microsoft token here. Select the Microsoft Connection separately and put only recipient email addresses in To.',
].join('\n');

const subjectHelp = [
  'What this field is: The subject line shown in the recipient mailbox.',
  'Why it matters: It tells the recipient why the email was sent and helps them recognize the workflow message.',
  'When to fill it: Required for Send Email.',
  'What to enter: Use short text, optionally including mapped workflow values such as an order number or ticket ID.',
  'Where the value comes from: Type a fixed subject or map a prepared subject from a previous node.',
  'How to use it later: The node preserves incoming fields and adds {{$json.success}}, but Microsoft Graph does not return a message ID or subject output.',
  'Accepted format: Plain text. Keep it concise and avoid line breaks.',
  'Real workplace example: Order {{$json.orderId}} is ready for review.',
  'If it is empty or wrong: Runtime treats it as missing and returns _error before sending.',
  'Common mistake: Putting the full message body in Subject. Put only the inbox headline here and use Body for the message.',
].join('\n');

const bodyHelp = [
  'What this field is: The plain-text content sent in the email body.',
  'Why it matters: This is the actual message the recipient reads after opening the Outlook email.',
  'When to fill it: Required for Send Email.',
  'What to enter: Type the message text or map content generated by an earlier workflow step.',
  'Where the value comes from: Use a fixed template, a form response, a report summary, or an AI-generated message from a previous node.',
  'How to use it later: After sending, downstream nodes can check {{$json.success}} and still use incoming fields, but not a Graph message ID.',
  'Accepted format: Plain text. The current executor sends contentType Text, not HTML.',
  'Real workplace example: Hi {{$json.firstName}}, your ticket {{$json.ticketId}} has been received.',
  'If it is empty or wrong: Runtime returns _error before sending, or the recipient receives incomplete plain text.',
  'Common mistake: Expecting HTML formatting. The current Outlook executor sends this field as plain text through Microsoft Graph.',
].join('\n');

export const outlookDoc: NodeDoc = {
  slug: 'outlook',
  displayName: 'Outlook',
  category: 'Communication',
  logoUrl: '/integrations-logos/Outlook.svg',
  description: 'Send plain-text emails from a connected Microsoft Outlook mailbox through Microsoft Graph.',
  credentialType: 'Microsoft OAuth2 Connection',
  credentialSetupSteps: [
    'What this is: The Outlook node uses a saved Microsoft OAuth2 connection so CtrlChecks can call Microsoft Graph without exposing tokens in workflow fields.',
    'Where to start: In CtrlChecks, open Connections, choose Add Connection, and select Microsoft.',
    'How to connect: Sign in with the Microsoft account or shared mailbox owner that should send the email.',
    'Scopes used: User.Read lets CtrlChecks identify and test the account. Mail.Send lets Microsoft Graph send mail from the connected mailbox. offline_access lets CtrlChecks refresh the OAuth token.',
    'What is stored: CtrlChecks stores OAuth tokens in the Connections credential vault, not in normal workflow fields.',
    'What not to store: Do not paste Microsoft access tokens, refresh tokens, passwords, client secrets, or tenant secrets into To, Subject, Body, or any ordinary node field.',
    'Test it: Save the connection, run a simple Outlook Send Email step to your own address, and confirm Microsoft Graph accepts the sendMail request.',
    'Connect the output or outgoing line to the next node only when that node should run after Graph accepts the message.',
    'Every downstream service node still needs its own account connection; the Microsoft connection on Outlook does not authenticate other services.',
  ],
  credentialDocsUrl: 'https://learn.microsoft.com/graph/api/user-sendmail',
  resources: [
    {
      name: 'Email',
      description: 'Outlook currently exposes one visible operation: send a plain-text email.',
      operations: [
        {
          name: 'Send Email',
          value: 'send_email',
          description: 'Send a plain-text email from the selected Microsoft account using Microsoft Graph. The runtime resolves template values in To, Subject, and Body, sends the request to /me/sendMail, asks Graph to save the message to Sent Items, and returns success true when Graph accepts the request.',
          fields: [
            {
              name: 'Operation',
              internalKey: 'operation',
              type: 'select',
              required: true,
              description: 'Choose the Outlook action to run.',
              helpText: operationHelp,
              defaultValue: 'send_email',
              options: ['send_email'],
              example: 'send_email',
            },
            {
              name: 'To',
              internalKey: 'to',
              type: 'email',
              required: true,
              description: 'Recipient email address or comma-separated recipient list.',
              helpText: toHelp,
              placeholder: 'recipient@example.com',
              example: 'customer@example.com, manager@example.com',
            },
            {
              name: 'Subject',
              internalKey: 'subject',
              type: 'string',
              required: true,
              description: 'Email subject line.',
              helpText: subjectHelp,
              placeholder: 'Email subject',
              example: 'Order {{$json.orderId}} is ready for review',
            },
            {
              name: 'Body',
              internalKey: 'body',
              type: 'textarea',
              required: true,
              description: 'Plain-text message body.',
              helpText: bodyHelp,
              placeholder: 'Email body content...',
              example: 'Hi {{$json.firstName}}, your ticket {{$json.ticketId}} has been received.',
            },
          ],
          outputExample: {
            orderId: 'ORD-1042',
            customerEmail: 'buyer@example.com',
            success: true,
          },
          outputDescription: 'On success, Outlook preserves incoming fields and adds success: true. Microsoft Graph sendMail returns an empty accepted response, so there is no messageId, sentAt, or recipient output. Failures preserve incoming fields and return _error, and Graph response text may appear in _errorDetails.',
          usageExample: {
            scenario: 'Send an order confirmation email through the connected Outlook mailbox after a checkout form is received.',
            inputValues: {
              operation: 'send_email',
              to: '{{$json.customerEmail}}',
              subject: 'Order {{$json.orderId}} received',
              body: 'Hi {{$json.firstName}}, we received your order {{$json.orderId}}.',
            },
            expectedOutput: 'When Microsoft Graph accepts the message, downstream nodes can check {{$json.success}} and still read {{$json.orderId}} from the original input.',
          },
          externalDocsUrl: 'https://learn.microsoft.com/graph/api/user-sendmail',
        },
      ],
    },
  ],
  commonErrors: [
    {
      error: 'Outlook: access token not found',
      cause: 'No Microsoft OAuth2 Connection was selected or the saved connection could not be resolved for the workflow owner.',
      fix: 'Reconnect Microsoft in CtrlChecks Connections, approve Mail.Send, and select the Microsoft Connection for this node.',
    },
    {
      error: 'Outlook: to, subject, and body are required',
      cause: 'A required send field is empty or an upstream expression resolved to an empty value.',
      fix: 'Fill To, Subject, and Body, then verify mapped values such as {{$json.customerEmail}} resolve before this node runs.',
    },
    {
      error: 'Outlook: Unsupported operation',
      cause: 'The operation value is not send_email or the legacy alias send.',
      fix: 'Choose Send Email from the dropdown or set operation to send_email.',
    },
    {
      error: 'Outlook sendMail failed (401 or 403)',
      cause: 'The OAuth grant is expired, revoked, or missing the Mail.Send delegated permission.',
      fix: 'Reconnect Microsoft and approve User.Read, Mail.Send, and offline_access permissions, then run the node again.',
    },
    {
      error: 'Next node cannot find a message ID',
      cause: 'Microsoft Graph sendMail accepts the request but does not return a message ID to this runtime path.',
      fix: 'Route on {{$json.success}} or use a later Outlook/Gmail search pattern if you must find a sent message record.',
    },
  ],
  relatedNodes: ['google_gmail', 'email', 'amazon_ses', 'mailgun', 'outlook_trigger'],
};
