import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const graphWebhooksDocs = 'https://learn.microsoft.com/graph/api/resources/webhooks';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Microsoft OAuth2 connection ID. If blank, the active Microsoft connection is used.',
    helpText: 'What this field means: Connection points to the saved Microsoft OAuth2 account CtrlChecks uses to create the Microsoft Graph subscription and read the mail/calendar item when a notification arrives. Why it matters: CtrlChecks needs a Microsoft access token with Mail.Read and Calendars.Read to both register the Graph subscription and fetch the actual message/event content the notification refers to (Graph notifications never include the content itself, only an ID). When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Microsoft connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you complete Microsoft OAuth2 sign-in. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw access token. Real workplace example: A support team connects the shared support@company.com Outlook mailbox once, and every Outlook Trigger node in the workspace reuses that connection. If it is empty or wrong: Empty falls back to the active Microsoft connection; a wrong or missing connection can cause No active Microsoft connection found. Common mistake: Assuming a Microsoft connection made before this trigger existed already has the right scopes — reconnect if Mail.Read/Calendars.Read were not originally granted.',
    placeholder: 'Uses your active Microsoft connection',
    example: 'microsoft_oauth_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Resource',
    internalKey: 'resource',
    type: 'string',
    required: false,
    description: 'Which Outlook resource to watch: mail or calendar.',
    helpText: 'What this field means: Resource decides whether this trigger watches new email or calendar changes. Why it matters: Mail and Calendar are completely different Microsoft Graph subscriptions with different fields available afterward (subject/from/snippet for mail, start/end/attendees for calendar). When to fill it: Always set it deliberately — the default is Mail, but many workflows need Calendar instead. What to enter: mail to watch a mailbox folder, or calendar to watch calendar events. Where the value comes from: Decide based on whether the workflow should react to incoming email or to calendar changes. How to use it later: This decides which output fields are populated; check {{$json.eventType}} (message_created vs event_created/event_updated/event_deleted) to confirm which resource fired. Accepted format: mail or calendar (dropdown selection). Real workplace example: A scheduling assistant sets Resource to calendar so it reacts to new meeting invites, while a support triage workflow sets it to mail. If it is empty or wrong: Empty defaults to mail. Choosing the wrong resource means Mail Folder is ignored (Calendar mode) or start/end/attendees stay empty (Mail mode). Common mistake: Leaving Resource on Mail while expecting calendar invite fields such as {{$json.start}} or {{$json.attendees}} to be populated.',
    placeholder: 'mail',
    defaultValue: 'mail',
    example: 'mail',
    options: ['mail', 'calendar'],
  },
  {
    name: 'Change Types',
    internalKey: 'changeTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated Microsoft Graph change types to accept.',
    helpText: 'What this field means: Change Types decides which kinds of Graph changes (created, updated, deleted) are allowed to start this workflow. Why it matters: Mail subscriptions in this trigger are effectively always "created" (new messages), while Calendar subscriptions commonly also care about updated (rescheduled) or deleted (cancelled) events. When to fill it: Keep the default (created) for most mail and simple calendar-invite workflows. Add updated and/or deleted for a calendar workflow that must react to reschedules or cancellations. What to enter: Comma-separated Graph change type names: created, updated, deleted. Where the value comes from: Pick from Microsoft Graph\'s supported changeType values for the resource you are watching. How to use it later: Route with {{$json.eventType}}, which becomes message_created for mail, or event_created/event_updated/event_deleted for calendar depending on the change type. Accepted format: Comma-separated text. Real workplace example: created, updated, deleted for a meeting-room booking workflow that must know about new bookings, reschedules, and cancellations. If it is empty or wrong: Empty defaults to created only. Requesting a change type Graph does not support for the chosen resource can cause subscription creation to fail. Common mistake: Expecting deleted mail notifications — mail resources in this trigger only subscribe to created; there is no delete tracking for messages today.',
    placeholder: 'created',
    defaultValue: 'created',
    example: 'created',
  },
  {
    name: 'Mail Folder',
    internalKey: 'folderName',
    type: 'string',
    required: false,
    description: 'Mail folder to watch (mail resource only).',
    helpText: 'What this field means: Mail Folder is the Outlook folder this trigger watches for new messages, used only when Resource is set to mail. Why it matters: Without this, CtrlChecks would need to guess which folder matters; most mailboxes have many folders and only new mail landing in the chosen one should start the workflow. When to fill it: Leave it as Inbox (the default) for normal incoming-mail workflows. Fill it with another folder\'s display name when watching a specific folder such as a shared mailbox\'s support queue or a rules-filtered folder. What to enter: The exact folder display name as it appears in Outlook, such as Inbox or Support Queue — not a folder path with slashes. Where the value comes from: Look at the folder name in the Outlook folder list on the left side of the mailbox. How to use it later: This is a setup/subscription value only; it is not emitted as {{$json.folderName}} to downstream nodes. Accepted format: Plain folder display name text. Real workplace example: A billing team watches a folder named Billing Escalations instead of the default Inbox so only pre-sorted, high-priority emails trigger the workflow. If it is empty or wrong: Empty defaults to Inbox. A folder name that does not exist in the mailbox causes the Graph subscription request itself to fail. Common mistake: Typing a nested folder path like Inbox/Support instead of just the folder\'s own display name, such as Support.',
    placeholder: 'Inbox',
    example: 'Inbox',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional keyword matched against the subject, sender, and snippet.',
    helpText: 'What this field means: Keyword Filter only lets events whose subject, sender address, or body preview contains a word or phrase start the workflow. Why it matters: A busy mailbox or calendar can produce a lot of notifications; this keeps the workflow focused on urgent or relevant items without a second Graph subscription. When to fill it: Use it when the workflow should react only to a phrase such as urgent, invoice, or a customer name. Leave it blank to accept every event matching Resource and Change Types. What to enter: A simple keyword or short phrase, not Outlook search syntax. Where the value comes from: Pick the label, customer name, module name, or keyword your team uses in subjects, sender addresses, or message previews. How to use it later: The accepted event output still includes {{$json.subject}}, {{$json.from}}, and {{$json.snippet}} for downstream routing. Accepted format: Plain text, case-insensitive contains match against subject + from + snippet combined. Real workplace example: invoice starts only billing-related email workflows, ignoring unrelated inbox traffic. If it is empty or wrong: Empty accepts every event matching the other filters; a too-specific or misspelled filter silently drops matching Graph notifications with no visible error, since this trigger acknowledges Graph immediately and processes notifications in the background. Common mistake: Expecting Outlook\'s advanced search operators (such as from:boss@company.com) here — this is a simple text contains filter, not Outlook search syntax.',
    placeholder: 'invoice',
    example: 'invoice',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive notification',
  value: 'receive',
  description: 'Starts the workflow when an accepted Microsoft Graph change notification for the watched mail folder or calendar arrives — CtrlChecks re-fetches the referenced message/event from Graph and normalizes it before filtering.',
  fields,
  outputExample: {
    eventId: 'msg-1-created',
    eventType: 'message_created',
    source: 'outlook',
    userId: 'billing@example.com',
    username: 'Billing Team',
    text: 'Your invoice is ready for review...',
    timestamp: '2026-07-19T10:20:00.000Z',
    resourceId: 'msg-1',
    subject: 'Invoice #123',
    from: 'billing@example.com',
    to: 'you@company.com',
    snippet: 'Your invoice is ready for review...',
    conversationId: 'conversation-1',
    start: null,
    end: null,
    attendees: [],
    raw: {},
    trigger: 'outlook',
    workflow_id: 'workflow_123',
    node_id: 'outlook-trigger-1',
    sessionId: 'outlook_workflow_123_conversation-1',
    _outlook: true,
  },
  outputDescription: 'eventId: resourceId-changeType composite, always unique per notification. eventType: message_created for mail, or event_created/event_updated/event_deleted for calendar. source: outlook. userId/username: sender (mail) or organizer (calendar) identity. text/snippet: message body preview or calendar event body preview. timestamp: received time (mail) or event start time (calendar), or the notification time as a fallback. resourceId: the Graph message/event ID this notification refers to. subject/from/to: mail header fields, to is a comma-joined recipient list, empty for calendar. conversationId: mail thread ID, null for calendar. start/end: calendar event times as ISO strings, null for mail. attendees: calendar attendee email addresses, empty array for mail. raw: the full re-fetched Graph message or event object. trigger/workflow_id/node_id/sessionId/_outlook: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'AI triage for new support emails, then reply from the Outlook action node',
    inputValues: {
      resource: 'mail',
      changeTypes: 'created',
      folderName: 'Inbox',
      query: '',
    },
    expectedOutput: 'Use {{$json.subject}}, {{$json.from}}, and {{$json.snippet}} in an AI Agent, then reply using the Outlook action node with {{$json.conversationId}}.',
  },
  externalDocsUrl: graphWebhooksDocs,
};

export const outlookTriggerDoc: NodeDoc = {
  slug: 'outlook_trigger',
  displayName: 'Outlook Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Outlook.svg',
  description: 'Start workflows from new Outlook email or calendar events delivered through Microsoft Graph change notifications.',
  credentialType: 'Microsoft OAuth2',
  credentialSetupSteps: [
    'Connect Microsoft (Outlook) in Connections if not already connected. This grants the Mail.Read and Calendars.Read Graph scopes needed to watch the mailbox or calendar (test call: GET https://graph.microsoft.com/v1.0/me).',
    'Add this trigger to a workflow, choose Resource (Mail or Calendar), set Change Types and (for Mail) Mail Folder, and save/activate the workflow.',
    'CtrlChecks automatically creates a Microsoft Graph subscription pointing at the generated webhook URL — no external dashboard setup is required, unlike Gmail Pub/Sub or Jira\'s manual webhook admin page.',
    'Graph subscriptions expire after roughly 3 days; CtrlChecks automatically renews any subscription expiring within 24 hours using a background job that sweeps every 6 hours, so no manual renewal is needed while the workflow stays active.',
    'Notifications are validated with a per-subscription clientState secret CtrlChecks generates and stores; this happens automatically and needs no setup from you.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Microsoft connection only authorizes reading the mailbox/calendar, not the Slack, CRM, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: graphWebhooksDocs,
  resources: [
    {
      name: 'Webhook',
      description: 'Receives Microsoft Graph change notifications and emits a normalized event payload.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'No active Microsoft connection found',
      cause: 'The workflow owner has not connected Microsoft (Outlook), or the connection lacks the Mail.Read/Calendars.Read scopes.',
      fix: 'Connect Microsoft (Outlook) in Connections and re-register the subscription. Existing connections made before this trigger existed may need to be reconnected to grant the new scopes.',
    },
    {
      error: 'Ignored notification with invalid clientState',
      cause: 'The notification did not include the shared secret CtrlChecks generated when creating the Graph subscription.',
      fix: 'This should not happen under normal use; re-register the subscription if it persists.',
    },
    {
      error: 'Workflow does not fire even though mail/calendar changed',
      cause: 'Microsoft Graph notifications are acknowledged immediately (a 202 within seconds) and then processed silently in the background — an invalid clientState, a missing/expired Microsoft credential, a failed Graph re-fetch, or a Keyword Filter mismatch all fail silently with no visible error response.',
      fix: 'Check worker logs for "[Outlook Trigger]" entries, confirm the Microsoft connection is still valid, and temporarily clear Keyword Filter to test whether filtering is the cause.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Outlook subscriptions.',
      cause: 'CtrlChecks cannot build the public callback URL Microsoft Graph must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'Microsoft Graph API error (400/403/404): ...',
      cause: 'The Graph subscription request failed, commonly from an invalid Mail Folder name, an unsupported Change Type for the resource, or insufficient token scopes.',
      fix: 'Check the Mail Folder display name for typos, confirm Change Types are valid for the selected Resource, and confirm the Microsoft connection has Mail.Read/Calendars.Read.',
    },
    {
      error: 'Outlook Trigger node not found in this workflow.',
      cause: 'The webhook URL points to a node ID that is missing, renamed incorrectly, or no longer has type outlook_trigger.',
      fix: 'Save the workflow with the Outlook Trigger node still present, then re-register the subscription so a fresh URL is generated.',
    },
    {
      error: 'Next node cannot find Outlook trigger fields',
      cause: 'A downstream node is mapped to a field only present for the other resource, such as expecting {{$json.start}}/{{$json.attendees}} while Resource is set to mail.',
      fix: 'Use {{$json.eventType}} to confirm whether the event is message_created (mail) or event_created/updated/deleted (calendar) before mapping resource-specific fields.',
    },
    {
      error: 'Permission denied after Outlook Trigger',
      cause: 'The trigger fired correctly, but the downstream Outlook action, Slack, CRM, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Microsoft connection has Mail.Send if the workflow needs to reply.',
    },
  ],
  relatedNodes: ['outlook', 'ai_agent'],
};
