import type { FieldDoc, NodeDoc } from '../types';
import { richFieldHelp } from './_sharedFieldHelp';

const operationField: FieldDoc = {
  name: 'Operation',
  internalKey: 'operation',
  type: 'select',
  required: true,
  description: 'Choose which ScheduleWise appointment action to run: Get Schedules, Create Appointment, Update Appointment, or Delete Appointment.',
  helpText: richFieldHelp({
    what: 'The ScheduleWise appointment action the node performs.',
    why: 'Runtime validates this value and returns INVALID_OPERATION unless it is getSchedules, createAppointment, updateAppointment, or deleteAppointment.',
    when: 'Always choose one operation before running the node.',
    enter: 'Choose Get Schedules to list appointments, Create Appointment to book a new slot, Update Appointment to change a slot or status, or Delete Appointment to remove a slot.',
    source: 'Choose from the dropdown based on the workflow purpose; upstream nodes may also set operation when generating workflow JSON.',
    later: 'The chosen value is returned as {{$json.operation}} so logs and later branches can tell which ScheduleWise action ran.',
    format: 'Dropdown value: getSchedules, createAppointment, updateAppointment, or deleteAppointment.',
    example: 'A patient intake form uses Create Appointment after collecting patientId, staffId, and startDateTime.',
    empty: 'Runtime returns success false with error code INVALID_OPERATION.',
    mistake: 'Using a display label or old value instead of one of the exact runtime values.',
  }),
  options: ['Get Schedules', 'Create Appointment', 'Update Appointment', 'Delete Appointment'],
  notes: 'Get Schedules reads /appointments with filters and makes dateFrom, dateTo, patientId, staffId, and limit useful. Create Appointment posts patientId, staffId, startDateTime, endDateTime, serviceType, and notes. Update Appointment sends appointmentId plus changed startDateTime, endDateTime, staffId, status, or notes. Delete Appointment sends appointmentId and optional hardDelete.',
  placeholder: 'getSchedules',
  example: 'getSchedules',
  defaultValue: 'getSchedules',
};

const fields: FieldDoc[] = [
  operationField,
  {
    name: 'Credential',
    internalKey: 'credentialId',
    type: 'string',
    required: false,
    description: 'Visible reference field for a saved ScheduleWise credential; runtime selects the saved schedulewise credential for the node rather than reading this ID directly.',
    helpText: richFieldHelp({
      what: 'A visible credential reference or note for the ScheduleWise connection.',
      why: 'The real runtime credential lookup uses the saved schedulewise credential attached through CtrlChecks Connections; this field is not the direct secret value.',
      when: 'Use it only as a reference in visual workflows. The actual connection must exist in the credential vault unless Mock Mode is on.',
      enter: 'Enter a credential label or ID such as cred_schedulewise_prod if your workflow builder uses one, but never paste the API key itself here.',
      source: 'Create the ScheduleWise API Key connection in Connections using apiUrl plus either accessToken or apiKey.',
      later: 'Successful calls return {{$json.success}}, {{$json.operation}}, {{$json.data}}, and {{$json.executionTimeMs}}; the credential ID is not returned.',
      format: 'Short text reference. Secrets belong in the credential vault, not this field.',
      example: 'A clinic workflow notes prod-schedulewise while the vault stores the real API key.',
      empty: 'Runtime can still use the saved schedulewise credential. Without a saved credential and with Mock Mode off, it returns NO_CREDENTIALS.',
      mistake: 'Pasting the ScheduleWise API key into credentialId and expecting runtime to authenticate with it.',
    }),
    placeholder: 'cred_schedulewise_prod',
    example: 'cred_schedulewise_prod',
  },
  {
    name: 'Date From',
    internalKey: 'dateFrom',
    type: 'string',
    required: false,
    description: 'Start date filter for Get Schedules.',
    helpText: richFieldHelp({
      what: 'The earliest appointment date included when Operation is Get Schedules.',
      why: 'Runtime adds it as dateFrom on the /appointments query string so ScheduleWise can narrow the result set.',
      when: 'Fill it for Get Schedules when you only want appointments from a specific day or range.',
      enter: 'Use a date such as 2026-07-20 or a full ISO timestamp such as 2026-07-20T00:00:00Z.',
      source: 'Map it from a form date picker, scheduler trigger, database row, or previous step as {{$json.startDate}}.',
      later: 'Matching appointments are returned in {{$json.data.schedules}} in mock mode, or the provider response under {{$json.data}} in live mode.',
      format: 'ISO 8601 date or date-time string.',
      example: 'A daily front-desk workflow sets Date From to {{$json.today}} to list today appointments.',
      empty: 'No lower date filter is sent; the provider may return more appointments than expected.',
      mistake: 'Using a local date format such as 20/07/2026 that the API may not parse consistently.',
    }),
    placeholder: '2026-07-20 or {{$json.startDate}}',
    example: '2026-07-20',
  },
  {
    name: 'Date To',
    internalKey: 'dateTo',
    type: 'string',
    required: false,
    description: 'End date filter for Get Schedules.',
    helpText: richFieldHelp({
      what: 'The latest appointment date included when Operation is Get Schedules.',
      why: 'Runtime adds it as dateTo on the ScheduleWise /appointments query string.',
      when: 'Fill it with Date From when you need a bounded day, week, or custom range.',
      enter: 'Use a date or ISO timestamp such as 2026-07-21T23:59:59Z.',
      source: 'Map it from a calendar range, report request, or upstream value such as {{$json.endDate}}.',
      later: 'Use {{$json.data.schedules}} or the provider-specific {{$json.data}} response to loop through returned appointments.',
      format: 'ISO 8601 date or date-time string.',
      example: 'A weekly care-team report maps Date To from {{$json.weekEnd}}.',
      empty: 'No upper date filter is sent; live API results may include later appointments.',
      mistake: 'Setting Date To earlier than Date From and then assuming the node failed instead of returning an empty provider result.',
    }),
    placeholder: '2026-07-21 or {{$json.endDate}}',
    example: '2026-07-21',
  },
  {
    name: 'Patient ID',
    internalKey: 'patientId',
    type: 'string',
    required: false,
    description: 'ScheduleWise patient identifier used for filters and appointment creation.',
    helpText: richFieldHelp({
      what: 'The patient record ID recognized by ScheduleWise.',
      why: 'Get Schedules can filter by patient, and Create Appointment sends patientId in the request body.',
      when: 'Fill it when listing one patient appointments or creating a patient appointment.',
      enter: 'Use the exact ID from ScheduleWise, such as patient_123, or map {{$json.patientId}} from intake data.',
      source: 'Find it in ScheduleWise patient records, an earlier lookup step, an intake form, or your patient database.',
      later: 'Mock responses include patientId under {{$json.data.schedules[0].patientId}} or {{$json.data.appointment.patientId}}.',
      format: 'Provider-specific text ID.',
      example: 'A reminder workflow filters schedules with patientId from a CRM patient record.',
      empty: 'No patient filter is sent for Get Schedules; Create Appointment may be rejected by the live API if patientId is required.',
      mistake: 'Entering the patient display name instead of the ScheduleWise patient ID.',
    }),
    placeholder: 'patient_123 or {{$json.patientId}}',
    example: 'patient_123',
  },
  {
    name: 'Staff ID',
    internalKey: 'staffId',
    type: 'string',
    required: false,
    description: 'ScheduleWise staff member identifier used for filters, creates, and updates.',
    helpText: richFieldHelp({
      what: 'The provider, clinician, employee, or staff record ID in ScheduleWise.',
      why: 'Get Schedules can filter by staff, Create Appointment assigns the appointment to staffId, and Update Appointment can change staffId.',
      when: 'Fill it when a workflow needs appointments for one staff member or creates/updates assigned staff.',
      enter: 'Use the exact ScheduleWise staff ID, or map it from {{$json.staffId}}.',
      source: 'Find it in the ScheduleWise staff profile, a previous lookup, or an internal routing table.',
      later: 'Use returned staff fields from {{$json.data}} to notify the assigned provider or branch by staff.',
      format: 'Provider-specific text ID.',
      example: 'A dental office maps staffId from the chosen hygienist before creating an appointment.',
      empty: 'No staff filter is sent for Get Schedules; Create Appointment may fail if the live API requires assigned staff.',
      mistake: 'Using a staff email or name when the API expects the internal staff ID.',
    }),
    placeholder: 'staff_456 or {{$json.staffId}}',
    example: 'staff_456',
  },
  {
    name: 'Appointment ID',
    internalKey: 'appointmentId',
    type: 'string',
    required: false,
    description: 'ScheduleWise appointment identifier required for Update Appointment and Delete Appointment.',
    helpText: richFieldHelp({
      what: 'The exact appointment record ID to update or delete.',
      why: 'Runtime builds /appointments/{appointmentId} for update and delete calls.',
      when: 'Required for Update Appointment and Delete Appointment.',
      enter: 'Map the ID returned by a prior Get Schedules/Create Appointment step, such as {{$json.data.appointment.id}}.',
      source: 'Use ScheduleWise appointment records, webhook payloads, database records, or earlier node output.',
      later: 'Delete mock output returns {{$json.data.deletedId}}, and update output returns the updated appointment under {{$json.data.appointment}}.',
      format: 'Provider-specific appointment ID text.',
      example: 'A cancellation workflow maps appointmentId from the patient portal cancellation request.',
      empty: 'Runtime still constructs a URL, but live ScheduleWise likely rejects or routes the request incorrectly.',
      mistake: 'Using patientId or staffId where appointmentId is required.',
    }),
    placeholder: 'appt_789 or {{$json.appointmentId}}',
    example: 'appt_789',
  },
  {
    name: 'Start Date/Time',
    internalKey: 'startDateTime',
    type: 'string',
    required: false,
    description: 'Appointment start time for Create Appointment and Update Appointment.',
    helpText: richFieldHelp({
      what: 'The appointment start date and time.',
      why: 'Create Appointment sends it in the request body, and Update Appointment can change the stored start time.',
      when: 'Fill it when booking a new appointment or rescheduling an existing one.',
      enter: 'Use an ISO timestamp with timezone, such as 2026-07-20T09:00:00Z, or map {{$json.startDateTime}}.',
      source: 'Use a form time slot, calendar selection, scheduling rule output, or previous ScheduleWise response.',
      later: 'The created or updated appointment response can be read from {{$json.data.appointment.startTime}} in mock mode or provider-specific data in live mode.',
      format: 'ISO 8601 date-time string with timezone.',
      example: 'A patient self-booking workflow maps the selected slot into Start Date/Time before creating the appointment.',
      empty: 'Live ScheduleWise may reject Create Appointment or leave the update unchanged if no start time is sent.',
      mistake: 'Sending a local time without timezone and accidentally booking the wrong hour.',
    }),
    placeholder: '2026-07-20T09:00:00Z or {{$json.startDateTime}}',
    example: '2026-07-20T09:00:00Z',
  },
  {
    name: 'End Date/Time',
    internalKey: 'endDateTime',
    type: 'string',
    required: false,
    description: 'Appointment end time for Create Appointment and Update Appointment.',
    helpText: richFieldHelp({
      what: 'The appointment end date and time.',
      why: 'It tells ScheduleWise how long the booking lasts and can be changed on update.',
      when: 'Fill it when creating an appointment or changing appointment duration.',
      enter: 'Use an ISO timestamp such as 2026-07-20T09:30:00Z or map {{$json.endDateTime}}.',
      source: 'Use duration logic, appointment type defaults, calendar selections, or upstream scheduling data.',
      later: 'Use returned end-time data from {{$json.data.appointment.endTime}} or live provider data for confirmations.',
      format: 'ISO 8601 date-time string with timezone.',
      example: 'A consultation workflow sets a 30-minute slot by mapping start and end date-time values from an availability step.',
      empty: 'Live ScheduleWise may reject create calls or keep the old end time on update.',
      mistake: 'Setting the end time before the start time.',
    }),
    placeholder: '2026-07-20T09:30:00Z or {{$json.endDateTime}}',
    example: '2026-07-20T09:30:00Z',
  },
  {
    name: 'Service Type',
    internalKey: 'serviceType',
    type: 'string',
    required: false,
    description: 'Type of service for a created appointment.',
    helpText: richFieldHelp({
      what: 'The appointment service category or visit type.',
      why: 'Create Appointment includes it so ScheduleWise and staff know what kind of work is being booked.',
      when: 'Fill it for Create Appointment when your clinic or team distinguishes consultation, follow-up, lab, intake, or other services.',
      enter: 'Use the exact service type expected by ScheduleWise or map {{$json.serviceType}} from a booking form.',
      source: 'Use the patient selection, internal service catalog, or appointment type mapping table.',
      later: 'Use returned serviceType in {{$json.data.appointment.serviceType}} for confirmation messages or routing.',
      format: 'Text value accepted by your ScheduleWise setup.',
      example: 'A clinic maps serviceType to follow-up when a patient books a post-visit check.',
      empty: 'Runtime sends undefined in create body; the live API may default it or reject the request.',
      mistake: 'Using a friendly label that ScheduleWise does not recognize instead of the configured service value.',
    }),
    placeholder: 'consultation or {{$json.serviceType}}',
    example: 'consultation',
  },
  {
    name: 'Notes',
    internalKey: 'notes',
    type: 'textarea',
    required: false,
    description: 'Optional appointment notes sent on create or update.',
    helpText: richFieldHelp({
      what: 'Free-text notes attached to the appointment.',
      why: 'Notes carry scheduling context, patient requests, or internal handling instructions.',
      when: 'Fill it when the booking, update, or cancellation context should be visible in ScheduleWise.',
      enter: 'Type a concise note or map {{$json.notes}} from an intake form.',
      source: 'Use form comments, call-center notes, CRM notes, or previous workflow summaries.',
      later: 'Returned appointment notes can be used in confirmation messages or staff notifications.',
      format: 'Plain text. Avoid sensitive health details unless your workflow and account permissions are approved for them.',
      example: 'A front-desk workflow sends Patient requested morning slot after a phone request.',
      empty: 'No notes are sent, or update leaves notes unchanged when omitted.',
      mistake: 'Putting operational secrets or unrelated internal comments into patient-facing appointment notes.',
    }),
    placeholder: 'Patient requested morning slot or {{$json.notes}}',
    example: 'Patient requested morning slot',
  },
  {
    name: 'Status',
    internalKey: 'status',
    type: 'select',
    required: false,
    description: 'Appointment status used by Update Appointment.',
    helpText: richFieldHelp({
      what: 'The appointment status value for an update.',
      why: 'Runtime includes status in the update body when Operation is Update Appointment.',
      when: 'Fill it when marking an appointment Confirmed, Pending, or Cancelled.',
      enter: 'Choose Confirmed for booked appointments, Pending for awaiting confirmation, or Cancelled when the appointment should no longer proceed.',
      source: 'Use workflow decisions, caller actions, patient responses, or staff approval steps.',
      later: 'Use {{$json.data.appointment.status}} in mock mode or provider response data to notify patients and staff.',
      format: 'Dropdown value: confirmed, pending, or cancelled.',
      example: 'A reminder workflow sets Status to Confirmed after the patient replies yes.',
      empty: 'No status value is sent on update, so the existing provider status may remain unchanged.',
      mistake: 'Trying to set status during Delete Appointment; delete uses appointmentId and hardDelete instead.',
    }),
    options: ['Confirmed', 'Pending', 'Cancelled'],
    notes: 'Confirmed means the slot is accepted and should stay booked. Pending means the appointment is tentative or waiting for confirmation. Cancelled means the appointment should be marked cancelled during an Update Appointment operation.',
    placeholder: 'confirmed',
    example: 'confirmed',
  },
  {
    name: 'Limit',
    internalKey: 'limit',
    type: 'number',
    required: false,
    description: 'Maximum appointment count requested by Get Schedules.',
    helpText: richFieldHelp({
      what: 'The maximum number of appointment records requested from ScheduleWise.',
      why: 'Runtime sends it as a limit query parameter for Get Schedules.',
      when: 'Fill it when you want to cap results for a list, report, or loop.',
      enter: 'Type a number such as 25, 50, or 100.',
      source: 'Use a workflow setting, report size, or upstream value like {{$json.limit}}.',
      later: 'Use returned {{$json.data.schedules}} or provider data in a Loop or Split In Batches step.',
      format: 'Positive number.',
      example: 'A morning desk workflow uses 50 to fetch the next fifty appointments for staff review.',
      empty: 'The panel default is 50; live provider defaults may vary if the field is omitted.',
      mistake: 'Using a very high limit in a time-sensitive workflow and making the API call slow.',
    }),
    placeholder: '50',
    example: '50',
    defaultValue: '50',
  },
  {
    name: 'Hard Delete',
    internalKey: 'hardDelete',
    type: 'boolean',
    required: false,
    description: 'When true, delete sends ?hardDelete=true.',
    helpText: richFieldHelp({
      what: 'A switch that requests permanent deletion for Delete Appointment.',
      why: 'Runtime appends ?hardDelete=true to the delete URL when this is on.',
      when: 'Turn it on only when the appointment must be permanently removed and recovery is not needed.',
      enter: 'Leave off for normal soft delete, or turn on for permanent removal if your ScheduleWise policy allows it.',
      source: 'Use compliance rules, admin approval, or an upstream boolean such as {{$json.hardDelete}}.',
      later: 'Mock delete output includes {{$json.data.permanent}} so later steps can log whether hard delete was requested.',
      format: 'Boolean switch true or false.',
      example: 'An admin-only cleanup workflow turns Hard Delete on for test appointments created in a sandbox.',
      empty: 'Default false means the request does not include hardDelete=true.',
      mistake: 'Turning it on for routine cancellations when a reversible cancellation or status update would be safer.',
    }),
    placeholder: 'false',
    example: 'false',
    defaultValue: 'false',
  },
  {
    name: 'Mock Mode',
    internalKey: 'mockMode',
    type: 'boolean',
    required: false,
    description: 'Return synthetic ScheduleWise data without calling the API.',
    helpText: richFieldHelp({
      what: 'A testing switch that bypasses the live ScheduleWise API.',
      why: 'When enabled, runtime returns predictable success responses and does not require a saved credential.',
      when: 'Turn it on while building, demoing, or testing workflow branches before live credentials are ready.',
      enter: 'Set true for test data and false for real ScheduleWise calls.',
      source: 'Use a workflow environment flag, manual test setting, or fixed boolean chosen in the panel.',
      later: 'Mock output still uses {{$json.success}}, {{$json.operation}}, {{$json.data}}, and {{$json.executionTimeMs}} so downstream mapping can be tested.',
      format: 'Boolean switch true or false.',
      example: 'A trainer turns Mock Mode on to show appointment creation without changing the real clinic calendar.',
      empty: 'Default false means runtime attempts the live API and requires credentials.',
      mistake: 'Leaving Mock Mode on in production and wondering why real appointments are not created.',
    }),
    placeholder: 'false',
    example: 'false',
    defaultValue: 'false',
  },
  {
    name: 'Timeout',
    internalKey: 'timeoutSec',
    type: 'number',
    required: false,
    description: 'HTTP request timeout in seconds.',
    helpText: richFieldHelp({
      what: 'How many seconds to wait for the ScheduleWise API before aborting.',
      why: 'Runtime uses this value with AbortController and returns TIMEOUT if the API does not respond in time.',
      when: 'Adjust it for slow reports, strict webhook response limits, or unreliable networks.',
      enter: 'Type a number of seconds such as 15, 30, or 60.',
      source: 'Choose from service reliability needs, workflow timeout policy, or a config step like {{$json.timeoutSec}}.',
      later: 'Timeout failures return success false with error.code TIMEOUT and executionTimeMs for logs.',
      format: 'Positive number of seconds.',
      example: 'A real-time patient portal uses 10 seconds so the caller is not left waiting too long.',
      empty: 'Runtime defaults to 30 seconds.',
      mistake: 'Typing milliseconds such as 30000 when this ScheduleWise field expects seconds.',
    }),
    placeholder: '30',
    example: '30',
    defaultValue: '30',
  },
  {
    name: 'Retries',
    internalKey: 'retries',
    type: 'number',
    required: false,
    description: 'Retry count for 5xx or network failures.',
    helpText: richFieldHelp({
      what: 'How many extra attempts runtime makes after certain temporary failures.',
      why: 'Runtime retries network errors and 5xx HTTP responses with exponential backoff.',
      when: 'Use it for background syncs where waiting a little longer is acceptable.',
      enter: 'Type 0 for no retries, 1 for one extra attempt, or a small number such as 3 for resilient background jobs.',
      source: 'Choose from workflow urgency, API rate limits, or an upstream setting like {{$json.retries}}.',
      later: 'Final failures return success false with error.code NETWORK_ERROR or HTTP_ERROR and executionTimeMs.',
      format: 'Whole number.',
      example: 'An overnight appointment sync uses 2 retries to ride through brief provider outages.',
      empty: 'Runtime defaults to 0 retries.',
      mistake: 'Using many retries in an interactive webhook workflow, causing the caller to wait too long.',
    }),
    placeholder: '0',
    example: '0',
    defaultValue: '0',
  },
  {
    name: 'Output Format',
    internalKey: 'outputFormat',
    type: 'select',
    required: false,
    description: 'Visible JSON/Raw selector. Runtime currently parses responses as JSON regardless of this value.',
    helpText: richFieldHelp({
      what: 'A visible selector for JSON or Raw output preference.',
      why: 'The field is present in the UI and schema, but runtime currently reads the provider response text and always JSON-parses it.',
      when: 'Leave JSON for current behavior. Treat Raw as a future/metadata option, not a real raw-response mode today.',
      enter: 'Choose JSON for normal workflows; Raw is visible but not honored by runtime.',
      source: 'Use the dropdown value from the panel or generated workflow config.',
      later: 'Successful live responses appear under {{$json.data}} after JSON parsing; parse failures return PARSE_ERROR.',
      format: 'Dropdown value JSON or Raw.',
      example: 'A reporting workflow leaves Output Format as JSON and reads {{$json.data.appointments}}.',
      empty: 'The default is JSON.',
      mistake: 'Choosing Raw and expecting plain response text; Output Format Raw is not honored today.',
    }),
    options: ['JSON', 'Raw'],
    notes: 'JSON is the actual current behavior. Raw is exposed in the panel but runtime still parses the response as JSON and returns PARSE_ERROR if parsing fails.',
    placeholder: 'json',
    example: 'json',
    defaultValue: 'json',
  },
];

const outputDescription = [
  'success: true when the operation completed, false when validation, credentials, HTTP, timeout, parse, or network handling failed.',
  'operation: The ScheduleWise operation that ran, such as getSchedules or createAppointment.',
  'data: Provider response data on success. Mock getSchedules returns schedules, totalCount, and nextPageToken; create/update returns appointment; delete returns deletedId and permanent.',
  'executionTimeMs: Elapsed runtime in milliseconds.',
  'error: Present on failure with code, message, and httpStatus. Known codes include INVALID_OPERATION, NO_CREDENTIALS, PARSE_ERROR, TIMEOUT, NETWORK_ERROR, and HTTP_ERROR.',
].join('\n');

export const schedulewiseDoc: NodeDoc = {
  slug: 'schedulewise',
  displayName: 'ScheduleWise',
  category: 'HTTP & API',
  logoUrl: '/icons/nodes/schedulewise.svg',
  description: 'Read, create, update, and delete ScheduleWise appointments through the ScheduleWise REST API, with mock mode for safe workflow testing.',
  credentialType: 'ScheduleWise API Key',
  credentialSetupSteps: [
    'Create a ScheduleWise API Key connection in Connections/credential vault before live runs. The credential can store API Base URL plus either an Access Token or API Key.',
    'The runtime looks up the saved schedulewise credential for this node. It accepts apiUrl/api_url, accessToken/access_token, or apiKey/api_key/value from the vault.',
    'Use an Access Token when your ScheduleWise account issues bearer tokens; use an API Key when the API expects X-Api-Key. Do not paste these secrets into normal workflow fields such as credentialId.',
    'Turn Mock Mode on to test mappings without a saved credential or live API call. Turn it off before production.',
    'Test the connection from Connections if available, then run Get Schedules with a small date range and verify {{$json.success}}, {{$json.operation}}, {{$json.data}}, and {{$json.executionTimeMs}}.',
    'Connect the ScheduleWise node output to the next node with an outgoing line; downstream service node account connection setup is still required for Slack, email, CRM, or database nodes that use the appointment data.',
  ],
  credentialDocsUrl: 'https://developer.schedulewise.com/',
  resources: [
    {
      name: 'Appointments',
      description: 'Manage ScheduleWise appointment records through the /appointments REST endpoint.',
      operations: [
        {
          name: 'Get Schedules',
          value: 'getSchedules',
          description: 'Retrieve ScheduleWise appointments with optional date, patient, staff, and limit filters. Runtime sends a GET request to /appointments and returns the provider response under data, or mock schedules when Mock Mode is on.',
          fields,
          outputExample: {
            success: true,
            operation: 'getSchedules',
            data: {
              schedules: [{ id: 'mock_sched_001', patientId: 'patient_123', staffId: 'staff_456', status: 'confirmed' }],
              totalCount: 1,
              nextPageToken: null,
            },
            executionTimeMs: 41,
          },
          outputDescription,
          usageExample: {
            scenario: 'List today appointments for one staff member before sending the schedule summary to an operations channel.',
            inputValues: {
              operation: 'getSchedules',
              credentialId: 'prod-schedulewise',
              dateFrom: '{{$json.dateFrom}}',
              dateTo: '{{$json.dateTo}}',
              patientId: '{{$json.patientId}}',
              staffId: '{{$json.staffId}}',
              appointmentId: '{{$json.appointmentId}}',
              startDateTime: '{{$json.startDateTime}}',
              endDateTime: '{{$json.endDateTime}}',
              serviceType: '{{$json.serviceType}}',
              notes: '{{$json.notes}}',
              status: 'confirmed',
              limit: '50',
              hardDelete: 'false',
              timeoutSec: '30',
              retries: '1',
              outputFormat: 'json',
              mockMode: 'false',
            },
            expectedOutput: 'Use {{$json.success}} to branch, {{$json.operation}} for logs, {{$json.data.schedules}} or provider {{$json.data}} for appointment records, and {{$json.error.code}} when success is false.',
          },
          externalDocsUrl: 'https://developer.schedulewise.com/',
        },
        {
          name: 'Create Appointment',
          value: 'createAppointment',
          description: 'Create a new ScheduleWise appointment by sending patientId, staffId, startDateTime, endDateTime, serviceType, and notes in a POST request to /appointments. Use this after an intake form, booking request, or staff-approved slot selection.',
          fields,
          outputExample: {
            success: true,
            operation: 'createAppointment',
            data: {
              appointment: { id: 'mock_appt_1042', patientId: 'patient_123', staffId: 'staff_456', status: 'confirmed' },
            },
            executionTimeMs: 58,
          },
          outputDescription,
          usageExample: {
            scenario: 'Book an appointment from a patient intake form after the workflow chooses an available staff member and time slot.',
            inputValues: {
              operation: 'createAppointment',
              credentialId: 'prod-schedulewise',
              dateFrom: '{{$json.dateFrom}}',
              dateTo: '{{$json.dateTo}}',
              patientId: '{{$json.patientId}}',
              staffId: '{{$json.staffId}}',
              appointmentId: '{{$json.appointmentId}}',
              startDateTime: '{{$json.startDateTime}}',
              endDateTime: '{{$json.endDateTime}}',
              serviceType: 'consultation',
              notes: 'Patient requested morning slot',
              status: 'confirmed',
              limit: '50',
              hardDelete: 'false',
              timeoutSec: '30',
              retries: '0',
              outputFormat: 'json',
              mockMode: 'false',
            },
            expectedOutput: 'Use {{$json.data.appointment.id}} in the confirmation message, {{$json.executionTimeMs}} for logs, and {{$json.error.code}} if success is false.',
          },
          externalDocsUrl: 'https://developer.schedulewise.com/',
        },
        {
          name: 'Update Appointment',
          value: 'updateAppointment',
          description: 'Update an existing ScheduleWise appointment by sending appointmentId in the URL and only the provided update fields in the request body. Use it to reschedule, change staff assignment, update notes, or mark an appointment Confirmed, Pending, or Cancelled.',
          fields,
          outputExample: {
            success: true,
            operation: 'updateAppointment',
            data: {
              appointment: { id: 'appt_789', staffId: 'staff_456', status: 'confirmed', notes: 'Patient confirmed by SMS' },
            },
            executionTimeMs: 63,
          },
          outputDescription,
          usageExample: {
            scenario: 'Mark an appointment confirmed after a patient replies yes to an automated reminder.',
            inputValues: {
              operation: 'updateAppointment',
              credentialId: 'prod-schedulewise',
              dateFrom: '{{$json.dateFrom}}',
              dateTo: '{{$json.dateTo}}',
              patientId: '{{$json.patientId}}',
              staffId: '{{$json.staffId}}',
              appointmentId: '{{$json.appointmentId}}',
              startDateTime: '{{$json.startDateTime}}',
              endDateTime: '{{$json.endDateTime}}',
              serviceType: '{{$json.serviceType}}',
              notes: 'Patient confirmed by SMS',
              status: 'confirmed',
              limit: '50',
              hardDelete: 'false',
              timeoutSec: '30',
              retries: '1',
              outputFormat: 'json',
              mockMode: 'false',
            },
            expectedOutput: 'Use {{$json.data.appointment.status}} to confirm the update and {{$json.error.code}} for INVALID_OPERATION, NO_CREDENTIALS, HTTP_ERROR, TIMEOUT, NETWORK_ERROR, or PARSE_ERROR handling.',
          },
          externalDocsUrl: 'https://developer.schedulewise.com/',
        },
        {
          name: 'Delete Appointment',
          value: 'deleteAppointment',
          description: 'Delete a ScheduleWise appointment by sending a DELETE request to /appointments/{appointmentId}. Leave Hard Delete off for normal deletion behavior, or turn it on only when the workflow should request permanent removal.',
          fields,
          outputExample: {
            success: true,
            operation: 'deleteAppointment',
            data: { deletedId: 'appt_789', permanent: false },
            executionTimeMs: 36,
          },
          outputDescription,
          usageExample: {
            scenario: 'Cancel a duplicate appointment after an operations review approves the removal.',
            inputValues: {
              operation: 'deleteAppointment',
              credentialId: 'prod-schedulewise',
              dateFrom: '{{$json.dateFrom}}',
              dateTo: '{{$json.dateTo}}',
              patientId: '{{$json.patientId}}',
              staffId: '{{$json.staffId}}',
              appointmentId: '{{$json.appointmentId}}',
              startDateTime: '{{$json.startDateTime}}',
              endDateTime: '{{$json.endDateTime}}',
              serviceType: '{{$json.serviceType}}',
              notes: 'Duplicate appointment removed after approval',
              status: 'cancelled',
              limit: '50',
              hardDelete: 'false',
              timeoutSec: '30',
              retries: '0',
              outputFormat: 'json',
              mockMode: 'false',
            },
            expectedOutput: 'Use {{$json.data.deletedId}} for the audit log, {{$json.data.permanent}} to record whether hard delete was requested, and {{$json.error.code}} when success is false.',
          },
          externalDocsUrl: 'https://developer.schedulewise.com/',
        },
      ],
    },
  ],
  commonErrors: [
    {
      error: 'INVALID_OPERATION',
      cause: 'Operation is missing or not one of getSchedules, createAppointment, updateAppointment, or deleteAppointment.',
      fix: 'Choose a supported operation from the dropdown and avoid display labels in generated workflow JSON.',
    },
    {
      error: 'NO_CREDENTIALS',
      cause: 'Mock Mode is off and the runtime could not find a saved schedulewise credential in the credential vault.',
      fix: 'Create a ScheduleWise API Key connection in Connections with apiUrl plus accessToken or apiKey, or turn Mock Mode on for testing.',
    },
    {
      error: 'PARSE_ERROR',
      cause: 'The live ScheduleWise response body could not be parsed as JSON. Output Format Raw is not honored; runtime still parses JSON today.',
      fix: 'Check the provider response, endpoint URL, and account environment. Keep Output Format on JSON until raw output is implemented.',
    },
    {
      error: 'TIMEOUT',
      cause: 'The API did not respond within timeoutSec seconds.',
      fix: 'Increase Timeout for slow background jobs, reduce response size with filters, or check provider availability.',
    },
    {
      error: 'NETWORK_ERROR',
      cause: 'Fetch failed after network, DNS, or connectivity trouble.',
      fix: 'Verify the ScheduleWise API base URL, network access, and temporary provider outage status.',
    },
    {
      error: 'HTTP_ERROR',
      cause: 'The provider returned a non-2xx HTTP response. Only 5xx responses are retried.',
      fix: 'Check credentials, permissions, required fields, appointmentId, patientId, staffId, and provider error message.',
    },
    {
      error: 'Credential ID is metadata only',
      cause: 'Runtime looks up the saved schedulewise credential by provider key, not by reading credentialId as the secret.',
      fix: 'Use Connections/credential vault for apiKey or accessToken and keep credentialId as a reference only.',
    },
  ],
  relatedNodes: ['webhook', 'http_request', 'google_calendar', 'slack_message'],
};
