import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const shopifyWebhookDocs = 'https://shopify.dev/docs/apps/build/webhooks/verify-deliveries';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Shopify connection ID. If blank, the active Shopify Admin API connection is used.',
    helpText: 'What this field means: Connection points to the saved Shopify Admin API credential (Store URL, Admin API access token, and App Client Secret/Webhook Signing Secret) CtrlChecks uses to create webhook subscriptions and validate deliveries. Why it matters: Without a resolvable connection, CtrlChecks has no Admin API token to register webhooks with and no signing secret to validate the X-Shopify-Hmac-Sha256 header on incoming deliveries. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Shopify connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save the Shopify Admin API Store URL, token, and client secret. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw Admin API token. Real workplace example: A merchant saves one Shopify Admin API connection for their store, and every Shopify Trigger node in the workspace reuses it. If it is empty or wrong: Empty falls back to the active Shopify connection; a missing or incomplete connection causes No Shopify shop domain found or No complete Shopify Trigger connection found. Common mistake: Saving the Admin API access token but forgetting the App Client Secret/Webhook Signing Secret — HMAC validation cannot work without it.',
    placeholder: 'Uses your active Shopify connection',
    example: 'shopify_api_key_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Shop Domain Filter',
    internalKey: 'shopDomain',
    type: 'string',
    required: false,
    description: 'Optional myshopify.com shop-domain filter. The saved connection Store URL is used when omitted.',
    helpText: 'What this field means: Shop Domain Filter restricts this trigger to webhook deliveries from one specific Shopify store. Why it matters: A connection can technically be reused across stores in some setups, and this filter keeps the wrong store\'s webhook traffic from starting the workflow. When to fill it: Leave it blank in almost every setup — the saved connection\'s Store URL is used automatically for both registration and filtering. Fill it only to override which store this specific node targets. What to enter: The bare myshopify.com domain, such as your-shop.myshopify.com, not a full https:// URL and not a custom storefront domain. Where the value comes from: Read it from the Shopify Admin URL bar, or from {{$json.shopDomain}} on a previous test event. How to use it later: The trigger output includes {{$json.shopDomain}} for logging or routing. Accepted format: Plain myshopify.com domain text. Real workplace example: An agency managing several client stores sets Shop Domain Filter on each workflow to keep client-a.myshopify.com traffic from ever reaching client-b\'s workflow. If it is empty or wrong: Empty uses the connection\'s Store URL; a mismatched domain silently ignores incoming events with Ignored Shopify shop. Common mistake: Pasting a custom domain (such as shop.example.com) instead of the underlying *.myshopify.com domain Shopify actually sends in webhook headers.',
    placeholder: 'my-store.myshopify.com',
    example: 'my-store.myshopify.com',
  },
  {
    name: 'Webhook Topics',
    internalKey: 'topics',
    type: 'string',
    required: false,
    description: 'Comma-separated Shopify webhook topics.',
    helpText: 'What this field means: Webhook Topics decides which Shopify Admin API webhook topics CtrlChecks actually subscribes to, and which of those are accepted afterward. Why it matters: This value drives both the real Shopify webhook subscription (CtrlChecks creates one webhook per topic listed) and the trigger\'s own filtering — a topic never listed here is never subscribed to at all. When to fill it: Keep the broad default while exploring; narrow it before production to only the topics this workflow actually needs, since Shopify counts each subscribed topic and unnecessary ones add noise. What to enter: Comma-separated Shopify topic names such as orders/create, orders/paid, customers/create, products/update, refunds/create, checkouts/create, app/uninstalled. Where the value comes from: Pick from Shopify\'s Admin API webhook topic list based on the store events your workflow should react to. How to use it later: Route with {{$json.eventType}} (topic with slashes replaced by underscores, such as orders_paid) or {{$json.topic}} (the raw topic with slashes). Accepted format: Comma-separated text. Real workplace example: orders/create, orders/paid for an order-fulfillment workflow; customers/create for a welcome-email workflow. If it is empty or wrong: Empty defaults to a broad set covering orders, customers, products, refunds, checkouts, and app uninstall. A typo\'d topic name causes Shopify webhook creation to fail for that topic specifically. Common mistake: Using underscores (orders_create) instead of the real Shopify topic format with a slash (orders/create).',
    placeholder: 'orders/create, orders/paid, customers/create',
    example: 'orders/create, orders/paid, customers/create',
  },
  {
    name: 'Financial Status',
    internalKey: 'financialStatus',
    type: 'string',
    required: false,
    description: 'Optional order financial status filter.',
    helpText: 'What this field means: Financial Status only lets order events whose payment status matches through to start the workflow. Why it matters: An order-related workflow (like triggering fulfillment) usually should only run once the order is actually paid, not the moment it is merely created. When to fill it: Fill it whenever downstream steps depend on payment state, such as only fulfilling paid orders. Leave it (Any) to accept orders regardless of payment status. What to enter: Choose from the dropdown: paid, pending, authorized, partially_paid, refunded, or voided. Where the value comes from: Match it to the Shopify order financial_status values relevant to your process. How to use it later: The trigger output includes {{$json.financialStatus}} for confirmation, logging, or further branching. Accepted format: One exact Shopify financial status value. Real workplace example: A fulfillment workflow sets Financial Status to paid so orders are only sent to the warehouse once payment clears. If it is empty or wrong: Empty (Any) accepts every financial status; a status that never matches an incoming order silently ignores it with Ignored Shopify financial status. Common mistake: Expecting this filter to apply to non-order topics such as customers/create or products/update — it only affects order-shaped payloads that include a financial_status field.',
    placeholder: 'paid',
    example: 'paid',
    options: ['paid', 'pending', 'authorized', 'partially_paid', 'refunded', 'voided'],
  },
  {
    name: 'Fulfillment Status',
    internalKey: 'fulfillmentStatus',
    type: 'string',
    required: false,
    description: 'Optional order fulfillment status filter.',
    helpText: 'What this field means: Fulfillment Status only lets order events whose shipping/fulfillment state matches through to start the workflow. Why it matters: A shipping-confirmation workflow should only run once an order is actually fulfilled, not at every order update. When to fill it: Fill it whenever the workflow should react to a specific fulfillment stage, such as sending a "your order shipped" email only when fulfilled. Leave it (Any) to accept orders regardless of fulfillment status. What to enter: Choose from the dropdown: fulfilled, partial, unfulfilled, or restocked. Where the value comes from: Match it to the Shopify order fulfillment_status values relevant to your process. How to use it later: The trigger output includes {{$json.fulfillmentStatus}} for confirmation, logging, or further branching. Accepted format: One exact Shopify fulfillment status value. Real workplace example: A shipping-notification workflow sets Fulfillment Status to fulfilled so customers are emailed only once their order actually ships. If it is empty or wrong: Empty (Any) accepts every fulfillment status; a status that never matches silently ignores the event with Ignored Shopify fulfillment status. Common mistake: Combining this with a topic like customers/create where there is no fulfillment_status field to match against at all.',
    placeholder: 'fulfilled',
    example: 'fulfilled',
    options: ['fulfilled', 'partial', 'unfulfilled', 'restocked'],
  },
  {
    name: 'Customer ID',
    internalKey: 'customerId',
    type: 'string',
    required: false,
    description: 'Optional Shopify customer ID filter.',
    helpText: 'What this field means: Customer ID restricts this trigger to events belonging to one specific Shopify customer. Why it matters: This turns a store-wide trigger into a focused watcher on a single, already-known customer account. When to fill it: Fill it only when you need a workflow tied to one specific customer, such as a VIP account monitor. Leave it blank for normal store-wide workflows. What to enter: The numeric Shopify customer ID, not the customer\'s name or email. Where the value comes from: Read {{$json.customerId}} from a previous test event, or find it in Shopify Admin under the customer\'s profile URL. How to use it later: The trigger output includes {{$json.customerId}}, {{$json.customerEmail}}, and {{$json.customerName}} for confirmation or logging. Accepted format: Numeric Shopify customer ID text. Real workplace example: An account manager watches only their top enterprise customer\'s ID so a Slack alert fires whenever that specific account places an order. If it is empty or wrong: Empty accepts events for any customer; an ID that never matches silently ignores the event with Ignored Shopify customer. Common mistake: Entering the customer\'s email address here instead of their numeric Shopify customer ID.',
    placeholder: '1234567890',
    example: '1234567890',
  },
  {
    name: 'Product ID',
    internalKey: 'productId',
    type: 'string',
    required: false,
    description: 'Optional Shopify product ID filter.',
    helpText: 'What this field means: Product ID restricts this trigger to events involving one specific Shopify product. Why it matters: This turns a store-wide trigger into a focused watcher on a single, already-known product, useful for inventory or pricing alerts on a hero SKU. When to fill it: Fill it only when you need a workflow tied to one specific product. Leave it blank for normal store-wide workflows. What to enter: The numeric Shopify product ID, not the product title or handle. Where the value comes from: Read {{$json.productId}} from a previous test event, or find it in the product\'s Shopify Admin URL. How to use it later: The trigger output includes {{$json.productId}} and {{$json.productTitle}} for confirmation or logging. Accepted format: Numeric Shopify product ID text. Real workplace example: A merchandising team watches their best-selling product\'s ID so low-stock alerts can be built around its order activity. If it is empty or wrong: Empty accepts events for any product; an ID that never matches silently ignores the event with Ignored Shopify product. Common mistake: Entering the product\'s handle/slug (such as blue-t-shirt) instead of its numeric Shopify product ID.',
    placeholder: '1234567890',
    example: '1234567890',
  },
  {
    name: 'Minimum Total Price',
    internalKey: 'minTotalPrice',
    type: 'number',
    required: false,
    description: 'Optional minimum order total filter.',
    helpText: 'What this field means: Minimum Total Price only lets order events whose total is at or above this amount through to start the workflow. Why it matters: It lets a workflow focus on high-value orders, such as flagging large purchases for manual review or VIP treatment. When to fill it: Fill it for a workflow that should ignore small routine orders and only react to big-ticket ones. Leave it blank to accept orders of any size. What to enter: A plain number in the store\'s currency, without a currency symbol, such as 100 for $100. Where the value comes from: Decide the threshold based on your store\'s typical order value and what counts as "high value" for your process. How to use it later: The trigger output includes {{$json.totalPrice}} and {{$json.currency}} so downstream steps can double-check the exact amount and currency. Accepted format: Plain number, no currency symbol or commas. Real workplace example: A fraud-review workflow sets Minimum Total Price to 500 so only orders of $500 or more are flagged for manual review. If it is empty or wrong: Empty accepts orders of any size; orders below the threshold are silently ignored with Ignored Shopify total. Common mistake: Typing a currency symbol or comma (such as $1,000) instead of a plain number (1000) — plain numbers only are accepted.',
    placeholder: '100',
    example: '100',
  },
  {
    name: 'Currency',
    internalKey: 'currency',
    type: 'string',
    required: false,
    description: 'Optional ISO currency filter.',
    helpText: 'What this field means: Currency only lets order events in one specific currency through to start the workflow. Why it matters: A multi-currency store can receive orders in several currencies; this keeps a currency-specific workflow (such as a regional fulfillment process) scoped correctly. When to fill it: Fill it for a store that sells in multiple currencies and this workflow should only react to one of them. Leave it blank to accept orders in any currency. What to enter: A lowercase ISO currency code such as usd, eur, or inr. Where the value comes from: Match it to the currencies your store actually transacts in, visible in Shopify Admin\'s order list. How to use it later: The trigger output includes {{$json.currency}} alongside {{$json.totalPrice}} so downstream steps can format amounts correctly. Accepted format: Lowercase 3-letter ISO currency code. Real workplace example: A store selling in both USD and EUR routes EUR orders to a different fulfillment workflow by setting Currency to eur on that workflow. If it is empty or wrong: Empty accepts orders in any currency; a currency that never matches silently ignores the event with Ignored Shopify currency. Common mistake: Using an uppercase or symbol form (USD or $) instead of the lowercase ISO code (usd) that Shopify actually sends.',
    placeholder: 'usd',
    example: 'usd',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional keyword filter for order, customer, product, ID, and status fields.',
    helpText: 'What this field means: Keyword Filter only lets events whose combined order name, customer email/name, product title, object ID, or status fields contain a word or phrase start the workflow. Why it matters: A busy store can produce a lot of webhook traffic; this keeps a workflow focused on a specific term without needing a second set of webhook subscriptions. When to fill it: Use it when the workflow should react only to a phrase such as a specific product name, VIP customer email, or status keyword. Leave it blank to accept every event matching the other filters. What to enter: A simple keyword or short phrase, not Shopify search syntax. Where the value comes from: Pick the label, customer name, product keyword, or status term your team cares about. How to use it later: The accepted event output still includes {{$json.text}}, {{$json.orderName}}, {{$json.customerEmail}}, {{$json.productTitle}} and the other normalized fields for downstream routing. Accepted format: Plain text, case-insensitive contains match across the combined fields. Real workplace example: wholesale starts only order/customer workflows whose name, email, or status mentions wholesale accounts. If it is empty or wrong: Empty accepts every event matching the other filters; a too-specific or misspelled filter causes Ignored Shopify event not matching this trigger. Common mistake: Expecting Shopify\'s advanced search syntax (such as financial_status:paid) here — this is a simple text contains filter, not Shopify search.',
    placeholder: 'VIP, wholesale, product title, customer email',
    example: 'wholesale',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Store Events',
  value: 'store_events',
  description: 'Starts the workflow when a Shopify Admin API webhook delivery for a subscribed topic (orders, customers, products, refunds, checkouts, or app uninstall) arrives, after validating the X-Shopify-Hmac-Sha256 signature.',
  fields,
  outputExample: {
    eventId: '820982911946154508',
    eventType: 'orders_paid',
    source: 'shopify',
    userId: '207119551',
    username: 'buyer@example.com',
    text: '#1001',
    timestamp: '2026-07-19T10:20:00.000Z',
    topic: 'orders/paid',
    shopDomain: 'my-store.myshopify.com',
    webhookId: '820982911946154508',
    apiVersion: '2025-10',
    objectId: '450789469',
    adminGraphqlApiId: 'gid://shopify/Order/450789469',
    orderId: '450789469',
    orderName: '#1001',
    orderNumber: '1001',
    financialStatus: 'paid',
    fulfillmentStatus: null,
    totalPrice: 125.5,
    subtotalPrice: 115.5,
    totalTax: 10,
    currency: 'usd',
    customerId: '207119551',
    customerEmail: 'buyer@example.com',
    customerName: 'Alex Morgan',
    productId: null,
    productTitle: null,
    variantId: null,
    inventoryItemId: null,
    checkoutId: null,
    cartToken: null,
    refundId: null,
    lineItems: [{ title: 'Blue T-Shirt', quantity: 1, price: '115.50' }],
    raw: {},
    trigger: 'shopify',
    workflow_id: 'workflow_123',
    node_id: 'shopify-trigger-1',
    sessionId: 'shopify_workflow_123_820982911946154508',
    _shopify: true,
  },
  outputDescription: 'eventId: webhook delivery ID, or the order/product ID as a fallback. eventType: the topic with slashes replaced by underscores, such as orders_paid. source: shopify. userId/username: the customer ID/email tied to the event when available. text: order name, product title, customer name/email, or a topic+id fallback. timestamp: the X-Shopify-Triggered-At header, or a payload timestamp field. topic: the raw Shopify topic with a slash, such as orders/paid. shopDomain/webhookId/apiVersion: delivery metadata from Shopify\'s webhook headers. objectId: the order/product/refund/checkout/customer ID this event is about. adminGraphqlApiId: the Shopify GraphQL global ID when the payload includes one. orderId/orderName/orderNumber/financialStatus/fulfillmentStatus/totalPrice/subtotalPrice/totalTax/currency: order-specific fields, null on non-order topics. customerId/customerEmail/customerName: customer identity, populated on most topics that reference a customer. productId/productTitle/variantId/inventoryItemId: product-specific fields, null on non-product topics. checkoutId/cartToken: checkout-specific fields, null otherwise. refundId: refund-specific field, null otherwise. lineItems: the order\'s line items array when present, otherwise null. raw: the original Shopify webhook payload. trigger/workflow_id/node_id/sessionId/_shopify: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Route a paid Shopify order to fulfillment and notify the warehouse in Slack',
    inputValues: {
      shopDomain: '',
      topics: 'orders/paid',
      financialStatus: 'paid',
      fulfillmentStatus: '',
      customerId: '',
      productId: '',
      minTotalPrice: '',
      currency: '',
      query: '',
    },
    expectedOutput: 'A normalized Shopify order payload available as {{$json.orderId}}, {{$json.customerEmail}}, {{$json.totalPrice}}, and {{$json.lineItems}} for a fulfillment or Slack notification node.',
  },
  externalDocsUrl: 'https://shopify.dev/docs/api/admin-rest/latest/resources/webhook',
};

export const shopifyTriggerDoc: NodeDoc = {
  slug: 'shopify_trigger',
  displayName: 'Shopify Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Shopify.svg',
  description: 'Start a workflow from signed Shopify webhook events for orders, customers, products, checkouts, refunds, and app uninstall events.',
  credentialType: 'Shopify Admin API',
  credentialSetupSteps: [
    'In Shopify Admin, create or open a custom app with Admin API access (Settings -> Apps and sales channels -> Develop apps).',
    'Grant the app access to the topics you want to subscribe to, such as orders, customers, products, refunds, and checkouts.',
    'Copy the Store URL, Admin API access token, and the app\'s Client Secret/Webhook Signing Secret.',
    'In CtrlChecks, open Connections -> Add Connection -> Shopify and save the Store URL, Admin API Access Token, and App Client Secret / Webhook Signing Secret (the secret is required for HMAC validation).',
    'Choose the Shopify webhook topics this workflow should receive on the Webhook Topics field, then save and activate the workflow.',
    'CtrlChecks creates the Shopify webhook subscriptions automatically (one per topic) and validates every delivery with X-Shopify-Hmac-Sha256 against your stored secret — no manual webhook setup in Shopify Admin is required.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Shopify connection only authorizes reading/registering webhooks, not the Slack, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: shopifyWebhookDocs,
  resources: [
    {
      name: 'Webhook Events',
      description: 'Receive Shopify webhook deliveries signed with X-Shopify-Hmac-Sha256.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'No Shopify shop domain found. Save a Shopify Admin API connection with Store URL first.',
      cause: 'Neither the saved Shopify connection nor the Shop Domain Filter field has a usable store domain.',
      fix: 'Save a Shopify Admin API connection with a valid Store URL in Connections, then re-activate the workflow.',
    },
    {
      error: 'No complete Shopify Trigger connection found. Save a Shopify Admin API connection with Admin API token and app client secret/webhook signing secret.',
      cause: 'The saved Shopify connection is missing the Admin API access token or the App Client Secret/Webhook Signing Secret.',
      fix: 'Open the Shopify connection in Connections and fill in the missing Admin API Access Token or App Client Secret / Webhook Signing Secret.',
    },
    {
      error: 'Invalid Shopify webhook signature.',
      cause: 'The X-Shopify-Hmac-Sha256 header did not match the stored webhook secret, or the raw body was altered before validation.',
      fix: 'Confirm the App Client Secret / Webhook Signing Secret on the connection matches the Shopify app, then re-register the webhook subscriptions by saving the active workflow again.',
    },
    {
      error: 'Ignored non-actionable Shopify payload.',
      cause: 'The delivery had no recognizable topic, such as a connectivity test.',
      fix: 'No action needed for test pings; confirm Webhook Topics if you expected a real workflow run.',
    },
    {
      error: 'Ignored Shopify event not matching this trigger.',
      cause: 'The event was valid, but Webhook Topics, Shop Domain Filter, Financial Status, Fulfillment Status, Customer ID, Product ID, Currency, Minimum Total Price, or Keyword Filter filtered it out.',
      fix: 'Broaden the relevant filter, clear filters temporarily, trigger a fresh Shopify test event, then narrow the filters again after confirming the output.',
    },
    {
      error: 'Shopify API error (401/403/422): ...',
      cause: 'The Admin API access token is invalid, lacks the required topic permissions, or the request body was rejected by Shopify.',
      fix: 'Confirm the Admin API token scopes cover the topics you selected, then save the workflow again to retry registration.',
    },
    {
      error: 'Shopify webhook creation for topic "..." did not return a webhook id.',
      cause: 'Shopify accepted the request but did not return webhook data for that specific topic, often because the app lacks permission for it.',
      fix: 'Check the custom app\'s Admin API scopes cover that topic\'s resource, then save the workflow again to retry.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Shopify webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Shopify must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'Shopify Trigger node not found in this workflow.',
      cause: 'The webhook URL points to a node ID that is missing, renamed incorrectly, or no longer has type shopify_trigger.',
      fix: 'Save the workflow with the Shopify Trigger node still present, then re-register the webhooks so fresh subscriptions are created.',
    },
    {
      error: 'Next node cannot find Shopify trigger fields',
      cause: 'A downstream node is mapped to a field only present for another topic family, such as expecting {{$json.productTitle}} on an orders/create event.',
      fix: 'Use {{$json.topic}} or {{$json.eventType}} to branch by topic family before mapping topic-specific fields.',
    },
    {
      error: 'Permission denied after Shopify Trigger',
      cause: 'The trigger fired correctly, but the downstream Shopify action, Slack, email, or fulfillment node lacks its own account connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Shopify Admin API token has write access if the action needs to update the store.',
    },
  ],
  relatedNodes: ['shopify', 'stripe_trigger', 'webhook'],
};
