import type { NodeDoc } from '../types';

export const slackMessageDoc: NodeDoc = {
  slug: 'slack_message',
  displayName: 'Slack',
  category: 'Communication',
  logoUrl: '/icons/nodes/slack_message.svg',
  description: 'Send messages using a Slack app/bot connection.',
  credentialType: 'Slack OAuth2',
  credentialSetupSteps: [
    'What this is: A Slack OAuth2 connection lets CtrlChecks post messages through your Slack app/bot without storing tokens in workflow fields.',
    'Where to start: Create or select a Slack app at api.slack.com/apps, then open OAuth & Permissions.',
    'Add the Bot Token Scope chat:write. Add channels:read or users:read only if your workspace setup needs channel or user lookup.',
    'Install the app to your workspace and connect it in CtrlChecks through Connections -> Add Connection -> Slack.',
    'Invite the bot to private channels before sending messages: /invite @YourBotName.',
    'Use the Slack node for bot/API messages, channel targeting, and optional Block Kit payloads. Use Slack Webhook for a saved Incoming Webhook URL.',
  ],
  credentialDocsUrl: 'https://api.slack.com/authentication',
  resources: [
    {
      name: 'Configuration',
      description: 'Slack sends through the selected Slack OAuth2 connection.',
      operations: [
        {
          name: 'Execute',
          value: 'default',
          description: 'Send a message to a Slack channel or direct message with chat.postMessage.',
          fields: [
            {
              name: 'Channel',
              internalKey: 'channel',
              type: 'string',
              required: false,
              description: 'Slack channel name, channel ID, or user ID. Required when using OAuth bot sending.',
              helpText: 'Use #general, a channel ID like C01234567, or a user ID. Channel IDs are safer when channels may be renamed.',
              placeholder: '#general',
              example: '#deployments',
            },
            {
              name: 'Message',
              internalKey: 'message',
              type: 'textarea',
              required: true,
              description: 'Message text to send to Slack.',
              helpText: 'Slack supports simple formatting such as *bold*, _italic_, `code`, and line breaks. Use this as fallback text when sending Blocks.',
              placeholder: 'Deployment complete for {{$json.version}}',
              example: 'Deployment complete for {{$json.version}}',
            },
            {
              name: 'Blocks',
              internalKey: 'blocks',
              type: 'json',
              required: false,
              description: 'Optional Slack Block Kit JSON array.',
              helpText: 'Paste a Block Kit JSON array from app.slack.com/block-kit-builder. The message field remains the notification fallback text.',
              placeholder: '[{"type":"section","text":{"type":"mrkdwn","text":"Hello"}}]',
              example: '[{"type":"section","text":{"type":"mrkdwn","text":"Hello"}}]',
            },
            {
              name: 'Bot Name',
              internalKey: 'username',
              type: 'string',
              required: false,
              description: 'Optional sender name override, if the Slack app allows customized bot messages.',
              placeholder: 'CtrlChecks Bot',
            },
            {
              name: 'Icon Emoji',
              internalKey: 'iconEmoji',
              type: 'string',
              required: false,
              description: 'Optional sender icon emoji override, if the Slack app allows customized bot messages.',
              placeholder: ':rocket:',
            },
          ],
          outputExample: {
            id: '1704067200.123456',
            status: 'sent',
            provider: 'slack',
            ok: true,
            channel: 'C01234ABCDE',
            ts: '1704067200.123456',
            message: 'Deployment complete',
          },
          outputDescription: 'id/ts identify the Slack message. channel is the Slack channel returned by chat.postMessage. status is sent or failed.',
          usageExample: {
            scenario: 'Alert the deployments channel when a workflow completes',
            inputValues: {
              channel: '#deployments',
              message: 'Deploy complete for `{{$json.version}}` at {{$now}}',
            },
            expectedOutput: 'The message appears in the target channel from the connected Slack bot.',
          },
          externalDocsUrl: 'https://api.slack.com/methods/chat.postMessage',
        },
      ],
    },
  ],
  commonErrors: [
    {
      error: 'channel_not_found',
      cause: 'The bot is not in the channel, or the channel value is incorrect.',
      fix: 'Invite the bot to the channel or use the channel ID from Slack channel details.',
    },
    {
      error: 'not_authed',
      cause: 'The selected Slack OAuth2 connection is missing, expired, or not injected.',
      fix: 'Reconnect Slack in CtrlChecks Connections and select that connection on the node.',
    },
    {
      error: 'invalid_blocks',
      cause: 'The Blocks field is not valid Slack Block Kit JSON.',
      fix: 'Validate the JSON array in Slack Block Kit Builder and keep Message filled as fallback text.',
    },
  ],
  relatedNodes: ['slack_webhook'],
};
