import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const slackEventsDocs = 'https://api.slack.com/apis/connections/events-api';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Slack OAuth2 connection ID. If blank, the active Slack connection is used.',
    helpText: 'What this field means: Connection points to the saved Slack OAuth2 workspace connection (bot token and app Signing Secret) CtrlChecks uses to verify your Slack app and validate incoming request signatures. Why it matters: CtrlChecks uses this connection to confirm the bot token still works (via Slack\'s auth.test) during registration and to read the Signing Secret used to validate every incoming Slack request. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Slack connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you complete Slack OAuth2 sign-in. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw bot token. Real workplace example: A support team connects one Slack workspace, and every Slack Trigger node in the workspace reuses that connection. If it is empty or wrong: Empty falls back to the active Slack connection; a wrong or missing connection can cause No active Slack connection found or Selected connection is not a Slack connection. Common mistake: Pasting a Slack bot token into a normal workflow field instead of connecting Slack in Connections.',
    placeholder: 'Uses your active Slack connection',
    example: 'slack_oauth_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated events to accept.',
    helpText: 'What this field means: Event Types decides which kinds of Slack callbacks (Events API messages, slash commands, and interactivity payloads) this trigger accepts. Why it matters: App mentions, plain messages, slash commands, and button/modal interactions usually need very different workflows. When to fill it: Keep the default while testing; narrow it before production so unrelated Slack activity does not start the workflow. What to enter: Comma-separated values such as app_mention, message, slash_command, interaction. Aliases such as mention, dm, command, interactive, block_action, shortcut, and view_submission are also accepted, and interaction also matches the more specific interaction.block_actions, interaction.message_action, interaction.shortcut, and interaction.view_submission subtypes. Where the value comes from: Decide which Slack Events API subscriptions, slash commands, and interactivity features your Slack app is configured to send. How to use it later: Route with {{$json.eventType}}; interaction covers all interactivity payload subtypes unless you list a specific one. Accepted format: Comma-separated text, matched case-insensitively. Real workplace example: app_mention, message for an AI Slack assistant; slash_command for a /support command workflow; interaction for a workflow reacting to button clicks. If it is empty or wrong: Empty defaults to app_mention, message, slash_command, interaction. Unsupported values cause matching events to be ignored with no workflow execution. Common mistake: Subscribing to message without narrowing Allowed Channel IDs — this can make the workflow start on every message in every channel the bot is in.',
    placeholder: 'app_mention, message, slash_command, interaction',
    defaultValue: 'app_mention, message, slash_command, interaction',
    example: 'app_mention, message',
  },
  {
    name: 'Allowed Channel IDs',
    internalKey: 'channelIds',
    type: 'string',
    required: false,
    description: 'Optional Slack channel allowlist.',
    helpText: 'What this field means: Allowed Channel IDs restricts this trigger to events from specific Slack channels. Why it matters: One Slack app callback URL can receive events from every channel the bot is in; this keeps a channel-specific workflow from reacting to unrelated channels. When to fill it: Use this when one Slack app callback URL receives events from several channels but this workflow should handle only some of them. Leave it blank to accept events from any channel routed to this app. What to enter: Comma-separated Slack channel IDs such as C0123456789, not the #channel-name. Where the value comes from: Right-click the channel in Slack -> View channel details -> copy the Channel ID at the bottom, or read {{$json.channelId}} from a previous test event. How to use it later: The trigger output includes {{$json.channelId}} and {{$json.chatId}} for replies. Accepted format: Comma-separated text. Real workplace example: An IT support bot scopes to the #it-support channel ID only, so casual chatter in other channels never starts the workflow. If it is empty or wrong: Empty allows every channel; a channel ID that never matches silently ignores the event with Ignored Slack event from a channel that is not allowed. Common mistake: Typing the channel name (such as #it-support) instead of its Channel ID (such as C0123456789).',
    placeholder: 'C0123456789, C9876543210',
    example: 'C0123456789',
  },
  {
    name: 'Allowed User IDs',
    internalKey: 'allowedUserIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated Slack user IDs allowed to trigger this workflow.',
    helpText: 'What this field means: Allowed User IDs limits the trigger to specific Slack members. Why it matters: It can keep a testing or sensitive workflow from reacting to messages or commands from anyone other than approved people. When to fill it: Use it for internal testing, approved reviewers, or a controlled rollout. Leave it blank for a normal bot that should respond to any workspace member. What to enter: Comma-separated Slack user IDs such as U0123456789, not the person\'s display name. Where the value comes from: Read {{$json.userId}} from a previous test event sent by that person, or check their Slack profile\'s "Copy member ID" option. How to use it later: The accepted event output still includes {{$json.userId}} and {{$json.username}} for replies or audits. Accepted format: Comma-separated text. Real workplace example: Before launching an HR bot workspace-wide, the team allows only two HR staff user IDs so they can test without responding to everyone. If it is empty or wrong: Empty allows every matching user; a user ID that never matches silently ignores that person\'s activity with Ignored Slack event from a user that is not allowed. Common mistake: Using the person\'s display name or @handle instead of their Slack user ID.',
    placeholder: 'U0123456789, U9876543210',
    example: 'U0123456789',
  },
  {
    name: 'Slash Command Filter',
    internalKey: 'commandFilter',
    type: 'string',
    required: false,
    description: 'Optional slash command filter.',
    helpText: 'What this field means: Slash Command Filter only accepts one exact slash command when the trigger receives slash_command events. Why it matters: A single Slack app callback URL can serve several different slash commands (such as /support and /status); this keeps each workflow scoped to the command it actually handles. When to fill it: Fill it whenever the same Slack app has more than one slash command pointed at this trigger URL. Leave it blank if this trigger only ever receives one slash command, or if Event Types does not include slash_command at all. What to enter: The exact command text including the leading slash, such as /support. Where the value comes from: Match it to the command name configured in Slack app settings -> Slash Commands. How to use it later: The trigger output includes {{$json.command}} and {{$json.text}} (the text typed after the command) for downstream use. Accepted format: Plain text starting with /. Real workplace example: /support and /feedback both point at CtrlChecks; one workflow sets Slash Command Filter to /support so only that command reaches it. If it is empty or wrong: Empty accepts any slash command that reaches this trigger; a value that never matches the incoming command silently ignores it with Ignored Slack slash command because it did not match the configured command. Common mistake: Leaving off the leading slash (typing support instead of /support) — Slack always sends the command with the slash included.',
    placeholder: '/support',
    example: '/support',
  },
  {
    name: 'Workspace Team ID',
    internalKey: 'teamId',
    type: 'string',
    required: false,
    description: 'Optional Slack workspace/team ID filter.',
    helpText: 'What this field means: Workspace Team ID restricts this trigger to events from one specific Slack workspace. Why it matters: If your Slack app is installed into multiple workspaces, this keeps a workspace-specific workflow from reacting to another workspace\'s activity. When to fill it: Fill it only if your Slack app is installed into more than one workspace and this workflow should only react to one of them. Leave it blank for a single-workspace app. What to enter: The Slack workspace/team ID, such as T0123456789, not the workspace name. Where the value comes from: Read {{$json.teamId}} from a previous test event, or find it in your Slack app\'s installed-workspace settings. How to use it later: The trigger output includes {{$json.teamId}} for logging or routing. Accepted format: Slack team ID text starting with T. Real workplace example: A vendor\'s Slack app installed into two customer workspaces scopes one workflow to Customer A\'s team ID only. If it is empty or wrong: Empty accepts events from any workspace; a team ID that never matches silently ignores the event with Ignored Slack event for a different workspace. Common mistake: Entering the workspace\'s display name (such as Acme Corp) instead of its team ID.',
    placeholder: 'T0123456789',
    example: 'T0123456789',
  },
  {
    name: 'Signing Secret',
    internalKey: 'signingSecret',
    type: 'string',
    required: false,
    description: 'Optional Slack app signing secret fallback. Prefer storing it on the Slack connection or worker env.',
    helpText: 'What this field means: Signing Secret is a fallback place to store the Slack app\'s signing secret directly on this node, used only if the saved connection and worker environment variable do not already have one. Why it matters: CtrlChecks needs the exact Slack app signing secret to validate the X-Slack-Signature header on every incoming request; without it, signature validation cannot succeed. When to fill it: Leave it blank in almost every setup — save the signing secret on the Slack connection in Connections instead, which is reusable across every Slack Trigger node. Fill it here only as a last-resort override for one specific node. What to enter: The exact Signing Secret string from Slack app settings -> Basic Information -> App Credentials -> Signing Secret. Where the value comes from: Copy it directly from your Slack app\'s Basic Information page in api.slack.com/apps. How to use it later: This is setup-only and is never emitted as {{$json.signingSecret}} to downstream nodes. Accepted format: Plain secret text; the visual field uses a standard text control even though the value should be treated as secret material. Real workplace example: A team temporarily sets Signing Secret here while debugging a connection issue, then removes it once the Slack connection itself is fixed. If it is empty or wrong: Empty falls back to the connection\'s signing secret, then the worker\'s SLACK_SIGNING_SECRET environment variable; if none resolve, real Slack requests fail with Invalid Slack webhook signature. Common mistake: Confusing this with the Slack bot token (which starts with xoxb-) — the signing secret is a separate value from Basic Information, not App Credentials\' bot token.',
    placeholder: 'Prefer saving this on the Slack connection',
    example: 'a1b2c3d4e5f6',
    notes: 'The visual config field uses a standard text control because password is not a supported node panel field type, but the value should still be treated as secret material.',
  },
  {
    name: 'Validate Slack Signature',
    internalKey: 'validateSignature',
    type: 'boolean',
    required: false,
    description: 'Validates X-Slack-Signature and X-Slack-Request-Timestamp.',
    helpText: 'What this field means: Validate Slack Signature checks that Slack itself signed the incoming request using your app\'s signing secret, and that the request timestamp is recent. Why it matters: A public webhook URL should reject requests that did not come through Slack, and reject old/replayed requests. When to fill it: Keep it enabled for production. Disable only for a controlled local test where you cannot generate a real Slack signature. What to enter: true/enabled for real workflows; false/disabled only for temporary debugging. Where the value comes from: This is a security choice made by the workflow owner or admin. The signing secret itself comes from the Slack connection, this node\'s Signing Secret field, or the worker\'s SLACK_SIGNING_SECRET environment variable. How to use it later: This setting protects whether a workflow starts; it is not output as {{$json.validateSignature}}. Accepted format: Boolean checkbox. Real workplace example: A live Slack support bot keeps validation enabled so only genuine, recent Slack requests can create replies or tickets. If it is empty or wrong: Default true requires a resolvable signing secret and a request timestamp within about 5 minutes of the current time; if either check fails, requests fail with Invalid Slack webhook signature. Common mistake: Turning this off permanently instead of correctly saving the Signing Secret on the connection.',
    defaultValue: 'true',
    example: 'true',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive event',
  value: 'receive',
  description: 'Starts the workflow when an accepted Slack Events API callback, slash command, or interactivity payload arrives, after validating the X-Slack-Signature HMAC and a fresh request timestamp.',
  fields,
  outputExample: {
    eventId: 'Ev0123ABCDE',
    eventType: 'app_mention',
    source: 'slack',
    userId: 'U0123456789',
    username: '',
    text: '<@UAPPBOT> can you check this order?',
    timestamp: '2026-07-19T10:20:00.000Z',
    teamId: 'T0123456789',
    enterpriseId: null,
    channelId: 'C0123456789',
    channelName: '',
    chatId: 'C0123456789',
    threadTs: '1784260800.000100',
    messageTs: '1784260800.000100',
    command: '',
    triggerId: '',
    responseUrl: '',
    callbackId: '',
    actionId: '',
    interactionType: '',
    raw: {},
    trigger: 'slack',
    workflow_id: 'workflow_123',
    node_id: 'slack-trigger-1',
    sessionId: 'slack_workflow_123_T0123456789_1784260800.000100',
    _slack: true,
  },
  outputDescription: 'eventId: Slack event_id, message ts, or a generated fallback depending on event type. eventType: app_mention, message, slash_command, interaction (or a specific interaction.block_actions/message_action/shortcut/view_submission subtype), or url_verification. source: slack. userId/username: the Slack member behind the event when available. text: message text, slash command text, or interaction value/title. timestamp: ISO event time. teamId/enterpriseId: workspace and (if applicable) Enterprise Grid identifiers. channelId/channelName/chatId: channel identity for replies; chatId always equals channelId. threadTs/messageTs: thread and message timestamps for threaded replies. command/triggerId/responseUrl: populated only for slash_command events. callbackId/actionId/interactionType: populated only for interaction events. raw: the original Slack payload (or parsed interaction payload). trigger/workflow_id/node_id/sessionId/_slack: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Reply to a Slack app mention with an AI Agent in the same thread',
    inputValues: {
      eventTypes: 'app_mention, message',
      channelIds: '',
      allowedUserIds: '',
      commandFilter: '',
      teamId: '',
      signingSecret: '',
      validateSignature: 'true',
    },
    expectedOutput: 'Use {{$json.channelId}} as the Slack Message channel and {{$json.threadTs}} as Thread Timestamp to reply in the same thread.',
  },
  externalDocsUrl: 'https://api.slack.com/events-api',
};

export const slackTriggerDoc: NodeDoc = {
  slug: 'slack_trigger',
  displayName: 'Slack Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Slack.svg',
  description: 'Start workflows from real-time Slack Events API, slash command, and interaction callbacks.',
  credentialType: 'Slack OAuth2',
  credentialSetupSteps: [
    'Create or open your Slack app at api.slack.com/apps.',
    'Add bot scopes for the events you need: chat:write, app_mentions:read, channels:history, groups:history, im:history, mpim:history, and commands.',
    'Install the app to your workspace, then connect Slack in CtrlChecks Connections (tested against https://slack.com/api/auth.test).',
    'Copy the app Signing Secret from Slack app settings -> Basic Information -> App Credentials and save it on the Slack connection, or set SLACK_SIGNING_SECRET on the worker.',
    'In Slack Event Subscriptions, Slash Commands, and Interactivity & Shortcuts settings, use this workflow trigger\'s generated webhook URL as the callback URL — Slack will send a url_verification challenge that CtrlChecks answers automatically.',
    'Subscribe to app_mention and message events as needed, and invite the bot to any private channel it should read or reply in.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Slack connection only authorizes verifying/replying through the bot, not the CRM, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: slackEventsDocs,
  resources: [
    {
      name: 'Webhook',
      description: 'Receives Slack signed webhook callbacks and emits a normalized event payload.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Invalid Slack webhook signature.',
      cause: 'The signing secret is missing or wrong, the X-Slack-Signature header did not match, or the request timestamp is older than about five minutes.',
      fix: 'Save the Slack app Signing Secret on the Slack connection (or set SLACK_SIGNING_SECRET on the worker), then retry from Slack.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'A valid, signed Slack request arrived, but the workflow has not been activated.',
      fix: 'Activate the workflow in CtrlChecks, then resend or wait for the next real Slack event.',
    },
    {
      error: 'Slack webhook received, no events matched this trigger.',
      cause: 'The request was valid, but Event Types, Allowed Channel IDs, Allowed User IDs, Workspace Team ID, or Slash Command Filter filtered it out.',
      fix: 'Broaden Event Types or clear filters temporarily, send a fresh Slack test event, then narrow the filters again after confirming the output.',
    },
    {
      error: 'No active Slack connection found. Create one in Connections first.',
      cause: 'The workflow owner has not connected Slack, or the saved connection expired.',
      fix: 'Reconnect Slack in CtrlChecks -> Connections, then activate the workflow again.',
    },
    {
      error: 'Selected connection is not a Slack connection.',
      cause: 'The saved connection ID points to another provider or an inactive credential.',
      fix: 'Select a Slack OAuth2 connection or leave Connection blank so CtrlChecks can use the active Slack connection.',
    },
    {
      error: 'channel_not_found (from a downstream Slack Message reply)',
      cause: 'The Slack bot is not a member of the target channel, or the workflow is replying to the wrong channel ID.',
      fix: 'Invite the bot to the Slack channel and map {{$json.channelId}} into the Slack Message node\'s channel field.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Slack webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Slack must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'Next node cannot find Slack trigger fields',
      cause: 'The next step is mapped to a field that is only present for another event type, such as {{$json.command}} on an app_mention event or {{$json.callbackId}} on a plain message.',
      fix: 'Use {{$json.eventType}} to branch by event family before mapping event-specific fields.',
    },
    {
      error: 'Permission denied after Slack Trigger',
      cause: 'The trigger received the event, but the downstream Slack Message, CRM, email, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node account connection and make sure the Slack bot has chat:write and any channel-specific permission the action needs.',
    },
  ],
  relatedNodes: ['slack_message', 'ai_agent'],
};
