import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const stripeWebhookDocs = 'https://docs.stripe.com/webhooks';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Stripe connection ID. If blank, the active Stripe Secret Key connection is used.',
    helpText: 'What this field means: Connection points to the saved Stripe Secret Key credential CtrlChecks uses to create the webhook endpoint on your Stripe account. Why it matters: CtrlChecks needs a working Stripe secret key to call Stripe\'s API and register a webhook endpoint that Stripe will call back to. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Stripe connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save a Stripe Secret Key. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw sk_live_/sk_test_ key. Real workplace example: A merchant saves one Stripe connection for their account, and every Stripe Trigger node in the workspace reuses it. If it is empty or wrong: Empty falls back to the active Stripe connection; a missing or invalid connection causes No active Stripe connection found. Common mistake: Pasting a raw Stripe secret key into a normal workflow field instead of saving it under Connections.',
    placeholder: 'Uses your active Stripe connection',
    example: 'stripe_api_key_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated Stripe event type names.',
    helpText: 'What this field means: Event Types decides which Stripe webhook events CtrlChecks actually subscribes to when it creates the webhook endpoint, and which of those are accepted afterward. Why it matters: This value drives both the real Stripe webhook subscription (only listed event types are ever delivered) and the trigger\'s own filtering. When to fill it: Keep the broad default while exploring; narrow it before production to only the events this workflow actually needs. What to enter: Comma-separated exact Stripe event names such as checkout.session.completed, payment_intent.succeeded, invoice.payment_succeeded, customer.subscription.created, charge.refunded. Where the value comes from: Pick from Stripe\'s event type list (docs.stripe.com/api/events/types) based on what your workflow should react to. How to use it later: Route with {{$json.eventType}}, which is always the exact Stripe event name such as payment_intent.succeeded. Accepted format: Comma-separated text. Real workplace example: checkout.session.completed, payment_intent.succeeded for an order-fulfillment workflow; invoice.payment_succeeded for a billing workflow. If it is empty or wrong: Empty defaults to a broad set covering checkout, payments, invoices, subscriptions, and refunds. A misspelled event name is simply never delivered by Stripe (no error, just silence). Common mistake: Guessing at an event name instead of copying the exact string from Stripe\'s event type reference — Stripe event names are case-sensitive and use dots, not underscores.',
    placeholder: 'checkout.session.completed, payment_intent.succeeded',
    defaultValue: 'checkout.session.completed, payment_intent.succeeded, payment_intent.payment_failed, invoice.payment_succeeded',
    example: 'checkout.session.completed, payment_intent.succeeded',
  },
  {
    name: 'Stripe Connect Events',
    internalKey: 'connect',
    type: 'boolean',
    required: false,
    description: 'Receive events for connected accounts in a Stripe Connect platform.',
    helpText: 'What this field means: Stripe Connect Events tells CtrlChecks to register the webhook endpoint as a Connect endpoint, which receives events from every connected account under your Stripe Connect platform, not just your own account. Why it matters: A regular (non-Connect) webhook endpoint only ever receives events for your own Stripe account; platforms that manage connected merchant/seller accounts need this enabled to see their events at all. When to fill it: Enable it only if you operate a Stripe Connect platform and this workflow should react to connected accounts\' activity. Leave it disabled for a normal single-account Stripe integration. What to enter: true/enabled for a Connect platform; false/disabled (the default) otherwise. Where the value comes from: This depends entirely on whether your Stripe account is a Connect platform — check Stripe Dashboard for Connect settings if unsure. How to use it later: The trigger output includes {{$json.accountId}} identifying which connected account the event came from. Accepted format: Boolean checkbox. Real workplace example: A marketplace platform enables this so it can auto-generate payout notifications whenever any seller\'s payment succeeds. If it is empty or wrong: Default false (or unset) registers a regular account-only webhook; enabling it without actually being a Connect platform has no effect since there are no connected accounts to report on. Common mistake: Enabling this expecting it to filter to one specific connected account — it only controls whether Connect events are received at all; there is no per-connected-account filter on this node.',
    defaultValue: 'false',
    example: 'false',
  },
  {
    name: 'Live Mode Only',
    internalKey: 'livemode',
    type: 'boolean',
    required: false,
    description: 'Optional filter for live-mode or test-mode events.',
    helpText: 'What this field means: Live Mode Only only lets events matching one specific mode (live or test) through to start the workflow. Why it matters: Stripe sends webhook events for both real (live) payments and sandbox (test) payments to the same endpoint; this keeps a production workflow from firing on test data, or vice versa. When to fill it: Leave it completely unset while building and testing with Stripe test-mode data. Set it explicitly once the workflow is ready, so production only reacts to real payments. What to enter: Enable it to accept only live-mode events; leave the field at its untouched default to accept both live and test events (there is no dedicated "test-mode only" option — the filter only activates once a value is set). Where the value comes from: This is a deployment decision, not something copied from Stripe. How to use it later: The trigger output includes {{$json.livemode}} (true/false) so downstream steps can confirm which mode the event came from. Accepted format: Boolean checkbox. Real workplace example: A finance team enables Live Mode Only on the production fulfillment workflow so test payments from the developer sandbox never trigger a real shipment. If it is empty or wrong: Truly unset accepts both live and test events; once explicitly set to a value (including unchecking a previously checked box, which can save it as false) it will actively reject events of the other mode. Common mistake: Toggling this on then off while testing — unchecking it does not necessarily return it to "no filter"; it may save as an explicit false, which then only accepts test-mode events. Regenerate the field from defaults if you need a true no-filter state again.',
    defaultValue: '',
    example: 'true',
  },
  {
    name: 'Customer ID',
    internalKey: 'customerId',
    type: 'string',
    required: false,
    description: 'Optional Stripe customer ID filter.',
    helpText: 'What this field means: Customer ID restricts this trigger to events belonging to one specific Stripe customer. Why it matters: This turns an account-wide trigger into a focused watcher on a single, already-known customer. When to fill it: Fill it only when you need a workflow tied to one specific customer, such as a VIP account monitor. Leave it blank for normal account-wide workflows. What to enter: The Stripe customer ID, which always starts with cus_, not the customer\'s name or email. Where the value comes from: Read {{$json.customerId}} from a previous test event, or find it in Stripe Dashboard under the customer\'s detail page. How to use it later: The trigger output includes {{$json.customerId}} and {{$json.customerEmail}} for confirmation or logging. Accepted format: Stripe customer ID text starting with cus_. Real workplace example: An account manager watches only their top enterprise customer\'s ID so a Slack alert fires whenever that account\'s invoice is paid. If it is empty or wrong: Empty accepts events for any customer; an ID that never matches silently ignores the event with Ignored Stripe event for customer. Common mistake: Entering the customer\'s email address here instead of their Stripe customer ID (cus_...).',
    placeholder: 'cus_...',
    example: 'cus_ABC123',
  },
  {
    name: 'Currency',
    internalKey: 'currency',
    type: 'string',
    required: false,
    description: 'Optional ISO currency filter.',
    helpText: 'What this field means: Currency only lets events in one specific currency through to start the workflow. Why it matters: A multi-currency Stripe account can process payments in several currencies; this keeps a currency-specific workflow scoped correctly. When to fill it: Fill it for an account that charges in multiple currencies and this workflow should only react to one of them. Leave it blank to accept events in any currency. What to enter: A lowercase ISO currency code such as usd, eur, or gbp. Where the value comes from: Match it to the currencies your Stripe account actually charges in, visible in Stripe Dashboard\'s payments list. How to use it later: The trigger output includes {{$json.currency}} alongside {{$json.amount}} so downstream steps can format amounts correctly. Accepted format: Lowercase 3-letter ISO currency code. Real workplace example: A business charging in both USD and EUR routes EUR payments to a different accounting workflow by setting Currency to eur on that workflow. If it is empty or wrong: Empty accepts events in any currency; a currency that never matches silently ignores the event with Ignored Stripe event currency. Common mistake: Using an uppercase or symbol form (USD or $) instead of the lowercase ISO code Stripe actually sends.',
    placeholder: 'usd',
    example: 'usd',
  },
  {
    name: 'Minimum Amount',
    internalKey: 'minAmount',
    type: 'number',
    required: false,
    description: 'Optional minimum amount in the smallest currency unit.',
    helpText: 'What this field means: Minimum Amount only lets events whose amount is at or above this value through to start the workflow. Why it matters: It lets a workflow focus on high-value transactions, such as flagging large payments for manual review. When to fill it: Fill it for a workflow that should ignore small routine charges and only react to big-ticket ones. Leave it blank to accept transactions of any size. What to enter: A plain whole number in the smallest currency unit Stripe uses — cents for usd/eur (so 1000 means $10.00), or the equivalent zero-decimal unit for currencies like jpy. Where the value comes from: Decide the threshold based on your typical transaction size and what counts as high-value for your process, remembering Stripe amounts are in the smallest unit, not whole dollars. How to use it later: The trigger output includes {{$json.amount}} and {{$json.currency}} so downstream steps can double-check the exact value. Accepted format: Plain whole number, no currency symbol, decimal point, or commas. Real workplace example: A fraud-review workflow sets Minimum Amount to 50000 (meaning $500.00) so only large payments are flagged for manual review. If it is empty or wrong: Empty accepts transactions of any size; amounts below the threshold are silently ignored with Ignored Stripe event amount. Common mistake: Entering a whole-dollar amount like 500 expecting it to mean $500 — Stripe amounts are in cents, so this field must be 50000 for $500.00.',
    placeholder: '1000',
    example: '1000',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional keyword filter for customer email, object ID, description, and status.',
    helpText: 'What this field means: Keyword Filter only lets events whose combined text, customer email, customer ID, object ID, status, or description contain a word or phrase start the workflow. Why it matters: A busy Stripe account can produce a lot of webhook traffic; this keeps a workflow focused on a specific term without a second webhook endpoint. When to fill it: Use it when the workflow should react only to a phrase such as a specific product description or VIP customer email. Leave it blank to accept every event matching the other filters. What to enter: A simple keyword or short phrase, not Stripe search syntax. Where the value comes from: Pick the label, customer email, description keyword, or status term your team cares about. How to use it later: The accepted event output still includes {{$json.text}}, {{$json.customerEmail}}, {{$json.description}}, and {{$json.status}} for downstream routing. Accepted format: Plain text, case-insensitive contains match across the combined fields. Real workplace example: enterprise starts only payment/invoice workflows whose description or customer email mentions enterprise accounts. If it is empty or wrong: Empty accepts every event matching the other filters; a too-specific or misspelled filter causes Ignored Stripe event not matching this trigger. Common mistake: Expecting Stripe\'s search query syntax (such as amount>1000) here — this is a simple text contains filter, not Stripe search.',
    placeholder: 'enterprise, VIP, description keyword',
    example: 'enterprise',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Payment And Billing Events',
  value: 'payment_billing_events',
  description: 'Starts the workflow when a Stripe webhook delivery for a subscribed event type (Checkout, PaymentIntent, invoice, subscription, customer, or refund) arrives, after validating the Stripe-Signature HMAC.',
  fields,
  outputExample: {
    eventId: 'evt_1AbCdEfGhIjKlMnO',
    eventType: 'payment_intent.succeeded',
    source: 'stripe',
    userId: 'cus_ABC123',
    username: 'buyer@example.com',
    text: 'buyer@example.com',
    timestamp: '2026-07-19T10:20:00.000Z',
    livemode: false,
    apiVersion: '2024-06-20',
    accountId: null,
    objectId: 'pi_1AbCdEfGhIjKlMnO',
    objectType: 'payment_intent',
    customerId: 'cus_ABC123',
    customerEmail: 'buyer@example.com',
    amount: 2500,
    amountReceived: 2500,
    amountPaid: null,
    amountTotal: null,
    currency: 'usd',
    status: 'succeeded',
    paymentIntentId: 'pi_1AbCdEfGhIjKlMnO',
    chargeId: 'ch_1AbCdEfGhIjKlMnO',
    checkoutSessionId: null,
    invoiceId: null,
    subscriptionId: null,
    paymentMethodId: 'pm_1AbCdEfGhIjKlMnO',
    receiptUrl: 'https://pay.stripe.com/receipts/...',
    description: null,
    metadata: {},
    raw: {},
    trigger: 'stripe',
    workflow_id: 'workflow_123',
    node_id: 'stripe-trigger-1',
    sessionId: 'stripe_workflow_123_evt_1AbCdEfGhIjKlMnO',
    _stripe: true,
  },
  outputDescription: 'eventId: the Stripe event ID (evt_...). eventType: the exact Stripe event name, such as payment_intent.succeeded. source: stripe. userId/username: the customer ID/email tied to the event object when available. text: description, customer email, object ID, or a status fallback. timestamp: Stripe\'s event created time. livemode: true for real payments, false for test-mode. apiVersion: the Stripe API version the event was generated under. accountId: the connected account ID, only present when Stripe Connect Events is enabled. objectId/objectType: the Stripe object ID and its Stripe object type, such as payment_intent or checkout.session. customerId/customerEmail: customer identity. amount/amountReceived/amountPaid/amountTotal: whichever amount field the object actually has, in the smallest currency unit. currency: lowercase ISO code. status: the object\'s status field, such as succeeded or paid. paymentIntentId/chargeId/checkoutSessionId/invoiceId/subscriptionId/paymentMethodId: populated only when relevant to the object type, otherwise null. receiptUrl: a receipt or hosted invoice link when Stripe provides one. description: the object\'s description or statement descriptor. metadata: any custom metadata you attached in Stripe. raw: the original Stripe event payload. trigger/workflow_id/node_id/sessionId/_stripe: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Fulfill a paid Stripe Checkout order and notify the team in Slack',
    inputValues: {
      eventTypes: 'checkout.session.completed, payment_intent.succeeded',
      connect: 'false',
      livemode: '',
      customerId: '',
      currency: 'usd',
      minAmount: '',
      query: '',
    },
    expectedOutput: 'A normalized Stripe event payload available as {{$json.eventType}}, {{$json.customerId}}, {{$json.amount}}, and {{$json.paymentIntentId}} for a fulfillment or Slack notification node.',
  },
  externalDocsUrl: stripeWebhookDocs,
};

export const stripeTriggerDoc: NodeDoc = {
  slug: 'stripe_trigger',
  displayName: 'Stripe Trigger',
  category: 'Triggers',
  logoUrl: '/integrations-logos/Stripe.svg',
  description: 'Start a workflow from signed Stripe webhook events for Checkout, payments, invoices, subscriptions, customers, and refunds.',
  credentialType: 'Stripe Secret Key',
  credentialSetupSteps: [
    'Open Stripe Dashboard -> Developers -> API keys.',
    'Copy a Secret key. Use a test key while building and a live key only for real payment workflows.',
    'In CtrlChecks, open Connections -> Add Connection -> Stripe and save the key (tested against GET https://api.stripe.com/v1/account).',
    'Choose the Stripe event types this workflow should receive on the Event Types field, then save and activate the workflow.',
    'CtrlChecks creates the Stripe webhook endpoint automatically (Stripe API\'s /v1/webhook_endpoints) and stores the returned signing secret for Stripe-Signature validation — no manual webhook setup in Stripe Dashboard is required.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Stripe connection only authorizes registering the webhook, not the Slack, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: stripeWebhookDocs,
  resources: [
    {
      name: 'Webhook Events',
      description: 'Receive Stripe webhook deliveries signed with Stripe-Signature.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'No active Stripe connection found. Save a Stripe Secret Key connection first.',
      cause: 'The workflow owner has not connected Stripe, or the saved Secret Key is invalid.',
      fix: 'Save a valid Stripe Secret Key in Connections, then re-activate the workflow.',
    },
    {
      error: 'Invalid Stripe webhook signature.',
      cause: 'The Stripe-Signature header did not match the stored endpoint signing secret, or the request timestamp is outside Stripe\'s 5-minute tolerance.',
      fix: 'Re-register the webhook by saving the active workflow again so a fresh endpoint and signing secret are created.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'A valid, signed Stripe event arrived, but the workflow has not been activated.',
      fix: 'Activate the workflow in CtrlChecks, then resend or wait for the next real Stripe event.',
    },
    {
      error: 'Ignored non-actionable Stripe payload.',
      cause: 'The delivery had no recognizable event type or object, such as a connectivity test.',
      fix: 'No action needed for test pings; confirm Event Types if you expected a real workflow run.',
    },
    {
      error: 'Ignored Stripe event not matching this trigger.',
      cause: 'The event was valid, but Event Types, Live Mode Only, Customer ID, Currency, Minimum Amount, or Keyword Filter filtered it out.',
      fix: 'Broaden the relevant filter, clear filters temporarily, trigger a fresh Stripe test event, then narrow the filters again after confirming the output.',
    },
    {
      error: 'Stripe API error (401/403): ...',
      cause: 'The Stripe Secret Key is invalid, revoked, or restricted from managing webhook endpoints.',
      fix: 'Confirm the Secret Key is correct and has full API access, then save the workflow again to retry registration.',
    },
    {
      error: 'Stripe webhook endpoint creation did not return an endpoint id and signing secret.',
      cause: 'Stripe accepted the request but the response was missing expected fields, often due to a restricted API key.',
      fix: 'Use an unrestricted Stripe Secret Key (or one with webhook endpoint permissions), then save the workflow again to retry.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Stripe webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Stripe must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'Next node cannot find Stripe trigger fields',
      cause: 'A downstream node is mapped to a field only present for another object type, such as expecting {{$json.subscriptionId}} on a payment_intent event.',
      fix: 'Use {{$json.eventType}} or {{$json.objectType}} to branch by object type before mapping type-specific fields.',
    },
    {
      error: 'Permission denied after Stripe Trigger',
      cause: 'The trigger fired correctly, but the downstream Stripe action, Slack, email, or fulfillment node lacks its own account connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Stripe Secret Key has write access if the action needs to update Stripe.',
    },
  ],
  relatedNodes: ['stripe', 'shopify', 'webhook'],
};
