import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const telegramWebhookDocs = 'https://core.telegram.org/bots/api#setwebhook';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Telegram Bot Token connection ID. If blank, the active Telegram connection is used.',
    helpText: 'What this field means: Connection points to the saved Telegram Bot Token CtrlChecks uses to call setWebhook, deleteWebhook, and getMe on your bot. Why it matters: CtrlChecks needs the bot token to register (and re-register) the webhook URL with Telegram\'s API — without it, the trigger cannot receive any updates. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Telegram connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save a Telegram Bot Token (tested against GET api.telegram.org/bot{token}/getMe). How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw bot token. Real workplace example: A team saves one Telegram connection per bot they operate, such as a support bot and a sales bot, each with its own connection. If it is empty or wrong: Empty falls back to the active Telegram connection; a missing connection causes No active Telegram Bot Token connection found. Common mistake: Pasting the raw bot token (from BotFather) into a normal workflow field instead of saving it under Connections.',
    placeholder: 'Uses your active Telegram connection',
    example: 'telegram_bot_token_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Update Types',
    internalKey: 'updateTypes',
    type: 'select',
    required: false,
    description: 'Telegram update type to accept.',
    helpText: 'What this field means: Update Types decides which kinds of Telegram Bot API updates this trigger accepts, and is also sent to Telegram as the allowed_updates list when the webhook is registered. Why it matters: Telegram will only deliver the update kinds you subscribe to; message, edited_message, channel_post, and callback_query cover very different use cases (new messages, edits, channel posts, and inline button clicks). When to fill it: Keep message for a normal chatbot. Add callback_query when your bot uses inline keyboard buttons, or channel_post if the bot posts/monitors a channel rather than a private chat. What to enter: One value from the dropdown: message, edited_message, channel_post, or callback_query (the visual panel currently allows one selection at a time; advanced users can request more update kinds through the registration API directly). Where the value comes from: Decide based on what your bot actually needs to react to. How to use it later: The trigger output includes {{$json.updateType}} confirming which kind of update actually arrived. Accepted format: One of the four listed values. Real workplace example: message for an AI support chatbot; callback_query for a workflow that reacts to inline "Approve"/"Reject" button taps. If it is empty or wrong: Empty defaults to message. Choosing a type your bot never receives (for example callback_query with no inline keyboards anywhere) means the trigger simply never fires. Common mistake: Expecting the workflow to react to edited messages while only message is selected — edited_message is a separate update type that must be added explicitly.',
    placeholder: 'message',
    defaultValue: 'message',
    example: 'message',
    options: ['message', 'edited_message', 'channel_post', 'callback_query'],
  },
  {
    name: 'Allowed Chat IDs',
    internalKey: 'allowedChatIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated list of chat IDs allowed to trigger this workflow.',
    helpText: 'What this field means: Allowed Chat IDs restricts this trigger to messages from specific Telegram chats. Why it matters: One bot can be added to many private chats, groups, and channels; this keeps a chat-specific workflow from reacting to everyone who can message the bot. When to fill it: Use this when one bot is installed in multiple chats but this workflow should only react to some of them. Leave it blank to accept any chat that can message the bot. What to enter: Comma-separated numeric Telegram chat IDs, such as 123456789 for a private chat or a negative number like -1009876543210 for a group/supergroup. Where the value comes from: Read {{$json.chatId}} from a previous test message, or use @userinfobot/@RawDataBot in Telegram to look up a chat\'s ID. How to use it later: The trigger output includes {{$json.chatId}}, which you also use as the reply target in a downstream Telegram action node. Accepted format: Comma-separated numeric IDs, including negative signs for groups. Real workplace example: An internal ops bot restricts itself to the team\'s private group chat ID so random users who find the bot cannot trigger internal workflows. If it is empty or wrong: Empty allows any chat; a chat ID that never matches silently ignores the message with Ignored Telegram update from a chat that is not allowed. Common mistake: Typing the chat\'s display name or @username instead of its numeric chat ID.',
    placeholder: '123456789, -1009876543210',
    example: '123456789',
  },
  {
    name: 'Command Filter',
    internalKey: 'commandFilter',
    type: 'string',
    required: false,
    description: 'Optional slash command required at the start of the message.',
    helpText: 'What this field means: Command Filter only accepts messages that start with one specific slash command. Why it matters: A single bot can support several commands (such as /support and /status); this keeps each workflow scoped to the command it actually handles. When to fill it: Fill it whenever the bot should route different commands to different workflows. Leave it blank to accept every message regardless of command. What to enter: The command text; the leading slash is optional — CtrlChecks adds it automatically if you omit it, so support and /support behave the same. Where the value comes from: Match it to the commands you registered with BotFather (or plan to support) for this bot. How to use it later: The trigger output includes {{$json.text}}, which still contains the full message including the command, for downstream parsing of arguments after the command. Accepted format: A command word, with or without a leading slash. Real workplace example: /support and /feedback both work with the same bot; one workflow sets Command Filter to /support so only that command reaches it. If it is empty or wrong: Empty accepts any message, command or not; a command that never matches silently ignores the message with Ignored Telegram message because it does not start with .... Common mistake: Including trailing text or arguments in this field (such as /support now) — only the command word itself should go here; the match only checks that the message starts with the command.',
    placeholder: '/support',
    example: '/support',
  },
  {
    name: 'Secret Token',
    internalKey: 'secretToken',
    type: 'string',
    required: false,
    description: 'Optional webhook secret token validated against Telegram request headers.',
    helpText: 'What this field means: Secret Token is a shared value Telegram echoes back in the X-Telegram-Bot-Api-Secret-Token header on every webhook delivery, which CtrlChecks then checks against this field. Why it matters: Telegram webhooks are not otherwise signed; this header check is the only way to confirm a request actually came from Telegram\'s servers and not an outside caller who guessed your webhook URL. When to fill it: Set it before registering the webhook, and keep the same value for the life of the workflow. It is optional, but strongly recommended for any bot handling real user data. What to enter: A random string, ideally generated once and reused, such as a UUID or a long random token. Where the value comes from: Generate it yourself in a password manager or admin note — it does not come from Telegram or BotFather. How to use it later: This is setup-only and is never emitted as {{$json.secretToken}} to downstream nodes. Accepted format: Plain secret text; the visual field uses a standard text control even though the value should be treated as secret material. Real workplace example: A finance team sets a random Secret Token before registering the webhook, so an outside party who discovers the webhook URL still cannot inject fake Telegram updates. If it is empty or wrong: Empty means Telegram request validation is skipped entirely — any caller who knows the webhook URL can send fake updates. A value that does not match what was registered causes Invalid Telegram webhook secret token on every real Telegram delivery. Common mistake: Changing this field after the webhook was already registered with the old value — the node field and the value Telegram was told about must always match; re-register the webhook after changing it.',
    placeholder: 'optional-random-secret',
    example: 'a1b2c3d4e5f6',
    notes: 'The visual config field uses a standard text control because password is not a supported node panel field type, but the value should still be treated as secret material.',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive Update',
  value: 'default',
  description: 'Receives Telegram Bot API webhook updates, validates the optional secret token, filters accepted update types/chat/command, normalizes the update, and starts one workflow execution per accepted update.',
  fields,
  outputExample: {
    chatId: '123456789',
    messageId: 42,
    text: 'Hello bot',
    username: 'alice',
    firstName: 'Alice',
    lastName: 'Ng',
    userId: '987654321',
    updateType: 'message',
    raw: { update_id: 10001, message: { text: 'Hello bot' } },
    trigger: 'telegram',
    workflow_id: 'workflow_123',
    node_id: 'telegram-trigger-1',
    updateId: 10001,
    sessionId: 'telegram_workflow_123_123456789',
    timestamp: '2026-07-19T10:20:00.000Z',
    _telegram: true,
  },
  outputDescription: 'chatId: the Telegram chat this update came from — use it as the reply target in a downstream Telegram action node. messageId: the numeric Telegram message ID, when the update is a message. text: message text, caption, callback data, or inline query text, whichever applies. username/firstName/lastName: the sender\'s Telegram profile fields when available. userId: the sender\'s numeric Telegram user ID. updateType: message, edited_message, channel_post, edited_channel_post, callback_query, inline_query, or unknown. raw: the complete original Telegram update object. trigger/workflow_id/node_id/updateId/sessionId/timestamp/_telegram: CtrlChecks trigger metadata; updateId is Telegram\'s own update_id and sessionId is stable per chat so a reply node can target the same conversation.',
  usageExample: {
    scenario: 'Telegram chatbot that replies with an AI-generated answer',
    inputValues: {
      updateTypes: 'message',
      allowedChatIds: '',
      commandFilter: '',
      secretToken: '',
    },
    expectedOutput: 'A user sends your bot a message, the workflow starts immediately, and {{$json.chatId}} is used in the Telegram action node to reply to the same chat.',
  },
  externalDocsUrl: telegramWebhookDocs,
};

export const telegramTriggerDoc: NodeDoc = {
  slug: 'telegram_trigger',
  displayName: 'Telegram Trigger',
  category: 'Triggers',
  logoUrl: '/icons/nodes/telegram.svg',
  description: 'Start a workflow in real time when your Telegram bot receives a message or supported update.',
  credentialType: 'Telegram Bot Token',
  credentialSetupSteps: [
    'Open Telegram on your phone, desktop app, or web.telegram.org.',
    'Search for BotFather and start a chat.',
    'Send /newbot and follow the prompts to choose a bot name and username.',
    'Copy the bot token from BotFather. It looks like 123456789:ABCdef...',
    'In CtrlChecks, open Connections -> Add Connection -> Telegram, paste the token, save it, and run Test Telegram (checks GET api.telegram.org/bot{token}/getMe).',
    'Save and activate the workflow — CtrlChecks automatically calls Telegram\'s setWebhook for this bot token.',
    'Important: Telegram allows only one webhook URL per bot token. Saving/activating a workflow with a Telegram Trigger always re-registers the webhook with force enabled, which silently overwrites and disconnects any other active workflow currently using the same bot token — there is no confirmation prompt for this automatic path. Use a separate bot token (a separate BotFather bot) for each independently active Telegram workflow to avoid one workflow silently breaking another.',
    'Set Secret Token before relying on this trigger for real user data — Telegram webhooks are not otherwise signed, so this header check is the only protection against outside callers hitting your webhook URL directly.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Telegram connection only authorizes registering the webhook and reading bot info, not the CRM, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: 'https://core.telegram.org/bots/features#botfather',
  resources: [
    {
      name: 'Configuration',
      description: 'Configure which Telegram updates can start the workflow.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Invalid Telegram webhook secret token.',
      cause: 'The Secret Token saved on the node does not match the value Telegram was told about during registration (or a request came from somewhere other than Telegram).',
      fix: 'Re-register the webhook with the same Secret Token value, or clear the field on the node and re-register so both sides agree again.',
    },
    {
      error: 'This Telegram bot already has a webhook registered at ... Telegram allows one webhook per bot token.',
      cause: 'A manual, non-automatic re-registration call (with force not explicitly set) found the bot token\'s webhook already pointed somewhere else. Note: normal save/activate registration always uses force and will not show this error — it silently takes over instead.',
      fix: 'Use a separate bot token for this workflow, or intentionally force re-register only if this workflow should now own the bot exclusively.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'Telegram sent an update, but the saved workflow is not active.',
      fix: 'Activate and save the workflow, then send another message to the bot.',
    },
    {
      error: 'No active Telegram Bot Token connection found. Create one in Connections first.',
      cause: 'The workflow owner has not connected a Telegram bot, or the saved token is invalid.',
      fix: 'Save a valid Telegram Bot Token in Connections, then re-activate the workflow.',
    },
    {
      error: 'Telegram Bot Token is missing from the selected connection.',
      cause: 'The saved connection exists but has no usable token value.',
      fix: 'Re-save the Telegram connection with a fresh bot token from BotFather.',
    },
    {
      error: 'Telegram setWebhook failed (400/401): ...',
      cause: 'The bot token is invalid/revoked, or PUBLIC_BASE_URL does not point to a real HTTPS endpoint Telegram can reach.',
      fix: 'Confirm the bot token is current and PUBLIC_BASE_URL is a real, reachable HTTPS URL, then save the workflow again.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Telegram webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Telegram must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then save/activate the workflow again.',
    },
    {
      error: 'Next node cannot find Telegram trigger fields',
      cause: 'A downstream node is mapped to a field only present for another update type, such as expecting text on a callback_query with no message attached.',
      fix: 'Use {{$json.updateType}} to branch by update kind before mapping type-specific fields.',
    },
    {
      error: 'Permission denied after Telegram Trigger',
      cause: 'The trigger fired correctly, but the downstream Telegram action, CRM, email, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Telegram bot has permission to post in the target chat.',
    },
  ],
  relatedNodes: ['telegram', 'ai_agent'],
};
