import type { FieldDoc, NodeDoc } from '../types';

const help = (field: string, why: string, when: string, enter: string, source: string, format: string, example: string, wrong: string, mistake: string) => `What this field is: ${field}
Why it matters: ${why}
When to fill it: ${when}
What to enter: ${enter}
Where the value comes from: ${source}
How to use it later: Map previous data with {{$json.fieldName}} and use this node output later as {{$json.rows}}, {{$json.rowsAffected}}, {{$json.count}}, or {{$json.inserted}}.
Accepted format: ${format}
Real workplace example: ${example}
If it is empty or wrong: ${wrong}
Common mistake: ${mistake}`;

const f = (name: string, internalKey: string, type: FieldDoc['type'], required: boolean, description: string, text: Parameters<typeof help>, extra: Partial<FieldDoc> = {}): FieldDoc => ({
  name,
  internalKey,
  type,
  required,
  description,
  helpText: help(...text),
  ...extra,
});

const fields: FieldDoc[] = [
  f('Host', 'host', 'string', true, 'TimescaleDB/PostgreSQL host name.', ['The network address of the TimescaleDB server.', 'The executor uses it to open a PostgreSQL pool.', 'Fill it for every operation unless a saved TimescaleDB connection injects it.', 'Enter a host such as timescale.company.com or localhost.', 'Copy it from Timescale Cloud, your PostgreSQL hosting dashboard, application config, or DBA. You can map {{$json.timescaleHost}}.', 'Host name or IP address without postgres:// and without the port.', 'metrics-prod.timescale.cloud for production metrics data.', 'The run returns _error "host is required" or a connection failure.', 'Do not paste a full connection string here; split host, port, database, username, password, and SSL.'], { placeholder: 'timescale.example.com', example: 'metrics-prod.timescale.cloud' }),
  f('Port', 'port', 'number', false, 'TimescaleDB/PostgreSQL port.', ['The TCP port used by TimescaleDB.', 'Host and port identify the database service.', 'Fill it when the database does not use default PostgreSQL port 5432.', 'Enter 5432 for most TimescaleDB databases.', 'Find it in Timescale Cloud connection details or ask your DBA. You can map {{$json.pgPort}}.', 'Number between 1 and 65535.', '5432 for Timescale Cloud and most PostgreSQL hosts.', 'The run returns _error "port must be a valid number between 1 and 65535" or cannot connect.', 'Do not enter host:port in this field.'], { placeholder: '5432', defaultValue: '5432', example: '5432' }),
  f('Database', 'database', 'string', true, 'Database name.', ['The PostgreSQL database that contains the TimescaleDB hypertables.', 'The server may host multiple databases, so this selects the correct one.', 'Fill it for every operation unless a saved connection injects it.', 'Enter the exact database name.', 'Copy it from Timescale Cloud, psql, application config, or your DBA. You can map {{$json.databaseName}}.', 'Plain database name.', 'metrics_prod for IoT readings.', 'The run returns _error "database is required" or PostgreSQL reports the database does not exist.', 'Do not enter a schema or table name here.'], { placeholder: 'metrics_prod', example: 'metrics_prod' }),
  f('Username', 'username', 'string', true, 'TimescaleDB/PostgreSQL user.', ['The database login used for this connection.', 'PostgreSQL checks this user before allowing reads or writes.', 'Fill it when a saved connection does not inject it.', 'Enter a least-privilege database user.', 'Copy it from Timescale Cloud, a credential vault, or your DBA. You can map {{$json.timescaleUser}} only from secure generated config.', 'Plain PostgreSQL user name.', 'metrics_reader for dashboard query workflows.', 'The run returns _error "username is required" or PostgreSQL access denied.', 'Do not use a superuser for routine workflow automation.'], { placeholder: 'metrics_reader', example: 'metrics_reader' }),
  f('Password', 'password', 'password', true, 'TimescaleDB/PostgreSQL password.', ['The secret password for the database user.', 'The database rejects the connection without it.', 'Prefer storing it in Connections; fill the visible field only as a direct fallback.', 'Use the password for the selected database user.', 'Get it from Timescale Cloud, your password vault, or DBA. Avoid mapping secrets from normal workflow data.', 'Secret text stored as a masked value when entered directly.', 'A saved TimescaleDB Database Connection for metrics_reader.', 'The run returns _error "password is required" or authentication failed.', 'Do not paste database passwords into Query, Data, notes, or upstream JSON.'], { placeholder: 'Use Connections when possible', notes: 'Store database passwords in Connections or a credential vault whenever possible.' }),
  f('Use SSL', 'ssl', 'boolean', false, 'Whether to use SSL for the PostgreSQL connection.', ['This controls the pg Pool SSL option.', 'Managed TimescaleDB and PostgreSQL providers commonly require encrypted connections.', 'Turn it on when the provider requires SSL or production policy requires encryption.', 'Use true for SSL-required managed hosts and false for local development without SSL.', 'Check the Timescale Cloud connection guide or ask your DBA. You can map {{$json.useSsl}}.', 'Boolean true or false. true becomes rejectUnauthorized:false in the current executor.', 'true for Timescale Cloud.', 'The run may fail with TLS, certificate, or connection errors.', 'Do not disable SSL in production to work around a certificate issue.'], { defaultValue: 'false', example: 'true' }),
  f('Operation', 'operation', 'select', true, 'TimescaleDB action to run.', ['The action tells the executor whether to run raw SQL, write table rows, delete rows, or run Timescale time-series helpers.', 'It controls which fields are required and what output shape comes back.', 'Choose it before filling Query, Table, Data, Where, Time Column, Interval, Group Column, or Value Column.', 'Use executeQuery for raw SQL, insert/update/delete for table writes, timeBucket for grouped counts, first for first value per time bucket, and last for last value per time bucket.', 'Choose from the dropdown based on the time-series or table action in this workflow.', 'One of executeQuery, insert, update, delete, timeBucket, first, or last.', 'timeBucket to count device readings per hour.', 'The run returns _error "operation is required" or "operation must be one of..." for unsupported values.', 'Do not use stale select/query values; the live executor expects executeQuery for raw SQL.'], { options: ['executeQuery', 'insert', 'update', 'delete', 'timeBucket', 'first', 'last'], defaultValue: 'executeQuery' }),
  f('Query', 'query', 'textarea', false, 'Raw PostgreSQL/Timescale SQL query.', ['The SQL text sent to TimescaleDB for Execute Query.', 'It is the actual database instruction when you choose Execute Query.', 'Required for executeQuery.', 'Write PostgreSQL SQL with $1, $2 placeholders and put matching values in Params.', 'Write approved SQL yourself, copy from a DBA, or map a vetted query from {{$json.sql}}.', 'PostgreSQL SQL string. Use $1, $2 for parameter values.', "SELECT time_bucket('1 hour', time) AS bucket, AVG(value) FROM metrics WHERE device_id = $1 GROUP BY bucket", 'The run returns query is required for executeQuery operation or PostgreSQL syntax errors.', 'Do not paste untrusted values directly into SQL; use Params.'], { placeholder: "SELECT time, value FROM metrics WHERE device_id = $1", example: "SELECT time_bucket('1 hour', time) AS bucket, AVG(value) FROM metrics WHERE device_id = $1 GROUP BY bucket" }),
  f('Params', 'params', 'json', false, 'Ordered values for $1, $2 query placeholders.', ['A JSON array of values bound to Query placeholders.', 'Parameters keep values separate from SQL text.', 'Use it when Query contains $1, $2, and so on.', 'Enter an array such as ["device-17", "2026-07-20T00:00:00Z"].', 'Map values from webhooks, devices, forms, or previous database rows.', 'JSON array in placeholder order.', '["pump-22"] for WHERE device_id = $1.', 'Wrong order or missing items can produce query errors or wrong results.', 'Do not use a JSON object here; pg expects an ordered array.'], { placeholder: '["{{$json.deviceId}}"]', example: '["pump-22"]' }),
  f('Table', 'table', 'string', false, 'Table or hypertable name.', ['The table or hypertable that helper operations target.', 'Insert, Update, Delete, Time Bucket, First, and Last build SQL around this table.', 'Required for insert, update, delete, timeBucket, first, and last.', 'Enter the exact table or hypertable name.', 'Copy it from psql, Timescale Cloud Explorer, schema docs, or your DBA. You can map {{$json.tableName}} only from trusted routing data.', 'Plain table name; current executor wraps it in double quotes as one identifier.', 'metrics for device telemetry rows.', 'The run returns table is required or PostgreSQL says the relation does not exist.', 'Do not enter schema.table here unless you have tested how the current quoting handles it.'], { placeholder: 'metrics', example: 'metrics' }),
  f('Data', 'data', 'json', false, 'Row values for insert or update.', ['The column values to write.', 'Insert uses it as new readings or rows; Update uses it as replacement values for matching rows.', 'Required for insert and update.', 'Enter a JSON object for one row, or an array of objects for multiple inserts.', 'Map readings from IoT/webhook data, forms, upstream calculations, or previous database rows.', 'JSON object or JSON array of objects.', '{"time":"{{$json.timestamp}}","device_id":"{{$json.deviceId}}","value":42.7}', 'The run returns data is required or PostgreSQL rejects bad columns/types.', 'Do not omit the hypertable time column when inserting time-series rows.'], { placeholder: '{"time":"{{$json.timestamp}}","device_id":"{{$json.deviceId}}","value":42.7}', example: '{"time":"2026-07-20T09:00:00Z","device_id":"pump-22","value":42.7}' }),
  f('Where', 'where', 'json', false, 'Exact-match filter for update, delete, and time-series helpers.', ['The equality filter added to generated helper queries.', 'It narrows which rows are updated, deleted, or aggregated.', 'Required for update and delete; optional for timeBucket, first, and last.', 'Enter a JSON object where keys are column names and values are exact matches.', 'Use stable IDs from previous steps, such as {{$json.deviceId}} or {{$json.siteId}}.', 'JSON object. Multiple keys are combined with AND.', '{"device_id":"{{$json.deviceId}}"}', 'Update/delete returns where clause is required, or aggregations may include too much data.', 'Do not expect range operators here; use Execute Query for time windows and complex filters.'], { placeholder: '{"device_id":"{{$json.deviceId}}"}', example: '{"device_id":"pump-22"}' }),
  f('Time Column', 'timeColumn', 'string', false, 'Timestamp column used for time buckets.', ['The time column passed to time_bucket, first, or last.', 'TimescaleDB time-series helpers need a timestamp column to group by time.', 'Required for timeBucket, first, and last.', 'Enter the timestamp column name, usually time, created_at, or recorded_at.', 'Copy it from the hypertable schema or DBA docs. You can map {{$json.timeColumn}} only from trusted schema metadata.', 'Column name string.', 'time for a metrics hypertable.', 'The run returns timeColumn is required or PostgreSQL reports a missing column.', 'Do not enter a date value here; enter the column name that contains dates.'], { placeholder: 'time', example: 'time' }),
  f('Bucket Interval', 'interval', 'string', false, 'TimescaleDB time bucket interval.', ['The interval passed into time_bucket.', 'It controls the size of each time group.', 'Required for timeBucket, first, and last.', 'Enter an interval such as 5 minutes, 1 hour, or 1 day.', 'Choose it from reporting needs or map {{$json.bucketInterval}} from a trusted schedule/config step.', 'PostgreSQL interval string.', '1 hour for hourly IoT average calculations.', 'The run returns interval is required or PostgreSQL rejects the interval.', 'Do not let untrusted users type arbitrary interval text into generated SQL.'], { placeholder: '1 hour', example: '1 hour' }),
  f('Group Column', 'bucketColumn', 'string', false, 'Column grouped with each time bucket for Time Bucket.', ['The column included beside the time bucket in the Time Bucket query.', 'The current executor requires it for timeBucket and groups counts by it.', 'Required for timeBucket in this runtime.', 'Enter a dimension column such as device_id, region, or site_id.', 'Copy it from the hypertable schema or analytics requirement. You can map {{$json.groupColumn}} from trusted config.', 'Column name string.', 'device_id to count readings per device per hour.', 'The run returns bucketColumn is required for timeBucket operation.', 'Do not enter an aggregate expression here; use Execute Query for custom aggregations.'], { placeholder: 'device_id', example: 'device_id' }),
  f('Value Column', 'valueColumn', 'string', false, 'Value column used by first or last.', ['The column whose first or last value should be returned in each time bucket.', 'first() and last() need to know which measurement column to return.', 'Required for first and last.', 'Enter a measurement column such as temperature, pressure, status, or value.', 'Copy it from your hypertable schema or monitoring design. You can map {{$json.valueColumn}} from trusted config.', 'Column name string.', 'temperature to get the first temperature reading per hour.', 'The run returns valueColumn is required for first/last operation.', 'Do not enter the time column here; Time Column is separate.'], { placeholder: 'value', example: 'temperature' }),
];

const op = (name: string, value: string, description: string, inputValues: Record<string, string>, outputExample: Record<string, unknown>, outputDescription: string) => ({
  name,
  value,
  description,
  fields,
  outputExample,
  outputDescription,
  usageExample: {
    scenario: `${name} TimescaleDB rows or time-series buckets after a device, form, database, or scheduled reporting step provides data and filters.`,
    inputValues: { operation: value, host: 'metrics-prod.timescale.cloud', port: '5432', database: 'metrics_prod', username: 'metrics_reader', password: 'Use saved TimescaleDB connection', ...inputValues },
    expectedOutput: 'Use TimescaleDB output later as {{$json.rows}}, {{$json.rowsAffected}}, {{$json.count}}, or {{$json.inserted}}.',
  },
  externalDocsUrl: 'https://docs.timescale.com/',
});

export const timescaledbDoc: NodeDoc = {
  slug: 'timescaledb',
  displayName: 'TimescaleDB',
  category: 'Data',
  logoUrl: '/icons/nodes/timescaledb.svg',
  description: 'Run PostgreSQL/TimescaleDB queries, table writes, deletes, and time-series helper operations such as time_bucket, first, and last from a workflow.',
  credentialType: 'TimescaleDB Database Connection',
  credentialSetupSteps: [
    'Create or select a TimescaleDB Database Connection in CtrlChecks Connections so host, port, database, username, password, and SSL settings can live in the credential vault.',
    'Use a least-privilege PostgreSQL user: read-only for dashboards, insert permission for ingestion, update/delete only when the workflow truly needs it.',
    'For Timescale Cloud or managed PostgreSQL, use SSL when the provider requires it. Test with Execute Query using SELECT 1 before enabling writes.',
    'Use Execute Query for advanced time windows, joins, averages, continuous aggregates, or any filter more complex than equality.',
    'Connect this node output to the next node with an outgoing line; downstream service node account connection is still required for Slack, email, CRM, AI, or file steps.',
  ],
  credentialDocsUrl: 'https://docs.timescale.com/use-timescale/latest/security/',
  resources: [
    {
      name: 'Operations',
      description: 'TimescaleDB uses the pg driver. Successful data objects are flattened by the workflow executor; failures return _error from validation, connection, SQL, or Timescale function errors.',
      operations: [
        op('Execute Query', 'executeQuery', 'Runs raw PostgreSQL/Timescale SQL with optional Params. Use it for SELECT reports, time windows, joins, averages, continuous aggregates, and DBA-approved custom SQL.', { query: "SELECT time_bucket('1 hour', time) AS bucket, AVG(value) FROM metrics WHERE device_id = $1 GROUP BY bucket", params: '["pump-22"]' }, { rows: [{ bucket: '2026-07-20T09:00:00.000Z', avg: 42.7 }], rowsAffected: 1 }, 'rows: query result rows. rowsAffected: PostgreSQL rowCount. _error appears for validation, connection, or SQL execution failures.'),
        op('Insert', 'insert', 'Inserts one or more rows into a TimescaleDB table or hypertable and returns inserted rows. Use it for device readings, metrics, events, or operational time-series data.', { table: 'metrics', data: '{"time":"{{$json.timestamp}}","device_id":"{{$json.deviceId}}","value":42.7}' }, { inserted: [{ time: '2026-07-20T09:00:00Z', device_id: 'pump-22', value: 42.7 }], count: 1 }, 'inserted: rows returned by INSERT ... RETURNING *. count: number inserted. _error appears when table/data/credentials or SQL execution fails.'),
        op('Update', 'update', 'Updates rows in Table matching Where and returns changed rows. Use it sparingly for correction workflows or status flags on time-series-adjacent tables.', { table: 'device_status', data: '{"status":"online"}', where: '{"device_id":"{{$json.deviceId}}"}' }, { rows: [{ device_id: 'pump-22', status: 'online' }], rowsAffected: 1 }, 'rows: changed rows. rowsAffected: number updated. _error appears when table, data, or where is missing or execution fails.'),
        op('Delete', 'delete', 'Deletes rows in Table matching Where and returns deleted rows. Use it for tightly scoped cleanup of test, duplicate, or expired records.', { table: 'metrics_staging', where: '{"import_id":"{{$json.importId}}"}' }, { rows: [{ import_id: 'imp_1048' }], rowsAffected: 1 }, 'rows: deleted rows returned by DELETE ... RETURNING *. rowsAffected: number deleted. _error appears when table or where is missing or execution fails.'),
        op('Time Bucket', 'timeBucket', 'Groups rows by time_bucket(Interval, Time Column) and Group Column, returning count per bucket. Use it for hourly counts by device, region, or other dimension.', { table: 'metrics', timeColumn: 'time', interval: '1 hour', bucketColumn: 'device_id', where: '{"site_id":"site-7"}' }, { rows: [{ bucket: '2026-07-20T09:00:00.000Z', device_id: 'pump-22', count: '42' }], count: 1 }, 'rows: bucketed count rows. count: number of grouped rows returned. _error appears when table, timeColumn, interval, or bucketColumn is missing or SQL fails.'),
        op('First', 'first', 'Returns first(Value Column, Time Column) per time bucket. Use it for first recorded reading, opening status, or start-of-period value.', { table: 'metrics', timeColumn: 'time', interval: '1 hour', valueColumn: 'temperature', where: '{"device_id":"pump-22"}' }, { rows: [{ bucket: '2026-07-20T09:00:00.000Z', first_value: 41.8 }], count: 1 }, 'rows: bucket rows with first_value. count: number of buckets returned. _error appears when table, timeColumn, interval, or valueColumn is missing or SQL fails.'),
        op('Last', 'last', 'Returns last(Value Column, Time Column) per time bucket. Use it for closing readings, latest status per hour, or end-of-period values.', { table: 'metrics', timeColumn: 'time', interval: '1 hour', valueColumn: 'temperature', where: '{"device_id":"pump-22"}' }, { rows: [{ bucket: '2026-07-20T09:00:00.000Z', last_value: 43.2 }], count: 1 }, 'rows: bucket rows with last_value. count: number of buckets returned. _error appears when table, timeColumn, interval, or valueColumn is missing or SQL fails.'),
      ],
    },
  ],
  commonErrors: [
    { error: 'host is required / username is required / password is required / database is required', cause: 'A required connection field is missing or the saved TimescaleDB connection did not inject it.', fix: 'Complete the TimescaleDB Database Connection in Connections or fill the direct fallback fields.' },
    { error: 'operation must be one of: executeQuery, insert, update, delete, timeBucket, first, last', cause: 'The operation value is unsupported, stale, or still using old select/query UI values.', fix: 'Choose a current TimescaleDB operation from the dropdown; use executeQuery for raw SQL.' },
    { error: 'query is required for executeQuery operation', cause: 'Execute Query was selected without SQL Query.', fix: 'Enter a PostgreSQL/Timescale SQL statement and Params if needed.' },
    { error: 'where clause is required for update operation / where clause is required for delete operation', cause: 'A write/delete operation is missing its row filter.', fix: 'Add narrow Where JSON such as {"device_id":"{{$json.deviceId}}"}.' },
    { error: 'timeColumn/interval/bucketColumn/valueColumn is required for <operation> operation', cause: 'A Timescale helper is missing its required time-series field.', fix: 'Fill Time Column and Bucket Interval, plus Group Column for Time Bucket or Value Column for First/Last.' },
    { error: 'TimescaleDB operation failed', cause: 'Connection, SSL, table name, column name, SQL syntax, interval, or permission failed in PostgreSQL/TimescaleDB.', fix: 'Test SELECT 1, verify SSL, confirm table/column names, and use Execute Query for advanced filters.' },
  ],
  relatedNodes: ['postgresql', 'sql_server', 'mysql', 'db'],
};
