import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const trelloWebhookDocs = 'https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved Trello connection ID (API key, token, app secret). If blank, the active Trello connection is used.',
    helpText: 'What this field means: Connection points to the saved Trello credential (API Key, API Token, and App Secret) CtrlChecks uses to register the webhook and validate incoming deliveries. Why it matters: CtrlChecks needs the API key/token to call Trello\'s webhook API, and the App Secret to verify the X-Trello-Webhook signature on every delivery — without the App Secret specifically, registration fails outright. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active Trello connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save the Trello API Key, Token, and App Secret. How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not raw API credentials. Real workplace example: A project management team saves one Trello connection for the account that owns their boards, and every Trello Trigger node reuses it. If it is empty or wrong: Empty falls back to the active Trello connection; a missing App Secret causes Trello Trigger requires the Trello app secret for X-Trello-Webhook signature validation. Common mistake: Saving the API Key and Token but forgetting the App Secret — ordinary Trello actions do not need it, but this trigger cannot register or validate webhooks without it.',
    placeholder: 'Uses your active Trello connection',
    example: 'trello_api_key_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Model ID',
    internalKey: 'modelId',
    type: 'string',
    required: true,
    description: 'Board/card/member model ID Trello should watch.',
    helpText: 'What this field means: Model ID is the exact Trello object (board, card, member, or organization) this trigger\'s webhook is registered against. Why it matters: Trello webhooks belong to one idModel; this is the single most important setting because it decides what Trello will ever send you at all — everything else (Board/List/Card/Member ID filters) only narrows events after they already arrive. When to fill it: Always required — the trigger cannot register a webhook without it. What to enter: A Trello board ID for broad board/list/card activity (the most common choice), or a specific card or member ID for a narrower webhook that only watches that one object. Where the value comes from: Open the board in Trello, add .json to the URL (or use the Trello API\'s /1/members/me/boards endpoint) to find the board\'s ID, or read {{$json.boardId}}/{{$json.cardId}} from a previous test event. How to use it later: The trigger output includes {{$json.boardId}} and {{$json.cardId}} regardless of which model you watched. Accepted format: Trello object ID text (24-character hex string). Real workplace example: A support team sets Model ID to their support board\'s ID so all card activity on that board can start workflows. If it is empty or wrong: Leaving it blank fails validation with A Trello model ID is required; a wrong ID causes Trello API errors during registration because that object may not exist or the token cannot access it. Common mistake: Pasting the board\'s short URL name (like acme-support) instead of its actual ID — Trello IDs are 24-character hex strings, not the readable URL slug.',
    placeholder: 'board id',
    example: '5f8a1b2c3d4e5f6a7b8c9d0e',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'string',
    required: false,
    description: 'Comma-separated event filters.',
    helpText: 'What this field means: Event Types decides which normalized Trello activity kinds are accepted after the webhook has already delivered them, based on Model ID. Why it matters: A board webhook delivers every action on that board (card, list, checklist, member changes); this keeps a card-focused workflow from firing on unrelated list renames or checklist edits. When to fill it: Keep the default while testing; narrow it before production so only relevant activity starts the workflow. What to enter: Comma-separated normalized values such as card_created, card_updated, card_moved, card_commented, card_deleted, card_member_changed, card_label_changed, list_activity, checklist_activity. You can also use Trello\'s raw action type (such as updateCard) directly. Where the value comes from: Pick from the normalized event families your workflow should react to. How to use it later: Route with {{$json.eventType}}; card_moved is a special case of updateCard detected when listBefore/listAfter data is present. Accepted format: Comma-separated text, matched case-insensitively. Real workplace example: card_moved, card_commented for a workflow that tracks status changes and customer replies; list_activity for a workflow watching board structure changes. If it is empty or wrong: Empty defaults to card_created, card_updated, card_moved, card_commented, list_activity, checklist_activity. A value that never matches an incoming action silently ignores that event with Ignored Trello event type. Common mistake: Expecting card_updated to exclude moves — Trello reports every card move as an updateCard action; this trigger reclassifies it as card_moved only when list data is present, otherwise it stays card_updated.',
    placeholder: 'card_created, card_moved, card_commented',
    defaultValue: 'card_created, card_updated, card_moved, card_commented',
    example: 'card_moved',
  },
  {
    name: 'Board ID',
    internalKey: 'boardId',
    type: 'string',
    required: false,
    description: 'Optional board filter.',
    helpText: 'What this field means: Board ID restricts this trigger to events belonging to one specific Trello board. Why it matters: This is mainly useful when Model ID points to a member or organization (which can span multiple boards) and you still want to scope the workflow to one board. When to fill it: Fill it when Model ID is not already a board ID, or as an extra safety filter even when it is. Leave it blank otherwise — filtering by Model ID already handles most single-board setups. What to enter: The Trello board ID, not its name or short URL slug. Where the value comes from: Read {{$json.boardId}} from a previous test event, or the board\'s .json export. How to use it later: The trigger output includes {{$json.boardId}} and {{$json.boardName}} for logging or routing. Accepted format: Trello board ID text (24-character hex string). Real workplace example: A member-level webhook (Model ID set to a Trello member) sets Board ID to filter down to just one of that member\'s several boards. If it is empty or wrong: Empty accepts events from any board the webhook covers; a board ID that never matches silently ignores the event with Ignored Trello event for board. Common mistake: Using this field expecting it to also register the webhook narrowly — the actual Trello subscription scope is controlled by Model ID; this field only filters afterward.',
    placeholder: 'board id',
    example: '5f8a1b2c3d4e5f6a7b8c9d0e',
  },
  {
    name: 'List ID',
    internalKey: 'listId',
    type: 'string',
    required: false,
    description: 'Optional list filter.',
    helpText: 'What this field means: List ID restricts this trigger to events involving one specific Trello list. Why it matters: A board can have many lists (To Do, In Progress, Done); this keeps a list-specific workflow (such as "notify when a card reaches Done") from reacting to every list on the board. When to fill it: Fill it when the workflow should only react to cards in, entering, or leaving one particular list. Leave it blank to accept activity from every list on the board. What to enter: The Trello list ID, not its display name. Where the value comes from: Read {{$json.listId}}, {{$json.listBeforeId}}, or {{$json.listAfterId}} from a previous test event, or the board\'s .json export. How to use it later: For moved cards, this matches against either the before or after list, so both "cards leaving" and "cards entering" workflows are possible depending on how you branch on {{$json.listAfterId}} vs {{$json.listBeforeId}}. Accepted format: Trello list ID text (24-character hex string). Real workplace example: A fulfillment workflow sets List ID to the Done list\'s ID so it only reacts when a card is moved into or already active in that list. If it is empty or wrong: Empty accepts events from any list; a list ID that never matches (in either before or after position) silently ignores the event with Ignored Trello event outside list. Common mistake: Typing the list\'s display name (such as Done) instead of its ID.',
    placeholder: 'list id',
    example: '5f8a1b2c3d4e5f6a7b8c9d0f',
  },
  {
    name: 'Card ID',
    internalKey: 'cardId',
    type: 'string',
    required: false,
    description: 'Optional card filter.',
    helpText: 'What this field means: Card ID restricts this trigger to events about one specific Trello card. Why it matters: This turns a board-wide trigger into a focused watcher on a single, already-known card. When to fill it: Fill it only when you need a workflow tied to one specific card, such as watching a single incident-tracking card for comments. Leave it blank for normal board-wide workflows. What to enter: The Trello card ID, not its name or short link. Where the value comes from: Read {{$json.cardId}} from a previous test event, or open the card and use Share -> Link to see its short link, then resolve the full ID via the card\'s .json export. How to use it later: The trigger output includes {{$json.cardId}}, {{$json.cardName}}, and {{$json.cardUrl}} for confirmation or logging. Accepted format: Trello card ID text (24-character hex string). Real workplace example: A release manager sets Card ID to a specific "Release Checklist" card so they get notified of any comment on it. If it is empty or wrong: Empty accepts events for any card; an ID that never matches silently ignores it with Ignored Trello event for card. Common mistake: Pasting the card\'s short link (like abc12345) instead of its full 24-character ID.',
    placeholder: 'card id',
    example: '5f8a1b2c3d4e5f6a7b8c9d10',
  },
  {
    name: 'Member ID Filter',
    internalKey: 'memberId',
    type: 'string',
    required: false,
    description: 'Optional Trello member ID filter.',
    helpText: 'What this field means: Member ID Filter restricts this trigger to events created by, or involving, one specific Trello member. Why it matters: It lets you build a workflow around one particular teammate\'s activity, such as tracking everything a specific project lead does. When to fill it: Fill it only for person-specific automations. Leave it blank for normal team-wide triggers so any member\'s activity can start the workflow. What to enter: The Trello member ID, not their username or display name. Where the value comes from: Read {{$json.userId}} or {{$json.memberId}} from a previous test event triggered by that person, or use Trello\'s /1/members/{username} API to look up their ID. How to use it later: The trigger output includes {{$json.userId}}, {{$json.memberId}}, and {{$json.memberName}} for confirmation or logging. Accepted format: Trello member ID text (24-character hex string). Real workplace example: A workflow watches only the project lead\'s card creations so a Slack channel gets pinged specifically when they add new work. If it is empty or wrong: Empty accepts events from any member; an ID that never matches (as either the action performer or the affected member) silently ignores the event with Ignored Trello event not involving member. Common mistake: Entering the member\'s @username instead of their Trello member ID.',
    placeholder: 'member id',
    example: '5f8a1b2c3d4e5f6a7b8c9d11',
  },
  {
    name: 'Keyword Filter',
    internalKey: 'query',
    type: 'string',
    required: false,
    description: 'Optional keyword filter matched against card names and comment text.',
    helpText: 'What this field means: Keyword Filter only lets events whose card name or comment text contains a word or phrase start the workflow. Why it matters: A busy board can produce a lot of activity; this keeps a workflow focused on a specific term without needing a separate board or webhook. When to fill it: Use it when the workflow should react only to a phrase such as urgent, a customer name, or a specific card label word. Leave it blank to accept every event matching the other filters. What to enter: A simple keyword or short phrase, not Trello search syntax. Where the value comes from: Pick the label, customer name, or keyword your team uses in card titles or comments. How to use it later: The accepted event output still includes {{$json.cardName}} and {{$json.commentText}} for downstream routing. Accepted format: Plain text, case-insensitive contains match. Real workplace example: urgent starts only card/comment workflows whose card name or comment mentions urgent. If it is empty or wrong: Empty accepts every event matching the other filters; a too-specific or misspelled filter causes Ignored Trello event not matching this trigger. Common mistake: Expecting Trello\'s search syntax (such as board:X label:red) here — this is a simple text contains filter, not Trello search.',
    placeholder: 'urgent',
    example: 'urgent',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Card Activity',
  value: 'card_events',
  description: 'Starts the workflow when a Trello webhook delivery for the watched board/card/member arrives, after Trello\'s HEAD callback validation and the X-Trello-Webhook HMAC signature check.',
  fields,
  outputExample: {
    eventId: '5f8a1b2c3d4e5f6a7b8c9d20',
    eventType: 'card_moved',
    source: 'trello',
    userId: '5f8a1b2c3d4e5f6a7b8c9d11',
    username: 'alexmorgan',
    text: 'Follow up',
    timestamp: '2026-07-19T10:20:00.000Z',
    actionId: '5f8a1b2c3d4e5f6a7b8c9d20',
    actionType: 'updateCard',
    boardId: '5f8a1b2c3d4e5f6a7b8c9d0e',
    boardName: 'Support Board',
    boardUrl: 'https://trello.com/b/abc12345',
    listId: null,
    listName: null,
    listBeforeId: 'todo_list_id',
    listBeforeName: 'To Do',
    listAfterId: 'done_list_id',
    listAfterName: 'Done',
    cardId: '5f8a1b2c3d4e5f6a7b8c9d10',
    cardName: 'Follow up',
    cardUrl: 'https://trello.com/c/abc12345',
    cardShortLink: 'abc12345',
    commentText: null,
    checklistId: null,
    checklistName: null,
    checkItemId: null,
    checkItemName: null,
    memberId: '5f8a1b2c3d4e5f6a7b8c9d11',
    memberName: 'Alex Morgan',
    raw: {},
    trigger: 'trello',
    workflow_id: 'workflow_123',
    node_id: 'trello-trigger-1',
    sessionId: 'trello_workflow_123_5f8a1b2c3d4e5f6a7b8c9d20',
    _trello: true,
  },
  outputDescription: 'eventId: the Trello action ID, or a generated fallback. eventType: normalized activity such as card_created, card_updated, card_moved, card_commented, card_deleted, card_member_changed, card_label_changed, list_activity, or checklist_activity. source: trello. userId/username: the member who performed the action. text: comment text, card name, or a generated fallback. timestamp: Trello\'s action date. actionId/actionType: the raw Trello action ID and its original action type (such as updateCard) before normalization. boardId/boardName/boardUrl: the board the action occurred on. listId/listName: populated for non-move list actions; null for card_moved (use listBeforeId/listAfterId instead). listBeforeId/listBeforeName/listAfterId/listAfterName: populated only for card_moved events. cardId/cardName/cardUrl/cardShortLink: card identity. commentText: populated only for card_commented events. checklistId/checklistName/checkItemId/checkItemName: populated only for checklist_activity events. memberId/memberName: the member the action is about (may differ from userId/username, which is who performed it). raw: the original Trello webhook payload. trigger/workflow_id/node_id/sessionId/_trello: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Create a follow-up task when a Trello card is moved to Done',
    inputValues: {
      modelId: '5f8a1b2c3d4e5f6a7b8c9d0e',
      eventTypes: 'card_moved',
      boardId: '',
      listId: '',
      cardId: '',
      memberId: '',
      query: '',
    },
    expectedOutput: 'A normalized Trello card movement payload available as {{$json.cardId}}, {{$json.listAfterId}}, and {{$json.cardName}} for a downstream task or notification node.',
  },
  externalDocsUrl: trelloWebhookDocs,
};

export const trelloTriggerDoc: NodeDoc = {
  slug: 'trello_trigger',
  displayName: 'Trello Trigger',
  category: 'Triggers',
  logoUrl: '/icons/nodes/trello.svg',
  description: 'Start a workflow from signed Trello webhook events for cards, lists, comments, members, and checklists.',
  credentialType: 'Trello API Key & Token',
  credentialSetupSteps: [
    'Open trello.com/power-ups/admin (or trello.com/app-key) while signed in.',
    'Copy the API Key, then generate and copy the API Token, and copy the App Secret from the same page.',
    'In CtrlChecks, open Connections -> Add Connection -> Trello and save all three values — the App Secret specifically is required for this trigger\'s webhook signature validation, even though ordinary Trello actions do not need it.',
    'Set Model ID to the Trello board (or card/member) ID you want to watch, then save and activate the workflow so CtrlChecks can register the webhook.',
    'Trello validates the callback URL with an HTTP HEAD request during registration and requires it to return 200 before the webhook is created — this happens automatically; PUBLIC_BASE_URL must point to a reachable HTTPS URL.',
    'Every real delivery afterward is signed with X-Trello-Webhook (HMAC-SHA1 of the raw body plus the exact callback URL), which CtrlChecks validates automatically.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this Trello connection only authorizes registering the webhook, not the CRM, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: trelloWebhookDocs,
  resources: [
    {
      name: 'Webhook Events',
      description: 'Receive Trello webhook deliveries after Trello validates the callback URL with HEAD and signs POST bodies with X-Trello-Webhook.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Trello Trigger requires the Trello app secret for X-Trello-Webhook signature validation. Add App Secret to your Trello connection.',
      cause: 'The saved Trello connection has an API Key and Token but no App Secret.',
      fix: 'Edit the Trello connection and add the App Secret from trello.com/power-ups/admin, then re-activate the workflow.',
    },
    {
      error: 'A Trello model ID is required. Use a board ID for board/list/card activity, or a card/member ID for narrower events.',
      cause: 'Model ID was left blank when saving or activating the workflow.',
      fix: 'Open the Trello Trigger node and paste a Trello board, card, or member ID into Model ID.',
    },
    {
      error: 'No active Trello connection found. Save a Trello API Key & Token connection first.',
      cause: 'The workflow owner has not connected Trello, or the saved credentials are incomplete.',
      fix: 'Save a valid Trello API Key, Token, and App Secret in Connections, then re-activate the workflow.',
    },
    {
      error: 'Invalid Trello webhook signature.',
      cause: 'The X-Trello-Webhook header did not match the HMAC computed from the stored App Secret and the exact registered callback URL.',
      fix: 'Re-register the webhook by saving the active workflow again so the callback URL and secret are back in sync.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'A valid, signed Trello delivery arrived, but the workflow has not been activated.',
      fix: 'Activate the workflow in CtrlChecks, then trigger another real Trello action.',
    },
    {
      error: 'Ignored non-actionable Trello payload.',
      cause: 'The delivery had no recognizable action type, such as Trello\'s own connectivity check.',
      fix: 'No action needed for connectivity checks; confirm Model ID/Event Types if you expected a real workflow run.',
    },
    {
      error: 'Ignored Trello event not matching this trigger.',
      cause: 'The event was valid, but Event Types, Board ID, List ID, Card ID, Member ID Filter, or Keyword Filter filtered it out.',
      fix: 'Broaden the relevant filter, clear filters temporarily, trigger a fresh Trello action, then narrow the filters again after confirming the output.',
    },
    {
      error: 'Trello API error (401/404): ...',
      cause: 'The API Key/Token is invalid or expired, or Model ID does not exist or is not accessible to that token.',
      fix: 'Confirm the credentials are current in Trello and that Model ID is a real board/card/member ID your token can access.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register Trello webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Trello must call and HEAD-validate.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then save/activate the workflow again.',
    },
    {
      error: 'Next node cannot find Trello trigger fields',
      cause: 'A downstream node is mapped to a field only present for another event family, such as {{$json.commentText}} on a card_moved event.',
      fix: 'Use {{$json.eventType}} to branch by activity family before mapping event-specific fields.',
    },
    {
      error: 'Permission denied after Trello Trigger',
      cause: 'The trigger fired correctly, but the downstream Trello action, Slack, email, or ticketing node lacks its own account connection or permission.',
      fix: 'Connect the downstream service node under Connections and confirm the Trello token has access to the board the action targets.',
    },
  ],
  relatedNodes: ['trello', 'jira_trigger', 'linear'],
};
