import type { FieldDoc, NodeDoc, OperationDoc } from '../types';

const whatsappWebhookDocs = 'https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks';

const fields: FieldDoc[] = [
  {
    name: 'Connection',
    internalKey: 'connectionId',
    type: 'string',
    required: false,
    description: 'Optional saved WhatsApp connection ID. If blank, the active WhatsApp connection is used.',
    helpText: 'What this field means: Connection points to the saved WhatsApp Business API credential (permanent access token and Phone Number ID) CtrlChecks uses to subscribe the WhatsApp Business Account to webhook events. Why it matters: CtrlChecks uses this connection during registration to look up the Business Account ID and subscribe the app to receive events for it. When to fill it: You do not fill this in the current visual panel — it is not one of the exposed config fields; CtrlChecks always resolves your active WhatsApp connection automatically. What to enter: Nothing in the panel; manage the credential itself under Connections. Where the value comes from: CtrlChecks Connections stores it after you save the WhatsApp access token and Phone Number ID (tested against GET graph.facebook.com/v19.0/{phoneNumberId}?fields=display_phone_number,verified_name). How to use it later: This is a setup value only; it is not emitted as {{$json.connectionId}} to downstream nodes. Accepted format: Saved connection reference, not a raw access token. Real workplace example: A support team connects one WhatsApp Business number, and every WhatsApp Trigger node in the workspace reuses it. If it is empty or wrong: Empty falls back to the active WhatsApp connection; a missing or invalid connection can cause No active WhatsApp connection found. Common mistake: Pasting the raw Meta access token into a normal workflow field instead of connecting WhatsApp in Connections.',
    placeholder: 'Uses your active WhatsApp connection',
    example: 'whatsapp_api_key_123',
    notes: 'Credential-owned backend field, not currently exposed as a visual config field. Manage it from Connections instead.',
  },
  {
    name: 'Event Types',
    internalKey: 'eventTypes',
    type: 'select',
    required: true,
    description: 'WhatsApp event type that can start the workflow.',
    helpText: 'What this field means: Event Types decides which normalized WhatsApp Cloud events (incoming messages vs. delivery status updates) this trigger accepts. Why it matters: A chatbot workflow only cares about incoming messages, while a delivery-tracking workflow only cares about status changes — mixing both into one workflow usually causes confusing branching. When to fill it: Always required. Choose Incoming Messages for the vast majority of chatbot workflows. What to enter: One of: Incoming Messages (message — matches any message type), Text Messages (message.text), Media Messages (message.media), Delivery Statuses (status — matches any status type), Delivered (status.delivered), Read (status.read), or Failed (status.failed). Where the value comes from: Decide which Meta WhatsApp Cloud webhook field your workflow should react to. How to use it later: The trigger output includes {{$json.eventType}}, which is always one of message.text, message.media, status.sent, status.delivered, status.read, status.failed, or the broader status/message forms. Accepted format: One of the seven listed dropdown values. Real workplace example: Incoming Messages for an AI support chatbot; Delivered for a workflow that logs message delivery confirmations. If it is empty or wrong: This field is required in the panel, so it cannot be left blank; the backend default is message if somehow omitted. Common mistake: Selecting Delivery Statuses expecting message content — status events never include {{$json.text}}, only delivery state in {{$json.status}}.',
    placeholder: 'message',
    defaultValue: 'message',
    example: 'message',
    options: ['message', 'message.text', 'message.media', 'status', 'status.delivered', 'status.read', 'status.failed'],
    notes: 'Dropdown labels: Incoming Messages (message), Text Messages (message.text), Media Messages (message.media), Delivery Statuses (status), Delivered (status.delivered), Read (status.read), Failed (status.failed).',
  },
  {
    name: 'Phone Number ID',
    internalKey: 'phoneNumberId',
    type: 'string',
    required: false,
    description: 'Optional Meta WhatsApp Phone Number ID filter.',
    helpText: 'What this field means: Phone Number ID restricts this trigger to events for one specific WhatsApp Business phone number. Why it matters: A Business Account can have several phone numbers; without this filter, events for every number the app is subscribed to could start this workflow. When to fill it: Fill it when your Meta app manages multiple WhatsApp numbers and this workflow should only react to one of them. Leave it blank to accept events for the connected account\'s number. What to enter: The numeric Phone Number ID from Meta, not the actual phone number digits. Where the value comes from: Meta for Developers -> WhatsApp -> API Setup shows the Phone Number ID for the number you configured. How to use it later: The trigger output includes {{$json.phoneNumberId}} and {{$json.displayPhoneNumber}} for confirmation or logging. Accepted format: Numeric ID text such as 123456789012345. Real workplace example: A company with separate support and sales WhatsApp numbers filters the support workflow to only the support number\'s Phone Number ID. If it is empty or wrong: Empty accepts events for the connected account\'s number; a wrong ID causes valid events to be ignored as a different number with Ignored WhatsApp event for a different phone number ID. Common mistake: Entering the actual phone number (such as +15551234567) instead of Meta\'s numeric Phone Number ID.',
    placeholder: '123456789012345',
    example: '123456789012345',
  },
  {
    name: 'Allowed Senders',
    internalKey: 'allowedWaIds',
    type: 'string',
    required: false,
    description: 'Optional comma-separated WhatsApp sender allowlist.',
    helpText: 'What this field means: Allowed Senders limits the trigger to specific WhatsApp senders, identified by their WhatsApp ID (a phone number without formatting). Why it matters: It can keep a testing or VIP workflow from reacting to every person who messages the business number. When to fill it: Use it for internal testing, approved partner accounts, or a controlled rollout. Leave it blank for a normal public WhatsApp automation. What to enter: Comma-separated WhatsApp IDs such as 15551234567 (country code plus number, no plus sign or spaces). Where the value comes from: Read {{$json.waId}} or {{$json.chatId}} from a previous test message, or the customer\'s phone number in international format without the leading +. How to use it later: The accepted event output still outputs {{$json.waId}} and {{$json.chatId}} for replies or audits. Accepted format: Comma-separated numeric strings, no + or spaces. Real workplace example: Before launching a WhatsApp assistant, the team allows only two employee numbers so they can test without responding to real customers. If it is empty or wrong: Empty allows every matching sender; a WhatsApp ID that never matches silently ignores that person\'s events with Ignored WhatsApp event from a sender that is not allowed. Common mistake: Including a leading + or spaces/dashes in the phone number — Meta sends WhatsApp IDs as plain digits only.',
    placeholder: '15551234567,15557654321',
    example: '15551234567',
  },
  {
    name: 'Verify Token',
    internalKey: 'verifyToken',
    type: 'string',
    required: true,
    description: 'Secret value Meta sends during webhook URL verification.',
    helpText: 'What this field means: Verify Token is the shared text Meta sends during the webhook challenge to prove you configured the callback intentionally. Why it matters: Meta will not activate the webhook callback unless CtrlChecks returns the challenge for the exact matching token. When to fill it: Always required — fill it before verifying the callback URL in Meta for Developers. What to enter: A random phrase or generated secret unique to this workflow, such as wa-webhook-verify-2026. Where the value comes from: Create it yourself in a password manager or admin setup note, then enter the exact same value in Meta for Developers -> WhatsApp -> Configuration. How to use it later: This token is only for webhook setup; it is never emitted as {{$json.verifyToken}} to downstream nodes. Accepted format: Plain text shared token. Real workplace example: The support operations admin sets wa-support-prod-verify-rotate-me while adding the CtrlChecks callback URL to the Meta app. If it is empty or wrong: Callback verification returns Invalid verify token, and Meta will not save the webhook URL. Common mistake: Confusing this with the WhatsApp access token, app secret, or account password.',
    placeholder: 'a-long-random-secret',
    example: 'wa_verify_abc123',
  },
  {
    name: 'Validate Signature',
    internalKey: 'validateSignature',
    type: 'boolean',
    required: false,
    description: 'Validates Meta X-Hub-Signature-256 using the worker app secret.',
    helpText: 'What this field means: Validate Signature checks that Meta signed the webhook request with your app secret. Why it matters: A public webhook URL should reject requests that did not come through the expected Meta app. When to fill it: Keep it enabled for production. Disable only for a controlled local test where you cannot generate Meta signatures. What to enter: true/enabled for real workflows; false/disabled only for temporary debugging. Where the value comes from: This is a security choice made by the workflow owner or admin. The app secret itself comes from worker environment variables META_APP_SECRET, FACEBOOK_APP_SECRET, or WHATSAPP_APP_SECRET, not from a workflow field. How to use it later: This setting protects whether a workflow starts; it is not output as {{$json.validateSignature}}. Accepted format: Boolean checkbox. Real workplace example: A live WhatsApp support workflow keeps validation enabled so only signed Meta webhook deliveries can create replies or tickets. If it is empty or wrong: Default true requires the worker app secret; if the secret is missing or mismatched, requests fail with Invalid WhatsApp webhook signature. Common mistake: Turning this off permanently instead of configuring META_APP_SECRET/FACEBOOK_APP_SECRET/WHATSAPP_APP_SECRET correctly.',
    defaultValue: 'true',
    example: 'true',
  },
];

const receiveOperation: OperationDoc = {
  name: 'Receive Event',
  value: 'receive_event',
  description: 'Starts the workflow when a matching WhatsApp Cloud message or delivery status event arrives, after validating the Meta X-Hub-Signature-256 signature.',
  fields,
  outputExample: {
    eventId: 'wamid.HBgM...',
    eventType: 'message.text',
    source: 'whatsapp',
    userId: '15551234567',
    username: 'Alex Morgan',
    text: 'Hi, I need help with my order',
    timestamp: '2026-07-19T10:20:00.000Z',
    chatId: '15551234567',
    from: '15551234567',
    waId: '15551234567',
    contactName: 'Alex Morgan',
    profileName: 'Alex Morgan',
    messageId: 'wamid.HBgM...',
    messageType: 'text',
    mediaId: null,
    status: '',
    recipientId: null,
    phoneNumberId: '123456789012345',
    displayPhoneNumber: '+1 555-123-4567',
    businessAccountId: 'waba_123456789',
    raw: {},
    trigger: 'whatsapp',
    workflow_id: 'workflow_123',
    node_id: 'whatsapp-trigger-1',
    sessionId: 'whatsapp_workflow_123_15551234567',
    _whatsapp: true,
  },
  outputDescription: 'eventId: the WhatsApp message/status ID, or a generated fallback. eventType: message.text, message.media, status.sent, status.delivered, status.read, or status.failed. source: whatsapp. userId: the sender\'s WhatsApp ID for messages, or the recipient ID for status updates. username/contactName/profileName: the sender\'s WhatsApp profile display name (all three are the same value), empty for status events. text: message body/caption/button text, empty for status events. timestamp: Meta\'s event time. chatId/from/waId: the WhatsApp ID to use as the reply target — chatId always equals from (or recipientId for statuses). messageId/messageType/mediaId: message-specific fields, empty/null for status events. status: delivery status (sent/delivered/read/failed), empty for message events. recipientId: populated only for status events. phoneNumberId/displayPhoneNumber: which of your WhatsApp Business numbers received the event. businessAccountId: the Meta WhatsApp Business Account ID. raw: the original Meta webhook payload fragment. trigger/workflow_id/node_id/sessionId/_whatsapp: CtrlChecks trigger metadata.',
  usageExample: {
    scenario: 'Reply to incoming WhatsApp messages with an AI Agent',
    inputValues: {
      eventTypes: 'message',
      phoneNumberId: '',
      allowedWaIds: '',
      verifyToken: 'wa_verify_abc123',
      validateSignature: 'true',
    },
    expectedOutput: 'WhatsApp Trigger -> AI Agent -> WhatsApp Send Text with To = {{$json.chatId}}.',
  },
  externalDocsUrl: whatsappWebhookDocs,
};

export const whatsappTriggerDoc: NodeDoc = {
  slug: 'whatsapp_trigger',
  displayName: 'WhatsApp Trigger',
  category: 'Triggers',
  logoUrl: '/icons/nodes/whatsapp_trigger.svg',
  description: 'Start a workflow in real time when Meta WhatsApp Cloud sends an incoming message or delivery status webhook.',
  credentialType: 'WhatsApp Business API',
  credentialSetupSteps: [
    'Create or open a Meta app with the WhatsApp product enabled.',
    'In Meta for Developers -> WhatsApp -> API Setup, copy the permanent access token and Phone Number ID.',
    'In CtrlChecks -> Connections -> Add Connection -> WhatsApp, save the access token and Phone Number ID (tested against GET graph.facebook.com/v19.0/{phoneNumberId}?fields=display_phone_number,verified_name).',
    'Set META_APP_SECRET, FACEBOOK_APP_SECRET, or WHATSAPP_APP_SECRET on the worker so CtrlChecks can validate X-Hub-Signature-256.',
    'In your WhatsApp Trigger node, choose Event Types (Incoming Messages for most chatbot workflows), enter a Verify Token, save and activate the workflow.',
    'Use the webhook URL returned after save (or from /api/whatsapp/webhook/register) as the Meta callback URL, and use the same Verify Token in Meta for Developers -> WhatsApp -> Configuration.',
    'Activation attempts to subscribe your WhatsApp Business Account to app events automatically; the setup status still marks manualSetupRequired: true, so confirm the subscription in Meta if the automatic subscribe call is not permitted.',
    'Connect the trigger output to the next step with the outgoing line. Each downstream service node still needs its own account connection; this WhatsApp connection only authorizes registering the webhook and reading account info, not the CRM, email, database, or AI nodes that come after this trigger.',
  ],
  credentialDocsUrl: whatsappWebhookDocs,
  resources: [
    {
      name: 'Webhook',
      description: 'Receive Meta WhatsApp Cloud webhook events and normalize them for downstream nodes.',
      operations: [receiveOperation],
    },
  ],
  commonErrors: [
    {
      error: 'Invalid verify token.',
      cause: 'The token Meta sent during webhook verification does not match the Verify Token configured on the node.',
      fix: 'Copy the exact Verify Token from the WhatsApp Trigger node into Meta for Developers -> WhatsApp -> Configuration, then verify the callback URL again.',
    },
    {
      error: 'Invalid WhatsApp webhook signature.',
      cause: 'Validate Signature is enabled and the worker has no META_APP_SECRET/FACEBOOK_APP_SECRET/WHATSAPP_APP_SECRET, the secret is wrong, or the request was not signed by the configured Meta app.',
      fix: 'Set the correct app secret on the worker, restart it, and retry a real Meta webhook delivery. Disable validation only for temporary local tests.',
    },
    {
      error: 'Workflow is not active.',
      cause: 'A valid, signed WhatsApp event arrived, but the workflow has not been activated.',
      fix: 'Activate the workflow in CtrlChecks, then send another real WhatsApp message.',
    },
    {
      error: 'No active WhatsApp connection found. Create one in Connections first.',
      cause: 'The workflow owner has not saved a WhatsApp connection, or it is expired/revoked.',
      fix: 'Reconnect WhatsApp in CtrlChecks -> Connections with a valid access token and Phone Number ID, then activate the workflow again.',
    },
    {
      error: 'Selected connection is not a WhatsApp connection.',
      cause: 'The saved connection ID points to another provider or an inactive credential.',
      fix: 'Select a WhatsApp connection or leave Connection blank so CtrlChecks can use the active one.',
    },
    {
      error: 'WhatsApp access token is missing from the selected connection.',
      cause: 'The saved connection exists but has no usable access token value.',
      fix: 'Re-save the WhatsApp connection with a fresh permanent access token from Meta for Developers.',
    },
    {
      error: 'PUBLIC_BASE_URL is required to register WhatsApp webhooks.',
      cause: 'CtrlChecks cannot build the public callback URL Meta must call.',
      fix: 'Set PUBLIC_BASE_URL to the externally reachable CtrlChecks app URL, then open the webhook setup/registration flow again.',
    },
    {
      error: 'Next node cannot find WhatsApp trigger fields',
      cause: 'A downstream node is mapped to a field only present for another event kind, such as {{$json.text}} on a status.delivered event, which is always empty.',
      fix: 'Use {{$json.eventType}} to branch message events from status events before mapping event-specific fields.',
    },
    {
      error: 'Permission denied after WhatsApp Trigger',
      cause: 'The trigger received the event, but the downstream WhatsApp reply, CRM, email, or ticketing node lacks its own connection or permission.',
      fix: 'Connect the downstream service node account connection and confirm the WhatsApp access token has permission to send messages.',
    },
  ],
  relatedNodes: ['whatsapp', 'ai_agent'],
};
