import type { NodeDoc } from '../types';

export const writeBinaryFileDoc: NodeDoc = {
  slug: 'write_binary_file',
  displayName: 'Write Binary File',
  category: 'Data',
  logoUrl: '/icons/nodes/write_binary_file.svg',
  description: 'Create a managed workflow file asset from base64, a data URL, or plain text.',
  credentialType: 'None',
  credentialSetupSteps: [
    'This node does not need a saved account connection.',
    'Provide a file name and Binary Data.',
    'Keep Persist Metadata enabled when later nodes need to read the file by Asset ID.',
    'Use Google Drive, S3, Dropbox, or OneDrive nodes when you want to upload the file to cloud storage.',
  ],
  credentialDocsUrl: 'https://docs.ctrlchecks.com',
  resources: [
    {
      name: 'Configuration',
      description: 'Write Binary File stores bytes in the backend binary storage root and records metadata in workflow_file_assets.',
      operations: [
        {
          name: 'Configure',
          value: 'default',
          description: 'Create a managed workflow file asset.',
          fields: [
            {
              name: 'File Name',
              internalKey: 'fileName',
              type: 'string',
              required: true,
              description: 'Name for the file asset.',
              helpText: 'Include an extension so downstream nodes know the type.',
              placeholder: 'report.pdf',
              example: 'report.pdf',
            },
            {
              name: 'MIME Type',
              internalKey: 'mimeType',
              type: 'string',
              required: false,
              description: 'File MIME type.',
              helpText: 'Examples: application/pdf, image/png, text/csv.',
              placeholder: 'application/pdf',
              example: 'application/pdf',
            },
            {
              name: 'Binary Data',
              internalKey: 'dataBase64',
              type: 'string',
              required: true,
              description: 'Base64, data URL, or text payload to store.',
              helpText: 'Use {{$json.dataBase64}} from a previous download/PDF/file step. Data URLs like data:application/pdf;base64,... are also accepted.',
              placeholder: '{{$json.dataBase64}}',
              example: '{{$json.dataBase64}}',
            },
            {
              name: 'Folder',
              internalKey: 'folder',
              type: 'string',
              required: false,
              description: 'Optional namespace under managed workflow storage.',
              helpText: 'Examples: reports, invoices/2026.',
              placeholder: 'reports',
              example: 'reports',
            },
            {
              name: 'Persist Metadata',
              internalKey: 'persist',
              type: 'boolean',
              required: false,
              description: 'Save metadata in the database for Asset ID lookup.',
              helpText: 'Keep enabled for normal workflows.',
              placeholder: 'true',
              example: 'true',
            },
          ],
          outputExample: {
            success: true,
            assetId: 'asset-id',
            fileName: 'report.pdf',
            mimeType: 'application/pdf',
            sizeBytes: 2048,
            dataBase64: 'JVBERi0x...',
            storageKey: 'users/.../report.pdf',
            metadataPersisted: true,
          },
          outputDescription: 'Returns assetId, dataBase64, fileName, mimeType, sizeBytes, checksumSha256, storageProvider, storageKey, and filePath.',
          usageExample: {
            scenario: 'Save a generated PDF and upload it to Google Drive',
            inputValues: {
              fileName: 'report.pdf',
              mimeType: 'application/pdf',
              dataBase64: '{{$json.dataBase64}}',
            },
            expectedOutput: 'Use {{$json.assetId}} to read it later or {{$json.dataBase64}} to upload it immediately.',
          },
          externalDocsUrl: 'https://docs.ctrlchecks.com',
        },
      ],
    },
  ],
  commonErrors: [
    {
      error: 'dataBase64, data, content, fileData, or fileContent is required',
      cause: 'No file bytes were provided.',
      fix: 'Pass {{$json.dataBase64}} from a previous download/PDF/file step or paste a data URL.',
    },
    {
      error: 'unsafe file path outside binary storage root',
      cause: 'A custom path points outside the configured safe storage directory.',
      fix: 'Leave Custom Storage Path empty or use a relative path under BINARY_FILE_ROOT.',
    },
  ],
  relatedNodes: ['read_binary_file', 'google_drive', 'pdf', 'aws_s3', 'dropbox', 'onedrive'],
};
