const fs = require('fs');
const existing = fs.readFileSync('TODO_MASTER_IMPLEMENTATION_PLAN.md', 'utf8');
const lines = existing.split('\n');
const L = (s) => lines.push(s === undefined ? '' : s);

L();
L('---');
L();
L('## SECTION 6 - AI WORKFLOW GENERATION PIPELINE FIXES');
L('### Estimated: 6-8 days | Owner: Backend AI Team');
L();
L('### 6.1 - Workflow Planner Fixes');
L('- [ ] Fix workflow-planner.ts: ensure it can generate agent workflows when user asks for an agent - 3h');
L('- [ ] Fix workflow-planner.ts: ensure it generates trigger nodes when user describes event-based workflows - 2h');
L('- [ ] Add agent workflow template to workflow-templates.ts: ai_agent + chat_model + memory + tools - 2h');
L('- [ ] Add trigger workflow templates: gmail_trigger + action, webhook + action, schedule + action - 2h');
L('- [ ] Fix intent-engine.ts: detect agent intent keywords (agent, assistant, chatbot, autonomous) - 2h');
L('- [ ] Fix intent-engine.ts: detect trigger intent keywords (when, on new, every time, triggered by) - 2h');
L('- [ ] Fix node-resolver.ts: resolve agent sub-node types (chat_model, memory, tool) correctly - 2h');
L();
L('### 6.2 - Workflow DSL Compiler Fixes');
L('- [ ] Fix workflow-dsl-compiler.ts: support agent node compilation with sub-nodes - 3h');
L('- [ ] Fix workflow-dsl-compiler.ts: support trigger node compilation with event config - 2h');
L('- [ ] Add agent DSL type to workflow-dsl.ts: DSLAgentNode with model, memory, tools fields - 2h');
L('- [ ] Add trigger DSL type to workflow-dsl.ts: DSLTriggerNode with event and config fields - 2h');
L('- [ ] Fix DSL validation: validate agent nodes have at least one chat_model sub-node - 1h');
L();
L('### 6.3 - Workflow Builder Fixes');
L('- [ ] Fix workflow-builder.ts: hydrate agent node defaults from registry including sub-node defaults - 2h');
L('- [ ] Fix workflow-builder.ts: hydrate trigger node defaults from registry - 2h');
L('- [ ] Fix registry-based-node-hydrator.ts: handle agent sub-nodes during hydration - 2h');
L('- [ ] Fix workflow-validator.ts: validate agent node has chat_model attached - 1h');
L('- [ ] Fix workflow-validator.ts: validate trigger nodes have required event config - 1h');
L('- [ ] Fix final-workflow-validator.ts: include agent and trigger node validation - 2h');
L();
L('### 6.4 - System Prompt Updates');
L('- [ ] Update WORKFLOW_GENERATION_SYSTEM_PROMPT.md: add agent workflow generation instructions - 2h');
L('- [ ] Update WORKFLOW_GENERATION_SYSTEM_PROMPT.md: add trigger node generation instructions - 2h');
L('- [ ] Update WORKFLOW_GENERATION_SYSTEM_PROMPT.md: add all new trigger node types to available nodes list - 1h');
L('- [ ] Update WORKFLOW_GENERATION_SYSTEM_PROMPT.md: add agent sub-node types to available nodes list - 1h');
L('- [ ] Update CLARIFYING_QUESTIONS_SYSTEM_PROMPT.md: add questions for agent configuration - 1h');
L();
L('---');
L();
L('## SECTION 7 - DATABASE AND INFRASTRUCTURE');
L('### Estimated: 4-5 days | Owner: Backend/DevOps Team');
L();
L('### 7.1 - Supabase Schema Updates');
L('- [ ] Add trigger_state table: workflow_id, node_id, trigger_type, last_checked_at, cursor, is_active - 2h');
L('- [ ] Add active_triggers table: id, workflow_id, node_id, trigger_type, config, is_active, created_at - 2h');
L('- [ ] Add agent_executions table: id, workflow_id, session_id, status, messages, tool_calls, final_answer, iterations, created_at - 2h');
L('- [ ] Add agent_sessions table: id, workflow_id, user_id, memory_type, memory_data, created_at, updated_at - 2h');
L('- [ ] Add agent_tools table: id, agent_node_id, workflow_id, tool_node_type, tool_config, created_at - 2h');
L('- [ ] Enable pgvector extension in Supabase for vector memory - 1h');
L('- [ ] Add embeddings table: id, session_id, content, embedding vector(1536), created_at - 2h');
L('- [ ] Add RLS policies for all new tables: users can only access their own data - 2h');
L('- [ ] Add indexes: trigger_state(workflow_id, node_id), agent_executions(workflow_id, session_id) - 1h');
L();
L('### 7.2 - API Routes Registration');
L('- [ ] Register all trigger API routes in worker/src/index.ts - 1h');
L('- [ ] Register all agent API routes in worker/src/index.ts - 1h');
L('- [ ] Register memory API routes in worker/src/index.ts - 1h');
L('- [ ] Add rate limiting to trigger polling endpoints - 1h');
L('- [ ] Add authentication middleware to all new API routes - 1h');
L('- [ ] Add request validation middleware to all new API routes - 1h');
L();
L('### 7.3 - Environment Variables');
L('- [ ] Add TRIGGER_POLLING_INTERVAL_MS env var (default 60000) - 1h');
L('- [ ] Add AGENT_MAX_ITERATIONS env var (default 10) - 1h');
L('- [ ] Add AGENT_EXECUTION_TIMEOUT_MS env var (default 300000) - 1h');
L('- [ ] Add VECTOR_STORE_DIMENSIONS env var (default 1536 for OpenAI embeddings) - 1h');
L('- [ ] Add REDIS_URL env var for Redis memory backend - 1h');
L('- [ ] Document all new env vars in .env.example - 1h');
L();
L('---');
L();
L('## SECTION 8 - TESTING');
L('### Estimated: 8-10 days | Owner: Full Team');
L();
L('### 8.1 - Registry Tests');
L('- [ ] Write test: every node in node-library.ts has a matching entry in unified-node-registry.ts - 2h');
L('- [ ] Write test: every node in nodeTypes.ts (frontend) has a matching entry in node-library.ts (backend) - 2h');
L('- [ ] Write test: all trigger nodes have isTrigger=true in registry - 1h');
L('- [ ] Write test: all branching nodes have correct outgoingPorts - 1h');
L('- [ ] Write test: no duplicate node type registrations - 1h');
L('- [ ] Write test: all node defaultConfig() return valid objects with no undefined fields - 2h');
L('- [ ] Write test: all node validateConfig() catch missing required fields - 2h');
L();
L('### 8.2 - Agent Tests');
L('- [ ] Write test: agent ReAct loop executes correct number of iterations - 2h');
L('- [ ] Write test: agent tool call parser correctly extracts tool_name and tool_input - 2h');
L('- [ ] Write test: agent final answer detector stops loop correctly - 1h');
L('- [ ] Write test: agent memory stores and retrieves conversation turns - 2h');
L('- [ ] Write test: agent tool executor calls correct node executor - 2h');
L('- [ ] Write test: agent with no tools still works (pure LLM reasoning) - 1h');
L('- [ ] Write test: agent stops at maxIterations even if goal not achieved - 1h');
L('- [ ] Write test: agent handles tool execution error gracefully - 1h');
L();
L('### 8.3 - Trigger Tests');
L('- [ ] Write test: trigger polling service fires workflow when new item found - 2h');
L('- [ ] Write test: trigger deduplication prevents same item from firing twice - 2h');
L('- [ ] Write test: trigger activation/deactivation API works correctly - 1h');
L('- [ ] Write test: Gmail trigger correctly polls for new emails - 2h');
L('- [ ] Write test: webhook trigger correctly receives and processes POST request - 2h');
L('- [ ] Write test: schedule trigger fires at correct cron time - 2h');
L();
L('### 8.4 - Integration Tests');
L('- [ ] Write end-to-end test: Gmail trigger > AI agent > Slack message workflow - 3h');
L('- [ ] Write end-to-end test: Webhook trigger > Google Sheets write workflow - 2h');
L('- [ ] Write end-to-end test: Schedule trigger > HTTP request > log output workflow - 2h');
L('- [ ] Write end-to-end test: Form trigger > if_else > Gmail send workflow - 2h');
L('- [ ] Write end-to-end test: AI agent with Gmail tool + Sheets tool - 3h');
L('- [ ] Write end-to-end test: AI agent with memory across multiple sessions - 3h');
L();
L('### 8.5 - Frontend Tests');
L('- [ ] Write test: NodeLibrary renders all node categories - 1h');
L('- [ ] Write test: PropertiesPanel renders correct fields for each node type - 2h');
L('- [ ] Write test: AgentNodeCanvas renders chat_model, memory, tool sub-nodes - 2h');
L('- [ ] Write test: WorkflowCanvas correctly renders edges with correct types - 2h');
L('- [ ] Write test: ExecutionConsole shows agent ReAct steps - 2h');
L();
L('---');
L();
L('## SECTION 9 - DOCUMENTATION');
L('### Estimated: 3-4 days | Owner: Full Team');
L();
L('- [ ] Write AGENT_IMPLEMENTATION_GUIDE.md: how to use agent nodes, sub-nodes, tools - 3h');
L('- [ ] Write TRIGGER_NODES_GUIDE.md: how to set up trigger nodes per integration - 3h');
L('- [ ] Write NODE_OPERATIONS_REFERENCE.md: all operations per node with input/output fields - 4h');
L('- [ ] Update ADDING_NEW_NODES_GUIDE.md: include trigger node and agent sub-node patterns - 2h');
L('- [ ] Write CREDENTIAL_SETUP_GUIDE.md: how to connect each integration - 3h');
L('- [ ] Update API documentation: all new endpoints with request/response examples - 3h');
L();
L('---');
L();
L('## SECTION 10 - SPRINT PLAN AND TIME ESTIMATES');
L();
L('### Sprint 1 (Week 1-2): Foundation');
L('- Section 1: Registry and Node Library Verification — 8-10 days');
L('- Section 7.1: Supabase Schema Updates — 2 days');
L('- Section 7.3: Environment Variables — 0.5 days');
L('- Deliverable: All existing nodes verified, agent and trigger DB tables ready');
L();
L('### Sprint 2 (Week 3-4): Trigger Infrastructure + First 10 Triggers');
L('- Section 2.1: Trigger Infrastructure — 3 days');
L('- Section 2.2-2.11: First 10 trigger nodes (Gmail, Sheets, Slack, GitHub, Notion, Airtable, HubSpot, Stripe, Shopify, Telegram) — 7 days');
L('- Deliverable: Trigger system working, 10 triggers live');
L();
L('### Sprint 3 (Week 5-6): Remaining Triggers + Agent Core');
L('- Section 2.12-2.32: Remaining 22 trigger nodes — 7 days');
L('- Section 3.1: Agent Core Types and Contracts — 2 days');
L('- Section 3.2: Agent Backend Execution Engine — 3 days (start)');
L('- Deliverable: All 32 trigger nodes live, agent execution engine started');
L();
L('### Sprint 4 (Week 7-8): Agent Complete');
L('- Section 3.2: Agent Backend Execution Engine (finish) — 3 days');
L('- Section 3.3: Chat Model Sub-Node — 3 days');
L('- Section 3.4: Memory Sub-Node — 3 days');
L('- Section 3.5: Tool Sub-Node — 2 days');
L('- Deliverable: Agent fully working in backend');
L();
L('### Sprint 5 (Week 9-10): Agent UI + Frontend Fixes');
L('- Section 3.6: Agent Orchestrator Integration — 2 days');
L('- Section 3.7: Agent Frontend UI — 5 days');
L('- Section 3.8: Agent API Endpoints — 1 day');
L('- Section 5.1-5.3: NodeLibrary + WorkflowNode + PropertiesPanel fixes — 4 days');
L('- Deliverable: Agent fully usable in UI');
L();
L('### Sprint 6 (Week 11-12): Execution Fixes + AI Generation + Testing');
L('- Section 4: Backend Execution Engine Fixes — 5 days');
L('- Section 6: AI Workflow Generation Pipeline Fixes — 4 days');
L('- Section 5.4-5.7: Remaining Frontend fixes — 3 days');
L('- Section 8: Testing — 5 days');
L('- Section 9: Documentation — 3 days');
L('- Deliverable: Production-ready platform');
L();
L('---');
L();
L('## TOTAL SUMMARY');
L();
L('| Section | Description | Estimated Days |');
L('|---------|-------------|----------------|');
L('| 1 | Registry and Node Library Verification | 8-10 days |');
L('| 2 | Trigger Nodes Implementation (32 triggers) | 12-15 days |');
L('| 3 | Agent Implementation (full ReAct agent) | 20-25 days |');
L('| 4 | Backend Execution Engine Fixes | 8-10 days |');
L('| 5 | Frontend UI Fixes and Enhancements | 10-12 days |');
L('| 6 | AI Workflow Generation Pipeline Fixes | 6-8 days |');
L('| 7 | Database and Infrastructure | 4-5 days |');
L('| 8 | Testing | 8-10 days |');
L('| 9 | Documentation | 3-4 days |');
L('| TOTAL | | 79-99 engineering days |');
L();
L('### Team Allocation (4-6 engineers, 12 weeks)');
L('- Backend Engineer 1: Sections 1, 4, 7 (Registry, Execution, DB)');
L('- Backend Engineer 2: Section 2 (All Trigger Nodes)');
L('- Backend Engineer 3: Section 3 (Agent Backend - most complex)');
L('- Frontend Engineer 1: Sections 5, 6 (UI + AI Generation)');
L('- Frontend Engineer 2: Section 3.7 (Agent UI)');
L('- QA Engineer: Section 8 (Testing, parallel with development)');
L();
L('---');
L('# END OF MASTER IMPLEMENTATION PLAN');

fs.writeFileSync('TODO_MASTER_IMPLEMENTATION_PLAN.md', lines.join('\n'), 'utf8');
console.log('COMPLETE - Total lines: ' + lines.length);
