import type { UnifiedNodeDefinition } from '../../types/unified-node-contract';
import type { NodeSchema } from '../../../services/nodes/node-library';

export function overrideLinearTrigger(
  def: UnifiedNodeDefinition,
  _schema: NodeSchema,
): UnifiedNodeDefinition {
  const manualStatic = {
    default: 'manual_static' as const,
    supportsRuntimeAI: false,
    supportsBuildtimeAI: false,
  };

  return {
    ...def,
    type: 'linear_trigger',
    label: 'Linear Trigger',
    category: 'triggers',
    description: 'Trigger workflows on Linear issue, comment, project, cycle, label, reaction, document, initiative, customer, and user events',
    icon: 'CheckSquare',
    version: '1.0.0',
    isBranching: false,
    incomingPorts: [],
    outgoingPorts: ['default'],
    inputSchema: {
      connectionId: {
        type: 'string',
        description: 'Optional saved Linear connection ID.',
        required: false,
        ownership: 'credential',
        role: 'id',
        fillMode: manualStatic,
      },
      teamId: {
        type: 'string',
        description: 'Optional Linear team UUID to register against. Leave blank to watch all public teams.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      allPublicTeams: {
        type: 'boolean',
        description: 'Register the webhook for all public Linear teams when no team ID is provided.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      resourceTypes: {
        type: 'string',
        description: 'Comma-separated Linear resource types to subscribe to, such as Issue, Comment, Project, Cycle, IssueLabel, Reaction.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      eventTypes: {
        type: 'string',
        description: 'Comma-separated normalized event filters such as issue_created, issue_updated, issue_removed, comment_created, project_updated.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      issueId: {
        type: 'string',
        description: 'Optional Linear issue UUID or identifier filter.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      projectId: {
        type: 'string',
        description: 'Optional Linear project UUID filter.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      actorId: {
        type: 'string',
        description: 'Optional Linear actor/user UUID filter.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      query: {
        type: 'string',
        description: 'Optional keyword filter matched against issue title, comment body, project name, or event URL.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
    },
    outputSchema: {
      default: {
        name: 'default',
        description: 'Normalized Linear webhook event payload',
        schema: {
          type: 'object',
          properties: {
            eventId: { type: 'string' },
            eventType: { type: 'string' },
            source: { type: 'string' },
            timestamp: { type: 'string' },
            deliveryId: { type: 'string' },
            linearEvent: { type: 'string' },
            action: { type: 'string' },
            entityType: { type: 'string' },
            entityId: { type: 'string' },
            organizationId: { type: 'string' },
            webhookId: { type: 'string' },
            url: { type: 'string' },
            teamId: { type: 'string' },
            teamKey: { type: 'string' },
            teamName: { type: 'string' },
            issueId: { type: 'string' },
            issueIdentifier: { type: 'string' },
            issueTitle: { type: 'string' },
            issueUrl: { type: 'string' },
            stateId: { type: 'string' },
            stateName: { type: 'string' },
            assigneeId: { type: 'string' },
            assigneeName: { type: 'string' },
            commentId: { type: 'string' },
            commentBody: { type: 'string' },
            projectId: { type: 'string' },
            projectName: { type: 'string' },
            userId: { type: 'string' },
            username: { type: 'string' },
            text: { type: 'string' },
            raw: { type: 'object' },
          },
        },
      },
    },
    requiredInputs: [],
    defaultConfig: () => ({
      allPublicTeams: true,
      resourceTypes: 'Issue, Comment',
      eventTypes: 'issue_created, issue_updated, comment_created',
    }),
    validateConfig: () => ({ valid: true, errors: [] }),
    execute: async () => ({
      success: true,
      output: { triggered: false },
    }),
  };
}
