import type { UnifiedNodeDefinition } from '../../types/unified-node-contract';
import type { NodeSchema } from '../../../services/nodes/node-library';

export function overrideShopifyTrigger(
  def: UnifiedNodeDefinition,
  _schema: NodeSchema,
): UnifiedNodeDefinition {
  const manualStatic = {
    default: 'manual_static' as const,
    supportsRuntimeAI: false,
    supportsBuildtimeAI: false,
  };

  return {
    ...def,
    type: 'shopify_trigger',
    label: 'Shopify Trigger',
    category: 'triggers',
    description: 'Trigger workflows from signed Shopify webhooks for orders, customers, products, refunds, checkouts, and app uninstall events',
    icon: 'ShoppingCart',
    version: '1.0.0',
    isBranching: false,
    incomingPorts: [],
    outgoingPorts: ['default'],
    inputSchema: {
      connectionId: {
        type: 'string',
        description: 'Optional saved Shopify connection ID.',
        required: false,
        ownership: 'credential',
        role: 'id',
        fillMode: manualStatic,
      },
      shopDomain: {
        type: 'string',
        description: 'Optional shop-domain filter. If omitted, the saved connection Store URL is used for registration.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      topics: {
        type: 'string',
        description: 'Comma-separated Shopify webhook topics, such as orders/create, orders/paid, customers/create, products/update.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      financialStatus: {
        type: 'string',
        description: 'Optional order financial status filter, such as paid, pending, refunded, or voided.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      fulfillmentStatus: {
        type: 'string',
        description: 'Optional order fulfillment status filter, such as fulfilled, partial, or unfulfilled.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      customerId: {
        type: 'string',
        description: 'Optional Shopify customer ID filter.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      productId: {
        type: 'string',
        description: 'Optional Shopify product ID filter.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      minTotalPrice: {
        type: 'number',
        description: 'Optional minimum order total filter.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      currency: {
        type: 'string',
        description: 'Optional ISO currency filter, such as usd or inr.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      query: {
        type: 'string',
        description: 'Optional keyword filter matched against order name, customer email/name, product title, IDs, and statuses.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
    },
    outputSchema: {
      default: {
        name: 'default',
        description: 'Normalized Shopify webhook event payload',
        schema: {
          type: 'object',
          properties: {
            eventId: { type: 'string' },
            eventType: { type: 'string' },
            source: { type: 'string' },
            timestamp: { type: 'string' },
            topic: { type: 'string' },
            shopDomain: { type: 'string' },
            webhookId: { type: 'string' },
            apiVersion: { type: 'string' },
            objectId: { type: 'string' },
            adminGraphqlApiId: { type: 'string' },
            orderId: { type: 'string' },
            orderName: { type: 'string' },
            orderNumber: { type: 'string' },
            financialStatus: { type: 'string' },
            fulfillmentStatus: { type: 'string' },
            totalPrice: { type: 'number' },
            subtotalPrice: { type: 'number' },
            totalTax: { type: 'number' },
            currency: { type: 'string' },
            customerId: { type: 'string' },
            customerEmail: { type: 'string' },
            customerName: { type: 'string' },
            productId: { type: 'string' },
            productTitle: { type: 'string' },
            variantId: { type: 'string' },
            inventoryItemId: { type: 'string' },
            checkoutId: { type: 'string' },
            cartToken: { type: 'string' },
            refundId: { type: 'string' },
            lineItems: { type: 'array' },
            userId: { type: 'string' },
            username: { type: 'string' },
            text: { type: 'string' },
            raw: { type: 'object' },
          },
        },
      },
    },
    requiredInputs: [],
    defaultConfig: () => ({
      topics: 'orders/create, orders/paid, orders/updated, customers/create, products/create, products/update',
    }),
    validateConfig: () => ({ valid: true, errors: [] }),
    execute: async () => ({
      success: true,
      output: { triggered: false },
    }),
  };
}
