import type { UnifiedNodeDefinition } from '../../types/unified-node-contract';
import type { NodeSchema } from '../../../services/nodes/node-library';

export function overrideStripeTrigger(
  def: UnifiedNodeDefinition,
  _schema: NodeSchema,
): UnifiedNodeDefinition {
  const manualStatic = {
    default: 'manual_static' as const,
    supportsRuntimeAI: false,
    supportsBuildtimeAI: false,
  };

  return {
    ...def,
    type: 'stripe_trigger',
    label: 'Stripe Trigger',
    category: 'triggers',
    description: 'Trigger workflows from signed Stripe webhook events for Checkout, payments, invoices, subscriptions, customers, and refunds',
    icon: 'CreditCard',
    version: '1.0.0',
    isBranching: false,
    incomingPorts: [],
    outgoingPorts: ['default'],
    inputSchema: {
      connectionId: {
        type: 'string',
        description: 'Optional saved Stripe connection ID.',
        required: false,
        ownership: 'credential',
        role: 'id',
        fillMode: manualStatic,
      },
      eventTypes: {
        type: 'string',
        description: 'Comma-separated Stripe event types to subscribe to, such as checkout.session.completed, payment_intent.succeeded, invoice.payment_succeeded.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      connect: {
        type: 'boolean',
        description: 'Set true to receive events for connected accounts using Stripe Connect.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      livemode: {
        type: 'boolean',
        description: 'Optional filter for live-mode or test-mode events.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      customerId: {
        type: 'string',
        description: 'Optional Stripe customer ID filter.',
        required: false,
        ownership: 'value',
        role: 'id',
        fillMode: manualStatic,
      },
      currency: {
        type: 'string',
        description: 'Optional ISO currency filter, such as usd or eur.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      minAmount: {
        type: 'number',
        description: 'Optional minimum amount in the smallest currency unit.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
      query: {
        type: 'string',
        description: 'Optional keyword filter matched against customer email, object ID, description, and status.',
        required: false,
        ownership: 'value',
        role: 'config',
        fillMode: manualStatic,
      },
    },
    outputSchema: {
      default: {
        name: 'default',
        description: 'Normalized Stripe webhook event payload',
        schema: {
          type: 'object',
          properties: {
            eventId: { type: 'string' },
            eventType: { type: 'string' },
            source: { type: 'string' },
            timestamp: { type: 'string' },
            livemode: { type: 'boolean' },
            apiVersion: { type: 'string' },
            accountId: { type: 'string' },
            objectId: { type: 'string' },
            objectType: { type: 'string' },
            customerId: { type: 'string' },
            customerEmail: { type: 'string' },
            amount: { type: 'number' },
            amountReceived: { type: 'number' },
            amountPaid: { type: 'number' },
            amountTotal: { type: 'number' },
            currency: { type: 'string' },
            status: { type: 'string' },
            paymentIntentId: { type: 'string' },
            chargeId: { type: 'string' },
            checkoutSessionId: { type: 'string' },
            invoiceId: { type: 'string' },
            subscriptionId: { type: 'string' },
            paymentMethodId: { type: 'string' },
            receiptUrl: { type: 'string' },
            description: { type: 'string' },
            metadata: { type: 'object' },
            userId: { type: 'string' },
            username: { type: 'string' },
            text: { type: 'string' },
            raw: { type: 'object' },
          },
        },
      },
    },
    requiredInputs: [],
    defaultConfig: () => ({
      eventTypes: 'checkout.session.completed, payment_intent.succeeded, payment_intent.payment_failed, invoice.payment_succeeded',
      connect: false,
    }),
    validateConfig: () => ({ valid: true, errors: [] }),
    execute: async () => ({
      success: true,
      output: { triggered: false },
    }),
  };
}
