import type { DocsSearchIndexItem } from '../search-index';

export const activecampaignSearchIndex = [
  {
    type: 'node',
    title: 'ActiveCampaign',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign',
    text: 'ActiveCampaign adds, updates, or deletes contacts in your ActiveCampaign marketing automation account via API key.',
  },
  {
    type: 'operation',
    title: 'ActiveCampaign: Add',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign#operation-add',
    text: 'Add creates a new ActiveCampaign contact using Email, First Name, Last Name, or a raw Data payload.',
  },
  {
    type: 'operation',
    title: 'ActiveCampaign: Update',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign#operation-update',
    text: 'Update changes an existing ActiveCampaign contact identified by Contact ID.',
  },
  {
    type: 'operation',
    title: 'ActiveCampaign: Delete',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign#operation-delete',
    text: 'Delete permanently removes an ActiveCampaign contact identified by Contact ID.',
  },
  {
    type: 'field',
    title: 'ActiveCampaign fields',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign#operation-add',
    text: 'Fields include apiUrl, apiKey, operation add update delete, contactId, email, firstName, lastName, and data (raw JSON override).',
  },
  {
    type: 'field',
    title: 'ActiveCampaign outputs',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign#operation-add',
    text: 'Outputs operation and data. data.contact contains id, email, firstName, lastName for add/update; Delete returns data.deleted and data.contactId instead.',
  },
  {
    type: 'field',
    title: 'ActiveCampaign connection setup',
    slug: 'activecampaign',
    category: 'CRM',
    href: '/docs/nodes/activecampaign#connection-setup',
    text: 'Get your API URL and API Key from ActiveCampaign Settings -> Developer. Save the API Key under Connections; the API URL must still be entered on the node since it is account-specific.',
  },
] satisfies DocsSearchIndexItem[];
