import type { DocsSearchIndexItem } from '../search-index';

export const calendlySearchIndex = [
  {
    type: 'node',
    title: 'Calendly',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly',
    text: 'Calendly reads user, event type, and scheduled event data using a saved Calendly Personal Access Token connection.',
  },
  {
    type: 'operation',
    title: 'Calendly: Get User',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_user',
    text: 'Get User calls /users/me and returns user.uri for later event type and scheduled event lookups.',
  },
  {
    type: 'operation',
    title: 'Calendly: Get Events',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_events',
    text: 'Get Events lists scheduled_events, optionally filtered by User URI, and returns data, collection, and count when Calendly sends a list.',
  },
  {
    type: 'operation',
    title: 'Calendly: Get Event Types',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_event_types',
    text: 'Get Event Types requires userUri and returns booking-page event type records for a Calendly user.',
  },
  {
    type: 'operation',
    title: 'Calendly: Get Scheduled Events',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_scheduled_events',
    text: 'Get Scheduled Events requires userUri and can filter by eventTypeUri to find meetings for one booking type.',
  },
  {
    type: 'field',
    title: 'Calendly: Operation',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_user',
    text: 'Operation values are get_user, get_events, get_event_types, and get_scheduled_events.',
  },
  {
    type: 'field',
    title: 'Calendly: Personal Access Token',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_user',
    text: 'Personal Access Token is an optional fallback; prefer storing Calendly tokens in CtrlChecks Connections.',
  },
  {
    type: 'field',
    title: 'Calendly: User URI',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_event_types',
    text: 'User URI is required for get_event_types and get_scheduled_events, usually mapped from {{$json.user.uri}} after Get User.',
  },
  {
    type: 'field',
    title: 'Calendly: Event Type URI',
    slug: 'calendly',
    category: 'Productivity',
    href: '/docs/nodes/calendly#operation-get_scheduled_events',
    text: 'Event Type URI optionally filters scheduled events to one booking type, often mapped from {{$json.collection[0].uri}}.',
  },
] satisfies DocsSearchIndexItem[];
