import type { DocsSearchIndexItem } from '../search-index';

export const discordSearchIndex = [
  {
    type: 'node',
    title: 'Discord',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord',
    text: 'Discord Send messages to Discord channels via a Discord bot token, or reply to a slash command/component interaction using an interaction token. Communication',
  },
  {
    type: 'operation',
    title: 'Discord: Send Bot Message',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord#operation-default',
    text: 'Discord Configuration Send Bot Message. Posts to a channel with a bot token, or replies to a Discord interaction with Interaction Token plus Application ID.',
  },
  {
    type: 'field',
    title: 'Discord: Channel Id',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord#operation-default',
    text: 'Discord Channel Id channelId Discord channel ID where the bot should post the message. Enable Developer Mode to copy it.',
  },
  {
    type: 'field',
    title: 'Discord: Message',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord#operation-default',
    text: 'Discord Message message text to send. Required for every send. Supports Discord markdown.',
  },
  {
    type: 'field',
    title: 'Discord: Interaction Token',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord#operation-default',
    text: 'Discord Interaction Token interactionToken for slash command or component follow-up replies from Discord Trigger. Expires after 15 minutes.',
  },
  {
    type: 'field',
    title: 'Discord: Application Id',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord#operation-default',
    text: 'Discord Application Id applicationId required with Interaction Token for interaction follow-up replies.',
  },
  {
    type: 'field',
    title: 'Discord: Reply To Message Id',
    slug: 'discord',
    category: 'Communication',
    href: '/docs/nodes/discord#operation-default',
    text: 'Discord Reply To Message Id replyToMessageId optional message to reply to on the Bot API channel path.',
  },
] satisfies DocsSearchIndexItem[];
