import type { DocsSearchIndexItem } from '../search-index';

export const emailSearchIndex = [
  {
    type: 'node',
    title: 'Send Email (SMTP)',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email',
    text: 'Send Email SMTP sends plain-text or HTML email through a saved SMTP Account connection. Requires to, subject, text, and SMTP host, port, username, password in Connections. Optional html and from.',
  },
  {
    type: 'operation',
    title: 'Send Email (SMTP): Send Email',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email#operation-default',
    text: 'Send one email through SMTP for invoice notifications, support confirmations, password resets, reports, alerts, and operational messages.',
  },
  {
    type: 'field',
    title: 'Send Email (SMTP): To',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email#operation-default',
    text: 'to required recipient address or comma-separated recipient list. Map values such as {{$json.customerEmail}} from a previous step.',
  },
  {
    type: 'field',
    title: 'Send Email (SMTP): Subject',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email#operation-default',
    text: 'subject required inbox title. Use order IDs, ticket IDs, invoice numbers, report dates, or customer names when useful.',
  },
  {
    type: 'field',
    title: 'Send Email (SMTP): Text',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email#operation-default',
    text: 'text required plain-text body and reliable fallback. Runtime requires text or html before sending.',
  },
  {
    type: 'field',
    title: 'Send Email (SMTP): HTML',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email#operation-default',
    text: 'html optional rich email body for links and simple formatting. Avoid scripts, secrets, and unsupported interactive content.',
  },
  {
    type: 'field',
    title: 'Send Email (SMTP): From',
    slug: 'email',
    category: 'Communication',
    href: '/docs/nodes/email#operation-default',
    text: 'from optional sender address override. Leave blank to use the SMTP username or connection default; only use verified sender addresses.',
  },
] satisfies DocsSearchIndexItem[];
