import type { DocsSearchIndexItem } from '../search-index';

export const formSearchIndex = [
  {
    type: 'node',
    title: 'Form Trigger',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form',
    text: 'Form Trigger builds a public CtrlChecks form and starts a workflow when someone submits structured answers, files, or intake details.',
  },
  {
    type: 'operation',
    title: 'Form Trigger: Execute',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Execute starts the workflow when a person submits the form and passes answers by internal name plus data, files, form, and meta objects.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Form Title',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Form Title is the public heading, such as Support Request, Request a Demo, Vendor Onboarding, or Employee Equipment Request.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Form Fields',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Form Fields define labels, internal names, field types, required settings, placeholders, and options for submitted workflow data.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Field Type',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Field Type options: text, email, number, tel, url, date, textarea, select, checkbox, radio, and file. Choose the type that matches the answer format.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Internal Name',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Internal Name is the mapping key used later, such as customer_email in {{$json.customer_email}} or {{$json.data.customer_email}}.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Options',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Options are allowed choices for select and radio fields, such as Billing Team:billing, Technical Support:technical, and Sales:sales.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Success And Redirect',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Success Message confirms receipt on the form page. Redirect URL sends submitters to a full HTTPS thank-you or next-step page.',
  },
  {
    type: 'field',
    title: 'Form Trigger: Submission Controls',
    slug: 'form',
    category: 'Triggers',
    href: '/docs/nodes/form#operation-default',
    text: 'Allow Multiple Submissions, Require Authentication, and CAPTCHA control repeat submissions, public access, and spam prevention.',
  },
] satisfies DocsSearchIndexItem[];
