import type { DocsSearchIndexItem } from '../search-index';

export const httpRequestSearchIndex = [
  {
    type: 'node',
    title: 'HTTP Request',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request',
    text: 'HTTP Request calls external APIs and webhooks with url, method, headers, body, qs query parameters, and timeout. No saved credentials by itself; use secure secret references for protected API headers and connect downstream service accounts separately.',
  },
  {
    type: 'operation',
    title: 'HTTP Request: Send Request',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'Send one GET, POST, PUT, PATCH, or DELETE request. Use GET to read, POST to create, PUT to replace, PATCH to update selected fields, and DELETE to remove or cancel a resource.',
  },
  {
    type: 'field',
    title: 'HTTP Request: URL',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'url required full endpoint such as https://api.example.com/customers/{{$json.customerId}}. Runtime returns the final called URL as {{$json.url}}.',
  },
  {
    type: 'field',
    title: 'HTTP Request: Method',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'method optional dropdown. GET reads data, POST creates or submits data, PUT replaces a whole record, PATCH updates selected fields, DELETE removes or cancels a resource.',
  },
  {
    type: 'field',
    title: 'HTTP Request: Headers',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'headers optional JSON object for Content-Type, Accept, Authorization, X-API-Key, or service-specific headers. Use secure secret references instead of pasting private tokens.',
  },
  {
    type: 'field',
    title: 'HTTP Request: Body',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'body optional JSON request payload for POST, PUT, and PATCH. Runtime does not send Body for GET or DELETE.',
  },
  {
    type: 'field',
    title: 'HTTP Request: Query String Params',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'qs optional JSON query parameters such as {"status":"open","limit":100}. Runtime appends them to the URL and returns the final URL.',
  },
  {
    type: 'field',
    title: 'HTTP Request: Timeout',
    slug: 'http_request',
    category: 'HTTP & API',
    href: '/docs/nodes/http_request#operation-default',
    text: 'timeout optional milliseconds to wait for the remote server. Blank or invalid values default to 30000 and timeout failures return _error with errorDetails.timeout.',
  },
] satisfies DocsSearchIndexItem[];
