import type { DocsSearchIndexItem } from '../search-index';

export const microsoftTeamsSearchIndex = [
  {
    type: 'node',
    title: 'Microsoft Teams',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams',
    text: 'Microsoft Teams Send channel notifications through an Incoming Webhook URL or reply to Microsoft Teams Trigger conversations through Bot Framework with a saved Microsoft Teams Bot connection.',
  },
  {
    type: 'operation',
    title: 'Microsoft Teams: Send Message',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams#operation-default',
    text: 'Send one Teams message. Use Webhook URL for fixed channel alerts, or Service URL plus Conversation ID with a Microsoft Teams Bot connection for trigger replies.',
  },
  {
    type: 'field',
    title: 'Microsoft Teams: Webhook URL',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams#operation-default',
    text: 'Webhook URL webhookUrl Incoming Webhook URL for a Teams channel. Use for simple channel notifications, save in Connections when possible, and leave blank for Teams Trigger replies.',
  },
  {
    type: 'field',
    title: 'Microsoft Teams: Message',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams#operation-default',
    text: 'Message message Teams text to send. Include status, ticket ID, customer, owner, error summary, or next action. Map {{$json.response}}, {{$json.text}}, {{$json.ticketId}}, or other workflow fields.',
  },
  {
    type: 'field',
    title: 'Microsoft Teams: Service URL',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams#operation-default',
    text: 'Service URL serviceUrl Bot Framework service URL from Microsoft Teams Trigger. Map {{$json.serviceUrl}} for same-conversation replies, not a Teams browser link.',
  },
  {
    type: 'field',
    title: 'Microsoft Teams: Conversation ID',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams#operation-default',
    text: 'Conversation ID conversationId Teams Bot Framework conversation ID from Microsoft Teams Trigger. Map {{$json.conversationId}} for replies; this is not a Team ID or Channel ID.',
  },
  {
    type: 'field',
    title: 'Microsoft Teams: Reply To Activity ID',
    slug: 'microsoft_teams',
    category: 'Communication',
    href: '/docs/nodes/microsoft_teams#operation-default',
    text: 'Reply To Activity ID replyToId optional Teams activity ID. Map {{$json.replyToId}} or {{$json.activityId}} to attach the bot response to the original message.',
  },
] satisfies DocsSearchIndexItem[];
