import type { DocsSearchIndexItem } from '../search-index';

export const schedulewiseSearchIndex = [
  { type: 'node', title: 'ScheduleWise', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise', text: 'ScheduleWise manages appointments through getSchedules createAppointment updateAppointment deleteAppointment. Uses saved schedulewise credential unless mockMode is true. Output success operation data executionTimeMs error.' },
  { type: 'operation', title: 'ScheduleWise: Get Schedules', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-getschedules', text: 'Get Schedules sends GET /appointments with dateFrom dateTo patientId staffId and limit filters.' },
  { type: 'operation', title: 'ScheduleWise: Create Appointment', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-createappointment', text: 'Create Appointment sends patientId staffId startDateTime endDateTime serviceType and notes to /appointments.' },
  { type: 'operation', title: 'ScheduleWise: Update Appointment', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-updateappointment', text: 'Update Appointment uses appointmentId and sends changed startDateTime endDateTime staffId status or notes.' },
  { type: 'operation', title: 'ScheduleWise: Delete Appointment', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-deleteappointment', text: 'Delete Appointment deletes /appointments/{appointmentId}; hardDelete adds ?hardDelete=true.' },
  { type: 'field', title: 'ScheduleWise: Operation', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-getschedules', text: 'operation must be getSchedules createAppointment updateAppointment or deleteAppointment. INVALID_OPERATION is returned for unsupported values.' },
  { type: 'field', title: 'ScheduleWise: Credential', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-getschedules', text: 'credentialId is metadata only. Runtime uses saved schedulewise credentials from Connections with apiUrl accessToken or apiKey.' },
  { type: 'field', title: 'ScheduleWise: Date Range', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-getschedules', text: 'dateFrom and dateTo are ISO filters for Get Schedules and can map {{$json.startDate}} and {{$json.endDate}}.' },
  { type: 'field', title: 'ScheduleWise: Patient and Staff', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-createappointment', text: 'patientId and staffId are ScheduleWise IDs used for filters creates and updates.' },
  { type: 'field', title: 'ScheduleWise: Appointment ID', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-updateappointment', text: 'appointmentId is required for Update Appointment and Delete Appointment.' },
  { type: 'field', title: 'ScheduleWise: Start End Service Notes Status', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-createappointment', text: 'startDateTime endDateTime serviceType notes and status shape create and update appointment bodies.' },
  { type: 'field', title: 'ScheduleWise: Limit Hard Delete Mock Mode', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-getschedules', text: 'limit caps Get Schedules. hardDelete requests permanent delete. mockMode returns synthetic data without credentials or API calls.' },
  { type: 'field', title: 'ScheduleWise: Timeout Retries Output Format', slug: 'schedulewise', category: 'HTTP & API', href: '/docs/nodes/schedulewise#operation-getschedules', text: 'timeoutSec is seconds, retries handles network and 5xx retry attempts, outputFormat Raw is visible but not honored because runtime parses JSON.' },
] satisfies DocsSearchIndexItem[];
