import type { DocsSearchIndexItem } from '../search-index';

export const stripeSearchIndex = [
  { type: 'node', title: 'Stripe', slug: 'stripe', category: 'Ecommerce', href: '/docs/nodes/stripe', text: 'Stripe creates PaymentIntents or legacy charges, customers, refunds, subscriptions, invoices, and PaymentIntent lookups/lists. Some visible aliases are unsupported.' },
  { type: 'operation', title: 'Stripe: PaymentIntent or Charge', slug: 'stripe', category: 'Ecommerce', href: '/docs/nodes/stripe#operation-paymentintent', text: 'Use paymentintent charge or payment with amount in cents, currency, paymentMethodId/source, customerId, and description. Output paymentIntent or charge.' },
  { type: 'operation', title: 'Stripe: Customer Refund Subscription Invoice', slug: 'stripe', category: 'Ecommerce', href: '/docs/nodes/stripe#operation-create_customer', text: 'Runtime supports create_customer refund get_payment_intent list_payment_intents create_subscription and create_invoice. Outputs customer refund paymentIntent items subscription invoice.' },
  { type: 'field', title: 'Stripe: Operation', slug: 'stripe', category: 'Ecommerce', href: '/docs/nodes/stripe#operation-paymentintent', text: 'operation supports paymentintent charge payment refund create_customer get_payment_intent list_payment_intents create_subscription create_invoice; create_payment create_payment_intent get_payment list_payments create_refund are unsupported aliases.' },
  { type: 'field', title: 'Stripe: API Key', slug: 'stripe', category: 'Ecommerce', href: '/docs/nodes/stripe#operation-paymentintent', text: 'apiKey is optional fallback. Prefer Stripe API Key in Connections/credential vault.' },
  { type: 'field', title: 'Stripe: Amount Currency IDs', slug: 'stripe', category: 'Ecommerce', href: '/docs/nodes/stripe#operation-paymentintent', text: 'amount is smallest currency unit. currency lowercase code. paymentIntentId pi_, chargeId ch_, customerId cus_, paymentMethodId pm_, priceId price_.' },
] satisfies DocsSearchIndexItem[];
