import type { DocsSearchIndexItem } from '../search-index';

export const stripeTriggerSearchIndex = [
  { type: 'node', title: 'Stripe Trigger', slug: 'stripe_trigger', category: 'Triggers', href: '/docs/nodes/stripe_trigger', text: 'Stripe Trigger webhook payment checkout invoice subscription customer refund signed Stripe-Signature' },
  { type: 'operation', title: 'Stripe Trigger: Payment Events', slug: 'stripe_trigger', category: 'Triggers', href: '/docs/nodes/stripe_trigger#operation-payment_billing_events', text: 'Stripe payment_intent.succeeded payment_intent.payment_failed checkout.session.completed charge.refunded amount currency customerId paymentIntentId' },
  { type: 'operation', title: 'Stripe Trigger: Billing Events', slug: 'stripe_trigger', category: 'Triggers', href: '/docs/nodes/stripe_trigger#operation-payment_billing_events', text: 'Stripe invoice.payment_succeeded customer.subscription.created customer.subscription.updated customer.subscription.deleted invoiceId subscriptionId status' },
  { type: 'field', title: 'Stripe Trigger fields', slug: 'stripe_trigger', category: 'Triggers', href: '/docs/nodes/stripe_trigger#operation-payment_billing_events', text: 'Fields include connectionId, eventTypes, connect (Stripe Connect Events), livemode (Live Mode Only), customerId, currency, minAmount, and query.' },
  { type: 'field', title: 'Stripe Trigger outputs', slug: 'stripe_trigger', category: 'Triggers', href: '/docs/nodes/stripe_trigger#operation-payment_billing_events', text: 'Outputs eventId eventType source userId username text timestamp livemode apiVersion accountId objectId objectType customerId customerEmail amount amountReceived amountPaid amountTotal currency status paymentIntentId chargeId checkoutSessionId invoiceId subscriptionId paymentMethodId receiptUrl description metadata raw trigger workflow_id node_id sessionId _stripe.' },
  { type: 'field', title: 'Stripe Trigger connection setup', slug: 'stripe_trigger', category: 'Triggers', href: '/docs/nodes/stripe_trigger#connection-setup', text: 'Connect a Stripe Secret Key in Connections. CtrlChecks automatically creates the webhook endpoint via the Stripe API and validates deliveries with Stripe-Signature.' },
] satisfies DocsSearchIndexItem[];
