import type { DocsSearchIndexItem } from '../search-index';

export const switchSearchIndex = [
  {
    type: 'node',
    title: 'Switch',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch',
    text: 'Switch multi-path routing match one expression value to named case branches no credentials',
  },
  {
    type: 'operation',
    title: 'Switch: Configure',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch#operation-default',
    text: 'Switch Configure expression cases dynamic outgoing branch handles matchedCase caseMatched support ticket routing',
  },
  {
    type: 'field',
    title: 'Switch: Expression',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch#operation-default',
    text: 'Switch Expression previous-step value {{$json.status}} {{$json.category}} compared to case values',
  },
  {
    type: 'field',
    title: 'Switch: Cases',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch#operation-default',
    text: 'Switch Cases JSON value label unique branch output handles billing technical general paid failed pending',
  },
  {
    type: 'field',
    title: 'Switch: Routing Type',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch#operation-default',
    text: 'Switch Routing Type optional legacy compatibility hint string number expression leave empty for new workflows',
  },
  {
    type: 'field',
    title: 'Switch: Rules',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch#operation-default',
    text: 'Switch Rules deprecated alias for cases legacy workflows migrate to cases',
  },
  {
    type: 'connection',
    title: 'Switch: Branch Connections',
    slug: 'switch',
    category: 'Logic',
    href: '/docs/nodes/switch#operation-default',
    text: 'Switch connect each case output outgoing line downstream service node account connection fallback unmatched values',
  },
] satisfies DocsSearchIndexItem[];
