import type { DocsSearchIndexItem } from '../search-index';

export const telegramSearchIndex = [
  {
    type: 'node',
    title: 'Telegram',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram',
    text: 'Telegram Send text messages, media URLs, and message edits through a saved Telegram Bot Token connection. Use for Telegram bot replies, alerts, report delivery, approval buttons, and status updates.',
  },
  {
    type: 'operation',
    title: 'Telegram: Send Message / Send Media / Edit Message',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Operation options: send_message sends text with Chat ID and Message, send_photo sends an image URL with Media URL and optional Caption, edit_message updates an existing bot message with Edit Message ID and Message.',
  },
  {
    type: 'field',
    title: 'Telegram: Operation',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Operation operation choose send_message for text alerts and chatbot replies, send_photo for images, or edit_message to update a previous bot message.',
  },
  {
    type: 'field',
    title: 'Telegram: Chat ID',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Chat ID chatId numeric Telegram destination. Use {{$json.chatId}} from Telegram Trigger, a positive personal chat ID, or a negative group/channel ID. Bot must be started or added first.',
  },
  {
    type: 'field',
    title: 'Telegram: Message Type',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Message Type messageType options: text sends Message, photo/video/document/audio/animation use Media URL and optional Caption.',
  },
  {
    type: 'field',
    title: 'Telegram: Message',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Message message text for send_message or edit_message. Map {{$json.aiResponse}}, {{$json.response}}, {{$json.message}}, {{$json.text}}, or workplace IDs like {{$json.ticketId}}.',
  },
  {
    type: 'field',
    title: 'Telegram: Text Alias',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Text text backend alias for Message. Runtime reads text before message for imported or AI-generated configs.',
  },
  {
    type: 'field',
    title: 'Telegram: Parse Mode',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Parse Mode parseMode options: none for plain text, HTML for simple tags, Markdown for legacy markdown, MarkdownV2 for richer markdown that requires escaping.',
  },
  {
    type: 'field',
    title: 'Telegram: Disable Web Page Preview',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Disable Web Page Preview disableWebPagePreview hides Telegram link preview cards for compact report links or noisy status feeds.',
  },
  {
    type: 'field',
    title: 'Telegram: Media URL',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Media URL mediaUrl public HTTPS direct file URL required for photo, video, document, audio, and animation messages.',
  },
  {
    type: 'field',
    title: 'Telegram: Caption',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Caption caption optional media text with report date, owner, summary, customer, or next action. Formatting follows Parse Mode.',
  },
  {
    type: 'field',
    title: 'Telegram: Reply To Message ID',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Reply To Message ID replyToMessageId optional existing Telegram message ID. Map {{$json.messageId}} from Telegram Trigger or previous Telegram output.',
  },
  {
    type: 'field',
    title: 'Telegram: Edit Message ID',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Edit Message ID editMessageId required for edit_message. Use {{$json.messageId}} from a previous Telegram Send Message output.',
  },
  {
    type: 'field',
    title: 'Telegram: Reply Markup',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Reply Markup replyMarkup Telegram JSON for inline_keyboard, keyboard, remove_keyboard, or force_reply buttons and keyboards.',
  },
  {
    type: 'field',
    title: 'Telegram: Disable Notification',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Disable Notification disableNotification sends Telegram silently for routine digests, logs, or low-priority updates.',
  },
  {
    type: 'field',
    title: 'Telegram: Protect Content',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Protect Content protectContent asks Telegram to prevent forwarding or saving where supported for confidential reports or internal-only media.',
  },
  {
    type: 'field',
    title: 'Telegram: Allow Sending Without Reply',
    slug: 'telegram',
    category: 'Communication',
    href: '/docs/nodes/telegram#operation-send_message',
    text: 'Allow Sending Without Reply allowSendingWithoutReply sends even when Reply To Message ID is missing or deleted.',
  },
] satisfies DocsSearchIndexItem[];
