import type { DocsSearchIndexItem } from '../search-index';

export const telegramTriggerSearchIndex = [
  {
    type: 'node',
    title: 'Telegram Trigger',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger',
    text: 'Telegram Trigger starts workflows in real time when someone messages a Telegram bot. Use it for Telegram chatbot workflows.',
  },
  {
    type: 'operation',
    title: 'Telegram Trigger: Receive Update',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger#operation-default',
    text: 'Receive Telegram Bot API webhook updates, validate the optional secret token, filter updateTypes allowedChatIds commandFilter, and normalize chatId messageId text username firstName lastName userId updateType raw.',
  },
  {
    type: 'field',
    title: 'Telegram Trigger fields',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger#operation-default',
    text: 'Fields include connectionId, updateTypes message edited_message channel_post callback_query, allowedChatIds, commandFilter, and secretToken.',
  },
  {
    type: 'field',
    title: 'Telegram Trigger: Allowed Chat IDs',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger#operation-default',
    text: 'Allowed Chat IDs optional comma-separated chat allowlist for Telegram Trigger.',
  },
  {
    type: 'field',
    title: 'Telegram Trigger: Secret Token',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger#operation-default',
    text: 'Secret Token validates X-Telegram-Bot-Api-Secret-Token on incoming Telegram webhooks.',
  },
  {
    type: 'field',
    title: 'Telegram Trigger outputs',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger#operation-default',
    text: 'Outputs chatId messageId text username firstName lastName userId updateType raw trigger workflow_id node_id updateId sessionId timestamp _telegram.',
  },
  {
    type: 'field',
    title: 'Telegram Trigger connection setup',
    slug: 'telegram_trigger',
    category: 'Triggers',
    href: '/docs/nodes/telegram_trigger#connection-setup',
    text: 'Connect a Telegram Bot Token from BotFather in Connections. Saving/activating a workflow always force-registers the webhook, which can silently disconnect another workflow sharing the same bot token — use a separate bot per independently active workflow.',
  },
] satisfies DocsSearchIndexItem[];
