import type { DocsSearchIndexItem } from '../search-index';

export const trelloTriggerSearchIndex: DocsSearchIndexItem[] = [
  { type: 'node', title: 'Trello Trigger', slug: 'trello_trigger', category: 'Triggers', href: '/docs/nodes/trello_trigger', text: 'Trello Trigger webhook card created updated moved commented list board checklist member' },
  { type: 'operation', title: 'Trello Trigger: Card Moved', slug: 'trello_trigger', category: 'Triggers', href: '/docs/nodes/trello_trigger#operation-card_events', text: 'Trello card_moved listBeforeId listAfterId cardId boardId' },
  { type: 'operation', title: 'Trello Trigger: Comment Added', slug: 'trello_trigger', category: 'Triggers', href: '/docs/nodes/trello_trigger#operation-card_events', text: 'Trello card_commented commentCard commentText cardId member' },
  { type: 'field', title: 'Trello Trigger fields', slug: 'trello_trigger', category: 'Triggers', href: '/docs/nodes/trello_trigger#operation-card_events', text: 'Fields include connectionId, modelId (board/card/member ID), eventTypes, boardId, listId, cardId, memberId, and query (Keyword Filter).' },
  { type: 'field', title: 'Trello Trigger outputs', slug: 'trello_trigger', category: 'Triggers', href: '/docs/nodes/trello_trigger#operation-card_events', text: 'Outputs eventId eventType source userId username text timestamp actionId actionType boardId boardName boardUrl listId listName listBeforeId listBeforeName listAfterId listAfterName cardId cardName cardUrl cardShortLink commentText checklistId checklistName checkItemId checkItemName memberId memberName raw trigger workflow_id node_id sessionId _trello.' },
  { type: 'field', title: 'Trello Trigger connection setup', slug: 'trello_trigger', category: 'Triggers', href: '/docs/nodes/trello_trigger#connection-setup', text: 'Connect a Trello API Key, Token, and App Secret from trello.com/power-ups/admin in Connections. CtrlChecks registers the webhook via POST /1/webhooks and validates deliveries with X-Trello-Webhook.' },
];
