import type { DocsSearchIndexItem } from '../search-index';

export const webhookSearchIndex = [
  {
    type: 'node',
    title: 'Webhook Trigger',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook',
    text: 'Webhook Trigger starts a workflow when a form, app, website, payment system, or internal service sends data to a generated CtrlChecks webhook URL.',
  },
  {
    type: 'operation',
    title: 'Webhook Trigger: Execute',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook#operation-default',
    text: 'Webhook Trigger Execute receives an incoming HTTP request and passes body, headers, method, and query values to the next workflow step.',
  },
  {
    type: 'field',
    title: 'Webhook Trigger: Path',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook#operation-default',
    text: 'Path is the readable URL ending such as /new-order, /new-lead, or /support-ticket. Save the workflow and copy the full generated URL from Webhook settings.',
  },
  {
    type: 'field',
    title: 'Webhook Trigger: HTTP Method',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook#operation-default',
    text: 'HTTP Method options: GET for simple pings, POST for most JSON event payloads, PUT for record replacement events, PATCH for partial updates, and DELETE for removal events.',
  },
  {
    type: 'field',
    title: 'Webhook Trigger: Response Mode',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook#operation-default',
    text: 'Response Mode options: responseNode for a Respond to Webhook node, onReceived for fast acknowledgement, and lastNode for returning the final node output.',
  },
  {
    type: 'field',
    title: 'Webhook Trigger: Verify Signature',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook#operation-default',
    text: 'Verify Signature rejects unsigned or incorrectly signed webhook calls. Use it for production, payment, customer, and public webhook workflows.',
  },
  {
    type: 'field',
    title: 'Webhook Trigger: Signature Secret',
    slug: 'webhook',
    category: 'Triggers',
    href: '/docs/nodes/webhook#operation-default',
    text: 'Signature Secret is the private shared secret used for webhook signature verification. Do not use API keys, passwords, OAuth tokens, or customer data here.',
  },
] satisfies DocsSearchIndexItem[];
