import type { DocsSearchIndexItem } from '../search-index';

export const whatsappTriggerSearchIndex = [
  {
    type: 'node',
    title: 'WhatsApp Trigger',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger',
    text: 'WhatsApp Trigger starts workflows in real time from Meta WhatsApp Cloud incoming messages and status webhooks.',
  },
  {
    type: 'operation',
    title: 'WhatsApp Trigger: Receive Event',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger#operation-receive_event',
    text: 'Receive WhatsApp Cloud webhook events and normalize chatId from waId text messageId phoneNumberId eventType status timestamp raw.',
  },
  {
    type: 'field',
    title: 'WhatsApp Trigger: Verify Token',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger#operation-receive_event',
    text: 'Verify Token validates Meta webhook subscription challenge requests.',
  },
  {
    type: 'field',
    title: 'WhatsApp Trigger: Signature Validation',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger#operation-receive_event',
    text: 'Validate X-Hub-Signature-256 with META_APP_SECRET FACEBOOK_APP_SECRET or WHATSAPP_APP_SECRET.',
  },
  {
    type: 'field',
    title: 'WhatsApp Trigger fields',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger#operation-receive_event',
    text: 'Fields include connectionId, eventTypes message message.text message.media status status.delivered status.read status.failed, phoneNumberId, allowedWaIds, verifyToken, and validateSignature.',
  },
  {
    type: 'field',
    title: 'WhatsApp Trigger outputs',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger#operation-receive_event',
    text: 'Outputs eventId eventType source userId username text timestamp chatId from waId contactName profileName messageId messageType mediaId status recipientId phoneNumberId displayPhoneNumber businessAccountId raw trigger workflow_id node_id sessionId _whatsapp.',
  },
  {
    type: 'field',
    title: 'WhatsApp Trigger connection setup',
    slug: 'whatsapp_trigger',
    category: 'Triggers',
    href: '/docs/nodes/whatsapp_trigger#connection-setup',
    text: 'Connect a WhatsApp Business API permanent access token and Phone Number ID in Connections. Set the callback URL and Verify Token in Meta for Developers -> WhatsApp -> Configuration and configure META_APP_SECRET for signature validation.',
  },
] satisfies DocsSearchIndexItem[];
