import type { DocsSearchIndexItem } from '../search-index';

export const zoomVideoSearchIndex = [
  {
    title: 'Zoom Video',
    slug: 'zoom_video',
    type: 'node' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video',
    text: 'Zoom Video Create and manage Zoom meetings using a Zoom OAuth connection. Operations createMeeting listMeetings getMeeting updateMeeting deleteMeeting. Requires Zoom OAuth2 connection.',
  },
  {
    title: 'Zoom Video: Create Meeting',
    slug: 'zoom_video',
    type: 'operation' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video#operation-createMeeting',
    text: 'Create a Zoom meeting with topic startTime and duration using a selected Zoom OAuth2 connection.',
  },
  {
    title: 'Zoom Video: List Meetings',
    slug: 'zoom_video',
    type: 'operation' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video#operation-listMeetings',
    text: 'List scheduled Zoom meetings for the connected user.',
  },
  {
    title: 'Zoom Video: Get Meeting',
    slug: 'zoom_video',
    type: 'operation' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video#operation-getMeeting',
    text: 'Get Zoom meeting details by meetingId.',
  },
  {
    title: 'Zoom Video: Update Meeting',
    slug: 'zoom_video',
    type: 'operation' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video#operation-updateMeeting',
    text: 'Update a Zoom meeting by meetingId with optional topic duration or startTime.',
  },
  {
    title: 'Zoom Video: Delete Meeting',
    slug: 'zoom_video',
    type: 'operation' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video#operation-deleteMeeting',
    text: 'Delete a Zoom meeting by meetingId.',
  },
  {
    title: 'Zoom OAuth2 Connection',
    slug: 'zoom_video',
    type: 'field' as const,
    category: 'Communication',
    href: '/docs/nodes/zoom_video#credentials',
    text: 'Connect Zoom through the generic OAuth flow. Required scopes meeting:write:meeting meeting:read:meeting meeting:read:list_meetings user:read:user. Redirect URI https://worker.ctrlchecks.ai/api/credential-connections/oauth/callback.',
  },
] satisfies DocsSearchIndexItem[];
